ianstormtaylor/slate

docs/reference/plugins/plugins.md, lib/components/editor.js, lib/components/leaf.js, test/rendering/fixtures/custom-mark-multiple/index.js, test/rendering/fixtures/custom-mark-multiple/input.yaml, test/rendering/fixtures/custom-mark-multiple/output.html
=> add the ability to render based on multiple marks

docs/reference/models/state.md
=> {edge}Offset is Number (state.md)

docs/reference/models/transform.md, lib/models/transform.js, lib/models/transforms.js, test/transforms/fixtures/modify-node/single-block-string-shorthand/index.js, test/transforms/fixtures/modify-node/single-block-string-shorthand/input.yaml, test/transforms/fixtures/modify-node/single-block-string-shorthand/output.yaml, test/transforms/fixtures/modify-node/single-block/index.js, test/transforms/fixtures/modify-node/single-block/input.yaml, test/transforms/fixtures/modify-node/single-block/output.yaml
=> modifyNode transform

package.json
just dependency version update
=> change react-frame-aware-selection-plugin to 0.0.2, with safari fix.

package.json
latest version with fixes for safari
=> change react-frame-aware-selection-plugin to 0.0.3, with safari fix.

package.json
=> react-iframe-aware-select-plugin latest version

Readme.md
I found some broken links in the README. This PR corrects them.
=> Fix Documentation Links

docs/walkthroughs/saving-and-loading-html-content.md
This is a tiny thing, but I caught this when working through the walkthrough.
=> Fixes a small error in a code example in HTML walkthrough.

lib/components/content.js
=> Fix bug with non-immediate updating of readOnly state

lib/transforms/at-range.js, test/transforms/fixtures/at-range/insert-fragment-at-range/fragment-multiple-blocks-in-nested-block/fragment.yaml, test/transforms/fixtures/at-range/insert-fragment-at-range/fragment-multiple-blocks-in-nested-block/index.js, test/transforms/fixtures/at-range/insert-fragment-at-range/fragment-multiple-blocks-in-nested-block/input.yaml, test/transforms/fixtures/at-range/insert-fragment-at-range/fragment-multiple-blocks-in-nested-block/output.yaml
cc @Soreine
In the newly refactor codebase this is an embarrassingly simple fix 😄
=> Fix insert fragment multiple nested

src/models/node.js, src/transforms/at-range.js
=> change toSet to toOrderedSet

src/plugins/core.js
=> handling ctrl + k hotkey on mac

src/models/Readme.md
=> Fixed minor typo.

src/components/content.js, src/components/leaf.js
Things to note:
1. This won't work in IE / Edge because it uses [`closest()`](http://caniuse.com/#search=closest). However, slate uses `closest()` in several places so I just rolled with it.
2. I have no idea how to write tests for this.
3. I'm not sure if it resolves all issues with focus/blur, but I tested a few cases where it worked (and previously didn't).
4. Previously, `document.activeElement` didn't change. Now, after executing the blur transform, it will be the body element.
5. We can't trust `state.selection` in isLeaf because it might be out of date in environments that are a bit slow. Because it is not possible to get the real steat I added a DOM-based check that detects if our contenteditable is still responsible for handling the selection.
Closes #297 and maybe #418
=> Resolve issues with focus and blur transformations in the DOM

docs/reference/utils/utils.md, src/index.js, src/utils/generate-key.js
=> add resetKeyGenerator util

src/components/node.js, src/serializers/base-64.js
https://github.com/ianstormtaylor/slate/issues/480
=> Add options to Base64 serializeNode

package.json, src/constants/environment.js
Fixes https://github.com/ianstormtaylor/slate/issues/499
=> refactor environment detection, remove unused deps

docs/reference/models/transform.md
I added documentation to the transform.call from an earlier pull request.
=> Added documentation to transform.call

docs/reference/models/schema.md, docs/reference/serializers/raw.md, examples/focus-blur/Readme.md, examples/plugins/Readme.md, examples/rtl/Readme.md, examples/tables/Readme.md
Hey @ianstormtaylor, found a couple of more minor Readme issues that I came across. Hope it helps!
=> Fixing Readme and API docs

src/models/selection.js
Found some more of the deprecation warnings.
=> Selection: fix deprecated code call

docs/reference/models/node.md
=> Fix typo: 'Charaters' => 'Characters'

src/transforms/on-selection.js, test/transforms/fixtures/on-selection/select-all/basic/index.js, test/transforms/fixtures/on-selection/select-all/basic/input.yaml
=> Add functionality and test-case for selectAll

docs/walkthroughs/applying-custom-formatting.md
Running through the walkthroughs and the clean slate for the Applying Custom Formatting section was wrong.
=> docs: Delete dangling }

src/plugins/core.js
Fix mismatched event parameter.
=> Fix mismatched event parameter.

docs/reference/plugins/plugin.md
A small clarification to ensure no one else misunderstands how to prevent default behavior.
=> Clarify instructions for plugin preventing default behavior

docs/reference/models/node.md
Noticed a couple of useful functions I found useful that weren't documented. Also, fixed a couple of broken links.
=> Documenting node's 'getFirstText' & 'getLastText'

docs/reference/models/transform.md
As per [comment](https://github.com/ianstormtaylor/slate/issues/775#issuecomment-299079242) in #775.
=> Clarifying insertTextByKey description

src/models/mark.js, src/models/node.js, src/models/text.js, src/utils/memoize.js, test/index.js, test/plugins/index.js
Closes #793 
Seems to have a pretty decent improvements, and since many more complex methods are built from the base ones it should cascade nicely...
=> allow memoization without arguments for faster lookups

examples/Readme.md
When attempting to mess around locally I could never get anything to update. Sure enough I was looking in the wrong place and had missed the `/dev.html` on the end of my url.
Here's to hoping no one else struggles with this again.
=> Local examples url update

docs/walkthroughs/adding-event-handlers.md, docs/walkthroughs/applying-custom-formatting.md
Hi!
Thanks for taking the time to build such an awesome project!
I'm reading the documentation (which is great by the way) and thought to take the time to send a few PRs for some typos and things that wasn't immediately clear for me as a first time reader.
This is the first one.
Cheers,
Asaf K
=> Docs improvements suggestions

docs/reference/models/node.md
I remembered coming across these functions and then didn't find them in the docs. So, here they are now!
=> Documenting node's getFurther* functions

src/transforms/apply-operation.js
This fixes issue reported in a comment to PR #782.
=> Don't mutate `path` array, use instead a copy.

docs/Readme.md
Fixes #899, and also updates the project website.
=> Fix doc links

examples/images/index.js
Dropped images were being inserted at the previous selection rather than the drop target.
=> Fix image drop in example

src/utils/get-transfer-data.js
=> Fixes fragment matcher regex for pasting Slate fragments

docs/reference/serializers/raw.md
=> Document Raw serializer options

Contributing.md
Found this when searching how to test IME and thought everyone contributing would benefit.
=> Add link to IME reference page in Contributing.md

Contributing.md
=> Fixes #1010 — adds debuginfo to Contributing.md

docs/reference/components/editor.md, docs/reference/plugins/plugin.md, src/components/content.js, src/components/editor.js, src/models/stack.js, src/plugins/core.js
This PR exposed onKeyUp to editor so that plugins can use it
=> expose onKeyUp

docs/reference/models/transform.md, src/transforms/by-key.js, test/transforms/fixtures/by-key/insert-fragment-by-key/end-of-target/fragment.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/end-of-target/index.js, test/transforms/fixtures/by-key/insert-fragment-by-key/end-of-target/input.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/end-of-target/output.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/middle-of-target/fragment.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/middle-of-target/index.js, test/transforms/fixtures/by-key/insert-fragment-by-key/middle-of-target/input.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/middle-of-target/output.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/start-of-target/fragment.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/start-of-target/index.js, test/transforms/fixtures/by-key/insert-fragment-by-key/start-of-target/input.yaml, test/transforms/fixtures/by-key/insert-fragment-by-key/start-of-target/output.yaml
PR for #989 
I believe this will fix the issues with copy and paste that #1039 covers.
=> insertFragmentByKey

test/transforms/fixtures/on-selection/collapse-to-end/void/index.js, test/transforms/fixtures/on-selection/collapse-to-end/void/input.yaml, test/transforms/fixtures/on-selection/collapse-to-start/void/index.js, test/transforms/fixtures/on-selection/collapse-to-start/void/input.yaml
There were no tests for this so I added some.
=> Add tests for collapseToStart/End when selected node is void

src/plugins/core.js
Now drop fragments insert at correct location. As described here: https://github.com/ianstormtaylor/slate/issues/927
=> Fix drop contents insertion

src/models/node.js
=> fix empty selections active marks logic

docs/Summary.md, docs/reference/Readme.md, docs/reference/components/custom.md, examples/embeds/video.js, examples/emojis/index.js, examples/images/index.js, src/components/content.js, src/components/node.js, src/models/node.js, src/utils/is-index-in-range.js
This adds an `isSelected` prop to node components, which is `true` if they are in the selection at all—at the start, middle or end. And then it uses this new prop to simplify `shouldComponentUpdate` logic.
Fixes #1080
Fixes #1058 
Fixes #536
=> add isSelected prop, cleanup sCU, add custom component reference

src/components/content.js
This was a little too eagerly placed here while trying to deal with the deleteRange edge cases. It must be removed.
=> Remove an incorrect selection manipulation from Content

docs/reference/plugins/plugin.md
Fixes https://github.com/ianstormtaylor/slate/issues/1089 along with the rest of the event handlers.
=> Update plugin reference to use Change instead of State

src/components/content.js
Fix parameter name, remove trailing spaces.
=> Fix some typos

docs/reference/slate-html-serializer/index.md
Explain a few more aspects of the serializer.
=> Add more details about slate-html-serializer

packages/slate-base64-serializer/package.json, packages/slate-dev-logger/package.json, packages/slate-html-serializer/package.json, packages/slate-hyperscript/package.json, packages/slate-plain-serializer/package.json, packages/slate-prop-types/package.json, packages/slate-react/package.json, packages/slate-simulator/package.json, packages/slate/package.json
This should cause them to update the lib folders on `prepublish` @ianstormtaylor
=> Adding Regular Build to all of the Slate Packages

packages/slate-react/src/components/editor.js, packages/slate-react/src/plugins/core.js, packages/slate/src/index.js
=> re-add the onBeforeChange handling for normalizing to the <Editor>

docs/walkthroughs/using-plugins.md
The `BoldMark` function has been inlined below, it is no longer used here
=> [Doc] Remove unused code in Plugins Walkthroughs

packages/slate-react/src/components/content.js, packages/slate-react/src/plugins/before.js
Don't stop propagation of drag events.
Fix issue #1277.
=> Don't stop propagation of drag events.

packages/slate-base64-serializer/package.json, packages/slate-base64-serializer/src/index.js
This provides a polyfill for btoa and atob on base64 serializer for SSR
fixes:  https://github.com/ianstormtaylor/slate/issues/1198
=> Slate base64 serializer and SSR

packages/slate-react/src/plugins/after.js, packages/slate-react/src/utils/find-point.js
Fixes #1295 
Fixes #1285 
Fixes #1276 
Fixes #1271 
Fixes #1217
=> fix findRange for text nodes next to inlines

packages/slate-react/src/components/editor.js, packages/slate-react/src/constants/plugin-props.js, packages/slate-react/src/plugins/after.js
=> fix to reresolve the editor plugin less, add warning

packages/slate-react/src/plugins/after.js
This is a workaround for a [bug in React](https://github.com/facebook/react/issues/11379), and should fix #907 and #1173.
=> fix broken onSelect event

examples/plugins/index.js, packages/slate-react/Changelog.md, packages/slate-react/src/components/content.js, packages/slate/src/changes/with-schema.js
=> fix to always normalize ancestors of a node

packages/slate/src/changes/by-key.js
add method: Change.removeAllMarksByKey #1215
=> add change method to remove all marks from node by key

packages/slate/src/changes/at-current-range.js
Closes #1248 
Just take marks from value model and this can get fixed 😀
=> Fix missing marks on `insertText`

packages/slate-react/src/components/content.js, packages/slate-react/src/plugins/after.js, packages/slate-react/src/plugins/before.js
=> fix placeholder to not render when composing

docs/reference/slate/schema.md, examples/forced-layout/index.js, examples/images/index.js, packages/slate/src/models/schema.js, packages/slate/test/schema/custom/first-child-kind-invalid-custom.js, packages/slate/test/schema/custom/first-child-kind-invalid-default.js, packages/slate/test/schema/custom/first-child-type-invalid-custom.js, packages/slate/test/schema/custom/first-child-type-invalid-default.js, packages/slate/test/schema/custom/last-child-kind-invalid-custom.js, packages/slate/test/schema/custom/last-child-kind-invalid-default.js, packages/slate/test/schema/custom/last-child-type-invalid-custom.js, packages/slate/test/schema/custom/last-child-type-invalid-default.js
=> Add schema first/last definitions

docs/guides/rendering.md
- make the placeholder have an opacity
- correct `contentEditable` jsx attribute
=> Fix small error in docs

packages/slate/src/changes/at-range.js
=> fix(at-range): forward deletion now stays with next block.

packages/slate-react/src/utils/scroll-to-selection.js
Fixes #1461.
Also updated to use only the cursor position (rather than the entire selection) to calculate scroll position. Consider this selection:
If this is a forward selection, there is no real way to find the top of the cursor, so the calculation is currently off when you're trying to scroll up to the cursor position. Same issue if it's backwards and scrolling down.
Since we only care about cursor position, you can just collapse the range and using that rect instead.
=> fix: account for container padding in scrollToSelection

docs/walkthroughs/defining-custom-block-nodes.md
Fixes documentation suggested in issue #690.
=> Changed metaKey to crtlKey

Readme.md
Links to @ianstormtaylor plugins were deprected, updated to right path.
=> Update links to Plugins

docs/general/resources.md
Hi! I am the one of maintainers of the `slate-editor`, and I am very happy with the link on list of showcases! Can you guys change the organization name? :D
=> Change reboo to nossas organization's editor name

packages/slate-react/src/constants/hotkeys.js, packages/slate-react/src/plugins/after.js
Fixes https://github.com/ianstormtaylor/slate/issues/1518
I still need to verify it fixes both the issues that may be linked, and check it doesn't cause any regressions. Will report back!
=> Fix selecting with shift+(left|right) key

package.json, yarn.lock
=> Add back babel-cli as a development dependency.

docs/general/resources.md
I hope this tool will help others get a quick start with the proper way of building editorial tools for the web. Slate is the best tool to get it done; this package is simply an opinionated collection of code, plugins and design based on personal experience to skip ahead a few steps.
=> Added another editor package built on top of Slate.

packages/slate-react/src/constants/hotkeys.js
Close: https://github.com/ianstormtaylor/slate/issues/1617
Same as: https://github.com/ianstormtaylor/slate/pull/1729
=> fix: add missing hotkey for delete line backward, close: #1617

docs/walkthroughs/saving-to-a-database.md
Should be possessive (you're => your)
=> docs: walkthroughs: saving: Fix grammar

docs/reference/slate/change.md
=> added documentation for wrapNodeByKey

packages/slate/src/changes/by-key.js, packages/slate/test/changes/by-key/replace-text-by-key/replace-with-active-marks-with-data.js, packages/slate/test/changes/by-key/replace-text-by-key/replace-with-active-marks.js, packages/slate/test/changes/by-key/replace-text-by-key/replace-with-mark-and-active-mark.js, packages/slate/test/changes/by-key/replace-text-by-key/replace-with-node-index-mark.js, packages/slate/test/changes/by-key/replace-text-by-key/replace-without-any-marks.js, packages/slate/test/changes/by-key/set-text-by-key/replace-with-string-and-mark.js, packages/slate/test/changes/by-key/set-text-by-key/replace-with-string.js, packages/slate/test/helpers/h.js
There is not a easy way to replace a length of text
Provides two functions to replace a length of text
=> Feature: setTextByKey and replaceTextByKey

.github/PULL_REQUEST_TEMPLATE.md
Improving GitHub PR workflow.
Last week, I noticed that my PR didn't pass CI tests on GitHub because of linting errors.
I hadn't checked it beforehand, and had to add a commit just for a line-break. 
Plus I didn't know about the `yarn run prettier` command to automatically enforce code-style.
This checklist aim to have all PRs passing linting tests on first submission, and guide contributors so they can fix code-style efficiently.
Maybe more checks could be added?
=> Add checklist for tests to PR Template

packages/slate-react/src/utils/clone-fragment.js
Fixing a bug and cleaning up legacy stuff. I should probably have done this already in my [previous PR](https://github.com/ianstormtaylor/slate/pull/1815)...
We currently select more html than we need when copying marks (to work around browser quirks). This isn't needed anymore (since #1815), and also messes up the contents of the html clipboard register (see https://github.com/ianstormtaylor/slate/issues/1693). 
Since we now have full control of what's put in each clipboard register, we should be able to remove all COMPAT code for Chrome, Safari and Opera.
Fixes: https://github.com/ianstormtaylor/slate/issues/1693
=> Remove legacy COMPAT code from cloneFragment

packages/slate/src/changes/at-range.js, packages/slate/test/changes/at-current-range/delete-line-backward/text-start.js, packages/slate/test/changes/at-current-range/delete-line-forward/inline-middle-emoji.js, packages/slate/test/changes/at-current-range/delete-line-forward/inline-multi-voids.js, packages/slate/test/changes/at-current-range/delete-line-forward/inline-void-end.js, packages/slate/test/changes/at-current-range/delete-line-forward/inline-void-first.js, packages/slate/test/changes/at-current-range/delete-line-forward/text-end.js, packages/slate/test/changes/at-current-range/delete-line-forward/text-start.js, packages/slate/test/changes/at-current-range/delete-line-forward/word-middle.js
bug
The deleteForwardLine is using a wrong characters number.  This PR fixes the problem.
=> Fix the characters count in deleteForward

packages/slate/src/models/schema.js
improving a feature
document's marks in schema are now extendable
let say we have two plugins where each of them defines some marks to exist in the document such as
```js
const pluginA = {
schema: {
document: {
marks: [{ type: 'bold' }, { type: 'italic'}]
},
}
}
const pluginB = {
schema: {
document: {
marks: [{ type: 'underline' }, { type: 'strikethrough'}]
},
}
}
render() {
return (
<Editor plugins={[pluginA, pluginB]} />
)
}
```
previously the Editor's schema would be:
```js
schema =  {
document: {
marks: [{ type: 'bold' }, { type: 'italic'}]
},
}
```
with this PR the resulting schema would be:
```js
schema =  {
document: {
marks: [{ type: 'bold' }, { type: 'italic'}, { type: 'underline'}, { type: 'strikethrough' }]
},
}
```
Fixes: #
Reviewers: @
=> update schema customizer to merge marks

docs/reference/slate-react/plugins.md
Feature
Doc change only: add some missing information to the Plugins reference.
It is only rudimentary since I don't really know the codebase, but it's better than nothing :)
=> plugins reference: update available properties

docs/general/resources.md
Hi, I know one of the co-founder of [Taskade](https://www.taskade.com/): [John Xie](https://www.linkedin.com/in/johnxie/)   
[Taskade](https://www.taskade.com/)'s editor is really impressive.      
I know Slate.js because of Taskade.
I think Taskade should be in the list.
Thanks
=> Add Products: Taskade

packages/slate/src/changes/on-selection.js, yarn.lock
Fixing a bug
For pointForward, existance of next was not checked. Also, the method is called for both focus and anchor; updated the code to reflect this.
The same implementation as pointBackward()
Fixes #2036 
Fixes #2050
=> fix pointForward and pointBackward

packages/slate/src/models/schema.js
Bug.
All normalizing change methods should use `normalize: false` otherwise the normalization can recurse and cause strange errors.
=> fix schema defaultNormalize to use normalize:false

examples/images/index.js
bugfix
use new schema changes in the images example
Fixes: #
Reviewers: @
=> fix images example schema

packages/slate/src/changes/on-selection.js, yarn.lock
fixing a bug
fix undo/redo stack size
there was a typo in checking props'key's length on `Changes.select` that cause a `set_selection` messing with history stack. fixing the type fixed this behaviour
Fixes: #
=> Fix incorrect history stack

docs/walkthroughs/saving-and-loading-html-content.md
Typo in function definition
Fixes: #
Reviewers: @
=> Updating function in readme.md

docs/general/resources.md
Just a quick update here with a link to https://github.com/chatterbugapp/chatterslate !
=> Update resources with Chatterslate

docs/walkthroughs/saving-and-loading-html-content.md
=> Add missing import

docs/guides/commands-and-queries.md
Fixed the MD formatting of a link to change docs.
=> Fixed link

docs/guides/commands-and-queries.md
Nope. Just fixing a single typo in the docs.
N/A
Fixes: #
Reviewers: @
=> Fix a typo in the docs

packages/slate/src/controllers/editor.js
Improving documentation.
No new behavior introduced.
Done 0 checks, since it patches only a comment.
No
=> Fix typo in docs

docs/reference/slate/operation.md
Improving a feature.
Added documentation for the newly added `Operation.data` property.
No
=> Add documentation for the `Operation.data` property

examples/versions/index.js
Fixing a bug
Updated the code for the "Versions" example to handle latest version of slate.
Fixes: #2375
=> Fix broken "Versions" example

docs/Introduction.md
=> Fix broken links

docs/general/resources.md
Hi Ian! Took the liberty to add Sanity.io to the list 🙌
=> Add Sanity.io to the list of products

packages/slate/package.json
Bug
Removes unnecessary react peer dependency in slate core.
Fixes: #2439
=> remove react dependency from slate core

docs/reference/slate/commands.md
=> docs: replace change with editor

docs/general/resources.md
We just added tons of features to our text editor by switching to Slate and would love to rep it.
=> Adding Guilded to Products list

docs/general/resources.md
Added Prezly to product list. Here is a video on all the stuff we added to the editor (https://prezly.wistia.com/medias/4mjmw2ccrb) and are hoping to spend more time on contributing in the future.
=> Adding Prezly to Products list

packages/slate-react/package.json
Simple dependency fix.
Fixes #2590
=> Remove reference to deprecated slate-simulator package

packages/slate/src/models/block.js
Reverts ianstormtaylor/slate#2619
=> Revert "Use fromJS instead of Map to convert data into block data"

packages/slate/src/commands/at-range.js
=> Wrap insertTextAtRange in withoutNormalizing

examples/app.js
> **checklist** (noun) a list of items required, things to be done, or points to be considered, used as a reminder.
"Check List" sound like an action, not the thing being shown
Fixing a grammatical error/typo
No new behavior, but better clarity in the nav menu
It doesn't. 
Nope.
=> Update "Check Lists" nav item to "Checklists"

packages/slate-react/src/plugins/debug/debug-mutations.js
Fixing a bug and improvement
This PR does two things:
- Fixes a bug where plugins after this one don't have their lifecycle events called because there was a missing call to `next` from the lifecycle callbacks
- Prints  prettier output of a NodeList in mutations
- Adds the call to `next` in the plugin
- Converts a NodeList to a string that is its outer HTML without the inner HTML
Fixes: #
Reviewers: @
=> Improve debug mutations plugin

docs/walkthroughs/applying-custom-formatting.md
This is updating the docs in response to a recent API change.
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#0220--may-8-2019
No change in behavior, just updating the docs.
...
No.
Fixes: #
Reviewers: @
=> Replace renderNode with renderBlock in the docs

examples/mentions/index.js, packages/slate/src/commands/on-value.js, packages/slate/src/models/value.js
Fixing a bug
I have made some minor changes to get the mentions example working.
Fixes: #2826 
=> Fixed mentions example

docs/reference/slate/schema.md
fixing a bug
Add missing `previous` property in `rules`
Fixes: #
Reviewers: @
=> [Doc] Add missing `previous` property in `rules`

docs/general/resources.md
Added Archbee (a Wiki for engineering teams) to resources.md.
=> Add Archbee to resources.md

packages/slate-react/src/plugins/dom/after.js
Fixing a bug.
When drag-and-dropping nodes within the same editor, the removal of
the dragged nodes can cause paths and offsets to change. This is
really hard to compensate for.
Instead of compensating for it, rearranging the order things happen
mean we are always working with a document in a reasonable state.
Now, we:
1. Fire a MouseUp event on `event.target` (because we haven't done
anything, it's guaranteed to exist)
2. Save the range we're dragging (for later)
3. Select the target range (because we haven't deleted anything, this
is still valid)
4. Delete the range we're dragging (this will automatically adjust the
editor's selection)
5. Insert the dragged fragment at the current range (the adjusted target range)
No matter where we're dragging from or to, these should all be
pointing …
=> Drop dragged nodes into the correct place

docs/reference/slate/node.md
Fixing a bug in documentation - (Small fix - caught me out)
Removed incorrect function parameter for `getTexts()`
Updated documentation
Fixes: #
Reviewers: @
=> Update getTexts() documentation for Node Model

docs/general/resources.md, docs/guides/plugins.md
fix broken link and add a new product link
core plugin link works
correct link reference 
Fixes: #
=> Fix broken core-plugin link and add a new item to the products list in document

packages/slate-react/src/components/content.js
Fixing a bug.
Focusing on editor places caret next to cursor as expected.
Previously, in Firefox, focusing on an editor would result in `updateSelection` being called before
`onNativeSelectionChange` is triggered, but after the native selection has been changed, resulting in `removeAllRanges` being called on the native selection. To prevent this, this PR introduces a member `nativeSelection` which stores the native selection's state when `onNativeSelectionChange` is triggered, so that when `updateSelection` is called, we can check if the native selection has been updated before `onNativeSelectionChange` has been triggered, and if so, prevent `removeAllRanges` from being called.
Fixes: #2978
=> Bugfix: Fixes issue where focusing on editor always placed caret at offset 0

docs/reference/slate/text.md
Fix #3029 
Only update the document.
Only update the document.
NO NEED but still done  : )
Fixes: #3029 
Reviewers: @CameronAckermanSEL @ianstormtaylor
=> Correct the document mentioned by #3029

docs/guides/commands-and-queries.md
Just a small doc typo I spotted :)
=> Fixed typo in docs: addMarkAt_Ar_ange -> addMarkAt_R_ange

docs/reference/slate-react/plugins.md
Improving the documentation for available hooks.
Only documentation updates.
Make onMouseDown to be visible in SlateJS Documentation
* [*] The new code matches the existing patterns and styles.
* [*] The tests pass with `yarn test`.
* [*] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [*] The relevant examples still work. (Run examples with `yarn watch`.)
Fixes: #
Reviewers: @
=> Added onMouseUp into available hooks.

Changelog.md
fixing a _bug_
Changelog.md without bad links
Very well :)
Fixes: #
Reviewers: @
=> Removed 404 links from Changelog.md

docs/general/resources.md
I'd like to propose Slite.com as an example of usage. Our editor is extensively using Slate and collaboration with it.
=> Add Slite.com as example of usage

docs/walkthroughs/06-saving-to-a-database.md
=> Fix variable name in docs

docs/walkthroughs/05-executing-commands.md
=> Remove controlled value state from docs

docs/walkthroughs/01-installing-slate.md
No
Updated docs, no code changes
No
=> Fix typos in Installing Slate walkthrough

packages/slate-react/src/components/editable.tsx
Bug
Allow the property `autoFocus`
Fixes: #
Reviewers: @
=> fix: ts error

site/examples/mentions.js
bug
add editor parameter to define it outside the component
Fixes: #
Reviewers: @
=> fix: promptMention not defined

site/examples/images.js
Bug
The insert image button on the image example works again.
=> Fix InsertImageButton in image example

site/examples/mentions.js
bug
Before, only lower case search was working.
Now, support upper case search as well.
Fixes: #
Reviewers: @
=> fix: support upper case search

docs/concepts/08-rendering.md
Fixes a ridiculously small typo in the rendering code example :trollface: 
Fixing a typo in documentationl.
See docs
Fixes: #
Reviewers: @
=> Change B to I in code example

site/examples/markdown-preview.js
=> style: no-unused-vars

docs/concepts/07-plugins.md
Noticed a couple more small typos while reading up on the documentation. This PR fixes those.
=> Small docs changes

packages/slate-react/src/components/text.tsx, packages/slate/src/interfaces/text.ts, packages/slate/test/interfaces/Text/decorations/end.js, packages/slate/test/interfaces/Text/decorations/middle.js, packages/slate/test/interfaces/Text/decorations/overlapping.js, packages/slate/test/interfaces/Text/decorations/start.js
Re-adding a function to the slate core package.
There is now a new Text.decorations(node: Text, decorations: Range[]): Text[] api function.
=> moved getLeaves from react to slate core package and added some basic tests

Contributing.md
bugfix
Contributing.md now link to an updated JSFiddle
Fixes: #3376
Reviewers: @
=> update jsfiddle url

docs/walkthroughs/04-applying-custom-formatting.md
=> Typo: 04-applying-custom-formatting.md

Readme.md
Minor docs tweaks:
* fixed broken Walthrough URL
* changed all urls from `http` to `https`
=> readme: Documentation: fix broken url; http -> https

Readme.md
Getting started URL was broken.
=> Fixed Getting Started url

docs/walkthroughs/03-defining-custom-elements.md
=> An unused state was deleted.

packages/slate/test/interfaces/Node/first/success.js, packages/slate/test/interfaces/Node/last/success.js
adding unit tests
2 new unit tests for `node.ts` 
1 success test for `first` method
1 success test for `last` method
=> add unit tests for node first and last methods

.github/ISSUE_TEMPLATE.md
Updates the codepen in the ISSUE_TEMPLATE.md to be a working example of v0.58.0
Fixing the issue template codepen
Uses latest version of slate and uses a controlled value as uncontrolled values are no longer supported.
Fixes: #
Reviewers: @
=> Update codepen in ISSUE_TEMPLATE.md for v0.58.0

docs/general/resources.md
Adding slate-plugins-next in the resources
=> docs(resources): slate-plugins-next

docs/general/resources.md
No, it is adding GraphCMS to the products actively using slate
=> docs: add GraphCMS to products using slate

docs/walkthroughs/06-saving-to-a-database.md
No, it just fixes a code example in docs
=> docs: remove unused "selection" from code example

docs/concepts/06-editor.md
=> doc: fix parenthesis missing

.github/workflows/rebase.yml
Adding a new feature: To automatically Rebase PRs during review.
To automatically Rebase PRs during review, write /rebase as comment on a PR. 
It reduces time to manually do the rebase and push upstream. It also updates the latest changes from master unto your PR branch
Fixes: https://github.com/ianstormtaylor/slate/issues/3764
=> Auto Rebase Github Action

config/rollup/rollup.config.js
Just delete useless rollup config.
=> delete legacy rollup config

site/examples/Readme.md
=> doc: change example readme doc link

packages/slate/src/interfaces/editor.ts, packages/slate/src/interfaces/path.ts
Fixing some TS bugs/compile errors in the Main branch.
The types for the various interfaces/functions are now correct.
Simple fix of several TS types.  I worked on the PR that caused the type issue with an MLH fellow so I know the types are proper.
Relates to: #4003 
Reviewers: @thesunny
=> Fix TS type errors

Readme.md
This updates the links to examples in the Readme.md
=> Update URLs to examples in Readme.md

docs/general/resources.md
Nope
Add products
Fixes: #
Reviewers: @
=> docs: add TRPG Engine link to products using slate

site/examples/Readme.md
Replace .js with .tsx in the readme
=> Fixed example links

docs/concepts/06-editor.md
Bug.
Very small fix to a docs page.
Fixes: #
Reviewers: @
=> Small correction to docs concepts/06-editor.md

packages/slate-react/src/components/editable.tsx
=> fix: IME repeat input

packages/slate/src/interfaces/editor.ts
=> Add voids to the interface definition of positions

docs/concepts/09-serializing.md
- added demo describing how to handle 'bold' element
=> Updated serializing demo function

site/examples/images.tsx
Adding/improving a feature
The new change checks if the URL provided is an image URL using the present function isImageUrl
Also shows an alert when the URL is not an image. 
Fixes:  #3932
=> Added isImageUrl validation to button, added alert when not image

packages/slate-react/src/utils/dom.ts
Fix a bug
normalizeDOMPoint now get the editable dom point more near to the input non-editable dom point.
```
<div id="a">
<p>some text</p>
<div id="b" contenteditable="false">...</div>
</div>
```
It is about the triple click select. If use triple click first <p> content, it will finally result select nothing. which is because, when Editable internally calls ReactEditor.toSlateRange(window.getSelection()) in this case, the end point is at the 'b' div, which internally call ReactEditor.toSlatePoint(div 'a', 1), which will resolve to the [] position in the <p>[]some text</p>, but what we want is <p>some text[]</p> in this case. The problem is caused by the normalizeDOMPoint method, for this case, it internally call getEditableChild with direction 'forward', but it will finally return the p …
=> Fix normalizeDOMPoint to do better job.

Readme.md
Wanted to refresh my mind on the contributing guidelines, and saw that the link no longer worked, so just thought to update it really quick.
=> readme: minor fix for updated contributing link

docs/concepts/03-locations.md
Before: Link doesn't work
After: Link works
=> Fix range API link

docs/api/nodes/editor.md
Improve the documentation around the Editor, specifically around overrides
**Issue**
**Example**
**Context**
**Checks**
=> docs: improve editor docs

.github/workflows/release.yml
Updated the release workflow as the initial fix had an oversight
**Issue**
This PR follows-up on #4274
=> Tweak release workflow

Readme.md
Updates the contributing instructions link to point to the contributing page.
=> Fix contributing link

docs/general/resources.md
Hi gus!
I hope I can add the entrance of slate-angular, slate-angular is a good implementation.
=> feat(docs): add another member for slate

docs/concepts/02-nodes.md
I stumbled through this sentence when reading the docs. 
Hopefully this conveys the intent more clearly. 💙
=> fix sentence order in Node doc example

site/examples/hovering-toolbar.tsx
Merges the import statement of `slate`
=> Clean up imports

packages/slate-react/src/components/editable.tsx
Adding a feature.
user code can custom the behaviour of scrollInfoView
e.g. now we can add following code to the Editable's prop:
```
scrollSelectionIntoView={(editor, domRange) => {
const leafEl = domRange.startContainer.parentElement!
leafEl.getBoundingClientRect = domRange.getBoundingClientRect.bind(domRange)
scrollIntoView(leafEl, {
scrollMode: 'if-needed',
block: 'nearest', // block = start | center | end | nearest
})
delete leafEl.getBoundingClientRect
}}
```
Then this will work like if https://github.com/ianstormtaylor/slate/pull/3746 is merged, together with https://github.com/ianstormtaylor/slate/pull/4007 and the concern in https://github.com/ianstormtaylor/slate/pull/3678#issuecomment-754038215 without changing any existed user code's behaviour.
By introduce a customizable prop …
=> Support custom scrollIntoView behaviour from user side.

site/examples/paste-html.tsx
If this is not added issues like #3625 start surfacing. It was added to the documentation (https://github.com/ianstormtaylor/slate/pull/3889), but not in the example, so some users could be confused and catch bugs.
**Issue**
https://github.com/ianstormtaylor/slate/issues/3625
**Example**
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly …
=> Example: Add empty text if children are empty

.changeset/fix-ime-cursor-position.md, packages/slate-react/src/components/editable.tsx
See #4449 
**Issue**
Fixes: #4449 
**Example**
**Context**
See #4449 
**Checks**
=> Fix invalid cursor when IME converting

.changeset/heavy-plants-sell.md
Deliberate addition to the changeset to trigger an update to hopefully fix the release process after the update to yarn 3.
=> trigger changeset for 0.66 release

.changeset/eight-snakes-lick.md
Missed a changeset on #4512, adding it here.
=> add missing changeset

.github/workflows/release.yml
Working to fix the automated changeset process in the post 0.66.0 world of yarn 3.
=> correct immutability lockfile flag for yarn 3

.changeset/sixty-suns-hang.md, .github/workflows/release.yml, package.json
More work to fix the release versioning, apologies for the noise.
=> Fix release versioning

.github/workflows/release.yml, package.json
Working on fixing the automated changeset actions, nothing to see here. :)
=> Fix release versioning 3

docs/walkthroughs/01-installing-slate.md
It's an array of CutsomElement, TS complains about it
=> Fix code sample

docs/api/locations/README.md, docs/api/locations/location.md, docs/api/locations/path.md, docs/api/locations/point-entry.md, docs/api/locations/point-ref.md, docs/api/locations/point.md, docs/api/locations/range-ref.md, docs/api/locations/range.md, docs/api/locations/span.md, docs/api/nodes/README.md, docs/api/nodes/editor.md, docs/api/nodes/element.md, docs/api/nodes/node-entry.md, docs/api/nodes/node.md, docs/api/nodes/text.md, docs/api/operation.md, docs/api/transforms.md, docs/concepts/02-nodes.md, docs/concepts/03-locations.md, docs/concepts/04-transforms.md
This expands the (somewhat terse) documentation
=> Adds clarification & examples to demystify Transforms.

docs/api/locations/point-ref.md, docs/api/locations/range-ref.md, docs/api/nodes/editor.md, docs/general/faq.md
* Clarifies docs for RangeRef & PointRef
* fixes TOC for Editor API
* fixes TOC for FAQ
=> Clarifies docs for RangeRef & PointRef; fixes TOC for Editor API

docs/api/locations/README.md, docs/api/locations/path-ref.md, docs/api/locations/point-ref.md, docs/api/locations/range-ref.md, site/examples/paste-html.tsx
So far as I can tell, the interface exactly corresponds to PointRef and RangeRef. If that's not so, these docs will need to be updated.
=> Adds documentation for PathRef

.changeset/wild-penguins-shout.md, packages/slate/src/create-editor.ts
Reverts ianstormtaylor/slate#4769
=> Revert "Warn when normalization removes node"

.changeset/olive-bags-talk.md, packages/slate-react/src/components/editable.tsx
See note at https://github.com/ianstormtaylor/slate/pull/4749#issuecomment-1025742142
=> Revert #4749

.changeset/healthy-wasps-sit.md
I broke the release by quickly adding a changeset manually. Fixing it here.
=> Fix slate-react relase

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/ci.yml, .github/workflows/comment.yml, .github/workflows/release.yml
More work to switch GitHubActions to Node.js v16
=> Update release to use Node.js v16

.changeset/bright-buttons-march.md
We missed a changeset in #4889, adding it here.
=> add missing changeset from #4889

packages/slate-hyperscript/test/index.js
Fix an obvious typo in a testcase for slate-hyperscript.
=> Fix logic in test, fixes #4764

.changeset/friendly-dogs-judge.md, packages/slate/src/interfaces/editor.ts, packages/slate/src/transforms/node.ts, packages/slate/test/transforms/setNodes/merge/text.tsx
I create a new PR to help you adjust.
**Checks**
=> feat: add merge to setNodes and test

docs/api/nodes/element.md, docs/concepts/02-nodes.md
Documents how to implement a Void Element and gives an example.
**Issue**
There are several non-obvious requirements, which are difficult to tease out of the examples.
=> Documents how to implement a Void Element.

docs/general/resources.md
Yuque has its own editor implement long times, no longer uses slatejs
**Issue**
**Example**
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve …
=> docs: remove yuque in docs

docs/walkthroughs/01-installing-slate.md
Closed bracket on complete code example
**Issue**
Fixes: Added missing bracket in documentation example code.
=> closed bracket on complete code example in documentation

.github/workflows/codeql.yml
  Hey there,
   I was playing with the CodeQL workflow on some repos, trying to understand how it works.
    I got an alert when running the action on this project that I didn’t fully understand but felt like worth mentioning to you so that you can evaluate it yourself.    
      I think there’s a loose RegEx that could be dangerous if used to sanitise input but I’m not sure if it applies in this context.  
      
    
           I am sharing my original PR here that should trigger the action and fail with the same error: give it a look then feel free close this PR or keep the CodeQL action in your repo, maybe this was a false flag but the check it’s free and it runs very quick so you could find it useful for the future.  
      
      Cheers,
       Luigi
       
         What’s in the …
=> Add CodeQL Workflow

.changeset/unlucky-goats-return.md, packages/slate/src/create-editor.ts, packages/slate/src/interfaces/editor.ts, packages/slate/src/interfaces/node.ts, packages/slate/src/interfaces/path.ts, packages/slate/src/interfaces/point-ref.ts, packages/slate/src/interfaces/point.ts, packages/slate/src/interfaces/range.ts, packages/slate/src/interfaces/text.ts, packages/slate/src/interfaces/types.ts, packages/slate/src/transforms/node.ts, packages/slate/src/transforms/selection.ts, packages/slate/src/transforms/text.ts
Reverts ianstormtaylor/slate#4969
This effectively lands #4968. Sorry for the confusion.
=> Revert "Revert "Added types for options and common string literals""

packages/slate/src/interfaces/text.ts
Refactor `Text.decorations` method. No functional changes. 
**Checks**
=> Refactor text decorations method

docs/general/contributing.md, docs/walkthroughs/06-saving-to-a-database.md, docs/walkthroughs/xx-using-the-bundled-source.md
**Issue**
**Example**
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly helpful so that reviewers …
=> replace slate to Slate

docs/concepts/04-transforms.md
Wrong api name, in https://github.com/ianstormtaylor/slate/blob/main/docs/concepts/04-transforms.md。
a example for use `match`:
```
Transform.setNodes(
editor,
{ bold: true },
{
// This path references the editor, and is expanded to a range that
// will encompass all the content of the editor.
at: [],
// This only matches text nodes that are not already italic.
match: (node, path) => Text.isText(node) && node.italic !== true,
}
)
```
shoule be:
```
Transforms.setNodes(
editor,
{ bold: true },
{
// This path references the editor, and is expanded to a range that
// will encompass all the content of the editor.
at: [],
// This only matches text nodes that are not already italic.
match: (node, path) => Text.isText(node) && node.italic !== true,
}
)
```
**Issue**
Fixes: (link …
=> Fix wrong 'Transforms' name in concepts/04-transforms.md

packages/slate-react/src/plugin/react-editor.ts
Remove a line of code that is not used.
**Checks**
=> Remove unused code

docs/general/resources.md
* Adds descriptions to list of products
* Removes broken link
**Issue**
It’s hard for readers to know which products to look at from the names alone.
=> Adds descriptions to list of products

docs/general/resources.md
* Quill Forms spoke up after the previous PR was merged.
* GraphCMS has rebranded as Hygraph
=> Products: adds Quill Forms & renames GraphCMS to Hygraph

.github/workflows/ci.yml, .github/workflows/comment.yml, .github/workflows/release.yml, License.md
Update CI dependencies to Node 18
**Issue**
Fixes: Ideally issues with Netlify, but we'll see.
=> Update ci to Node 18

docs/general/resources.md
We're excited to have launched our Slate-based Notepad!
=> Docs: Add Eraser product

docs/api/operation.md, packages/slate/src/interfaces/operation.ts
Fixes typo in `operation.ts` and updates `Operation.md` according to it.
**Issue**
Fixes no issue.
**Context**
The documentation is formatted based on how pages are structured. Let me know if it should be written differently.
**Checks**
=> Update Operation API documentation

docs/general/resources.md
Add [Static CMS](https://www.staticcms.org/) to the list of products that use Slate.
=> doc: add static cms

docs/concepts/04-transforms.md
It will make code more readable and character difference is very less so it's worth changing.
=> chore: rename imageElmnts to imageElements in 04-transforms.md

docs/api/locations/range-ref.md
Fix documentation typo. Fixes #5427.
=> Fix docs typo for unref

packages/slate-react/src/utils/dom.ts
=> Fix typo in dom.ts

docs/api/locations/range.md, docs/general/faq.md, docs/libraries/slate-react/react-editor.md, docs/libraries/slate-react/with-react.md
Fixes a few typos found in the docs
=> Fix a few typos in the docs

.changeset/pink-lemons-guess.md, packages/slate-react/src/components/editable.tsx
Revert due to issues introduced in comments of #5542.
=> Revert #5542

docs/general/resources.md
Add EasyEmailPro to resources.md
**Issue**
Fixes: null
**Example**
**Context**
**Checks**
=> Add EasyEmailPro to resources.md

package.json
Fixes broken Playwright integration tests
**Example**
**Checks**
=> fix integration tests

.changeset/pink-pots-argue.md, packages/slate-react/src/index.ts
=> fix: expose use-composing

docs/libraries/slate-history/history-editor.md
=> Add `HistoryEditor.withNewBatch` to docs

package.json, yarn.lock
Update package.json: add "slate-dom": "workspace:*", to help IDE identify import xx from "slate-dom"
=> Update package.json: add "slate-dom": "workspace:*", to help IDE identify import xx from "slate-dom"

docs/libraries/slate-react/slate.md
Documents `Slate` props added in #5526.
=> docs: document `props.onValueChange` and `props.onSelectionChange`

docs/api/transforms.md
Fix a prettier error in docs/api/transforms.md
=> fix prettier formatting
