packages/slate-react/src/components/node.js

Hi,
It looks like all decorations, those passed from `decorateNode` for the current node, and those received from the parent, should go through relative range mapping.
The bug is evident when decorating text with existing marks as then decorations do not comply well.
Thanks.

Fix extracting relative ranges from decorations.

---

packages/slate-react/src/components/content.js
packages/slate/src/commands/on-history.js

_bug_
Should fix the following issues: #2891, #2729

Fix several undo/redo issues related to selection operation

---

docs/guides/data-model.md

Improving documentation
Clarify the allowable contents of a Block
Improved wording as per concerns in https://github.com/ianstormtaylor/slate/issues/2903
Fixes: #2903
Reviewers: @

Improve data model docs

---

packages/slate-react/src/utils/find-point.js

This fixes a bug.
findPoint return offset is wrong
findPoint created a new range, but forget it may be include some zero width string, so i removed
sorry, my English is poor
I found it myself.

FIX findPoint offset may be include zero width string

---

examples/embeds/video.js

Fixing a bug
Click on the video embed and change the url _in the middle_. The cursor should stay where you expect it. (instead of jumping to the end of the input)
Controlled inputs can't be backed by the editor state, but need a local state instead, so the solution is to wrap the input in a functional component with state and pass the onChange-handler on.
Fixes: #2504
Reviewers: @

fix cursor jumping to end in embeds example

---

packages/slate-react/src/utils/clone-fragment.js

Update deprecated function usage.
No waring in the chrome console.
Replace deprecated findDOMNode with editor.findDOMNode in cloneFragment.
Fixes: #

Replace deprecated findDOMNode with editor.findDOMNode in cloneFragment

---

docs/reference/slate/commands.md

- feature: improving docs
- Capitalises references to "Mark" in the `commands.md` docs. 
- Currently both `mark` and `Mark` are used frequently and which could lead to confusion around whether they are the same thing - at least for me.
- They all link to the same page and it appears they are referring to the same entity.
- In `mark.md` the capitalised `Mark` is used so I thought it should be standardised on that.
- Screenshot of current situation
- Screenshot with changes
- Trivial docs update for clarity
Fixes: n/a
Reviewers: Any

Capitalise references to Mark for consistency

---

examples/app.js

Spotted that this link was wrong on the Examples page.
The directory is at https://github.com/ianstormtaylor/slate/tree/master/examples/placeholder (without the last `s`)
Thanks for Slate! It's incredible!

Fixed /placeholder link on Examples page

---

examples/emojis/index.js
examples/emojis/value.json
packages/slate/src/commands/on-selection.js
packages/slate/src/utils/text-utils.js

This is basically PR #2680 in the current version of slate (Fixes #2635, fixes #2632)
Thanks @adjourn for starting this.
Plus, fixes a bug where the cursor could not be moved beyond block with arrow keys.
As explained in #2680 .
The emoji example has been extended to insert emojis as plain text (vs inline nodes) to demonstrate the new behaviour.
See #2680
Updated emoji example, see here:
Fixes: #2635, #2632
Reviewers: @adjourn @ianstormtaylor @kwokhuen

Fix unicode offset

---

packages/slate-react/src/components/content.js
packages/slate-react/src/plugins/dom/before.js

Fixing a bug
By default, the editor will not scroll on changes on the selection. Instead it will only scroll to make the cursor caret visible when a user action is performed
Some events on the `BeforePlugin` has been marked as *user action*. The plugin will set a local variable to `true` when a user event is triggered. Then, the `updateSelection` will check if a user action was done and will use a query to do that. A new command is added to put it back to `false` when the update is finished.
I'm not perfectly used to the codebase yet. If there is concerns or design changes to be done, I'll be happy to learn and make those changes!
Fixes:  #2967

Prevent scrolling when no user actions are performed

---

examples/paste-html/index.js

Bug fix
Paste HTML is working and not pasting content twice
Prevent default handler solves the issue.
Fixes: #2988
Reviewers: @

fixing paste html example

---

examples/search-highlighting/index.js

In search-highlighting example, when search text is empty, no need to split text and addAnnotation.
Note dom changes in the right

Fix when clear search text, all text split by blank

---

docs/guides/rendering.md

Fixing docs.
Change rendering docs to describe `renderBlock` and `renderInline` instead of deprecated `renderNode`.

Change renderNode docs to renderBlock and renderInline

---

packages/slate/src/models/operation.js

Fixing a bug.
When converting `set_annotation` operations to JS objects, they now include `type` and `data`.
Fixes: #
Reviewers: @

Include data and type when converting set_annotation to JS

---

packages/slate-hotkeys/src/index.js

Adding a feature - Slate should support Ctrl+Shift+Z as a hotkey for 'redo'.
The hotkey Ctrl+Shift+Z will now trigger 'redo' inside Slate. This is a very simple change that just involved adding an additional hotkey sequence for the Windows 'redo' inside the hotkey mapping dictionary.
When isRedo() is evaluated from slate-react, there will now be an additional hotkey sequence that qualifies as an undo hotkey according to the hotkey dictionary (for Windows).
Fixes: #
Reviewers: @

Add redo hotkey for Windows (Ctrl+Shift+Z)

---

packages/slate-react/src/components/editable.tsx

Typescript error:
```
Property 'onDOMBeforeInput' is missing in type '{}' but required in type ...
```
Fixing a bug
The following works when using typescript
```
<Slate editor={editor} defaultValue={defaultValue}>
<Editable />
</Slate>
```
Make onDOMBeforeInput optional

Editable: onDOMBeforeInput should be optional

---

docs/concepts/XX-migrating.md

This is typos fixing. 
In ### Hooks section under XX-migrating.md file, I suppose it is "they use React's Context API" rather than "the use React's Content API". Please ignore this if it is not a typo. Thanks.
Fixed typos.
Fixes: #
Reviewers: @

Fix typo in XX-migrating.md

---

Readme.md
site/examples/Readme.md
site/pages/examples/[example].js

I noticed that the links to examples weren't working. Probably because they've been altered with the Next merge. This PR updates the links to point to the correct location.
Fixes: #

fix links to examples in readme and site

---

docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/03-defining-custom-elements.md
docs/walkthroughs/04-applying-custom-formatting.md
docs/walkthroughs/05-executing-commands.md

Fixing minor bugs in docs. Typos, grammar, suggestions, etc
I was taking a look at the new 0.50.0 release and doing the walkthroughs from the docs and thought I would record what I found. 
I know this whole thing was work in progress so maybe the bugs are already fixed on another branch but at least they can get some visibility here. Contributors can take whichever pieces of this PR are important. Don't have to merge the whole thing.
I also saw errors with typescript that I will ~open separate issues~ add comments here for.

Docs fixes for 0.50.0

---

Contributing.md

improved the contributors.md file to call out more explicitly that the repo must be built for lerna to work and why
Fixes: #
Reviewers: @

Update contributors.md to discuss repo setup 

---

packages/slate-react/src/components/editable.tsx

This change improves `<Editable />` prop typings by removing a few uses of `any`.
This change is not strictly backwards-compatible, but any violations are *probably* bugs.
- `React.HTMLAttributes<HTMLDivElement>` replaces `{ [key: string]: any }`
- `React.CSSProperties` replaces `Record<string, any>`
Additional type annotations are needed throughout due to poor default interface. Omitting the type parameter from each event causes it to default to (e.g.) `FocusEvent<Element>` which is slightly less-specific than the best available type `FocusEvent<HTMLDivElement>`.
This slight change in types also requires the `isEventHandled` to need slightly different types to accept them all.
Fixes: _
Reviewers: _

improve prop typings for Editable

---

docs/walkthroughs/02-adding-event-handlers.md

The previous example no longer uses `onChange`, so don't reference it in this walkthrough.
No
Documentation change
No

Update Adding Event Handlers walkthrough

---

packages/slate-history/src/with-history.ts

fix bug
Do not clean redos on some specific operations.
Fixes: #3140 
Reviewers: @

fix: lost redos when trigger set_selection (fix #3140)

---

packages/slate-react/src/hooks/use-slate.tsx

This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided.
Bug
ts error
Fixes: #
Reviewers: @

fix: ts error

---

packages/slate-react/src/components/editable.tsx

Bug
When doing `<Editable onBlur={handleBlur} />`, if the identity of `handleBlur` changes because its dependencies have changed, the `Editable` component calls the original function because the component's internal `onBlur` is memonized without specifying any dependencies.
When using the `<Editable />` React component, if the identity of event handler functions change, then the internal handlers for `onBlur` will be updated to call the new functions.
Specify `attributes.onXYZ` as a dependency for the relevant `useCallback()` callbacks.
This looks like a much larger change than it actually is due to lint formatting. Functional change is https://github.com/ianstormtaylor/slate/commit/1b2a89f2f396e52584d580de65359b58ba7c224b

Fix missing callback dependencies in slate-react <Editable />

---

packages/slate-react/src/components/editable.tsx

fixing bug
Firefox composition input work fine
Slate use React `onBeforeUpdate` event to insert text, compositionend also trigger `onBeforeUpdate` so no need to insert text in compositionend

onCompositionEnd not need to insert text in firfox

---

site/examples/mentions.js

Improvement.
Adds an auto-complete popover to the mentions example.
It uses a `<Portal />` that waits to match a specific condition of the user having their cursor after an `@` for mentioning. And while the popover is active, hotkeys are intercepted to change the highlighted item and commit or cancel a suggestion.
Fixes: https://github.com/ianstormtaylor/slate/issues/3152
Fixes: https://github.com/ianstormtaylor/slate/pull/3206

upgrade mentions example to use a portal with suggestions

---

packages/slate-schema/src/checkers.ts
packages/slate-schema/test/validations/children/min/invalid-second-with-match.js
site/examples/forced-layout.js

Fixing a bug
In some situations, a `child_min_invalid` wasn't being thrown when necessary, often involving `match` arguments in the `children` rules. This was causing the Forced Layout example to not work correctly (if you highlighted everything and deleted it, you were left with a single paragraph instead of a title and a paragraph).
- When checking child nodes, the count is now only incremented when the child node matches the `match` property (or the default empty match of `{}`)
- The Forced Layout code was expecting an `index` property in the returned error, but the `checkers.ts` file never adds an index. Instead, it looks like it sends back the full expected path of the missing node. So I updated the forced layout example to just use the full returned path instead.
Fixes: #3182 …

Fix child_min_invalid checks

---

site/pages/examples/[example].js

Fixing a bug
Reloading the page on one of the examples now stays on that example.
Seems like next.js only populates `router.query` after it pushes a route itself. There may be a cleaner solution, but parsing the starting example out of the `asPath` parameter seems to work fine for both initial load and navigating between pages and gets it fixed for now.
Fixes: #3211

Load with correct starting example

---

packages/slate-react/src/components/editable.tsx

Fixing a bug.
`<Editable autoFocus ... />` now focuses after mounting.
Editable props include `TextareaHTMLAttributes<HTMLDivElement>`, which includes an `autoFocus` props. `autoFocus` does nothing on a div element, so auto focus needs to be handled manually in a useEffect hook.

Auto focus after mounting

---

site/examples/check-lists.js

Bug.
The check list example uses `ReactEditor.findPath(editor, ...)` instead of `editor.findPath()`. This allows to uncheck and check the checkboxes again.

Fix check list example

---

packages/slate-schema/src/checkers.ts
packages/slate-schema/src/errors.ts
packages/slate-schema/src/rules.ts
packages/slate-schema/src/with-schema.ts
packages/slate-schema/test/validations/leaves/invalid-unknown.js
packages/slate-schema/test/validations/leaves/invalid-value.js
packages/slate-schema/test/validations/leaves/valid.js
packages/slate-schema/test/validations/properties/invalid-unknown.js
packages/slate-schema/test/validations/properties/invalid-value.js

Improvement.
Changes the `properties` validation to be exhaustive, and adds a `leaves` validation for the properties of the leaf text nodes.
Fixes: https://github.com/ianstormtaylor/slate/issues/3250
Fixes: https://github.com/ianstormtaylor/slate/issues/3249

fix schema properties to be exhaustive, add leaves

---

docs/walkthroughs/04-applying-custom-formatting.md

Custom Format docs typo fix: leaf -> props

---

packages/slate/src/interfaces/editor/transforms/text.ts
packages/slate/test/transforms/delete/selection/block-inline-over.js

Fixing a bug
Deleting across inlines/text nodes within a single block no longer merges the parent block with the previous block.
Instead of using `isBlockAncestor`, I hoisted the block matching from the `startVoid`/`endVoid` checks and compared the paths of the starting/ending blocks to see if the selection was across multiple blocks.
I'm not 100% confident this is the right approach (not familiar enough with Slate's internals) but all tests are passing, along with the new test I added. Also, the Rich Text example now functions as expected when backspacing into the bolded text (it no longer merges the paragraph with the one above).
Fixes: #3255

Improved merging of blocks when deleting text

---

packages/slate-react/src/plugin/react-editor.ts

Fixing a bug
Selecting a void node no longer crashes.
`ReactEditor.toDOMPoint` forces an offset of 0 if the point is inside a void node.
I have no idea how to add tests for this, but can include some with a little guidance. 
Fixes: #3239

Force a zero offset when inside a void node

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/text.tsx
packages/slate-react/src/hooks/use-isomorphic-layout-effect.ts

Fixing a bug
No warning is displayed on SSR.
Suppresses warnings on SSR when using `useLayoutEffect` by falling back to `useEffect` when `window` is `undefined`.
This same approach is used in `react-redux` and `react-beautiful-dnd`.
Neither `useEffect` nor `useLayoutEffect` is run on server. Falling back to `useEffect` on server helps to keep consistency with the number and order of hooks within a component as well as preventing the warning from showing.
Fixes: https://github.com/ianstormtaylor/slate/issues/3254

implement isomorphic layout effect

---

site/examples/paste-html.js

Fixing a bug.
Pasting nested formatting, such as `<em>One <u>Two</u></em>` works instead of crashing.
Instead of a single `jsx("text", attrs, children)` call, the children are iterated over and return their own text nodes, which seems to handle multiple nested formats. I'm not sure if this ends up creating an excessive amount of text nodes, but it seems that `Editor.insertFragment` is smart enough to merge text nodes with identical attributes.
Fixes: #3188

Fix paste example: nested formatting

---

docs/Introduction.md

Existing links (to Github) were 404ing, so I changed them to point to slatejs.org.
Also: removed the final list item linking to the rest of the examples, since I can't see a page on slatejs.org that does that. Instead, I added a line after the examples list that talks about "View Source" and links to the Github folder listing.

Docs: Fix introduction links to examples

---

packages/slate-react/src/components/children.tsx

Fixing bug
`String` inserts trailing new line when block `isLast`
A bad comparison with `node.children.length` was preventing `String` from inserting a trailing new line at the end of a block.
For instance:
```javascript
if (command.type === 'insert_break' && command.soft) {
Editor.insertText(editor, '\n')
}
...
editor.exec({ type: 'insert_break', soft: true }) // <shift><enter>
```
Previously, if soft break was inserted at the end of the block, you'd need to insert it twice to see a new line because `isLast` was never going to be `true` 😜 
Fixes: 0.52.5

Fix trailing new line in blocks

---

packages/slate-react/src/components/editable.tsx

Feature
`Editable` is able to accept an optional `as` prop which can be an intrinsic element or a component (Class or Functional).
Example:
```typescript
<Editable as="section" /> // intrinsic element "section"
<Editable as={Component} /> // functional/class component
```
If a component is passed, it must forward refs. Added an example which shows how it should be done.

Make Editable accept 'as' prop

---

packages/slate/src/interfaces/editor/queries/location.ts
packages/slate/test/queries/next/default.js
packages/slate/test/queries/previous/default.js

Improvement.
This makes the `match` argument optional to `Editor.previous` and `Editor.next`, which makes the common use case of getting the previous/next sibling easy.

add previous/next sibling query support

---

packages/slate/src/interfaces/editor/queries/location.ts
packages/slate/src/interfaces/editor/queries/node.ts
packages/slate/src/interfaces/editor/transforms/node.ts
packages/slate/src/interfaces/editor/transforms/text.ts
packages/slate/src/interfaces/node.ts
packages/slate/test/queries/nodes/match-function/one.js
packages/slate/test/transforms/liftNodes/selection/block-nested.js
packages/slate/test/transforms/moveNodes/selection/block-nested-after.js
packages/slate/test/transforms/moveNodes/selection/block-nested-before.js
packages/slate/test/transforms/moveNodes/selection/block.js
packages/slate/test/transforms/splitNodes/depth/two.js
packages/slate/test/transforms/splitNodes/depth/zero.js
packages/slate/test/transforms/splitNodes/point/block.js
packages/slate/test/transforms/splitNodes/point/inline.js

Improvement.
This changes the `NodeMatch` matching function arguments to receive just a `Node` instead of a `NodeEntry`. So before this PR it was:
```js
const match = ([node, path]) => true
```
With this PR it is:
```js
const match = node => true
```
I realized that all of the core use cases (and likely most userland ones) that used the `path` could be implemented with just the `node`. And this simplification makes it easier to use and write matching functions because you can often directly pass in helpers like:
```js
{
match: isCodeBlock
}
```
Without having to write more awkward `isCodeBlockEntry` helpers.

remove the path from node matching functions

---

site/examples/forced-layout.js

Fixing a bug
Forced layout example works. In 0.53.0, it wasn't, due to a couple issues.
- Forced layout example was destructuring the first element of a `[node, path]` array into `[path]`, so `path` wasn't actually a path. And then it was forwarding `[path]` to the next pass, instead of `[node, path]`.
- It called `Node.children` but never imported it.
Note: If the plan is to execute #3275, then this PR should be ignored and `normalizeNode` should instead be changed to only use a path. But in the meantime, the example's broken.

Fix forced layout example

---

site/examples/links.js

For the Links example, allows links to be pasted even when there is no text selected.
It checks if the current selection's anchor == focus, and if so that means that there is no selection, and it should insert text before wrapping the link.
Fixes: #

Allow links to be pasted without a selection

---

docs/concepts/01-interfaces.md
docs/concepts/09-serializing.md
docs/walkthroughs/06-saving-to-a-database.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/string.tsx
packages/slate/src/interfaces/editor/queries/location.ts
packages/slate/src/interfaces/node.ts
packages/slate/test/interfaces/Node/string/across-elements.js
packages/slate/test/interfaces/Node/string/element.js
packages/slate/test/interfaces/Node/string/text.js
packages/slate/test/queries/string/block-across.js
packages/slate/test/queries/string/block-void.js
packages/slate/test/queries/string/block.js
packages/slate/test/queries/string/inline.js
packages/slate/test/queries/string/text.js
site/examples/hovering-toolbar.js
site/examples/markdown-shortcuts.js
site/examples/mentions.js

Improvement.
Renames `Node.text` to `Node.string` to reduce confusion with "text" nodes, since it just returns the string content of the node.
Fixes: https://github.com/ianstormtaylor/slate/issues/3276

rename `Node.text` to `Node.string`

---

packages/slate/src/create-editor.ts
packages/slate/src/interfaces/command.ts
site/examples/richtext.js

Improvement.
This splits the `format_text` command into two commands: `add_mark` and `remove_mark`.
> Note: there's still no `Mark` interface, or any of its baggage. But "mark" is a useful term that tends to mean text-level formatting (eg. the `<mark>` tag in HTML) and we're using it going forward to have a way to refer to text-level custom formatting properties.
It adds two new commands that replace what `format_text` did before.
This was necessary to allow people to easily be able to write logic that **always** adds or **always** removes marks. Otherwise, with the `format_text` command you'd have to know whether it was active or not to ensure you weren't toggling it off.
This has the benefit of leaving the "active" definition for toggling up to userland, since Slate's core no longer …

split `format_text` into two commands

---

packages/slate-react/src/components/editable.tsx

bugfix
the onBeforeInput callback is created on first render and then never changed, this means that if the user renders `<Editable>` with a different value of the `readOnly` prop, the callback will never see the updated value.
it correctly memoizes the callback passing `[readOnly]` in the dependencies
Fixes: #3345
Reviewers: @

fix onBeforeInput memoization

---

packages/slate/src/interfaces/command.ts

Docs fix for function naming in docstring

deletebackward -> deleteforward

---

Changelog.md

Fixing a bug.
Changelog incorrectly called `add_mark` when `isActive` is true. Should be the opposite.

Swap remove_mark/add_mark example

---

docs/general/faq.md

Improve documentation
Added warning about Android support in Slate 0.50+
Fixed docs
Fixes: #3314
Reviewers: @

Added a warning for Android in faq

---

docs/Introduction.md

Fixing documentation bug
Link in introduction to installing slate was point to an invalid URL
Fixed the link
Fixes: #
Reviewers: @

Fix broken link in introduction of docs

---

packages/slate-react/src/components/editable.tsx

Bugfix #3362 
When undoing, call undo command and vice versa with redo
Fixes: #3362
Reviewers: @

fix: undoing and redoing are switched #3362

---

packages/slate-history/src/with-history.ts
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/plugin/with-react.ts

Bug
TS2322: Type 'Editor' is not assignable to type 'ReactEditor'.

fix: Slate editor props

---

Readme.md

Fixing a bug in the readme (incorrect link)
- [*] The new code matches the existing patterns and styles.
- [*] The tests pass with `yarn test`.
- [*] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [*] The relevant examples still work. (Run examples with `yarn start`.)
Fixes: #incorrect link to docs in the readme

fix: update incorrect link

---

docs/concepts/10-normalizing.md

It should read "edit" instead of "editor".

Chore: Typo in docs

---

packages/slate-react/Readme.md

Fixed the "Plugins" link and changed the "Constants" link (a folder which no longer exists) to a "Hooks" link.
Improving docs
The links don't 404
...
Fixes: #
Reviewers: @

Fix links in slate-react readme

---

Readme.md
docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/02-adding-event-handlers.md
docs/walkthroughs/03-defining-custom-elements.md
docs/walkthroughs/04-applying-custom-formatting.md
docs/walkthroughs/05-executing-commands.md
docs/walkthroughs/06-saving-to-a-database.md

fix: editor's exec invoke
now, editor.exec() is not available in Slate v0.57.1
so, use editor.insertText() to instead it
and other wrong in doc: 
- code blocks's info string
- delete a nerver used value

fix some doc's bug (with v0.57.1)

---

packages/slate-hyperscript/src/creators.ts
packages/slate-hyperscript/test/fixtures/selection-offset-start.js

Fixing a bug.
This currently fails on `master`:
```jsx
<selection>
<anchor offset={0} path={[0]} />
<focus offset={0} path={[0]} />
</selection>
```
The reason is because the guards for checking the truthiness of offset in `createSelection` look like this:
```js
if (!anchor || !anchor.offset || !anchor.path) {
```
This won't work for zero, since that's falsy in JavaScript. This PR fixes this.
I check if the offset if falsy and explicitly not zero. I wanted to use something like `Number.isFinite` instead, but unfortunately that doesn't work for a `number | undefined` union.

Allow zero as offset on <anchor> and <focus> inside <selection>

---

site/examples/forced-layout.js

The forced layout demo included Editor, but not Transforms, and would crash when it needed to enforce the layout.
Fixing a bug
Fixes: #3502
This adds the missing imports to the demo.
Fixes: #3502
Reviewers: @

Adds Transforms import to forced-layout demo

---

packages/slate/test/interfaces/Editor/nodes/mode-all/block.js
packages/slate/test/interfaces/Editor/nodes/mode-highest/block.js

I realized the folder names for the tests in `interfaces/Editor/nodes/mode-all` and `interfaces/Editor/nodes/mode-highest` were swapped (ie. tests for mode-all was in mode-highest and vice versa). So I fixed that.
N/A
N/A
N/A
N/A

Fix test folders name swap for interfaces/Editor/nodes

---

Readme.md

The URL to the lerna website in README.md is not working, I noticed they changed it to a new one and updated the readme

Change lernajs to correct URL

---

site/examples/embeds.js

Bug
Using the correct updated API to find Paths.
Replacing editor.findPath(element) with ReactEditor.findPath(editor, element)
Fixes: #3392
Reviewers: @thesunny

Fixed incorrect editor usage in Embed example

---

config/rollup/rollup.config.js

Fixes https://github.com/ianstormtaylor/slate/issues/3471
Fixes https://github.com/ianstormtaylor/slate/issues/3400
No new behavior. This is a fix in babel setup in `rollup.config.js`.
[Experimental JS "Rest in objects" feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) in `packages/slate-react/dist/index.es.js` & `packages/slate-react/dist/index.js` becomes a valid JS that works in older browsers.
Example:
```js
const { autoFocus, decorate = defaultDecorate, onDOMBeforeInput: propsOnDOMBeforeInput, placeholder, readOnly = false, renderElement, renderLeaf, style = {}, as: Component = 'div', ...attributes } = props;
```
becomes:
```js
var {
autoFocus,
decorate = defaultDecorate,
onDOMBeforeInput: propsOnDOMBeforeInput, …
```

Enable processing of tsx files with babel in rollup.config.js

---

packages/slate-react/src/plugin/with-react.ts

Fixes https://github.com/ianstormtaylor/slate/issues/1681
Before:
After:
This PR fixes two issues:
1. The issue described in #1681. Plain text with `\r` or `\r\n` newlines would not be pasted into slate with newlines properly.
2. Pasting plain text content with normal `\n` newlines was also not working. This was because `Transform.splitNodes` was not splitting the paragraph after each newline. Adding `{ always: true }` fixes this.
Fixes: #
Reviewers: @

Fix pasting plain text with newlines

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/dom.ts

Fixing a bug.
This fixes https://github.com/ianstormtaylor/slate/issues/3414. Basically right now Paste and Match Style type of pasting from Chrome is working properly - as well as `mod+shift+v` shortcut from other browsers.
Since these types of pastes are not emitting `beforeinput` events, I handle them in `paste` event handler. After that it's just a matter of simply passing them to `insertData` of `ReactEditor`. I want to minimize the surface area of change, so this behavior is triggered only for pastes having exclusively `text/plain` ClipboardData in them.
Fixes: https://github.com/ianstormtaylor/slate/issues/3414
Reviewers: @

Fix Paste without Formatting / Paste and Match Style producing uneditable text nodes.

---

packages/slate-react/src/components/editable.tsx

Bug #3321
Even after readOnly is switched from true to false, onChange is called.
Demo after fixed:
https://issue3321-test-slate.netlify.com/examples/read-only
https://github.com/kena0ki/slate/commit/566432e5f46e0b90431d34c52f9de58045f206b5#diff-3377000c0769495e84953bfcdd9bb9fc (Source code)
In order for onDOMSelectionChange and onDOMBeforeInput to be updated, I added dependencies to the second argument of two useCallback hooks and two useIsomorphicLayoutEffect hooks.
Although dependencies I added to useIsomorphicLayoutEffect hooks is onDOMSelectionChange and onDOMBeforeInput, an undefined variable error occurs if they are at the current location. So I moved them down below where they are defined.
Fixes: #3321

Don't use stale readOnly prop. (Fix bug #3321)

---

packages/slate-react/package.json
packages/slate-react/src/components/editable.tsx
yarn.lock

Fixing a bug
Switched slate to use `lodash/throttle` instead of `debounce` package for selection changes in slate.
I just switched the method but the main change is the throttle will execute on the leading and trailing edge of the call while debounce only executed on the trailing edge. This means that the initial change was not reflected immediately causing some bugs when we grab the selection.
NOTE: I'm not experienced with typescript. I added `@types/lodash` package but am not sure if I did this properly, whether I grabbed the right version, or whether it's necessary at all.
Fixes: #3338 

Use lodash throttle instead of debounce for updating selection change

---

Readme.md
site/examples/Readme.md

The "hovering menu" example doesn't exists. Instead, there's an example called "hovering toolbar". So I update the link to that example.
Nope.
Nope.
I just fixed an unreachable link.
No.

docs: update an example's link

---

packages/slate-react/src/plugin/react-editor.ts

fixing a _bug_:
```ReactEditor.hasDOMNode``` checks ```isContentEditable``` of editor element. When element with ```contentEditable={false}```, which is not exists in editor value (e.g., some helper element), get selection, ```onDOMSelectionChange``` [checks](https://github.com/ianstormtaylor/slate/blob/22d9095c39a0e201878e1df04ef5e35d4d86a596/packages/slate-react/src/components/editable.tsx#L385-L386) work incorrectly.
demo: 
- https://codesandbox.io/s/slate-reproductions-lblhy
- on official [check-lists demo](https://www.slatejs.org/examples/check-lists) page (click near the left of the checkbox):
```ReactEditor.hasDOMNode``` now checks ```isContentEditable``` prop of target element instead of editor element.

fix: check isContentEditable of target element in ReactEditor.hasDOMNode

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
site/examples/editable-voids.js
site/pages/examples/[example].js

This change builds on top of PR #3389 (I can rebase when it is merged since I copied into the commit).
That PR allows void nodes to have any kind of element in them and the editor events will not respond to them if the void node renders with `contentEditable={false}`, this will treat all it's children as not editable unless specified otherwise, therefore events within the void node will be treated like they are outside the editor. Currently they cannot have inputs or any other content editable areas or the editor event handlers try to interpret them as part of the main editor document, when if they are in void nodes with `contentEditable` turned off, they should be treated as isolated islands.
This behavior could be achieved with the pre 0.50.x versions, therefore some of our projects …

Fix inputs from not being able to be used within void nodes in Firefox

---

docs/Introduction.md

Hovering menu => Hovering toolbar
I am fixing invalid link in the docs

Fix invalid example link

---

site/examples/embeds.js

Bug
This PR simplifies some selection based conditional rendering that was making it hard to edit the embedded input. 
* Removed conditionals that were rendering the input only when the VideoEmbed element was selected and focused. 
* Removed the div that was providing an outline to the VideoEmbed element - this was disrupting the input's select state.
Fixes: #
Reviewers: @

fixed some bugs with the input event handler on the embeds example

---

package.json
site/next.config.js
yarn.lock

Adding a feature.
Source maps are available to the Webpack config for the Slate libraries to be included with the source maps of the site.
The source map loader makes linked source maps available to Webpack to process like the rest of the first party files.
Fixes: #3444
Reviewers: @

Make source map's of Slate libraries available to the example site Webpack config

---

site/examples/markdown-shortcuts.js

Made a fix for the fact that if you were standing in a `<li>` wrapped in an `<ul>` with no text and pressed backspace, the `<ul>` would go away while the `<li>`'s stay.
Fixing a bug
When initially you have this in your editor (with the cursor in the last list item):
And then press backspace, the following happens:
With this fix, the following (correct behaviour) occurs:
I added `split=true` at the `Transforms.unwrapNodes()` point, just like in the example on the site with lists in rich text.
Fixes: #
Reviewers: @

Fix for backspace press in list

---

packages/slate/src/transforms/selection.ts
packages/slate/test/transforms/setPoint/offset.js

Fixing a bug.
The test case included in this PR and this code currently fail on `master`:
```javascript
Transforms.move(editor); // This can be anything that triggers a selection change.
Transforms.setPoint(editor, { offset: 0 }, { edge: 'focus' }); //=> TypeError: Cannot assign to read only property 'offset' of object '#<Object>'
```
The reason for this is that after the first selection change (`Transforms.move(editor)`), Immer has frozen the selection. In `Transforms.setPoint` there's a `Object.assign` call on the selection point, which throws the TypeError. This PR fixes this.
I never try to mutate any selection points. Instead I just create a new object.

Avoid mutating the selection in Transforms.setPoint

---

packages/slate-react/src/components/editable.tsx

The cloned dom node constructed when copying must be attached to the dom for getComputedStyle to work.
This adds the div to the body as a hidden element and removes after computing its text representation.
Fixing a bug.
See above description.
See above description.
Fixes: #3505 
Reviewers: @

Attach the cloned DOM node before coputing its plaintext representation when copying.

---

site/examples/embeds.js

Fixing a bug
Cursor is not jumping to end in Embeds example
Controlled inputs need a separate state to handle proper cursor management. This PR adds a state to the input that stores the current url value.
Fixes: #
Reviewers: @

use state to avoid cursor jumping in controlled input

---

packages/slate-react/src/plugin/react-editor.ts

Bug
This fixes #3518 by allowing zero width characters to be considered editable dom targets, thereby alloing `onDOMSelectionChange` to select them.
This adds zero-width characters to the set of editable targets that are considered selectable DOM children of the editor
Examples checked:
* Mentions Example
* Editable Voids Example
* Embeds Example
* Checklist example (This defect was introduced accidentally as part of https://github.com/ianstormtaylor/slate/pull/3389)
Fixes: #
Reviewers: @

fix issue where inline voids can no longer be selected

---

Changelog.md
Contributing.md
docs/Introduction.md
docs/api/locations.md
docs/concepts/02-nodes.md
docs/concepts/03-locations.md
docs/concepts/04-commands.md
docs/concepts/05-operations.md
docs/concepts/06-editor.md
docs/concepts/07-plugins.md
docs/concepts/08-rendering.md
docs/concepts/09-serializing.md
docs/concepts/10-normalizing.md
docs/concepts/XX-migrating.md
docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/XX-using-the-bundled-source.md

I read the docs thoroughly in preparation for upgrading to 0.57 so I figured I might as well fix a few things along the way. 😉 
Updating documentation
None
N/A
- [√] The new code matches the existing patterns and styles.
- [√] The tests pass with `yarn test`.
- [√] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [√] The relevant examples still work. (Run examples with `yarn start`.)
Fixes: #
Reviewers: @

Documentation: Fix typos and other minor issues

---

docs/walkthroughs/03-defining-custom-elements.md

Updating documentation
In the defining custom elements walkthrough, when following the code and attempting to use the `Ctrl-` to switch to a code block the following error is shown:
```
ReferenceError: Transforms is not defined
onKeyDown
./pages/index.js:35
32 |   match: (n) => n.type === 'code',
33 | });
34 | // Toggle the block type depending on whether there's already a match.
> 35 | Transforms.setNodes(
| ^  36 |   editor,
37 |   { type: match ? 'paragraph' : 'code' },
38 |   { match: (n) => Editor.isBlock(editor, n) }
```
The code in the documentation appears to be missing the import of Transforms. Updated the documentation to include it resulting in a working example.
N/A
Fixes: #3462
Reviewers: @

Import Transforms in custom elements walkthough

---

docs/general/resources.md

Proposing Clause as an example of usage, which is built on top of the Accord Project Markdown Editor - based on Slate.

docs(resources): add product and editor

---

docs/concepts/02-nodes.md
docs/concepts/10-normalizing.md

No, documentation update
N/A
N/A
Fixes: Issue brought up in [Slate Slack](https://slate-js.slack.com/archives/C1RH7AXSS/p1587664807028400)

docs(concepts): include normalizing inline default behavior

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

Fixing a bug with selection not working properly if it has backwards direction.
Use `Selection` instead of `Range` so that the direction of selection is preserved.
Account for `data-slate-zero-width` nodes that have offset `0` in slate selection but `1` in DOM selection. Thanks to @JonathanWbn @kilrain for pointing this out.
Fixes: #3544
Fixes: #3531
Fixes: #3386
Fixes: #3333
Fixes: #3143
Fixes: #1969

Fix backwards selection

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/dom.ts
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts

improving a _feature_, by fixing a regression.
Previously (#1429), the equivalent of setFragmentData was pluggable, which meant we could alter the fragment used for a copy, cut, or drag. During a subsequent rearchitecture, it became impossible to do that without fully reimplementing setFragmentData.
This PR moves setFragmentData onto ReactEditor and makes it pluggable, such that a user can now do:
```ts
const withMyPlugin = <T extends ReactEditor>(
e: T,
) => {
const { setFragmentData } = e
e.setFragmentData = (data: DataTransfer) => {
console.log("My handler")
setFragmentData(data)
}
}
```
It also adds a new method `getFragment` to Editor and makes it pluggable in the same way. The default implementation is simply `Node.fragment(editor, selection)`.
Finally, setFragmentData is modified …

Make setFragmentData and getFragment pluggable in ReactEditor

---

docs/Summary.md
docs/libraries/slate-history.md
docs/libraries/slate-hyperscript.md
docs/libraries/slate-react.md

No, documentation update
N/A
N/A
Fixes: Initiates adding a `Libraries` section to the documentation. Does nothing with `slate-hyperscript`.

docs(libraries): init docs for slate sub-libraries

---

docs/api/locations.md
docs/api/nodes.md
docs/concepts/01-interfaces.md
docs/concepts/02-nodes.md
docs/concepts/03-locations.md
docs/concepts/06-editor.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/components/slate.tsx
packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/element.ts
packages/slate/src/interfaces/operation.ts
packages/slate/src/interfaces/point.ts
packages/slate/src/interfaces/range.ts
packages/slate/src/interfaces/text.ts
packages/slate/src/transforms/general.ts
packages/slate/src/transforms/node.ts

Improvement.
Mostly fixes issue #3416, superseding WIP PR attempt #3473.
(Arguably fixes a bug for TypeScript users)
As described in issue #3416, the current type interfaces for most important Slate objects looks something like this:
```ts
interface Text {
text: string;
[key: string]: any;
}
```
This PR mainly changes this and similar types to:
```ts
interface Text {
text: string;
[key: string]: unknown;
}
```
---
The original purpose of the `[key: string]: any` was to say, effectively "This `Text` object is allowed to have other key-value pairs besides `text`", which is needed.
However, because the value for every arbitrary key is of type `any`, it muffles any errors or warnings TypeScript would otherwise give, causing potential runtime errors. See below:
As in the example, `unknown` is …

TypeScript Improvement: Use `[key: string]: unknown`, not `[key: string]: any`

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

Related pull #3572 
fixing a bug
Fixes: #3647 #3648
Reviewers: @

Fixing selection across a void node (i.e. mention or image) with the mouse

---

packages/slate-react/src/components/editable.tsx

This fixes the bug reported in #3651
When the initial click into an editor controlled tree of the DOM was a void node, the `useIsomorphicLayoutEffect` handler would attempt to generate a slate range from the dom selection, except the dom selection could be anything outside of the editor and therefore not have a valid slate selection state. This would cause an exception.
This was not noticed on non-void blocks because, for some reason, the dom selection there resolves to the text node immediately and there's never a state where it is outside the editor when the `useIsomorphicLayoutEffect` event is firing.
The new behavior is that when we handle the `useIsomorphicLayoutEffect`, we check that the anchor and the focus node are inside of the editor before attempting to resolve them to slate …

fix issue #3651 where initial click on a void block can cause the editor to crash

---

site/examples/hovering-toolbar.js

Fixing the hovering toolbar hotkeys error
The default event has not been blocked before, so the code in the red box will be executed. I don't think this part of the code is necessary. Select should be handled by the plug-in itself
N/A
Fixes: #3661 
Reviewers: @

fix hovering toolbar format hotkeys

---

docs/concepts/02-nodes.md
docs/concepts/07-plugins.md
docs/general/resources.md
docs/walkthroughs/02-adding-event-handlers.md
docs/walkthroughs/04-applying-custom-formatting.md

When migrating to the latest and greatest slate, I noticed a few issues in the documentation.
Updating documentation and adding Kitemaker to the list of sites using Slate
None
N/A
No

Fix a few issues with the documentation

---

docs/general/resources.md

Adjusting for the new monorepo for Accord Project Markdown Editor.

docs(resources): adjust editor link

---

docs/walkthroughs/01-installing-slate.md

PROBLEM: "Value is defined in the upper scope (eslint: no-shadow)"
If you are trying to follow the guide using eslint there is "no-shadow" error because "value" is defined as a state variable and being used again in onChange.
FIX:
replace value with "newValue" on onChange.

Fix: ESlint Error (eslint: no-shadow)

---

docs/general/resources.md

See https://github.com/outline/rich-markdown-editor/pull/150 
Neither - fixing the docs.

Remove Outline since they switched editors

---

packages/slate-react/src/components/editable.tsx

Previously the `onPaste` handler was not being called, it was being short-circuited in the conditional.
`onPaste` handler now gets called.
Check `isHandledEvent` first in the conditional so that it does not get short-circuited.
Fixes: #3668
Reviewers: @ianstormtaylor @CameronAckermanSEL

Fix Editable onPaste handler not getting called

---

packages/slate-react/src/components/editable.tsx

fixing a _bug_ #3316
After selecting text, selection is not collapsed to leading void node.
In some cases after `selectionchange` event browser emit `click` event, especially when using mouse. Because trigger of these events is the same - `mousedown` event.
According to https://github.com/facebook/react/issues/9678 this is normal behaviour of react.
Сonsidering this fact try to check in `onClick` handler that void node is selected explicitly.
Fixes: #3316
Reviewers: @

Fix selection, if click event fired after

---

packages/slate-react/src/components/editable.tsx

Fixing a bug
Supplies the selected element specifically as a ["boundary"](https://github.com/stipsan/compute-scroll-into-view#boundary) to the scroll-into-view-if-needed library to determine whether or not Slate's selection is in the viewport.
This seems to solve well for cases where we may have multiple editors in a page, or where the bounding box of the page is not the same as the bounding box of the Slate editor.
I think longer term this behaviour _should_ be configurable in user space but this is a tactical solution to fix a broad use case and a blocker to adoption of new Slate for me and others.
See above.
Fixes: #3463 
Reviewers: @CameronAckermanSEL

Fix scrolling boundary detection (see #3463)

---

packages/slate-react/src/components/leaf.tsx

fixing a _bug_
When the placeholder is shown and the user hits ctrl + A (select all), the placeholder doesn't get highlighted.
Before the change, the placeholder got highlighted when clicking on ctrl + A:
After the change, you can't highlight the placeholder.
Fixes: #
Reviewers: @

disabled user select on placeholder

---

packages/slate/src/interfaces/path.ts
packages/slate/test/interfaces/Path/transform/move_node/ends-after-to-ends-equal.js
packages/slate/test/interfaces/Path/transform/move_node/ends-before-to-ends-equal.js

Fixing a bug I discovered while working on Slate collab OT. Added unit tests to around the fix. 

Fix path transform against sibling move operations

---

packages/slate/src/interfaces/operation.ts
packages/slate/test/interfaces/Operation/inverse/moveNode/backward-in-parent.js
packages/slate/test/interfaces/Operation/inverse/moveNode/child-to-ends-after-parent.js
packages/slate/test/interfaces/Operation/inverse/moveNode/child-to-ends-before-parent.js
packages/slate/test/interfaces/Operation/inverse/moveNode/child-to-parent.js
packages/slate/test/interfaces/Operation/inverse/moveNode/ends-after-parent-to-child.js
packages/slate/test/interfaces/Operation/inverse/moveNode/ends-before-parent-to-child.js
packages/slate/test/interfaces/Operation/inverse/moveNode/forward-in-parent.js
packages/slate/test/interfaces/Operation/inverse/moveNode/non-sibling.js

Another breaking fix, but should be safer as it seems like only slate-history uses inverse in the main packages. 
PTAL @CameronAckermanSEL @ianstormtaylor

Fix inverse of sibling move operation

---

packages/slate-react/src/components/leaf.tsx

fixing a _bug_
When writing into the editor with marked text (i.e.: bold, italic, etc.) and then deleting the text, the placeholder used to show as bold or italic according to the marked text before. Now I overrode the styles of the placeholder to not show as bold or underline or italic.
Before:
After:
Fixes: #
Reviewers: @

Overrode Mark Styles in Placeholder

---

packages/slate/src/create-editor.ts

fixing a _bug_
#3620 broke copying of void nodes with a slightly different default behaviour for getting the fragment to copy. Prior to that PR, it was not checking for an expanded range. I mistakenly introduced a stricter check, which prevented void nodes from being copied when they were the only thing selected.
With this PR, copying the image in the images example works again.
It removes the superfluous expanded range check.
Fixes: #3665
Reviewers: @CameronAckermanSEL, @lcswillems, @evasteingrims

Allow void nodes to be copied. Fixes #3665

---

docs/concepts/10-normalizing.md

Add `Transforms` to slate import so code runs when copy/pasted 😃

Add missing import in Normalization documentation snippet

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/environment.ts

Fixing a bug.
This is the behavior on Chrome 75 and lower. I tested to Chrome 65. An extra character was being inserted during render that slate didn't know about. So it blows up when you try to type again, because it can't resolve a DOM point. 
In the GIF, I typed a single `k` but 2 are rendered. Then, when you type an additional char, the crash occurs. 
This now works on Chrome 75 and lower. 
I found that in Chrome, versions below 75, when using the native `beforeinput` event was somehow causing React to fire an extra synthetic event called `textInput` that would inject an extra piece of text into the DOM. This extra character however was not inserted into the SLATE data object. 
Here is where the extra event was affecting the DOM:
By not using the native `beforeinput` this extra event …

fix older chrome support

---

packages/slate-react/src/components/leaf.tsx

Using verticalAlign: text-top was causing a slight height change when entering actual content. So typing the first letter caused the entire editor height to shrink by roughly 1px (notice the bottom edge of the editor jumping as I type)
Fixing a bug
The height no longer changes.
Remove `verticalAlign: "text-top"` from the placeholder's inline style.

Fix placeholder text alignment

---

docs/concepts/08-rendering.md

docs improvement
The additional line highlights the difference between decorations and marks
n/a
Fixes: #
Reviewers: @

minor elaboration on decorations

---

packages/slate/src/interfaces/operation.ts
packages/slate/src/transforms/node.ts
packages/slate/test/interfaces/Operation/isOperation/merge_node.js
packages/slate/test/interfaces/Operation/isOperation/split_node.js

Removing some operation properties that are not used. Looks like cruft from earlier revisions.

Remove legacy target operation property

---

packages/slate-react/src/components/editable.tsx

Resolves #3778 by checking for an editable event target before handling the paste event (calling the provided paste prop).
Does what it says on the tin. We don't want the paste handler to be firing for non-Slate nodes (e.g. an input in the React tree). I think that #3670 accidentally reordered the two calls that were being moved, so this just reorders it correctly.
N/A
Fixes: #3778 
Reviewers: @CameronAckermanSEL (since you have context)

Resolves iamstormtaylor/slate#3778: Check if editable target before handling paste event

---

packages/slate-react/src/plugin/with-react.ts

fixing a bug
`editor.insertText` is triggered by paste event too.
Fixes: #3775
Reviewers: @

Trigger editor.insertText by paste too

---

packages/slate/src/interfaces/range.ts

This is just bringing this method inline with its other equivalents. Given the first line of the function is setting a default value I think this was always intended and just overlooked.

Make Range.transform options optional

---

config/rollup/rollup.config.js
docs/api/locations.md
docs/api/nodes.md
packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/node.ts
packages/slate/src/interfaces/range.ts

Fixing a bug.
Replace the `Iterable` type used in Slate core with the correct `Generator` type.
The `Iterable` type used in Slate core is not technically correct.  What is returned from most `*functions` is a `Generator`.  The types should be updated to reflect this so you can use things like `.next()` and not have Typescript complain at you that `.next()` doesn't exist on the `Iterable` type.
Fixes: #
Reviewers: @CameronAckermanSEL, @timbuckley

Replace Iterable with Generator.

---

packages/slate-react/src/components/editable.tsx

Signed-off-by: Diana Lease <dianarlease@gmail.com>
Fixing a _bug_ as outlined in https://github.com/ianstormtaylor/slate/issues/3617
onDOMBeforeInput will update when the prop passed to `Editable` as onDOMBeforeInput changes.
Old behavior: https://codesandbox.io/s/slate-reproductions-svctp?file=/index.js:0-1406
New behavior: https://www.loom.com/share/fcf4adfa5c754cd98744fa04aacf745d
- React updates the function passed to `useCallback` when any of its dependencies have changed. I have added `propsOnDOMBeforeInput` to the dependency array for `onDOMBeforeInput`
Fixes: #3617 
Reviewers: @CameronAckermanSEL

fix(slate-react): update onDOMBeforeInput when onDOMBeforeInput prop changes (#3617)

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/utils/dom.ts

This PR would fix a bug.
According to MDN [Range/setStart](https://developer.mozilla.org/en-US/docs/Web/API/Range/setStart), there is no way to create a reverse selection. So `slate` will render a 'no-reverse' dom-selection when `editor.selection` is reverse.
It is broken when user re-render the component when selection is change. Here is an example:
```jsx
export default function Demo() {
const [currentSelection, setCurrentSelection] = useState('')
function onChange() {
const { selection } = editor
if (selection) {
setCurrentSelection(JSON.stringify(currentSelection))
}
}
return (
<Slate editor={editor} value={value} onChange={onChange}>
<Editable />
</Slate>
)
}
```
`Demo` will re-render when selection change, and then `Demo` will re-render `Editable`。
If selection is not reversed(eg …

fix inconsistent render reversed selection

---

package.json
yarn.lock

`rollup-plugin-ugliy` was removed here https://github.com/ianstormtaylor/slate/pull/3093 and replaced with the `rollup-plugin-terser` it has a security vulnerability in which the maintainers appear to also not be addressing for some time by upgrading the version of `serialize-javascript`
No Change

Remove unused dependency rollup-plugin-ugliy with security vulnerability

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/dom.ts

This pull request fixes an issue where the virtual keyboard in Chrome on Android closes when all selections are removed. The code removes all selections and adds the new selection as part of its resynchronization. However, this causes the virtual keyboard to close.
The virtual keyboard on Android does not close when resynchronizing the focus.
Instead of removing the selection and adding a new range, this change will set the selection's base and extent to the desired selection. As the selection is never lost, Chrome on Android doesn't close the virtual keyboard.
As part of this change, I also replaced `setReverseDomSelection` with `Selection#setBaseAndExtent`. As `setReverseDomSelection` assumes the selection has no range, it would not work with the previous changes. …

Fixed issue where virtual keyboard closes when resynchronizing selection in Chrome on Android

---

docs/libraries/slate-react.md
packages/slate-react/src/components/children.tsx
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/components/string.tsx
packages/slate-react/src/components/text.tsx
packages/slate-react/src/hooks/use-editor.tsx
packages/slate-react/src/hooks/use-slate-static.tsx
packages/slate-react/src/index.ts
site/examples/check-lists.tsx
site/examples/editable-voids.tsx
site/examples/embeds.tsx
site/examples/images.tsx

**Is this adding or improving a feature or fixing a bug?**
Naming/documentation improvement
**What's the new behavior?**
Renamed `useEditor` hook to `useSlateStatic` to indicate that the editor object does not re-render when changes occur. Updated documentation to differentiate between `useSlate` and `useSlateStatic`.
**How does this change work?**
`useSlateStatic` should be the hook that is used instead of `useEditor`.
**Have you checked that...?**
Does this fix any issues or need any specific reviewers?
Fixes: [#3849](https://github.com/ianstormtaylor/slate/issues/3849)

Differentiate between useSlate and useEditor hooks

---

package-lock.json
packages/slate/src/interfaces/editor.ts

fixing a bug
Slate should now guard against a node not being there so that there will never be an error thrown during the course of normalization. If a node does not exist in the tree, it will not be normalized.
editor.normalize now checks if a node exists using `Node.has(editor, dirtyPath)` **before** calling `Editor.node`
Fixes: #3902

Check if a node exists before normalization in Editor.normalize

---

packages/slate/src/interfaces/path.ts
packages/slate/test/interfaces/Path/hasPrevious/root.tsx
packages/slate/test/interfaces/Path/hasPrevious/success.tsx

Improving a feature 
A new method to address some of the concern in #3422
Add's a new method to the Path API called `hasPrevious` which checks if the path of previous sibling node exists
as per the `previous` API which returns a path, but returns an error if the path of the previous sibling does not exist, this is safe check you can make before calling `previous`
- [Y] The new code matches the existing patterns and styles.
- [Y] The tests pass with `yarn test`.
- [Y] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [Y] The relevant examples still work. (Run examples with `yarn start`.)
Fixes: #3422 
Reviewers: @

Add hasPrevious method to Path

---

packages/slate-react/src/index.ts

closes: #3960 
Based on this comment, https://github.com/ianstormtaylor/slate/pull/3941#issuecomment-718927157, we still want `useEditor` to be exported out of the package for people to use.

export useEditor back out of package

---

Contributing.md

Minor fix for the help link in the Contributing docs.
The link currently filters issues by the label [`♥ help please`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%99%A5+help+please%22) which shows zero results. But this update filters by the correct label of [`♥ help`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%99%A5+help%22) instead.

docs: update help label and link

---

packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/after/path-void.tsx
packages/slate/test/interfaces/Editor/after/point-void.tsx
packages/slate/test/interfaces/Editor/after/range-void.tsx
packages/slate/test/interfaces/Editor/before/path-void.tsx
packages/slate/test/interfaces/Editor/before/point-void.tsx
packages/slate/test/interfaces/Editor/before/range-void.tsx
packages/slate/test/interfaces/Editor/positions/voids-true/block-all-reverse.tsx
packages/slate/test/interfaces/Editor/positions/voids-true/block-all.tsx
packages/slate/test/interfaces/Editor/positions/voids-true/inline-all-reverse.tsx
packages/slate/test/interfaces/Editor/positions/voids-true/inline-all.tsx
packages/slate/test/interfaces/Editor/string/block-voids-true.tsx
packages/slate/test/transforms/moveNodes/path/text-nodes.tsx
packages/slate/test/transforms/moveNodes/voids-true/block.tsx

Fixing a bug
`Editor.next` and `Editor.previous` now return the **1st match** instead of the 2nd match.
This changes works by using `Editor.before` and `Editor.after` to find the point before/after the current position passed into `Editor.previous` and `Editor.next` respectively.
However, this implementation relies in a modification to `Editor.before`, `Editor.after`, `Editor.positions`, and `Editor.string` where all four functions now accept an optional voids parameter so that you can iterate void nodes instead of treating them as a single point. By default the option is set to false to match original behavior, but passing in `voids: true` to these functions should enable the new behavior that make this implementation work.
Finally I had to adjust two test cases because of a new issue I …

Editor.next and Editor.previous now return the first match

---

packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Element/isElement/editor.tsx
packages/slate/test/interfaces/Element/isElementList/full-editor.tsx

Adding a new feature as suggested with issue #3956.
I moved the `getDirtyPaths()` function from an external function in `create-editor.ts` into the editor object as `editor.getDirtyPaths()`, so you can override Slate's default calculation of dirty paths for an operation. It's meant to be used in conjunction with `editor.normalizeNode()` where you might want to check additional paths due to custom normalization constraints as show by this issue #3758.
To use this, you would create a plugin to override Slate's default behavior. It actually works _very_ similarly to creating custom normalization behavior for `editor.normalizeNode()`. There will be an example in the nextsection.
Most of the customizable slate functions like `editor.normalizeNode()` are created with the `editor` instance in …

getDirtyPaths can now be customized by Slate users

---

packages/slate-react/src/hooks/use-editor.tsx

Fix ```The `useEditor` hook must be used inside the <Slate> component's context.``` error since useSlateStatic introduced.
Slate will still work with useEditor
During introduce useSlateStatic, the EditorContext inside use-editor.tsx is no longer referenced and set editor instance to it.
But for old code which still use useEditor, it will get null editor value by the useEditor call. So this PR change this behaviour by share use the same EditorContext between useSlateStatic and useEditor, so they both works now.
Fixes: #
Reviewers: @

Fix useEditor not inside Slate error caused by introduce useSlateStatic

---

Readme.md

Replaced old .js links with current .tsx format
Bugfix
Readme now directs users to appropriate example code instead of 404 page.
- Old links ended in '.js' and broke when code was updated to support TypeScript
- Fixed links end in '.tsx' and work as expected 
Fixes: Docs / not a specified issue to my knowledge 
Reviewers: @BrentFarese, @timbuckley and @thesunny ☝️

Docs: Fix example code links

---

packages/slate-history/package.json
packages/slate/package.json
packages/slate/src/interfaces/node.ts
yarn.lock

Upgrading a dependency.
Hopefully none.
I'm proposing this upgrade because I've run across immerjs/immer#559, a fix for which is included in immer >= 6.0.4. This issue does not occur in Slate itself (hence why I didn't mark this PR as fixing a bug), but rather when a Slate type such as `Range` is stored in an immer-controlled container, and `transform`ed. For example this:
```typescript
let state = {
anchor: { path: [0, 0], offset: 0 },
focus: { path: [0, 0], offset: 10 },
}
state = produce(state, s => Range.transform(s, { type: 'insert_text', path: [0, 0], offset: 5, text: 'new' }))
```
will result in `state.focus.path` being a revoked proxy.
Since this changes a major version of a public dependency it is also a breaking change in Slate. However, I have verified that Slate works with …

Upgrade immer to 7.0.0

---

Readme.md
docs/Introduction.md

I recently studied Slatejs, but found that its Chinese documentation was badly behind the current version. So I translate according to the latest version of the document, and will update according to the official document.
The translated documents are up to date and will be updated later according to the official documents to facilitate Chinese developers.

docs: Update document in Chinese

---

packages/slate/src/transforms/general.ts
packages/slate/test/operations/split_node/element-empty-properties.tsx
packages/slate/test/operations/split_node/element.tsx
packages/slate/test/operations/split_node/text-empty-properties.tsx
packages/slate/test/operations/split_node/text.tsx
packages/slate/test/transforms/splitNodes/path/block-with-attributes.tsx
packages/slate/test/transforms/splitNodes/point/text-with-marks.tsx

Fixing a bug
Slate no longer clones nodes when applying a `split_node` operation. This clone is unnecessary, and it causes a problem in real-time collaboration (I'll explain at the end, it's hard to make a video so I'll try explaining it conceptually).
When Slate constructs a `split_node` operation, it ensures the operation contains all properties except `text` and `children`:
https://github.com/ianstormtaylor/slate/blob/b1f291ef88d6d0ae921e61690e3661a4962db5e9/packages%2Fslate%2Fsrc%2Ftransforms%2Fnode.ts#L634-L640
This change leverages that guarantee by not cloning the existing node when applying a `split_node` operation. I added tests for the existing behaviour to ensure it did not break, and also tests that are resolved by the change.
Given this document structure:
```
<element data> …
```

Don't clone nodes when applying a split_node operation

---

packages/slate/src/transforms/index.ts

Fixing a bug
Transforms methods respect custom types
`Transforms` is not an actual interface, and instead it combines objects that each define their own interface. These interfaces all refer to the 'ExtendedTypes', however since the Transform object generates an inferred interface during package generation, it doesn't have any extended types, resulting in an interface that uses the base types.
By explicitly combining these interfaces in the declaration we let typescript keep the extended types in the declaration for us. 
Reviewers: @BrentFarese

Mark transform type explicitly

---

packages/slate/Readme.md
packages/slate/src/interfaces/element.ts
packages/slate/src/interfaces/node.ts
packages/slate/src/interfaces/operation.ts
packages/slate/src/interfaces/text.ts
packages/slate/test/interfaces/Element/isElementList/not-full-element.tsx
packages/slate/test/interfaces/Node/isNodeList/not-full-node.tsx
packages/slate/test/interfaces/Operation/isOperationList/not-full-operaion.tsx
packages/slate/test/interfaces/Operation/isOperationList/notOperaion.tsx
packages/slate/test/interfaces/Text/isTextList/not-full-text.tsx
site/tsconfig.json

fix a bug
old code
```javascript
// packages/slate/src/interfaces/operation.ts
isOperationList(value: any): value is Operation[] {
return (
Array.isArray(value) &&
(value.length === 0 || Operation.isOperation(value[0]))
)
}
```
The old code just Determine if `value[0]` is a `Operation` Object
```javascript
// packages/slate/src/interfaces/operation.ts
isOperationList(value: any): value is Operation[] {
if (!Array.isArray(value)) {
return false
}
for (const valueItem of value) {
if (!Operation.isOperation(valueItem)) {
return false
}
}
return true
},
```
Reviewers: @thesunny

fix: `Operation.isOperationList`  just check value[0]

---

packages/slate/Readme.md
packages/slate/src/interfaces/editor.ts
packages/slate/src/transforms/node.ts
site/tsconfig.json

Feature
The NodeMatch function provided in several functions on the  `Editor` and `Transform` now takes a second parameter which is the path of the node provided as the first parameter.
This is a non breaking change.
In the editor.ts, the `Editor.levels` and `Editor.nodes` functions are the only two that explicitly call `match`, so these have been updated to account for the `nodePath` as the second parameter.
In transforms/node.ts, all match functionality is deferred to one of the two functions above but they had a different type, not `NodeMatch<T>` but `(node: node) => boolean`. This has now been updated as well.
Fixes: #3967
Reviewers: @BrentFarese

Adds path parameter to NodeMatch

---

packages/slate/src/interfaces/text.ts
packages/slate/test/interfaces/Text/decorations/adjacent.js
packages/slate/test/interfaces/Text/decorations/collapse.js
packages/slate/test/interfaces/Text/decorations/intersect.js

It seems that intersecting decorations do not separate the text correctly. This creates the problem of implementing multiple cursors when they intersect. 
I came across this when displaying the intersection of several cursors on the same line at https://slate-collaborative.herokuapp.com. Fixed it, added tests for this case.
Also relates and fix [#3714](https://github.com/ianstormtaylor/slate/pull/3714)
Now Text decorations function produce correct list of leaves.
Fixes: #3693

Fix intersected Text decorations && add tests for that case

---

Readme.md

Fixing a bug
Fixing the broken example links on the ReadMe
Fixes: #
Reviewers: @

Fixing the broken example links on the readme

---

site/examples/code-highlighting.tsx

Fixing a bug
Properly accessing properties with hyphens in them
It looks like when the syntax highlighting change originally went in during #3762, the attribute access was typed as `leaf.attr-name`, and then the linter/prettier came and added whitespace to make it `leaf.attr - name`, which is incorrect, although it doesn't 'fail' because there happens to be the global `name` variable

Fix broken attribute references

---

packages/slate/src/transforms/node.ts
packages/slate/test/transforms/moveNodes/selection/block-siblings-after.tsx
packages/slate/test/transforms/moveNodes/selection/block-siblings-before.tsx

Fixing a bug
moveNodes transform properly handles sibling moves when multiple nodes are moved
During application, 'moveNodes' uses path refs to track the nodes that are being moved, as well as the destination path. This relied on the fact that when a node is inserted, the node that was originally at that location is pushed after, so the transform would ensure subsequent moves occur after the previous ones. 
However when a sibling move occurs from an earlier to later index, the node at that location actually shifts earlier. This means when we loop through the move ops, subsequent moves end up being targeted to before the previous ones, reversing the order of the nodes. 
Detect a sibling move, and adjust the destination of the move in the loop when that's the case

Handle sibling moves in moveNodes transform

---

docs/general/resources.md

Discord uses slate
Add Discord to the list of products
**Issue**
Discord uses slate and they are not on this list
**Example**
**Checks**
- [ x ] The new code matches the existing patterns and styles.
- [ x ] The tests pass with `yarn test`.
- [ x ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ x ] The relevant examples still work. (Run examples with `yarn start`.)

Add discord to the list of products that use slate

---

site/examples/iframe.tsx

I found it 404 when I tried to access the iframe sample page
**Issue**
Fixes: none
**Example**
**Context**
I rename the `site/examples/iframe.ts` to `site/examples/iframe.tsx`, and I fix some typescript error.
**Checks**

fix: fix 404 status of iframe example page

---

lerna.json
packages/slate-history/package.json
packages/slate-history/src/history-editor.ts
packages/slate-hyperscript/package.json
packages/slate-react/package.json
packages/slate-react/src/plugin/react-editor.ts
packages/slate/package.json

Extending `Editor` did not work properly because of issues with `ReactEditor` and `HistoryEditor`.
There were two primary issues:
1. `HistoryEditor` was a type and not an interface which was inconsistent with `ReactEditor`. This was problematic in itself because there should not be two different ways to extend the editor with these plugins.
2. `ReactEditor` and `HistoryEditor` extended `Editor` which caused a circular reference which would cause them to become `any`. This was fixed by having then extend `BaseEditor` instead.
**Issue**
No issue submitted but is related to getting TypeScript working
**Example**
Since it's types, there are no examples.
**Context**
Unfortunately, TypeScript can be unpredictable, especially through published NPM packages, so the solution …

Enable Extending `Editor` types in TypeScript

---

lerna.json
packages/slate-react/package.json
packages/slate-react/src/custom-types.ts
packages/slate-react/src/hooks/use-slate-static.tsx
packages/slate-react/src/hooks/use-slate.tsx
site/examples/custom-types.d.ts

`useSlate` and `useSlateStatic` returns `ReactEditor` but we need it to return the custom `Editor`
**Issue**
n/a
**Example**
n/a
**Context**
Tried to do this by having `useSlate` and `useSlateStatic` to return the `Editor` type from `slate`; however, TypeScript seems to do an optimization which replaced `Editor` with `ReactEditor` during the build. So the workaround for now is to set it up as a generic.
**Checks**

Allow useSlate and useSlateStatic to use a generic to return a Custom Editor

---

docs/concepts/09-serializing.md

If line 170 is not added issues like https://github.com/ianstormtaylor/slate/issues/3625 start surfacing. 
Because the deserialize example is mostly directly copy-pasted into projects, the added line would save many head-scratching down the lane.
Fixes: #
Reviewers: @

Documentation: Add empty text if children are empty

---

docs/concepts/09-serializing.md
docs/concepts/11-typescript.md

In the Serializing docs, for the `serialize` function for HTML example,
we import `Node` but never use it in the scope of the example. 
Remove it to eliminate the possibility for confusion.
**Checks**

[docs] Prune import that is never used

---

docs/libraries/slate-react.md

In docs `ReacEditor.toSlatePoint` has been written twice instead of `ReactEditor.toSlatePoint` and `ReactEditor.toSlateRange`. So I updated it
**Example**
Old docs
```md
```
New docs
```md
```

docs : Update duplicated toSlatePoint to toSlateRange

---

docs/general/resources.md

No. I have simply added a line in the docs to reference a pre-packaged editor.
N/A
N/A
N/A
No
Fixes: #
Reviewers: @

docs: add react-force/slate-editor to the list of pre-packaged editors

---

packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/components/text.tsx
packages/slate-react/src/utils/range-list.ts
packages/slate/src/interfaces/text.ts
packages/slate/test/interfaces/Text/matches/undefined-false.js
packages/slate/test/interfaces/Text/matches/undefined-true.js

There are bugs with the memoization checks in the element, text, and leaf components.
The `renderLeaf` function to the Editable cannot be memoized as if it is, the rendering of leaves are not reconciled correctly on the DOM as the old node is allowed to stay despite the leaf being different. This is because the leaf element does not actually check it's text content in the memoization check.
The placeholder decorator is not re-rendered when the placeholder text is changed, this is because the element, leaf and text components do not check the decorator properties.
Bug.
The appropriate components check in the memoization comparison if two decorator range list items are placeholders, and if they are, if their text equals.
You will also be able to memoize the `renderLeaf` function when using …

Fix element memoization checks. Allows placeholder to change dynamically based on the props. Allows renderLeaf to be memoized.

---

packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/node.ts

It's fixing a performance problem.
Becasue of #4061, any call to Editor.isEditor/Element.isElement or etc. on the editor instance or an element with lots of children causes that entire tree to be walked which can be quite expensive.
Here's typing on the rich text example with ~800 root level nodes before:
After:
It memoizes `Node.isNodeList` with a `WeakMap`. I'm happy to memoize `Element.isElement` and `Editor.isEditor` as well if people want that, I just did `Node.isNodeList` because it catches the bulk of the cost. It's worth mentioning that there's the potential for this to be wrong if a node list is a node list at one point and then it's mutated and it's no longer a node list, I feel like that's not a huge issue because these things shouldn't really be mutated but just wanted to …

Memoize Node.isNodeList and Editor.isEditor

---

packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/lines.ts

This PR resolves #1623 and allows a `deleteBackward({ unit: 'line' })` to delete the current line.
This PR mimics native text editor functionality and allows the `CMD + BACKSPACE` or (`deleteBackward({ unit: 'line' })` command) to delete the current line where the selection lives.
A quick highlight of the logic for this addition:
1. Runs during the `deleteBackward` command is ran with `unit='line'`
2. The editor must have a selection value that is collapsed
3. It then finds a parent block element
4. If a parent element exists it will determine a `Range` for the current line
- This range is found by getting an array of valid positions within the parent element
- We then compare the `BoundingClientRect` of positions against the current selection to find the maximum range which is on the …

feat: delete current line when deleting backward with line unit

---

packages/slate/package.json
packages/slate/src/interfaces/text.ts
packages/slate/test/interfaces/Text/equals/complex-exact-equals.js
packages/slate/test/interfaces/Text/equals/complex-exact-not-equal.js
packages/slate/test/interfaces/Text/equals/complex-loose-equals.js
packages/slate/test/interfaces/Text/equals/complex-loose-not-equal.js
packages/slate/test/interfaces/Text/equals/exact-equals.js
packages/slate/test/interfaces/Text/equals/exact-not-equal.js
packages/slate/test/interfaces/Text/equals/loose-equals.js
packages/slate/test/interfaces/Text/equals/loose-not-equal.js

Feature
Related to the problem with the `Text.matches` function called out #3299, the `Text.equals(nodeA, nodeB)` function would incorrectly return false if a property on both nodes were equivalent objects/arrays.
This means that some consumers of this library (such as my company), who would expect Slate to merge Text nodes together if they have similar properties, to find that expectation false if they use non-primitive values for Text node properties.
The new logic merely makes use of `lodash`'s  `isEqual` function to recurse through the objects looking for discrepancies. It will also omit the `text` property for each node under `loose` mode.

`Text.equals` now works with more nested Text nodes, and non-primitive attributes.

---

packages/slate-react/src/components/editable.tsx

TS will report an error when trying to access event.inputType since it was declared of type "Event" and not "InputEvent".

Correct onDOMBeforeInput typings

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx

Fixing a bug
Instead of long placeholder values overflowing the editor bounds horizontally, we now wrap the text and have the editor grow in height.
When the `Leaf` component is rendered, grab the height of the placeholder and the editor. Then, in a `useEffect` dynamically set the editor `minHeight` to that of the placeholder.
Also removed the, now unneeded, styles from the placeholder that were causing the horizontal overlap.
Fixes: #4018, #2922

Add support for longer placeholder values

---

packages/slate-react/src/components/editable.tsx

cut do not remove void element when only select void element
**Issue**
Fixes:  no
**Example**
see context
**Context**
`onCut`  event only deleteFragment when Range.isExpanded and will do nothing when select only one void element.
this pr will remove void element when Range.isCollapsed and selection is in a void element
**Checks**
there is no tests for `slate-react`

fix: cut do not remove void element when only select void element

---

packages/slate/src/transforms/node.ts
packages/slate/test/transforms/mergeNodes/depth-block/block-nested-multi-child.tsx
packages/slate/test/transforms/mergeNodes/depth-block/block-nested-only-child.tsx

fix bug
mergeNodes will remove emptyNode which has only children node
But if emptyNode has nested multi-children node, it will also be remove.
recursive to confirm the node has only one children node
Fixes: #
Reviewers: @

fix: mergeNodes by point would delete nested multi-child node

---

packages/slate/src/create-editor.ts

feature
Normalize the node moved by a `move_node` operation.
When normalizations of a custom node depend on its parent, one currently must write them as
```typescript
editor.normalizeNode = entry => {
const [node, path] = entry
if (isCustomNode(node)) {
// parent-independent normalization
}
for (const [child, childPath] of Node.children(editor, path)) {
if (isCustomNode(child) && isCustomNodeParent(node)) {
// parent-dependent normalization
}
}
}
```
with this change this can be instead written as
```typescript
editor.normalizeNode = entry => {
const [node, path] = entry
if (isCustomNode(node)) {
// parent-independent normalization
const [parent, parentPath] = Editor.parent(editor, path)
if (isCustomNodeParent(node)) {
// parent-dependent normalization
}
}
}
```
which helps keep related …

Normalize moved node

---

packages/slate-react/src/plugin/react-editor.ts

Fixing a bug
If you put some input/textarea in your void element, the input.textarea can be focused (though still need 2nd click)
Currently, the offset counting is wrong, since the zero-length span count as length 1. This PR fix the offset counting, then the offset is correct.
Without this fix, one click will trigger in onClick one time Transform.select, and the other time Transform.select in onDOMSelectionChange, but the two select is targeting to the different range (with offset 0 and offset 1 then), because the change and the invalid offset, the click (input/textarea trying to focus) will finally got nothing. After the offset fix, finally user can focus the input/textarea inside a void element.
Fixes: #
Reviewers: @

Fix toSlatePoint wrong offset for void element.

---

packages/slate-react/src/components/editable.tsx

Currently you're unable to set spellCheck/autoCorrect/autoCapitalize attributes in browsers without support for the `onBeforeInput` event.
That's ok, because it's supposed to fix some buggy behavior, but `spellcheck` is enabled by default in firefox with no way of disabling it.
This PR fixes that, by explicitly setting these attributes to false, rather than undefined.

Disable spellCheck/autoCorrect/autoCapitalize in browsers without onBeforeInput

---

packages/slate-react/src/plugin/with-react.ts

when apply move_node operation, will trigger a fully re-render, because the parents' key is not restored. (There is a TODO comment in current code)
**Issue**
May Fixes: #3740 #3748
**Context**
This is a minimized fix, which does exactly same as those for insert_node/remove_node/merge_node/split_node, except we found the move_node common parents of source and target.
**Checks**

Fix move_node caused full re-render.

---

packages/slate/src/transforms/text.ts
packages/slate/test/transforms/delete/selection/block-void-end-hanging.tsx
packages/slate/test/transforms/delete/selection/block-void-end.tsx

This PR fixes deletion of hanging ranges that have a trailing void node. 
It follows the recommended changes that were proposed in the review of this PR https://github.com/ianstormtaylor/slate/pull/3990 by @BrentFarese.
**Issue**
Fixes #4005, Fixes #4021, Fixes #3989
Related:  #3456
**Example**
Hanging ranges that end with a void block are not currently deleted properly.
_Before:_
https://user-images.githubusercontent.com/1416436/111383592-d0ae0980-867e-11eb-9cd1-b6b9dd521e27.mp4
https://user-images.githubusercontent.com/1416436/111384510-fa1b6500-867f-11eb-9981-2d26e6ea23d8.mp4
_After:_
https://user-images.githubusercontent.com/1416436/111383754-0e129700-867f-11eb-8bed-20eb574c3b8e.mp4
https://user-images.githubusercontent.com/1416436/111384517-fdaeec00-867f-11eb-838c-2ff2 …

Fix deletion of hanging ranges with trailing void block

---

packages/slate/src/transforms/general.ts
packages/slate/test/operations/set_selection/custom-props.tsx
packages/slate/test/operations/set_selection/remove.tsx

This adds support for removing custom selection properties using `Transforms.setSelection` we use the editor.selection object to store implementation specific selection states. Without this change it's impossible to remove that state once it's set.
**Context**
This will update or delete the properties on editor.selection when the `set_selection` is applied instead of just adding. It also clones the newProperties if the current selection is null this is because immer will Object.freeze the original input selection range since that was set as a direct reference on the editor. It's written to be small not efficient so it does both delete/set in for loop even when it goes from null to selection but I think that transition is rare, it's far more common that new properties are …

added support for deleting selection properties by setting them to null

---

packages/slate-react/src/plugin/react-editor.ts

Slate-react support of Babel loose mode.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4098
**Example**
https://user-images.githubusercontent.com/79687911/109308385-c4931100-7863-11eb-8252-c0433b3baf39.mp4
https://user-images.githubusercontent.com/79687911/109310679-ac70c100-7866-11eb-935c-ba665e21a40f.mp4
**Context**
After using Babel in ReactEditor from slate-react querySelectorAll does not actually return an array and concat just adds as one element instead of expanding everything. Babel convert original code:
`var removals = [...contents.querySelectorAll('[data-slate-zero-width]'), ...contents.querySelectorAll('[contenteditable=false]')];`
into
`var removals = [].concat(contents.querySelectorAll('[data-slate-zero-width]'), …

Fixed converting querySelectorAll results to array for Babel loose mode.

---

packages/slate-react/src/components/slate.tsx

Rerender slate when focus changes. Fixes #3987
Fixing a bug
I've shown the old behavior in the initial bug report. When the editor loses focus due to the user pressing tab or escape the `useFocused` hook does not update. While debugging I found that this is due to the `Slate` wrapper not rerendering, so the `useFocused` Context Provider never receives a new value.
Here is a code snippet which can be used to demonstrate the new behavior. Without the new code `is focused` only logs when you click outside the editor. With the new behavior `is focused` logs when you tab outside of the editor or press escape.
```tsx
import React, { useEffect, useMemo, useState } from 'react'
import { createEditor, Node } from 'slate'
import { Editable, Slate, useFocused, withReact } from 'slate-react'
const …
```

rerender slate when focus changes.

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/element.tsx
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/src/hooks/use-decorate.ts

This PR will largely increase the performance of re-render caused by decorate update, in my case, avg 100+ms -> 30+ms.
You probably need first fix decorate related bug by #4137, then apply this optimize PR. Even though, this PR can be applied without that fix.
**Issue**
Fixes: 
**Context**
When decorate function updated, currently all Element get re-rendered, since memo compare failed, but the Element just for pass the decorate to Children, the only component which use decorate is Editable and Children. Well, then let's use context provider to supply the decorate to Children, and the performance is hugely improved by this.
**Checks**

Decorate re-render optimize to not re-render all elements.

---

.gitattributes

In windows git will convert the LF line breaks to CRLF by default and due to eslint configuration the eslint will throw error. If you are using eslint plugin in vscode this leads to whole screen becoming red.  Which should be avoided.
Thats why we will set the EOL to be LF in `.gitattributes ` so that git wont convert the LF to CRLF.
For reference 
- [eslint]( https://eslint.org/docs/rules/linebreak-style)
- [stackoverflow](https://stackoverflow.com/a/42135910)
**Checks**

Create .gitattributes and explicitly set the line breaks to be LF

---

docs/walkthroughs/01-installing-slate.md

Fix docs.
**Issue**
See commit.
Gotta say, the error I got with the current example is pretty non-trivial:
```
const editor = useMemo(() => withReact(createEditor()), []);
```
squiggly on `createEditor`:
```
Argument of type 'BaseEditor' is not assignable to parameter of type 'ReactEditor'.
Type 'BaseEditor' is missing the following properties from type 'ReactEditor': insertData, setFragmentData, hasRange
```
Woah, that's some sideways error, thanks TypeScript.

Stop basic installation from throwing typescript errors

---

site/examples/hovering-toolbar.tsx

I ran the example code and the underline button in `Hovering Toolbar Example` did not work.
**To reproduce**
* Run the example code for `Hovering Toolbar Example`
* Highlight text
* Click the "Underline" format button
**Checks**

Fix Underline <FormatButton /> in `Hovering Toolbar Example`

---

.changeset/four-poets-move.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate/src/interfaces/editor.ts

We will return if DOM selection is equal to `editor.selection` when we  sync DOM selection state as below
```ts
if (
hasDomSelection &&
hasDomSelectionInEditor &&
selection &&
Range.equals(ReactEditor.toSlateRange(editor, domSelection), selection)
) {
return
}
```
`ReactEditor.toSlateRange`  will call `normalizeDOMPoint(domPoint)` to normalize a DOM point so that it always refers to a text node nearby as comment says.
think of DOM structure below
```
<span>
<span contentEditable={false}></span>
<cursor>
<span data-slate-node="text">
<span data-slate-leaf="true" >
<span data-slate-string="true">xx</span>
</span>
</span>
```
there is no need to sync DOM selection without this PR。but if typing `测试` using IME it will result in 
```
<span>
<span contentEditable={false}></span> …
```

feat: sync selection to extactly matched DOM selection

---

.changeset/lovely-walls-knock.md
packages/slate-react/src/components/leaf.tsx

this pr will force `String` element refresh it self to avoid ime double input
**Issue**
No
**Example**
**Context**
while we should get 
this is becasue we memoizedLeaf to avoid refresh. now we will refresh all sibling leaf when a leaf changes
**Checks**

fix ime double input with mark

---

docs/walkthroughs/01-installing-slate.md

This PR updates TypeScript link in the `Installing Slate` documentation for new users to a valid reference. Looks like this URL changed in the past, so this is just fixing a 404. Thanks!

Updates outdated TypeScript link in first walkthrough document

---

.changeset/giant-adults-matter.md
packages/slate/src/transforms/general.ts
packages/slate/src/transforms/text.ts

There's no need to remove_text of 0 length, so prevent that from happening.
It's arguably an optimization, and some plugins that hook into editor.apply may balk this happening.  So, it seems like a good idea to do in general.  If you don't agree with this, then just close this PR.
**Checks**

Save some remove_text calls if the text is zero length

---

.changeset/two-lies-appear.md
packages/slate/src/create-editor.ts
packages/slate/src/transforms/node.ts
packages/slate/test/transforms/setNodes/text/merge-across.tsx

This pull request aims to solves a couple of things:
- In setNodes, if splitting has to happen, it should be set to always at :
- [start](https://github.com/ridhambhat/slate/blob/d808c4ba6f36829064dc2cce42bcb502502343ca/packages/slate/src/transforms/node.ts#L603-L610) if anchor is not at the start of the node
- [end](https://github.com/ridhambhat/slate/blob/d808c4ba6f36829064dc2cce42bcb502502343ca/packages/slate/src/transforms/node.ts#L595-L602) if focus is not at the end of the node
- In [normalizeNode](https://github.com/ridhambhat/slate/blob/d808c4ba6f36829064dc2cce42bcb502502343ca/packages/slate/src/create-editor.ts#L195), while iterating through children, the variable [prev](https://github.com/ridhambhat/slate/blob/d808c4ba6f36829064dc2cce42bcb502502343ca/packages/slat …

Correcting the splitting logic in setNodes

---

packages/slate/src/interfaces/editor.ts

This includes [various refactorings to Editor.positions](https://github.com/ianstormtaylor/slate/pull/3644#issuecomment-623120703) to make the function easier to work with in the future.
**Context**
`Editor.positions` had a bug #3458 that was fixed in PR #3644, along with several refactorings to the function ([see overview](https://github.com/ianstormtaylor/slate/pull/3644#issuecomment-623120703)).  PR #3644 was never merged, however, and later later the same bug was fixed in PR #4073, which was merged.
While the fix is no longer necessary, based off [discussions in #3644](https://github.com/ianstormtaylor/slate/pull/3644#issuecomment-818813221) it seems useful to include these refactorings in any case, and this PR contains these refactorings plus a few minor differences …

refactor: New Editor.positions based off PR#3644

---

site/examples/shadow-dom.tsx

Fix 404 page not fuond when I access to `examples/shadow-dom`.
**Issue**
I couldn't find the related issue.
**Example**
Before:
After:
**Context**
rename `shadow-dom.js` to `shadow-dom.tsx`,  
then update type hints to compile successfully.
**Checks**

fix: shadow-dom example not found in examples

---

.changeset/thick-apricots-fly.md
cypress/integration/iframe.ts
packages/slate-react/src/plugin/react-editor.ts

Fixes iframe crashes
Context: The exception is thrown if an editor root element does not inherit from `Document`. However an document inside iframe will never inherit the same prototype as `window.document`, this change prevents triggering this exception if we are inside an iframe
**Issue**
Fixes: #4170
**Example**
Currently the iframe example crashes with the exception `Unable to find DocumentOrShadowRoot for editor element ...`
With this change it works again:
**Checks**

Fix iframe crash

---

.changeset/move-word-collapse.md
packages/slate-react/src/components/editable.tsx

This PR fixes the `moveWordBackward` / `moveWordForward` hotkey handling of `slate-react`. 
**Issue**
I could not find any existing related open issues.
The  `moveWordBackward` / `moveWordForward` hotkeys need to collapse expanded selections before moving the selection by word. The current behaviour is not aligned with how selection is moved in unmanaged `contenteditable` elements nor is it aligned with how other text editors work.
**Example**
_Before:_
https://user-images.githubusercontent.com/1416436/115253692-9eb71980-a0fa-11eb-83a8-e20eca5f4a06.mp4
_After:_
https://user-images.githubusercontent.com/1416436/116178116-fa793800-a6e2-11eb-9cbc-c6520d25407d.mp4
Slate above, native Textarea element below for reference
**Checks**

Collapse expanded selection before move word hotkey

---

.changeset/drag-and-drop.md
packages/slate-react/src/components/editable.tsx

This PR fixes a number of different issues that happen today with drag and drop. 
It's loosely based off of this abandonned PR: https://github.com/ianstormtaylor/slate/pull/3562
**Issue**
Fixes: 
https://github.com/ianstormtaylor/slate/issues/4222
https://github.com/ianstormtaylor/slate/issues/3522
https://github.com/ianstormtaylor/slate/issues/3137
https://github.com/ianstormtaylor/slate/issues/2076
**Examples**
https://user-images.githubusercontent.com/1416436/117067981-b1d00900-acf8-11eb-9271-df09e50ed963.mp4
https://user-images.githubusercontent.com/1416436/117067990-b4326300-acf8-11eb-838f-feb8b49c23f3.mp4
https://user-images.githubusercontent.com/1416436/117202852-51a29b00-adbc-11eb-8f0e-b9f20718ee33.mp4
https://user-images.githubusercontent.com/1416436/117068035-c14f …

Fix duplicated content and other bugs related to drag and drop handling

---

.changeset/bright-pants-grin.md
.changeset/sixty-glasses-beg.md
packages/slate/src/interfaces/editor.ts
packages/slate/src/transforms/general.ts
packages/slate/test/transforms/general/invalid-insert_node.tsx

Applying an `insert_node` operation now throws an exception if the path to insert is invalid. Previously it only threw an exception if the parent path doesn't exist.
**Context**
This came up while developing our collaborative editor based on Slate. Allowing invalid `insert_node` operations means a mistake in the transforms is not picked up immediately; it only causes a failure when a subsequent operation depends on the invalid insert. This makes bugs harder to track down, and is inconsistent with how every other operation is applied.
Other operation apply cases throw an exception when the operation is invalid - either directly or implicitly by calling `Node.get`. `insert_node`, however, only used `Path.parent` and then `splice` directly on the children array. Splice does …

Added insert_node path checking to match how other operations are applied

---

.changeset/silver-snakes-perform.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/transforms/normalization/move_node.tsx
packages/slate/test/transforms/normalization/split_node-and-insert_node.tsx

There are some edge cases in Slate that result in `editor.normalizeNode()` triggering the exception `Error: Cannot get the start point in the node at path [...] because it has no start text node` after a valid action.
**Example**
There aren't any features of `slate-react` that trigger this but it's quite easy to replicate in a collaborative editor. I've added two test cases; `move_node` is the simplest code I could find that replicates the bug, `split_node` is the one that came up in my production code.
**Context**
The problem stems from normalization fixes that depend on valid document state. The normalization logic attempts to fix problems in an order that prevents this from being a problem, but sometimes it just isn't possible. The specific normalization fix that these …

Apply no-children normalization fix before normalization

---

.changeset/forty-mails-roll.md
packages/slate-react/src/components/editable.tsx

#4118 and #4150 introduced IS_FIREFOX_LEGACY, but this block of code was not updated to reflect that. This breaks insertion of emoji and unicode characters in slate-react. This change fixes #3855.
As noted in #3855, Firefox crashes when inserting emoji using the emoji keyboard.
**Issue**
Fixes: #3855
**Example**
This fixes an obviously overlooked update/typo. The example in #3855 shows the issue before this change. With this fix, the editor behaves as expected (doesn't crash when inserting an emoji)
**Context**
Correct a typo
**Checks**

Update IS_FIREFOX_LEGACY flag to prevent FF crash

---

.changeset/three-parrots-remember.md
packages/slate/src/create-editor.ts

Collaborate editor relies on onChange and editor.operations, but in editor.addMark and editor.removeMark, onChange is called directly without check it was already scheduled by editor.apply method. which will cause onChange with same group or part of same group of editor.operations be called twice, then cause problem with collaborate editors.
**Issue**
**Context**
This PR simply check whether there was already a scheduled onChange, if so, do not call onChange in addMark and removeMark.
**Checks**

Fix addMark/removeMark caused unexpected onChange.

---

packages/slate-history/test/undo/delete_backward/block-text.tsx
packages/slate-history/test/undo/delete_backward/custom-prop.tsx
packages/slate-history/test/undo/delete_backward/inline-across.tsx
packages/slate-history/test/undo/insert_break/basic.tsx
packages/slate-history/test/undo/insert_fragment/basic.tsx
packages/slate-history/test/undo/insert_text/basic.tsx
packages/slate-history/test/undo/insert_text/contiguous.tsx
packages/slate/test/interfaces/Node/ancestor/success.tsx
packages/slate/test/interfaces/Node/child/success.tsx
packages/slate/test/interfaces/Node/descendant/success.tsx
packages/slate/test/interfaces/Node/get/root.tsx
packages/slate/test/transforms/delete/unit-line/text-end.tsx
packages/slate/test/transforms/delete/unit-line/text-start-reverse.tsx

[ This was previously reported as PR #3718 last June, but never merged.  I closed that PR in favor of this. ]
Several round-trip tests, tests that check that the output is the same as the input, set `output = input`, which means both input and output point to the same object.  By the looks of it, when the input is modified the output is as well, making the tests no-ops.
We need to do deep copy instead of shallow/reference copy, and when this is done by this PR, 4 tests, that by the looks of it previously should have failed, now start to fail:
- slate-history / undo / delete_backward / block-text
- slate-history / undo / delete_backward / custom-prop
- slate-history / undo / delete_backward / inline-across
- slate / interfaces / Node / get / root
This PR converts `const output = input` to …

Ensure round-trip tests don't mutate output before checking against it => reveals 4 tests are broken

---

.changeset/red-bears-cry.md
packages/slate/package.json
packages/slate/src/interfaces/text.ts
yarn.lock

This PR removes the dependency on `loadsh/omit` reducing bundle size by ~50Kb
> Edit: The scope of this has expanded to replace all usages of lodash, see below
**Example**
Before
After
**Checks**

replace lodash depency in slate

---

packages/slate-react/src/index.ts

The `Editable` and `AndroidEditable` are not exported. Some people need access to these as exports.
**Issue**
n/a
**Example**
n/a
**Context**
@clauderic has mentioned they need access to the default `Editable`.
**Checks**

Add DefaultEditable and AndroidEditable to exports

---

.changeset/fix-globalthis-errors.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/environment.ts

This PR fixes errors thrown in [browsers that do not implement](https://caniuse.com/mdn-javascript_builtins_globalthis) the [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) global object.
**Issue**
I could not find any open issues related to this. This is a fairly recent issue introduced by this commit https://github.com/ianstormtaylor/slate/commit/6a1376332bbd2567336c444c57c1e64fdf706feb
**Example**
Before:
After:
**Checks**

Fix errors accessing `globalThis` in browsers that do not implement it

---

.github/workflows/release.yml

There was an issue with the `0.64.0` release of `slate-react` not properly being tagged under `latest` on npm. 
**Example**
**Context**
This happened because the `dev` workflow ran before the `latest` workflow, and it noticed that `slate-react@0.64.0` hadn't been published yet and decided to publish it. 
By the time the `latest` workflow ran, the `dev` workflow had already released 0.64.0 so it resulted in a no-op.
This could arguably be a bug in changesets, though I think this PR is still the right solution, we should run the `latest` workflow before the `dev` workflow.
**Checks**
cc @circlingthesun

Update release workflow to ensure that the `latest` job runs before the `dev` job

---

.github/workflows/release.yml

Setting max parallel number of jobs to 1 and updated the job order so that the `latest` job runs before the `dev` job.
The `yarn changeset publish` command deletes files in the .changesets folder, so it's not safe to run two changeset steps in the same job.
Which means that by the time the `snapshot` release command runs, there are no changesets found and it exits early:
**Issue**
Follows-up on #4291 and #4274

Revert to using matrix for release workflow

---

.changeset/metal-suits-reply.md
packages/slate-react/src/components/editable.tsx

Wile running tets in Jest, I received multiple warning related to issues on `autoCorrect` and `autoCapitalize`. It appears there was already an opened issue on this subject.
Related warnings are:
```txt
Warning: Received `false` for a non-boolean attribute `autoCorrect`.
Warning: Received `false` for a non-boolean attribute `autoCapitalize`.
```
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4248
**Example**
A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If …

FIX warnings related to `autoCorrect` and `autoCapitalize`

---

.changeset/chilly-gifts-dance.md
.changeset/override-event-handlers.md
docs/libraries/slate-react.md
packages/slate-react/src/components/editable.tsx

From the [Slate Slack channel](https://slate-js.slack.com/archives/CC58ZGGU9/p1622124885032100):
We noticed that our own custom dnd behavior broke with the upgrade to 0.63 due to the changes introduced in this [PR](https://github.com/ianstormtaylor/slate/pull/4238). For some context: We use react-dnd to enable users, among other things, to drag Nodes next to each other to automatically set up column layouts. Thus, while we want to use Slate's internal dnd logic in some cases, we need to prevent the default logic in others.
The root cause of the issue lies within the `state.isDraggingInternally` property that was introduced and that is set in the `onDragStart` handler. Unfortunately, it is not possible to overwrite `onDragStart` and prevent the default logic on the Editable …

Allow control of Slate's event handler execution in custom event handler API

---

.changeset/delete-inline-void.md
packages/slate-react/src/components/editable.tsx

This PR fixes deletion of selected inline void nodes in Chrome. Chrome does not fire a `beforeinput` event when deleting backwards within an inline void node, so we need to add special logic to handle this edge-case for Chrome only.
Both Firefox and Safari do not exhibit this behaviour, and fire the `deleteContentBackward` / `deleteContentForward` beforeinput event when deleting backward/forward in a void inline node.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/3456
**Example**
https://user-images.githubusercontent.com/1416436/120367264-a9aabf80-c2de-11eb-917c-98673f776800.mp4
https://user-images.githubusercontent.com/1416436/120368409-09559a80-c2e0-11eb-8f4c-63dd1c323335.mp4
https://user-images.githubusercontent.com/1416436/120367276-ab748300-c2de-11eb- …

Fix handling of delete in Chrome when inline void node is selected

---

.changeset/bright-cameras-drum.md
packages/slate-react/package.json
packages/slate-react/src/components/editable.tsx

#3835 accidentally started bundling a chunk of `slate-history` inside `slate-react` ([this change](https://github.com/ianstormtaylor/slate/pull/3835/files#diff-1d0c52ec4c5562d96965f789988bd4efd4a6d24b88527918987d06bcc43d15adL769-R770)). The fix for now is to revert the change (plus some TypeScript shenanigans now that `ReactEditor` is more strictly typed). A more complete fix would require either:
* Moving the history type and `isHistoryEditor` code into core (not ideal)
* Exporting events that would allow `slate-history` to hook into the keyboard events itself (see [slack thread](https://slate-js.slack.com/archives/CC58ZGGU9/p1621280180168400))
**Issue**
Fixes: Bundle regression caused by #3835
**Example**
It's easy to confirm; after `yarn build:rollup` open …

Don't import slate-history to slate-react

---

.changeset/safari-backwards-typing.md
packages/slate-react/src/components/editable.tsx

Safari doesn't always remove the selection, even if the contenteditable element no longer has focus. In this scenario, we need to forcefully remove the selection on blur https://stackoverflow.com/questions/12353247/force-contenteditable-div-to-stop-accepting-input-after-it-loses-focus-under-web
**Issue**
I could not find any open issues related to this specific bug. There are other issues open with regards to backwards typing bugs but they are unrelated.
**Example**
To replicate, I simply added a button in the toolbar that calls `ReactEditor.blur(editor)` when clicked:
https://user-images.githubusercontent.com/1416436/121074881-75ce0f00-c7a2-11eb-94e7-9f3fb3356943.mp4
https://user-images.githubusercontent.com/1416436/121074888-7797d280-c7a2-11eb-8a80-122ec2754b0b.mp4 …

Fix backward typing bug in Safari by ensuring the selection is removed on blur

---

packages/slate/src/interfaces/editor.ts

This PR exposes an API on Editor to control the normalization state. The reason for exposing this is `withoutNormalizing` is not sufficient in complex systems. Imaging a complex product where slate is just one collaborative surface. The main operation sync loop might look something like:
```
onOperationBatchReceived(ops: Operations): void {
this.emit(START_BATCH);
for (const op of ops) {
// Not every op in a batch has the same objectId
const obj = findObj(op.objectId);
// Not every object here is a Slate Editor and the API is a shared interface for all collaborative objects
obj.apply(op);
}
this.emit(END_BATCH);
}
```
The op batches are handled at a level and abstraction above slate which makes applying all operations in a withoutNormalizing callback difficult. Instead our SlateEditor …

Expose interface to setNormalizing

---

.changeset/safari-delete-inlinevoid.md
packages/slate-react/src/components/editable.tsx

This PR fixes the deletion of inline void nodes on Safari. It's basically an extension of #4307, so it applies also in Safari.
**Issue**
Fixes: #4330 
**Example**
**Checks**

fix: fix deletion in safari when inline node is selected

---

packages/slate/test/operations/move_node/path-not-equals-new-path.tsx

Added test for the `move-node` operation when `path` is not equal to the `new path`.
**Checks**
~- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)~

Added test for 'move-node' operation

---

docs/concepts/12-typescript.md
docs/walkthroughs/01-installing-slate.md

In the docs, this adds annotations to `useState` and the editor's initial values to avoid typing errors.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4280
**Before**
**After**

Fix typescript docs

---

.changeset/sixty-ties-fetch.md
packages/slate-react/src/components/leaf.tsx

Currently memoization uses `Text.matches` to compare new and previous leaf. This means that any new property added to a leaf — for example a decoration — will not cause the leaf to be re-rendered.
**Example**
Our editor supports a “tracking changes” mode. Among other things this means that when you delete text it's not removed from the editor, but marked as deleted. The problem occurs when user tries to remove an entire paragraph:
while paragraph is marked as removed, this is not reflected in the UI. This is because the decoration spans whole paragraph, and so the only change is addition of a new property to the leaf, which is not considered a change by `Text.matches`. When using `Text.equals` this works fine:
Note that I've tested this change on 0.59, but it should work …

Re-render leaf when new properties were added to it

---

.changeset/poor-moose-approve.md
packages/slate-react/src/components/editable.tsx
site/examples/scroll-into-view.tsx

When typing at the bottom of the Editor, the editor will always scroll into view; however, the parent scrollable containers won't scroll into view.
**Issue**
Noticed this issue independently but I think it may resolve the below issue as well.
Fixes:
https://github.com/ianstormtaylor/slate/issues/3750
**Example**
See https://github.com/ianstormtaylor/slate/issues/3750
**Context**
This is a very small change that removes the `boundary` option of `scrollIntoVIew` which limits the scrolling to the editor.
```ts
scrollIntoView(leafEl, {
scrollMode: 'if-needed',
// boundary: el,
})
```
Note: I added an examples to the `examples` folder to see this in action. I kept it there so that if there were issues with the solution, the framework to look at the issue doesn't have to be …

Fix scroll into view to scroll parent scrollables

---

Readme.md

The contribution heading on `ReadMe.md` refers to a file that doesn't exist, This Pull Request aims to solve that issue.
**Example**
Currently, it takes you to [this page](https://github.com/ianstormtaylor/slate/blob/main/Contributing.md) (which obviously doesn't exist).
This Pull Request will change the link to the [contribution](https://github.com/ianstormtaylor/slate#contributing) part on `README.md`

Fix contributing link

---

docs/walkthroughs/01-installing-slate.md

The markup ` ```typescript jsx ` doesn't render properly on [https://docs.slatejs.org/walkthroughs/01-installing-slate](https://docs.slatejs.org/walkthroughs/01-installing-slate), because it's not supported by GitBook. This PR changes it to just  ` ```typescript ` (without the `jsx`) to fix the issue.
**Issue**
Fixes: n/a
**Example**
**Context**
The change is trivial.
**Checks**

Fix display bug in GitBook

---

docs/api/nodes/editor.md

Fix broken link in docs.
I'm not sure if a changeset is needed for a simple broken link docs fix?
**Issue**
Fixes: https://docs.slatejs.org/api/nodes/editor was linking to https://github.com/ianstormtaylor/slate/tree/a02787539a460fb70730085e26df13cca959fabd/concepts/07-plugins/README.md which is incorrect. Fixed with the right relative path.
**Example**
Trivial: Broken link.
**Context**
Trivial
**Checks**

Fix broken plugins link in Editor documentation

---

docs/walkthroughs/01-installing-slate.md

The useEffect Hook is imported, but is not actually being used in any of the examples on the page. The import is redundant; there's no reason to keep it.
**Issue**
Fixes: n/a
**Example**
**Context**
The change is trivial.
**Checks**

Remove unused useEffect import

---

cypress/integration/examples/shadow-dom.ts
site/examples/shadow-dom.tsx

Adds a cypress test for the shadow dom examples
**Video**
https://user-images.githubusercontent.com/2987087/128340496-7ad85e5f-5a2e-4ad3-9638-f05ef4e2d998.mp4
**Checks**

cypress: shadow-dom example test

---

packages/slate/test/interfaces/Editor/positions/all/inline-normalized.tsx

This PR adds a test case to cover the bug in positions reported in #4103. The bug has been fixed but the test case has been added to prevent regressions.

add test case to cover issue from #4103

---

.changeset/khaki-readers-battle.md
packages/slate/src/transforms/node.ts
packages/slate/test/transforms/wrapNodes/block/omit-all.tsx

`Transforms.wrapNodes` attempts to detect when zero nodes match, but it missed an edge case where one node matches - the editor. The function very quickly throws `Error: Cannot get the parent path of the root path []` when this happens.
**Example**
The test shows the failure condition. The editor I'm working on supports `contenteditable=false` sections in document content, and while we are able to handle most of the filtering outside of slate this is one case that is difficult to handle without a lot of extra code.
**Context**
There are a few other ways I can think of to fix this - such as wrapping the supplied `match` function to enforce `!Editor.isEditor` - but this seemed like the least invasive way to deal with it.
**Checks**

Skip wrapping nodes when the only match is an editor

---

.changeset/four-kangaroos-invite.md
packages/slate-react/package.json
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/test/index.js
yarn.lock

The combination of https://github.com/ianstormtaylor/slate/pull/4152 and https://github.com/ianstormtaylor/slate/pull/4138/ broke decoration in `Editable`: the `decorate` function is not called on immediate children of the editor (because the function is retrieved from a React context before the context is set).
This change fixes the bug by adding a wrapper component around each child in `useChildren`, so the context is set by the time we retrieve the `decorate` function.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4277
**Example**
A `decorate` function passed to `Editable` is called on the immediate children of the editor.
**Context**
As above, the issue is that a React context (added in https://github.com/ianstormtaylor/slate/pull/4138/) is used …

fix bug: decorate is not called for immediate children of editor

---

.changeset/tricky-moles-battle.md
packages/slate-react/src/components/editable.tsx

Don't show the placeholder when composing.
**Issue**
I found a related issue #4306 but it's closed. I think this issue should be handled inside the editable component because hiding placeholder when composing is an expected behavior.
**Example**
Old behavior:
https://user-images.githubusercontent.com/13460383/123546900-27a0a000-d791-11eb-967c-b188a9a927a2.mov
New behavior:
https://user-images.githubusercontent.com/13460383/123546923-3edf8d80-d791-11eb-8b9a-9490d862bfdd.mov
**Checks**

Don't show the placeholder when composing

---

.changeset/metal-trees-rest.md
packages/slate-react/src/components/editable.tsx

Fix a bug
IME input won't duplicate.
IOS chrome looks just fine, so no need special code on compositionEnd to insertData.
Fixes: #
Reviewers: @

Fix ios chrome ime double input issue.

---

.changeset/quiet-teachers-kneel.md
packages/slate-react/src/plugin/with-react.ts

It is highly useful to get a copy of the exact selection and it is available in slate-react as e.setFragmentData. Unfortunately the type definition currently requires a DataTransfer object which is difficult to stub as this object comes from ClipboardData or drag-n-drop events. In practice, the only requirement slate-react actually needs is getData/setData. Users could provide a data object that looks like this (let me know if this should be provided as a utility method):
```
const getDataTransfer = () => {
const storage = new Map()
return {
getData: (key: string) => storage.get(key),
setData: (key: string, value: string) => storage.set(key, value),
}
}
```
**Issue**
Fixes: Allows an easy way to get access to the slate tree in `application/x-slate-fragment`, `'text/html'`, …

Allow setFragmentData without clipboardData object

---

packages/slate-react/src/components/android/use-android-input-manager.ts

See https://github.com/ianstormtaylor/slate/pull/4417#discussion_r684247757
**Context**
https://github.com/ianstormtaylor/slate/pull/4417
**Checks**

Fix useTimeout type to use browser type instead of nodejs type

---

cypress/integration/examples/code-highlighting.ts

The introduction of a test in #4409 was not allowing sufficient time for the test to succeed. This test was causing failures in unrelated PRs such as #4037 and #3888.
**Issue**
Fixes: Failing test due to insufficient default timeout.
**Checks**
No changeset as this lives outside the packages covered by changesets.

prevent code highlighting test failure due to timeout

---

site/examples/search-highlighting.tsx

The Ui for the search highlighting example had a search icon and a placeholder. They were overlapping and were not aligned with each other.
This small PR fixes this and ensures that they don't overlap.
BEFORE THE CHANGE:-
AFTER THE CHANGE:-
**Checks**

[Small-Fix] Small UI fix for the search icon and placeholder of the search highlighting

---

docs/libraries/slate-react.md

This is a small addition to the documentation of the sub-library Slate React.
Slate React implements a React and DOM-specific version of the `Editor` interface called `ReactEditor`.
It has a method named `toSlateRange` for translating a Slate range from a DOM range. This method accepts up to three parameters:
- editor: ReactEditor (required)
- domRange (required)
- an optional third parameter that is an object with property `exactMatch` and value is a boolean.
However, the current version of the documentation doesn't mention this parameter.
**Example**
Example of this implementation can be found at the `Editable` component of `slate-react`, inside the custom `onDOMSelectionChange`.
```
const onDOMSelectionChange = useCallback(
throttle(() => {
if (...) {
const root = …
```

feat(docs): mention third parameter to `toSlateRange` method in the docs

---

.changeset/rich-wasps-leave.md
packages/slate/src/interfaces/element.ts
packages/slate/test/interfaces/Element/isElement/elementType.tsx
packages/slate/test/interfaces/Element/isElement/isElementDiscriminant.tsx
packages/slate/test/interfaces/Element/isElement/isElementDiscriminantFalse.tsx
packages/slate/test/interfaces/Element/isElement/isElementType.tsx
packages/slate/test/interfaces/Element/isElement/isElementTypeFalse.tsx

Trying to add isElementType function support like what suggested in the proposal
**Issue**
#4327 
**Example**
https://user-images.githubusercontent.com/16449020/123110300-87840780-d46e-11eb-965e-3e1c9d4666bd.mp4
**Context**
Not sure if this is the correct implementation like what suggested in proposal, since node.type will has type `string` instead of the string literal like implemented in CustomType. I hope there is a suggestion about how to make it become string literal
**Checks**

feature(slate): Add isElementType utility function to Element Interface

---

.changeset/itchy-poems-lie.md
packages/slate-history/package.json

As discussed in https://github.com/ianstormtaylor/slate/pull/4050#issuecomment-887904120 immer was upgraded in slate-history but it was not published (this was before the changeset auto-publish system was introduced). Merging this means the package will be included in the next publish.
**Issue**
Follow up to: #4050
**Context**
I can't find any reference to `immer` in the current `slate-history` code so this should be safe.
**Checks**

Remove unused slate-history dependency on immer

---

.changeset/real-jobs-bow.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/use-children.tsx

The combination of #4152 and #4138 broke decoration in `Editable`: the `decorate` function is not called on immediate children of the editor (because the function is retrieved from a React context before the context is set).
I fixed this in #4394 by adding a wrapper component around each child in `useChildren`, so the context is set by the time we retrieve the `decorate` function.
But after some discussion with @ulion (on #4277 and #4394) I think it's better not to wrap every child, but only the immediate children of `Editable`; this achieves the same thing without adding extra layers to the render tree. And since the immediate children of `Editable` are not passed to `renderLeaf`, it's not necessary to wrap them individually for #4152. So this change reverts the changes …

fix decorate bug (#4277) without adding extra layers of render tree

---

.changeset/spotty-squids-walk.md
packages/slate/src/transforms/node.ts
packages/slate/test/operations/set_node/remove-null.tsx
packages/slate/test/operations/set_node/remove-undefined.tsx
packages/slate/test/transforms/unsetNodes/operation-contents-check.tsx
packages/slate/test/transforms/unsetNodes/text.tsx

Having `null` values in `set_node` operations is unnecessary, thanks to #4078, and adds complexity to collaboration transforms.
**Issue**
Follow up to #4078
**Context**
After #4078 was submitted @ianstormtaylor suggested omitting removed keys, rather than setting them to `null`, which was a much cleaner solution. This tidies up the last place that null values might be set.
**Checks**

Don't set null in set_node newProperties when using unsetNodes

---

.changeset/orange-jeans-sing.md
packages/slate/src/transforms/general.ts
packages/slate/test/normalization/text/merge-adjacent-empty-after-nested.tsx
packages/slate/test/normalization/text/merge-adjacent-empty-after.tsx
packages/slate/test/operations/remove_node/cursor-nested.tsx
packages/slate/test/operations/remove_node/cursor.tsx
packages/slate/test/transforms/mergeNodes/path/text-hanging-nested.tsx
packages/slate/test/transforms/mergeNodes/path/text-hanging.tsx

This PR changes the point resolution of `remove_node` ops, such that if the previous point doesn't share a common ancestor and the next point is available, prefer the next one.
**Example**
see test cases
**Context**
I ran into this behavior when trying to write helpers that preserve cursor position. I insert empty text nodes like: `{ text: '', anchor: true }`. If a change deleted from the beginning of a line, I noticed the cursor would end up in the prior line.
**Checks**

Fix mergeNodes moving node into parent sibling

---

docs/general/resources.md

Add CoCal to list of Slate resources. Just a couple of links adds to the docs.

Add CoCalc to list of resources

---

cypress/integration/examples/code-highlighting.ts

Even with a longer timeout, this test is intermittently failing, causing most PRs to show as failing.
One of the recent integration tests is failing intermittently. I'm commenting it out until someone has time to address it as it's causing most PRs to fail their tests.
**Checks**
No changeset as it's just commenting out a test.

Comment out currently flaky integration test

---

.changeset/polite-readers-talk.md
packages/slate/package.json
packages/slate/src/interfaces/text.ts
packages/slate/src/utils/deep-equal.ts
packages/slate/test/index.js
packages/slate/test/utils/deep-equal/deep-equals.js
packages/slate/test/utils/deep-equal/deep-not-equal-multiple-objects.js
packages/slate/test/utils/deep-equal/deep-not-equal.js
packages/slate/test/utils/deep-equal/simple-equals.js
packages/slate/test/utils/deep-equal/simple-not-equal.js
packages/slate/test/utils/deep-equal/undefined-key-equal-backward.js
packages/slate/test/utils/deep-equal/undefined-key-equal-forward.js
yarn.lock

This swaps to a custom slate-specific object deep equality check - based on the original `Text.equals` code -  that only supports nested objects, not arbitrary keys.
Across various discussions in #3532 and #4245 the text equality method was swapped out to support nested objects. In the end, using a library-based equality check causes a regression in an undocumented feature; text nodes with marks set to undefined should be able to merge with text nodes that don't include that mark.
This PR creates a custom deep equality method to restore that behaviour while retaining the nested object comparisons. I've also refactored it into `utils` so we can look at using it in other parts of the code.
**Checks**

Remove fast-deep-equal

---

.changeset/popular-ways-fail.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/normalization/block/insert-custom-block.tsx

My change in #4208 caused problems for anyone wanting to fix empty block nodes with custom behaviour, instead of the Slate default that inserts an empty text node.
**Issue**
Improves: #4208
**Example**
I have written a test for the desired behaviour that fails with my previous fix.
**Context**
It turns out just calling `editor.normalizeNode()` in the pre-normalization pass fixes both my initial test cases and the new test. There may be other edge cases that don't work so I've made this a minor level change.
**Checks**

Fixed regression in #4208 where normalization on empty block nodes could not be overridden

---

.changeset/mighty-zebras-relax.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/components/string.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/native.ts

See #3293, which hasn't seen any action despite a change request. This takes that PR and makes TextString a functional component, the one requested change.
Huge thanks to @luddep for doing almost all of the work here.
Fixes: #2061 (and some of #2051?)

Use native character insertion to fix browser/OS text features

---

cypress/integration/examples/code-highlighting.ts

The code highlighting example test fails intermittently even after https://github.com/ianstormtaylor/slate/pull/4423.
From the post [here](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/), it seems like toggling the select box can result in a race condition. Hence, in this patch I try to confirm that the select value is changed and only then perform subsequent actions
I've tried running this on https://github.com/MLH-Fellowship/slate twice, it seems to work. But since I can't simulate the CI environment locally, there's no guarantee.
**Checks**

cypress: fix flaky code highlight test

---

cypress/integration/examples/paste-html.ts

Adds cypress integration test for paste html example
**Video**
https://user-images.githubusercontent.com/2987087/129034226-3664ab7d-e11a-40a2-b8f6-09f871f5f4b1.mp4
**Checks**

cypress: test for paste html example

---

packages/slate-react/src/components/slate.tsx

The `value` and `editor` passed to the `<Slate>` component can be big. The `useMemo()` which creates the context is invoked whenever the value changes. This means the code would JSON.stringify() both the value and editor (which through .children also contains the value), just for the `invariant()` message which may not be used most of the time.
A lazy version of `invariant` would be nice to have (eg. `invariant(false, () => "<expensive string builder>")`). But to be honest I'd prefer dumping the object into the console via console.log/info/error, because then I can actually see and inspect it.

Do not needlessly JSON.stringify() the whole editor

---

.changeset/thick-geckos-kick.md
packages/slate-react/src/components/android/android-input-manager.ts

Currently on rich text example, the mark is not inserted on the inserted text.
step to replicate:
* toggle mark button
* insert some text
* text inserted without the mark
expected: mark should be inserted with the text
**Issue**
#4405 
**Example**
current example: 
fix example:
**Checks**

fix(android): Fix editors mark is not inserted on insert text in android

---

.changeset/flat-carpets-sort.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/environment.ts

Fixes Double IME issue in QQ browser (original PR in #3730, this rebases the PR against main)
**Issue**
Fixes: Several browsers require this fix to prevent double IME. This adds the QQ browser to that list.
**Checks**

fix: chinese input double in qq browser

---

.changeset/nervous-planes-wonder.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/dom.ts

From what im understand, the mutation should be detected from beforeInput event and only using onPaste as the fallback. But im found out, window.DataTransfer is not holding the slate-fragment data. For now, im only found out it missing when using safari on mac (safari version 14).
**Issue**
#3589, #4217
**Example**
**Context**
When try to debug this, im found out the application/x-slate-fragment is exist in onPaste clipboard but not in window data transfer that used in beforeInput event. Since `data-slate-fragment` also hold the same data,  i think its better to check to it as the fallback when `application/x-slate-fragment ` is missing. This also what i did in #4433 for android. Im using safari 14 and macos catalina.
**Checks**

Read data-slate-fragment when application/x-slate-fragment is missing

---

.changeset/old-bees-design.md
packages/slate-react/src/components/editable.tsx

When the user enters text using the input method, the browser will trigger `composition` event sequentially and insert  composition text in the DOM. At the end of composition, the browser will remove the previously inserted composition text and insert the final IME output text.
But the problem is, if we type with editor mark, slate will create a new node and insert the final text into the new node, which will cause the position of the inserted final text is different from the position of the the previously inserted composition text, which will cause the browser can't remove the inserted composition text correctly, and React can't detect the change too.
This will result in inconsistent data structure and DOM rendering and slate will crash when select text that shouldn't …

fix: insert new node in advance to avoid ime double input with editor marks

---

docs/walkthroughs/04-applying-custom-formatting.md

I have seen in the walkthrough the use of `useCallback` but I don't think are need it, and add a small complexity while understanding the concept, if we moved out the function outside of the component will be stable and will not require to maintain either referential identity or calculated complex logic. 
If people think this is a good idea I can go and update all documentation to remove unnecessary `useCallback` from the example.
unless I'm missing something.
Improving documentation
**Issue**
Removing little complexity from the example.
**Example**
I don't think the use of useCallback is necessary on the examples for the walkthroughs 
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way …

Proposal for Remove useCallback from walkthroughs documentation

---

.changeset/nine-windows-rush.md
packages/slate-react/src/components/string.tsx

An unnecessary React.memo wrapper introduced in #3888 /  25afbd4 was causing a double character insertion
**Issue**
Fixes: #4445
**Example**
See #4445
**Context**
See #4445
**Checks**

Double character insert regression

---

.changeset/seven-fishes-check.md
packages/slate/src/create-editor.ts
packages/slate/test/normalization/text/merge-adjacent-empty-before-inline.tsx

As the code exists today, if you have an empty text node before an inline node, the empty text node will not be removed if it has a nonempty node before it with differing attributes.
The issue is that we consider pairs of text nodes, and generally only remove the earlier node if that node is empty. The only time we remove the current node is if it is the last node in the block. This fails to behave correctly when the current node is the last node before an inline object, and leaves the empty text node lingering.
This PR aims to fix that edge case.
**Example**
This is just a copy/paste of the test case, but the test really exemplifies this better than anything else I can think of:
As things stand today, this input:
```
<editor>
<block>
<text>not empty</text>
<text a/> …
```

Normalization: Nonempty to empty to inline should remove empty node

---

site/examples/forced-layout.tsx

Fixes the original PR in #4388 to comply with lint/code structure guidelines.
Change the forced-layout example to enforce layout to an explicit block index to allow for block types beyond 'paragraph'.
Building from the current forced-layout example seems to prevent all types other than 'paragraph' from being used. The solution implemented here is to enforce the layout by an explicit block index. This way will not enforce subsequent blocks to be type 'paragraph.'
**Checks**
No changeset as it's just an update to an example

Layout example fix

---

.changeset/cold-beans-give.md
packages/slate-react/src/components/editable.tsx

onDomSelectionChange is called before the same click event triggered and processed, which may cause another round (if some element check useSelected and then render or by css/class name display differently) rerender which may change the dom and then cause the click event got unexpected event.target.
**Issue**
Fixes:
**Example**
No simple example, but if we do not delay onDomSelectionChange process, it will make the onClick event not reliable and got wrong event target and unexpected result.
**Context**
since the onDomSelectionChange does throttle with 100ms, and which is not time critical, but onClick is. So we first make sure onClick get correct event, then as throttled delay 100ms to check the dom selection change, which is harmless.
**Checks**

Make onDomSelectionChange triggered after onClick.

---

docs/concepts/12-typescript.md

Fixed #4467
Small syntax typo in documentation
**Issue**
Fixes: #4467 
**Checks**
docs only, no changeset

Fix typo in TypeScript concepts documentation

---

cypress/integration/examples/markdown-shortcuts.ts

Apparently the `markdown-shortcuts` test still fails sometimes in the CI. As a quick fix for now, just increasing the timeout.
For a better solution to this altogether maybe we should look into adding `@cypress/react` (https://github.com/cypress-io/cypress/tree/master/npm/react#readme). It looks like that can wait for the component to be mounted fully. I just had a shot at setting it up without success.
**Checks**

Increase timeout for markdown-shortcuts integration test for now

---

.changeset/calm-books-applaud.md
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/text.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/weak-maps.ts

The `KEY_TO_ELEMENT` WeakMap must be scoped to the editor instance to avoid collisions between multiple editors in the same DOM that share the same editor value (object equality on `Node`).
This is solved by wrapping it in another WeakMap keyed on the editor object, that returns the `KEY_TO_ELEMENT` WeakMap for that editor.
It could also be solved by just putting the `KEY_TO_ELEMENT` Weakmap directly on the editor instance, but I didn't want to tangle the `ReactEditor` interface with these (internal) things and keep using weak-maps only for this logic.
**Issue**
Fixes:
https://github.com/ianstormtaylor/slate/issues/3380
https://github.com/ianstormtaylor/slate/issues/3997
https://github.com/ianstormtaylor/slate/issues/4129
**Example**
This will illustrate the problem:
1) Go …

[slate-react]: fix selection bugs when multiple editors share value

---

cypress/integration/examples/select.ts
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

When triple clicking inside the editable component of Slate, it doesn't select the correct block. This poses two problems when Slate is to be used as a rich text editor:
- Give false visual feedback, e.g. the wrong toolbar button will be highlighted which leads to confusion
- Unable to apply new style to the selected block only.
This PR tries to select the correct block that users triple click on.
**Issue**
Fixes #4329 
**Example**
Before the fix:
After the fix:
**Context**
Given a node at path [1].
```js
const editor = {
children: [
{ // first node
}
{
type: 'paragraph', // the node that receives triple click
children: [
{ text: "Since it's rich text, you can do things like turn a selection of text " }, // path: [1, 0]
{ text: "bold", bold: true }, // path: [1, 1]
{ text: …
```

Fix(editable component): reselect the range created by triple click

---

.changeset/healthy-ads-trade.md
packages/slate-react/src/hooks/use-children.tsx

Adding key for SelectedContext.Provider in Children to remove warning from react in development mode.
**Issue**
Fixes: #4464
**Example**
**Context**
key will be `provider-` followed by children id. example `provider-0`
**Checks**

Add key for Children SelectedContext.Provider

---

.changeset/cool-rings-help.md
packages/slate/src/transforms/text.ts
packages/slate/test/transforms/insertFragment/of-blocks/block-empty.tsx

When pasting into an empty block, insert the entire fragment as-is, thereby preserving the structure of the first block.
**Issue**
Fixes: #4486
**Example**
Right - current, left - PR.
**Caveat**
Since the first node is not handled in a special way anymore, there will be a change to how complex structures like lists behave (GIF below). I feel that slate cannot handle this well on it's own without knowing the semantics of those elements (is it a list, is it a table, how does one paste a table into a table etc), and it should be up to the "plugin" that defines what a list is to define that behavior. If this is not acceptable, i propose we allow the clients to choose between two insert strategies, as we really need the PR behavior to work and list behavior for us is solved by …

Fix paste to empty node losing structure of first block

---

.changeset/neat-flies-eat.md
packages/slate/src/transforms/node.ts
packages/slate/test/transforms/insertNodes/path/multiple-inline-not-end.tsx
packages/slate/test/transforms/insertNodes/path/multiple-inline.tsx

When using `Transforms.insertNodes` to insert multiple nodes, the cursor will be placed only after the first inserted node. This mainly because we only move `at` to next path once, key code below:
```js
at = isAtEnd ? Path.next(path) : path
// ...
const point = Editor.end(editor, at)
if (point) {
Transforms.select(editor, point)
}
```
The `Path.next` will only invoke once which means the cursor only move after one node.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/3816
**Example**
before
after
**Context**
I just move the cursor every time a node is inserted, and because we go to next at first, so we need to go back at last.
Also I added two test cases for this situation, both cases are failed at the previous version.
**Checks**
Actually I can build the …

fix cursor not correct when insert multiple nodes using insertNodes

---

.changeset/curly-mails-allow.md
packages/slate-react/src/hooks/use-slate.tsx

Error message for useSlate is stale and points to an old API.
**Issue**
Fixes: #4479
**Checks**

Update error message for useSlate

---

.changeset/smart-pears-beam.md
packages/slate-react/src/plugin/react-editor.ts

fixes #4490 
Introducing fix for triple-click selection in this [PR](https://github.com/ianstormtaylor/slate/pull/4455#issuecomment-913821241) caused some regressions that I didn't expect.
This new PR will alleviate that.
**Issue**
Some of the issue caused by the triple click fix include, but not limited to:
- Crash when selecting void nodes #4490 
- Shift + down arrow then delete text doesn't delete it #4496 
**Context**
There are two problems with my triple-click fix:
- The condition for checking if an action is a triple-click is too broad.
- The logic for resetting `focusNode` of a selection is not fail-proof. The building block of the content component in a Slate editor are HTML element with attribute `data-slate-node="element"`. They may contain child elements …

Fix: regression caused by triple click fix

---

.changeset/old-planes-trade.md
.changeset/smart-pears-beam.md

In this PR, I added changeset for the fix for the triple click [here ](https://github.com/ianstormtaylor/slate/pull/4455) and removed changeset for this related [PR](https://github.com/ianstormtaylor/slate/pull/4498)
**Checks**

Add changeset for triple click fix

---

.changeset/gold-planets-pump.md
packages/slate-history/package.json
packages/slate-history/src/history.ts
packages/slate-hyperscript/package.json
packages/slate-hyperscript/src/hyperscript.ts
packages/slate-react/package.json
packages/slate/package.json
packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/element.ts
packages/slate/src/interfaces/operation.ts
packages/slate/src/interfaces/point.ts
packages/slate/src/interfaces/range.ts
packages/slate/src/interfaces/text.ts
packages/slate/src/utils/deep-equal.ts
yarn.lock

The `is-plain-object` package recently had a major version upgrade that broke libraries which import its default export, such as this one. This causes issues when other packages in the same application require a higher version of `is-plain-object`, resulting in an error originating in Slate's codebase. To remedy this, Slate is now depending on `is-plain-object@^5.0.0` and its import references across the codebase have been updated.
**Issue**
Fixes: #4499
**Example**
See issue
**Context**
See issue
**Checks**

Upgrade `is-plain-object` to v5.0.0

---

docs/api/transforms.md

While developers can look up the definition of a Location, it's far from clear how to select from the beginning of the editor content, or to the end of editor content.

Adds an example to the docs for Transforms.select

---

.github/workflows/release.yml
yarn.lock

Release process is broken after upgrading yarn to v3. Work in progress to try to fix it.
**Checks**

Attempt fix the release process

---

packages/slate-react/src/plugin/react-editor.ts

In my triple click fix, I reset the `focusNode` but forgot to reset the related `focusOffset` value. As a result, the Slate range computed from DOM selection is still not correct and cause a number of issues when users try to transform a block by applying formatting or deleting. 
**Issue**
Fixes: #4492 
**Example**
Before the fix
https://user-images.githubusercontent.com/28924121/133071690-27d21192-b86c-4b6a-9741-0f2f1ff53218.mp4
After the fix
- Selecting a block by clicking and dragging, then hitting Backspace should remove that block.
https://user-images.githubusercontent.com/28924121/133098079-78fdccd1-3eef-42a3-b852-ca0ba55453d9.mp4
- Selecting a block through clicking and hitting Shift + Arrow down, then hitting Backspace should remove that block. …

fix(react-editor): reset focus offset when triple clicking

---

.changeset/eleven-taxis-hear.md
packages/slate/src/utils/deep-equal.ts
packages/slate/test/utils/deep-equal/deep-not-equal-nested-undefined.js

I added this function in #4276 but missed a test case. When the second value doesn't have the key it triggers an exception.
This isn't critical for simple use cases, but my team just started using nested objects as mark values and we instantly hit the bug.

Fixed nested object comparison

---

.changeset/light-gorillas-train.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/native.ts

The code was backing out of a native insert if there are ops other than insert_text, but at that point the decision to preventDefault was already made. The PR takes into account the flush as well, and does a prevent default in case a flush has occured.
**Issue**
Fixes: #4527
**Notes**
Refactored asNative to record previous state and reset it in a finally clause. A variable is set, so the function should clean up after itself, to put it tersely. Also, captured the previous state of AS_NATIVE, as to account for potential nesting of the calls.
**Checks**

Fix erroneous text after native insert

---

docs/libraries/slate-react.md

Fix typo "exectue" to "execute"

docs: fix typo

---

.changeset/sharp-donkeys-sparkle.md
packages/slate/src/interfaces/range.ts
packages/slate/src/transforms/node.ts
packages/slate/test/interfaces/Range/transform/inward-collapsed.tsx
packages/slate/test/transforms/setNodes/split/noop-collapsed.tsx

When calling 'setNodes' with a collapsed range, and `split: true`, what should happen is nothing, (`split` means we want to style whatever is in between the two points, which will be nothing), however we were seeing a full node get styled as if a split never occurred. Tracked it down to two issues:
- When a range is already collapsed and the affinity was 'inward' (the default), it was possible to end up going too far 'inward' and have the anchor push past the focus. This change detects that case and just leaves it collapsed, preferring whichever direction the anchor would be moving. 
- setNodes uses this transform as part of a rangeRef to track edits while it splits the nodes at the provided range. Because the range was collapsed the rangeRef would end up outside the …

Fix setNodes when called with 'split' and a collapsed range

---

.changeset/loud-planets-count.md
packages/slate-react/src/components/editable.tsx

When you select an inline void element, and delete it (press "backspace"), no editor command are fired.
A `Transform.deleteBackward` is called instead.
[Ref in the code](https://github.com/ianstormtaylor/slate/blob/35b722cadd8ae594e6f83e2195682ba64bc79850/packages/slate-react/src/components/editable.tsx#L1196)
The problem: when you want to override default Editor's commands: that obviously doesn't work.
**Expectation**
Call `Editor.deleteBackward` instead of `Transforms.deleteBackward`.
**Environment**
- Slate React Version: 0.65.3
- Browser: Chrome, Safari
**Context**
[Issue 4525](https://github.com/ianstormtaylor/slate/issues/4525)

Fix - delete selected inline void in chrome

---

docs/walkthroughs/06-saving-to-a-database.md

As written, the "Saving to a Database" examples save even when the editor content is unchanged.  This is inefficient and often undesirable.

Updates "Saving to a Database" example to distinguish content changes

---

.changeset/modern-toes-invent.md
packages/slate-react/src/components/editable.tsx

**Context**
In #4529, i wanted to have a single `event.preventDefault()` for the entire callback, but missed an early return. Here, I've put the `preventDefault` call back to where it was, and called it again from the `onFlushed` callback.
**Issue**
Fixes: #4546 
**Checks**

Fix deletion of expanded range

---

.changeset/firefox-newline-bug.md
packages/slate-react/src/plugin/react-editor.ts

In Firefox, selecting the entire contents of a document via <kbd>Ctrl+A</kbd> causes the editor to crash when the document ends with a `\n` character.
Refer to the issue below for more specific replication steps.
Fixes: https://github.com/ianstormtaylor/slate/issues/4373
https://user-images.githubusercontent.com/1416436/134738138-60a927c6-ea82-429e-9aac-cbf46e3515bf.mp4
https://user-images.githubusercontent.com/1416436/134738159-4367050d-3bfc-454a-8a3c-9d37aefc5869.mp4
In Firefox, `range.cloneContents()` returns an extra trailing `\n`, when the document ends with a new-line character. This results in the offset length being off by one, so we need to subtract one to account for this.

Fix `toSlatePoint()` when text node ends in `\n` in Firefox

---

.changeset/firefox-newline-fix.md
packages/slate-react/src/plugin/react-editor.ts

This PR follows up on #4547.
**Context**
I meant to update the PR to only apply the offset fix when the cloned textContent ends in `\n\n` instead of `\n` but didn't get a chance to push that up before it was merged.
The rationale for this change is that we only need to apply this fix for the specific edge-case where Firefox returns `\n\n` for the `textContent` of the cloned range. 
**Checks**

Only apply Firefox `toSlatePoint()` offset fix when the cloned contents end in `\n\n`

---

.changeset/smart-eyes-enjoy.md
packages/slate-react/src/components/string.tsx

In #3888 the following code was added to force a re-render when an operation has been applied to the DOM but not reflected in the Slate representation:
``` ts
const TextString = (props: { text: string; isTrailing?: boolean }) => {
...
if (ref.current && ref.current.textContent !== text) {
forceUpdateFlag.current = !forceUpdateFlag.current
}
// This component may have skipped rendering due to native operations being
// applied. If an undo is performed React will see the old and new shadow DOM
// match and not apply an update. Forces each render to actually reconcile.
return (
<span data-slate-string ref={ref} key={forceUpdateFlag.current ? 'A' : 'B'}>
...
```
However, in certain cases (e.g. running in React dev mode under a `<React.StrictMode>`) the render function may be …

fix forced update in TextString in case of double render

---

.changeset/late-spoons-cheer.md
packages/slate/src/transforms/node.ts
site/examples/embeds.tsx
site/examples/forced-layout.tsx
site/examples/markdown-shortcuts.tsx
site/examples/richtext.tsx

Because Typescript can know which type of nodes we are modifying thanks to the `T` type inferred from the `match` function, if available, it can also properly narrow down the `props` argument type.
**Checks**

Improve `props` argument type in `Transforms.setNodes()` 

---

.changeset/bright-seahorses-share.md
packages/slate/src/utils/string.ts
packages/slate/test/utils/string.ts

This PR follows up on #4326. @gitcatrat found an issue with some older Unicode 1.1 smileys.
**Example**
Before:
https://user-images.githubusercontent.com/203411/135591426-237a9c26-1515-437e-a76c-6a9ac1dc03db.mp4
After:
https://user-images.githubusercontent.com/203411/135591553-53e61645-fa65-4692-a0cd-179af364469d.mp4
**Context**
`getCharacterDistance` does not use a whitelist anymore. If a character is followed by a variation selector, it is considered a sequence no matter what the character is. Also I tried to make the function more readable by reorganizing the code and adding a few comments.
**Checks**

Fix issue with Unicode 1.1 smileys

---

.changeset/wet-lobsters-travel.md
packages/slate-react/src/components/editable.tsx

Stop _trying_ to disable Grammarly extension from working in Slate editors.
**Issue**
Fixes: #4124 
**Example**
**Context**
The Grammarly extension is not causing DOM issues anymore, as they have reworked their highlighting logic: 
https://www.grammarly.com/blog/engineering/making-grammarly-feel-native-on-every-website/
Also the `data-gramm` attribute (introduced in #733) is no longer working actually (see #4124), as the Grammarly team changed the name.
Though applying Grammarly suggestions is still broken: #4579 (but it does not break the editor, so it may be fine).
**Checks**

Do not try to disable Grammarly in Slate

---

.changeset/beige-hotels-vanish.md
packages/slate-react/src/components/editable.tsx

As previously asked in [Slack](https://slate-js.slack.com/archives/C1RH7AXSS/p1636096147185300), this helps in automated testing where it's currently not possible to properly transfer data between the host app and the application under test. The previous `instanceof window.DataTransfer` fails as Cypress is not able to properly get hold of the window object Slate is referring to (despite using [cy.window](https://docs.cypress.io/api/commands/window)). To mitigate that the check is now checking for the constructor name.
**Checks**

fix: weak guard on DataTransfer to not rely on current window

---

docs/walkthroughs/01-installing-slate.md

**Issue**
Fixes: the walkthrough code doesn't work for typescript without adding Descendant as a dependency

Docs: first walkthrough missing TS 'Descendant' dependency

---

.changeset/green-penguins-check.md
packages/slate-react/src/components/editable.tsx

Disabled the  auto scroll behaviour when it's on selection
**Issue**
https://github.com/ianstormtaylor/slate/issues/4647
**Checks**

fix: default scroll selection

---

.changeset/warm-dolphins-roll.md
packages/slate-react/src/plugin/with-react.ts

Fixed the issue that copying from editable inside iframe does not work
https://github.com/leoc4e/slate/blob/d06706c9e15bbbdd7cdd9a1bbb38c87d37c85ea1/packages/slate-react/src/utils/dom.ts#L66-L70
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4660
**Example**
**Context**
The issues is due to `getPlainText` is returning empty string in iframe.
https://github.com/leoc4e/slate/blob/272ad7ffddae8d1163e395a44dd59f66e2b0f1b0/packages/slate-react/src/plugin/with-react.ts#L191-L192
This is because `isDomNode` would check if the element is an instance of the `ownerDocument.defaultValue.Node`
(https://github.com/leoc4e/slate/blob/d06706c9e15bbbdd7cdd9a1bbb38c87d37c85ea1/packages/slate-react/src/utils/dom.ts#L66-L70)
While slate is using default document when creating …

fix: use ownerDocument to create element

---

.changeset/chilled-bears-lick.md
packages/slate-react/src/components/editable.tsx

Fixes a regression introduced by https://github.com/ianstormtaylor/slate/pull/4132.
Some IMEs/Chrome extensions like e.g. Grammarly set the selection immediately before triggering a `beforeinput` expecting the change to be applied to the immediately before set selection. Defering this selection update causes the change to be applied to an outdated selection.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4579
**Example**
Before:
After:
**Checks**

fix: flush selection change on before input

---

.changeset/merge-nodes-issue
.changeset/wicked-mayflies-approve.md
packages/slate/src/utils/deep-equal.ts
packages/slate/test/utils/deep-equal/deep-equals-with-array.js
packages/slate/test/utils/deep-equal/deep-not-equals-with-array.js

deepEquals was always returning true if any array properties were equals.
**Issue**
**Example**
Code example :
```ts
const A = {
array: [1],
otherProp: true
};
const B = {
array: [1],
otherProp: false
};
deepEquals(A, B); // Should return false... but was returning true.
```
**Context**
**Checks**

Fix deep-equals for array properties

---

.changeset/strong-jeans-train.md
packages/slate-react/src/components/editable.tsx

Fixes 2 issue for Next.js (or any SSR method).
1) Under SSR the Editable component requires three props to be added to avoid a warning in the console.  This is because defaults are added to the component to deal with `HAS_BEFORE_INPUT_SUPPORT.` They are added because the check fails server side and the warning arrises because the check works client side, resulting in the prop mismatch.  The result is to force SSR users to add the following to avoid the warning.
```
<Editable
spellCheck={false}
autoCorrect="false"
autoCapitalize="false"
>
```
2) SSR users are not able to use `spellCheck, autoCorrect or autoCapitalize.` If the developer would like to opt-in to these features they can set them to true and the library will verify compatibility.  However it is not possible to …

fix ssr prop mismatch

---

.changeset/giant-comics-walk.md
packages/slate/src/utils/string.ts
packages/slate/test/utils/string.ts

This PR fixes the issue where the editor cursor jumps more than one character unexpectedly while you are navigating with arrow keys. The issue occurs when the cursor is around a digit, an asterisk, or a number sign.
**Issue**
Fixes: #4649
Fixes: #4655
Fixes: #4659
**Example**
https://user-images.githubusercontent.com/29035331/142804562-bbba8f7a-4c04-4066-a3c3-4b97d2f2e32c.mp4
Tested with Safari 15.1.
**Context**
The new code implements Unicode's [grapheme cluster boundary specification](https://www.unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table), which defines general rules for breaking Unicode text into individual characters.
The character sets in the regular expressions are generated from [`GraphemeBreakProperty.txt`](https://www.unicode.org/Public/UCD/latest/uc …

fix: cursor jumps more than one character unexpectedly

---

.changeset/tough-rockets-walk.md
packages/slate/src/interfaces/custom-types.ts
packages/slate/src/interfaces/operation.ts
packages/slate/test/interfaces/CustomTypes/custom-types.ts
packages/slate/test/interfaces/CustomTypes/customOperation-false.tsx
packages/slate/test/interfaces/CustomTypes/customOperation-true.tsx
packages/slate/test/interfaces/CustomTypes/type-guards.ts

This makes it possible to add your own custom operations to the `Operation` union type. Can be useful if you want to extend slate with extra operations (something I needed hence the PR :smile:).
**Issue**
Fixes: none
**Example**
`Operation` can now be extended as follows:
```
import type { BaseOperation } from 'slate'
type CustomOperation =
| BaseOperation
| YourCustomOperation
| AnotherCustomOperation
declare module 'slate' {
interface CustomTypes {
Operation: CustomOperation;
}
}
```
**Checks**

Allow Operation type to be extended

---

.changeset/hungry-dingos-do.md
packages/slate-react/src/components/editable.tsx

PR #4617 fixed a bug by checking `readOnly` in the `onDragStart` callback, but missed setting the dependency on `useCallback`. Consequently, if you have an editable that switches from readonly to not-readonly, the drag event will not add the internal fragment and the drop will fallback to plain text (because the fragment is not there).
**Issue**
related to #4548
**Checks**

Fix onDragStart callback dependency on 'readonly'

---

.changeset/large-melons-warn.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/environment.ts

* Resolve double input when using CJK IME
* adapt UC mobile which will input nothing after selected from the candidates
**Issue**
Fixes: #3914
**Example**
**Before**
**After**
**Context**
CJK IME, like the Mac OS/iOS native ones, will trigger events(compositionstart, compositionend, insertFromComposition), which will invoke "insertText" multiple times if the conditions are not considered.
This PR will skip some insert actions to avoid strange behaviors, like double input, no content after selection
**Checks**

Fix CJK IME(like Chinese, Japanese) double input

---

.changeset/brave-emus-refuse.md
docs/libraries/slate-react.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

Currently in order to know whether `setFragmentData` was called as a result of a copy, cut or drag; you have to overwrite all of the `onCut`, `onCopy`, `onDrag` methods and call your own function with the original event. This change adds a single property to `setFragmentData` called `originEvent` that can be set to `copy`, `cut`, `drag`. This allows you to set some extra data (or emit data) on the `DataTransfer` object based on whether `setFragmentData` was called as part of a drag, copy or cut event without having to modify a lot of code. We could potentially do the same thing for `insertData` as the same thing applies there but for `paste` and `drop`.
**Issue**
**Checks**

Add origin event type to setFragmentData to be able to distinguish copy, cut and drag

---

.changeset/cyan-games-share.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/editable.tsx

Fixes "Cannot resolve from DOM point" error on onDomSelectionChange for readonly void elements (see #4726). The code tries to update selection and falsely elects void elements in a readonly editor.
**Issue**
Fixes: #4726 
**Checks**

Fix "Cannot resolve from DOM point" error on onDomSelectionChange for readonly void elements

---

.changeset/quick-feet-melt.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/android/android-input-manager.ts
packages/slate-react/src/utils/weak-maps.ts

I asked some questions about Android devices earlier in #4705 . I tried to switch to `DefaultEditable` but that didn't resolve my questions. After i read source code about `AndroidEditable`.  I may sum up a few questions and try to resolve them.
Q:
1. As we can see in these issues #4715 #4714 or the first video, using the typing with association function will trigger an unexpected insertText operation .
2. We can't click block element on Android which also mentioned in #4719 .
A:
1. `MutationObserver` is used in `AndroidEditable` to monitor DOM changes. Whenever we input a character, `MutationObserver` will be triggered and `insertText` into the editor. However, in the keyboard association state, performing a delete operation or inputting characters may trigger character …

fix: [AndroidEditor] Solve input association problems and add click events.

---

docs/api/nodes/editor.md
docs/concepts/04-transforms.md
docs/concepts/11-normalizing.md

Cues programmers that sequences of Transforms may need to be wrapped in `Editor.withoutNormalizing` if the node tree should _not_ be normalized between Transforms.

Documents use of withoutNormalizing in conjunction with normalization

---

.changeset/clean-boats-film.md
.vscode/launch.json

Add vscode debug config (`launch.json`) for Chrome & Firefox.
**Context**
Needed to easily start/attach a debugger.
**Checks**

chore: add vscode launch.json debug config

---

site/examples/richtext.tsx

The [richtext.tsx](https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx#L99) example `isBlockActive`  was not working for me in my environment because `Editor.nodes` returns a Generator, not an Array. So `isBlockActive` always returned false. Wrapping it in `Array.from` fixes the example. 
**Issue**
Fixes: #4663
**Example**
| Before | After |
| -- | -- | 
| ![before](https://user-images.githubusercontent.com/647549/142044364-cd390842-8d99-4a4e-a59d-1e345bfadd1f.gif) | ![after](https://user-images.githubusercontent.com/647549/142044401-534cbe9d-2cad-4a71-b7a2-9f222da1a439.gif) | 
| `isBlockActive` always returns `false` | `isBlockActive` properly toggles |
**Checks**

fix: isBlockActive should use Array.from()

---

docs/api/nodes/editor.md
docs/api/transforms.md

Clarifies when to use Editor.insertNode vs. Transforms.insertNodes

Docs: Clarifies when to use Editor.insertNode vs. Transforms.insertNodes

---

packages/slate-react/src/components/string.tsx

This fix is the last or at least the next piece on the journey to [Use native character insertion to fix browser/OS text features](https://github.com/ianstormtaylor/slate/pull/3888/files) With all the good progress so far, native spellcheck as you type is still broken on practically all browsers (no spellcheck underlining on Safari & FF and blinking underlines on Chrome).
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4320
Related: https://github.com/ianstormtaylor/slate/pull/3888, https://github.com/ianstormtaylor/slate/issues/2051
**Example**
Safari, before (spellcheck prevented)
Chrome, before (spellcheck blinks)
**Context**
The reason for this is that the continuously changing text will rerender the virtual DOM on each keystroke, which in turn updates …

Optimize TextString rendering to support browser/OS text features, eg fix native spellcheck

---

.changeset/two-coins-enjoy.md
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/path.ts
packages/slate/src/utils/weak-maps.ts

While large bulk edits are not a common scenario, we noticed that the dirty path tracking during batches has an O(n^2) behavior in relation to the number of ops. This is because as every op gets applied, we loop over all previous dirty paths and transform them. This implements an optimization where we can bypass the no-op transform entirely if we know the op won't affect paths at all.
In a simple test where I had a slate with 1000 texts and I applied an 'insert_text' op appending a character to each text, I saw about a 50% time savings (went from ~2s down to ~1s)
**Checks**

Avoid transforming dirty paths if the op won't touch them

---

.changeset/soft-trees-taste.md
packages/slate/test/interfaces/Editor/unhangRange/block-hanging-over-void-with-voids-option.tsx
packages/slate/test/interfaces/Editor/unhangRange/block-hanging-over-void.tsx
packages/slate/test/interfaces/Editor/unhangRange/block-hanging.tsx
packages/slate/test/interfaces/Editor/unhangRange/collapsed.tsx
packages/slate/test/interfaces/Editor/unhangRange/text-hanging.tsx
packages/slate/test/interfaces/Editor/unhangRange/void-hanging-with-voids-option.tsx
packages/slate/test/interfaces/Editor/unhangRange/void-hanging.tsx

Add tests for `Editor.unhangRange()`
**Issue**
Related to #3683 
**Example**
n/a
**Context**
`Editor.unhangRange()` has zero tests. So it's really difficult to understand how it should work.
Also any changes to its behavior will not have obvious effect visible in tests expectations.
This PR documents the existing behavior of `Editor.unhangRange()` without modifying it.
**Checks**

Add tests for Editor.unhangRange()

---

.changeset/breezy-ears-happen.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/android/android-input-manager.ts
packages/slate-react/src/components/editable.tsx

Call `editor.insertText` instead of `Transforms.insertText` to allow overriding behavior in plugins.
**Issue**
Fixes: #4709
I was able to verify that this now works correctly on my Android device, but I am not sure how to add a test for this. 
**Checks**

Fix editor.insertText never gets called inside plugins on Android

---

.changeset/wild-penguins-shout.md
packages/slate/src/create-editor.ts

Slate requires the invariant that children are all blocks or all inlines. It enforces this in default normalization by removing children. When such a node is removed, it's almost certainly due to a programming error: the developer needs to fix their application to ensure it maintains this invariant. But currently Slate does not tell the developer this.
I made such a programming error, and spent a long time debugging nodes that mysteriously went missing. I would have fixed it within 30 seconds if Slate had warned me when it detected this error.
**Context**
Note I have used `console.warn` despite the eslint rule. As far as I can see, Slate has no other facility for runtime warnings.
**Checks**

Warn when normalization removes node

---

site/examples/inlines.tsx

There is a Chromium bug where, if you have an inline at the end of a block, clicking the end of a block puts the cursor inside the inline instead of inside the final text node.
This commit updates the inlines example to show the problem, and to show a known workaround for the problem.
**Issue**
https://github.com/ianstormtaylor/slate/issues/4704
**Checks**

Show example of a workaround for Chrome bug that puts cursor in wrong place

---

docs/walkthroughs/01-installing-slate.md

As already discussed almost a year ago in #3198, `useMemo` doesn't guarantee persistence. This breaks Fast Refresh.
`useState` without a setter is a straightforward fix that avoids dependencies; let's get the docs updated so Fast Refresh works again.
**Issue**
Fixes: #3198
**Checks**

Docs shouldn't `useMemo` for editor

---

docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/06-saving-to-a-database.md

Updated docs to explain that Slate provider is now an uncontrolled component, to match the changes introduced in this pr: https://github.com/ianstormtaylor/slate/pull/4540. Thanks to @KarimNahas for his [resetNodes example](https://github.com/ianstormtaylor/slate/pull/4540#issuecomment-951903419)
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4765
**Example**
N/A
**Context**
N/A
**Checks**

Update docs to reflect Slate is an uncontrolled component

---

.changeset/stale-poems-itch.md
packages/slate-react/src/components/slate.tsx

As described in the issue, the `useFocused` hook was returning incorrect/unexpected values. I debugged and realized it was displaying old values because of the order in which event listeners were running.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4754
**Example**
Here I repro the exact two behaviors I described in the linked issue, but with this fix in place. (View the GIFs in the issue to see what they looked like before this fix.)
**Context**
Based on my testing, I think there was a race condition between the focus/blur event listeners in `components/slate.tsx` (added in #3987) and the onFocus/onBlur handlers in `components/editable.tsx`. The `IS_FOCUSED` map was eventually consistent/had the correct values after all handlers ran, but the event …

run focus event listener after existing onFocus handlers

---

cypress/integration/examples/iframe.ts
site/examples/iframe.tsx

Makes the iframe example work on the Firefox and keeps it working on other browsers. It changes using the ref on the iframe to an `onLoad` event solution
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4285
**Example**
https://www.slatejs.org/examples/iframe on the Firefox
**Context**
Firefox resets the iframe content on the load event. I've tested on some older versions of the browser and it keeps happening too. Here is an issue on the react repo https://github.com/facebook/react/issues/22847
**Checks**

iframe example - use an onLoad callback instead of the ref

---

.changeset/dry-worms-happen.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/android/android-input-manager.ts
packages/slate-react/src/utils/weak-maps.ts

- Remove logic to delay the handling of text insertion
- Call `Transforms.setSelection` before `Editor.insertText` to adjust position
**Issue**
Fixes: #4709
Based on discussion from #4753 
**Checks**

Fix Android editor.insertText regression

---

.changeset/dry-worms-happen.md
.changeset/mean-ears-shop.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/android/android-input-manager.ts
packages/slate-react/src/utils/weak-maps.ts

* Rollback changes made in #4779 
* Always call `Transforms.setSelection` before calling `Editor.insertText`.
**Checks**

Rollback 4779 and always call Transforms.setSelection

---

.changeset/witty-moose-join.md
packages/slate-react/src/components/android/android-editable.tsx
packages/slate-react/src/components/android/android-input-manager.ts

Based on discussion from #4709 #4753  #4779 . We have discussed the issue of externally overridden `Editor.insertText` not being called, and I think there is still room for adjustment. 
`Editor.insertText` already contains the logic to set marks, https://github.com/ianstormtaylor/slate/blob/67aa1f10106e15486031b4103285c7fae4373056/packages/slate/src/create-editor.ts#L169-L182 so we can merge the logic here. This PR also avoids the situation that the externally override `Editor.insertText` will not be called when `marks` are set.
**Checks**

Android merge `Editor.insertText` logic.

---

packages/slate-react/src/components/slate.tsx

Use a single layout effect for subscribing to the focus and blur listeners. It is currently made in two separate effects.
**Issue**
**Example**
**Context**
**Checks**

Merge layout effects for adding focus and blur event listeners

---

.changeset/shiny-eagles-swim.md
packages/slate-react/src/components/editable.tsx

Sadly, I cannot create stand-alone reproduction environment, only happens in real world for me.
When switching between multiple editors quickly, there is around 5% chance of following error (location differs):
```
Uncaught (in promise) Error: Cannot resolve a DOM point from Slate point: {"path":[1,0],"offset":6}
```
which is caused by this line:
https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L217
No idea why this only happens on real-world, but I was not able to reproduce this behavior on some demo stage.
However, the environment is the following:
- Slate 0.72.3, Slate-React 0.72.1
- Plate 7.x
- Preact 10.5.4
- 2 or more editors are present on a same page
Due to fact it is not happening every time, looks like this is …

bugfix: On Preact, sometimes DOM & Slate selection are mismatching

---

.changeset/orange-zoos-exercise.md
packages/slate-react/src/components/string.tsx

The fix makes sure that the text content of the TextString component is rendered on the first render.
**Issue**
Fixes: server-side rendering issue introduced by #4733
**Example**
Before #4733: **slate-react@^0.72.1**
Text content is rendered as expected.
After #4733: **slate-react@^0.72.2**
Text content is not rendered.
**Context**
#4733 uses `useLayoutEffect` to fix the spellcheck issue. However, `useLayoutEffect` won't fire until the JavaScript is downloaded, which means the text content of the TextString component can't get rendered on ssr.
**Checks**

Fix text not rendered on server-side rendering

---

.changeset/rude-humans-marry.md
packages/slate-react/src/components/string.tsx

The fix makes sure that the text content of the TextString component is rendered on the first render.
**Issue**
Fixes: server-side rendering issue introduced by #4733.
Correct fix of #4796.
**Example**
Please see example in #4796.
**Context**
#4733 spellcheck fix changed the render behavior of the TextString component. TextString won't render the actual text content on the first-time render, which means server-side rendering is broken. This fix ensures that the text content will get rendered immediately on the first-time render.
**Checks**

Fix text content not rendered on ssr

---

.changeset/wise-kings-serve.md
packages/slate-react/src/components/editable.tsx

Fixes the same fundamental issue as #4669 did, only triggered in a slightly different way. If the editor isn't focused the first select causes the 2nd one that Grammarly causes to be delayed by the `onDOMSelectionChangeonDOMSelectionChange` throttle.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4801
**Example**
Before:
After:
**Checks**

fix: flush onDOMSelectionChange on onDOMBeforeInput

---

.changeset/kind-olives-add.md
packages/slate-react/src/plugin/react-editor.ts

`toSlatePoint` throws while using `suppressThrow` if the selection is inside a node with a `data-slate-leaf` attribute with no text child (due to calling `range.setStart` with `textNode` being `null`). This can happen when e.g. rendering a slate 0.47 editor inside a void element.
This pr adds a simple check to see if `textNode` is set.
**Checks**

fix: toSlatePoint suppressThrow leaf without text node

---

packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/unhangRange/inline-range-normal.tsx

Adding this here for now to get some help on trying to fix this particular bug and can then modify it into an actual fix later on.
Take a look at the test that I added. It fails right now.
It returns:
```
{
anchor: { path: [ 1, 0 ], offset: 0 },
focus: { path: [ 0, 0 ], offset: 12 }
}
```
which is clearly not what we want. Adding this here for now so we can explore why this happens.
@e1himself you've looked at this code recently (thanks for adding the tests! They're a big help.). Do you have some idea what might be going wrong here?
**Checks**

Fix failing unhangRange test case with inlines

---

.changeset/olive-bags-talk.md
packages/slate-react/src/components/editable.tsx

Apologies, I attempted revert a commit, GitHub UI failed, I rushed it, and committed something that fails due to Prettier not running. This removes the extraneous new line.

fix build (prettier)

---

.changeset/hot-beers-poke.md
packages/slate-react/src/components/slate.tsx

Changed so that the state of the slate component is not updated when unmounting.
**Issue**
Fixes: #4818 
**Checks**

fix not update state when unmounted

---

.changeset/dirty-bobcats-marry.md
packages/slate-react/src/components/editable.tsx

Currently `isDraggingInternally` is only reset if the `onDrop`/`onDragEnd` events aren't handled by the respective "external" editable event handlers. This potentially causes `isDraggingInternally` to stay `true` even though the user isn't dragging anymore blocking `onDOMSelectionChange` thus preventing the user from selecting anything inside the editor.
**Context**
This pr simply ensues `isDraggingInternally` is always reset `onDrop`/`onDragEnd`
**Checks**

fix isDraggingInternally reset logic

---

docs/concepts/11-normalizing.md

Slate imposes additional constraints on the schema that are not discussed. In particular, it assumes properties are JSON-serializable, and does not allow properties to be `null`. Developers need to know these constraints before they design their schema. In my case, I designed a schema that allowed `null`, and now have live documents with this value -- I would not have to fix this if I knew the constraints up front.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4836

Document additional schema constraints due to design of operations

---

.changeset/hip-pigs-film.md
packages/slate-react/src/components/element.tsx

Currently finding the dom range of a void node in read-only crashes the editor since slate doesn't render the void spacer in read-only.
This pr simply adjusts the Element component so that it is rendered even in read-only.
> ⚠️  I'm not sure why this wasn't the case before, so there might be something I'm missing here. 
**Checks**

render void spacer in readonly mode

---

.changeset/fast-doors-peel.md
packages/slate/src/interfaces/point.ts
packages/slate/test/interfaces/Point/transform/backward-insert-text-after-point.tsx
packages/slate/test/interfaces/Point/transform/backward-insert-text-at-point.tsx
packages/slate/test/interfaces/Point/transform/backward-insert-text-before-point.tsx
packages/slate/test/interfaces/Point/transform/forward-insert-text-after-point.tsx
packages/slate/test/interfaces/Point/transform/forward-insert-text-at-point.tsx
packages/slate/test/interfaces/Point/transform/forward-insert-text-before-point.tsx
packages/slate/test/interfaces/Range/transform/outward-collapsed.tsx

When one creates a RangeRef with affinity `outward` and the ref becomes collapsed, it can't be expanded again with an `insert_text` operation (although it should IMO). 
**Example**
Lets take an example string (and not care about paths for simplicity sake)
```
This is a test
```
The RangeRef is the following
```ts
{ 
affinity: 'outward',
current: { 
anchor: { offset: 4 }, 
focus: { offset: 4 } 
},
}
```
Now if the user types something at offset 4 (right after the first word) the RangeRef right now changes to the following
```ts
{ 
affinity: 'outward',
current: { 
anchor: { offset: 5 }, 
focus: { offset: 5 } 
},
}
```
Although I naively expected it to be this.
```ts
{ 
affinity: 'outward',
current: { 
anchor: { offset: 4 }, 
focus: { offset: 5 } 
},
}
```
**Context**
If you …

fix point transform for insert_text to account for affinity

---

docs/api/nodes/editor.md

There is currently no definition of this in the docs, so it's very hard to understand what this function is supposed to do, and whether it's buggy. I've written this definition based on Ian Taylor's messages on Slack:
Jason: Why does unhangRange only unhang the end of a range and not
the start as well? Trying to tell if this is a bug or some logic I'm
not following. If the start of the range is at the last index of a
text shouldn't unhangRange advance that to the next node?
ianstormtaylor: I don’t believe it’s a bug. It was designed to
handle ranges that result from triple-clicks. Not that there might
not be improvements, or that there might not be some other better
way to solve for triple-clicks, or that there might be a better
name for it
Jason: When you say triple-click …

Define "hanging range" and intended behavior of unhangRange

---

docs/concepts/10-serializing.md

The initial motivation for this was that the example did not provide details on how to deserialize marks.
Additionally I feel it's okay to return successfully serialized child nodes from unrecognized elements (default fallback of element switch), rather than just its text-content.
This also required the child map to be flattened.
While I was at it, I also replaced the numbers in the `nodeType` checks with their respective Constants (`Node.TEXT_NODE` and `Node.ELEMENT_NODE`), which makes the code easier to grasp for a reader.
**Context**
It took me quite a while how to figure out how to properly deserialize marks. An example is included for serialization (strong) but not for deserialization.
**Disclaimer**
While I have tested this in my actual code, the original is written …

DOCS: improved deserialization example

---

site/examples/custom-types.d.ts
site/examples/richtext.tsx

Add the basic alignment to the rich-text example. I looked around for it and was unable to find it anywhere and thought it might be helpful to someone else like me. 
If not needed, I can close.
**Example**
**Checks**

Example: Add Alignment to richtext example

---

.changeset/healthy-wasps-sit.md
packages/slate-react/src/components/editable.tsx

fixed cursor when we triple click on text and type over it
**Issue**
Fixes: ([bug when we triple click on text and type over it #4862](https://github.com/ianstormtaylor/slate/issues/4862))
**Example**
Before:
current:
**Checks**
- [ ✅] The tests pass with `yarn test`.
- [ ✅] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ✅] The relevant examples still work. (Run examples with `yarn start`.)

fixed cursor when we triple click on text and type over it #4862

---

.github/workflows/ci.yml
package.json
yarn.lock

Node.js v12 LTS is about to reach EOL, and Node.js v16 is the current LTS. THis PR will explore upgrading.

Update to Node v16 for infrastructure

---

docs/Introduction.md

Just removes a stray 'to' in the docs

Fix a teeny tiny typo

---

packages/slate-react/src/components/slate.tsx

As I described in https://github.com/ianstormtaylor/slate/pull/4755 it doesn't really solve the underlying problem and causes new issues to arise. The code has also has no indication about what it tries to fix. So we should be looking for a better fix that doesn't have side effects. 
**Issue**
**Checks**

Invert #4755

---

.github/workflows/ci.yml

Working to upgrade to Node 16. GH Actions are cached. Adding a key should clear the cache per various sources.

Attempt to clear GH actions cache with key

---

.changeset/cuddly-foxes-sell.md
packages/slate-react/src/utils/environment.ts

The chrome will hit 100 in a couple of weeks. this pr fix regex for checking three-digit chrome and edge version.
**Issue**
Fixes: [4869](https://github.com/ianstormtaylor/slate/issues/4869)
**Checks**

Fix chrome and edge three digit version check

---

packages/slate/src/interfaces/editor.ts
packages/slate/src/transforms/node.ts
packages/slate/test/transforms/normalization/set_node.tsx

add custom compare node props
**Example**
node = { type: 'p', attributes: { hidden: true } }
**Context**
If you don't do it, you may create an infinite loop when setting properties
**Checks**

feat: add custom compare node props

---

.changeset/fuzzy-teachers-develop.md
packages/slate-react/src/plugin/react-editor.ts

If you have a nested editor setup. For example, one editor has a void node that contains another editor. In this case, a resolution of a selection by the nested editor previously would consider that the selection is for a void node since an ancestor void node does exist. However, the selection is only a void node in the context of this editor if the ancestor void node is contained in the editor.
In the "Editable Voids" example on the docs site, you can see this bug when you clear the text of the nested editor, and type one character. The selection will jump back to the beginning.
**Issue**
Fixes: [(link to issue)](https://github.com/ianstormtaylor/slate/issues/4293)
**Example**
There is a GIF in the original ticket, the new behavior is what would be expected, after inserting one …

toSlatePoint should not consider a selection within a void node if the void node isn't in the editor itself.

---

.changeset/fair-forks-hope.md
docs/api/nodes/editor.md
docs/concepts/07-editor.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/hotkeys.ts
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Element/isElement/editor.tsx
packages/slate/test/interfaces/Element/isElementList/full-editor.tsx

A different behavior for inserting a soft break with `shift+enter` is quite common in rich text editors. Right now you have to do this in `onKeyDown` which is not so nice. This adds a separate `insertSoftBreak` method on the editor instance that gets called when a soft break is inserted. I made sure to maintain the current default behavior for backwards compatibility (it just splits the block). But at least you can easily overwrite it now.
If you rely on overwriting `editor.insertBreak` for extra behavior for soft breaks this might be a breaking change for you and you should overwrite `editor.insertSoftBreak` instead.
**Issue**
**Checks**

Add soft break as a separate overridable editor method

---

packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/src/transforms/node.ts
packages/slate/test/transforms/setNodes/merge/text.tsx

I have a problem adding marks and need to merge
**Example**
```
before
<editor>
<block>
<text a={{ b: 1 }}>
word
</text>
</block>
</editor>
after
<editor>
<block>
<text a={{ b: 2, c: 3 }}>
word
</text>
</block>
</editor>
```
**Checks**

Add merge to set node

---

.changeset/poor-hats-design.md
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/test/index.spec.tsx

Due to a regression, decorations that cross child elements were not properly passed to those elements for rendering; the offsets from the anchor and node were being applied to every child node, rather than the specific intersection. This PR ensures that the child elements always receive the intersecting range of the decoration. 
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4909
**Example**
Given this value, where some elments are nested under a parent element:
```javascript
[
{
type: "parent",
children: [
{ type: "block", children: [{ text: "foo" }] },
{ type: "block", children: [{ text: "bar" }] },
{ type: "block", children: [{ text: "baz" }] }
]
}
]
```
And this return from decorateNode on the parent element above:
```javascript
[
{
anchor: { path: [0, …
```

Fix child element decorations

---

.changeset/funny-humans-whisper.md
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/test/index.spec.tsx

Fixes https://github.com/ianstormtaylor/slate/issues/4900
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4900
**Example**
The logic in `with-react` was not resetting the node keys for the right nodes for `split_node` and `merge_node` operations. This fixes that so that on `split_node` the node being split does not get remounted and on `merge_node` the node being merged into also does not get remounted.
**Context**
See https://github.com/ianstormtaylor/slate/issues/4900
**Checks**

Fix NODE_TO_KEY correction for split_node and merge_node

---

.changeset/late-monkeys-hug.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/weak-maps.ts

Fixes macOS auto replacement and possibly issues with other IMES by restoring the intended user selection after beforeInput events with a target range.
**Example**
Before:
After:
**Context**
We currently select the before-input target range thus overwriting the actual intended user selection. The target range of the before-input event isn't meant to be used as the user selection. This pr stores the origin user selection before we select the target range and restores it once we have applied the change if no `set_selection` operation was applied on between.
There are definitely other ways to achieve to solve this, but I went with this approach as it was the simplest to do and shouldn't break any existing plugins. I don't really have a strong opinion about this.
Here is how …

Restore user selection after beforeinput with target range

---

.changeset/big-keys-grab.md
packages/slate-react/src/components/editable.tsx

Updates the `Editable` component to call the `keyDown` handler while composing.
**Context**
Ever since https://github.com/ianstormtaylor/slate/pull/4450 the `keyDown` event handler on the `Editable` isn't called while composing. While it makes sense to not call the `Editable`s own handler logic while the user is composing, we should still call user-defined keyDown handlers which can ignore `keyDown` events based on e.g. `event.nativeEvent.isComposing`. There are a lot of use-cases where you might want to act on keyDown events while composing (e.g. when stopping propagation)
**Checks**

Call user-defined keyDown handler while composing

---

.changeset/red-bottles-peel.md
docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/02-adding-event-handlers.md
docs/walkthroughs/03-defining-custom-elements.md
docs/walkthroughs/04-applying-custom-formatting.md
docs/walkthroughs/05-executing-commands.md
docs/walkthroughs/06-saving-to-a-database.md
packages/slate-react/src/components/slate.tsx
site/examples/check-lists.tsx
site/examples/code-highlighting.tsx
site/examples/custom-placeholder.tsx
site/examples/embeds.tsx
site/examples/forced-layout.tsx
site/examples/hovering-toolbar.tsx
site/examples/huge-document.tsx
site/examples/iframe.tsx
site/examples/images.tsx
site/examples/inlines.tsx
site/examples/markdown-preview.tsx
site/examples/markdown-shortcuts.tsx
site/examples/mentions.tsx
site/examples/paste-html.tsx
site/examples/plaintext.tsx
site/examples/read-only.tsx
site/examples/richtext.tsx
site/examples/scroll-into-view.tsx
site/examples/search-highlighting.tsx
site/examples/shadow-dom.tsx
site/examples/tables.tsx

Makes the `<Slate/>` `onChange` prop optional, updates the docs to treat the `<Slate/>` component as uncontrolled to avoid confusion.
**Context**
Ever since https://github.com/ianstormtaylor/slate/pull/4540 slate is in a weird half state. The API and docs suggest it's controlled as it requires a `onChange` and `value` prop and all examples keep a record of the state outside the component in a `useState`. This causes a lot of confusion, especially for people new to slate (see e.g. https://github.com/ianstormtaylor/slate/issues/4812) without any good reason.
**Checks**

Make onChange prop optional, update examples and docs to treat slate as uncontrolled

---

.changeset/five-emus-roll.md
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/utils/environment.ts

Run `<Slate />`'s focus event listeners after `<Editable />`'s focus handlers in React >= 17
**Issue**
Fixes: #4754
**Example**
See #4754 / #4755 - happy to provide more evidence if necessary
**Context**
In #4754, @jhurwitz noted that "the `useFocused` hook displays old values". I noticed this issue in my project as well, and the fix in #4755 solved the problem for me. However as noted by @bryanph, this change caused a regression when selecting between two different editors. Thus #4755 was reverted in #4874.
By chance, I noticed that running @jhurwitz's [code sandbox](https://codesandbox.io/s/stupefied-moore-qsmjh?file=/src/Editor.js) in slate's examples does not cause the "inverted" focus behaviour, and after some digging I realized that the difference is that the code …

Run <Slate />'s focus event listeners after <Editable />'s focus handlers in React >= 17

---

docs/concepts/12-typescript.md
docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/04-applying-custom-formatting.md
site/examples/editable-voids.tsx

Just noticed a few things I missed in the docs in https://github.com/ianstormtaylor/slate/pull/4922, sorry about that.
**Checks**

Update examples in docs, editable voids example

---

.changeset/chilly-boats-deny.md
packages/slate-hyperscript/src/index.ts

It is not possible to write slate-hyperscript tests in Typescript+React projects. As `<text>` element conflicts with React-defined SVG `<text>` element definition.
One possible solution could be to configure JSX with `createHyperscript()` by using the `createText` creator with a different name.  However, this is not possible, as `createText` is private and is never exported.
This PR solves it.
**Issue**
Fixes: #4931
**Example**
```tsx
import { createHyperscript, createText } from 'slate-hyperscript';
const jsx = createHyperscript({
creators: {
leaf: createText,
},
});
```
```tsx
<editor>
<paragraph>
<leaf bold>Welcome</leaf> 
</paragraph>
</editor>
```
**Checks**

Export `createText` from `slate-hyperscript`

---

.changeset/shy-wasps-mix.md
packages/slate-react/src/utils/environment.ts

Firefox v100 was [released to the beta channel today](https://www.mozilla.org/en-US/firefox/100.0beta/releasenotes/) and is being incorrect caught by the Firefox legacy check, breaking composition. This is the same as https://github.com/ianstormtaylor/slate/pull/4883 which fixed the checks for Chrome and Edge.
**Checks**

Fixed legacy check for Firefox v100+

---

docs/concepts/10-serializing.md

Right now the example of the recursive function in the docs for serializing is never ending because of a typo.

Doc serializing fix

---

.changeset/khaki-panthers-burn.md
packages/slate/src/transforms/node.ts
packages/slate/src/transforms/text.ts

May cause severe performance degradation if more and more point refs
need to be updated.
PointRef instances are not cleaned up in some of the `Transform` functions and can cause performance degradation especially with large documents.
**Issue**
Fixes: no issue filed
**Checks**

Fix pointRef leaks caused by not unref'ing

---

docs/api/nodes/element.md

add documentation for missing `Element` interface methods
**Issue**
Fixes: #4942 
**Context**
just changes documentation files (markdown files)
**Checks**

feat(docs): add missing Element methods

---

.changeset/fair-bobcats-accept.md
packages/slate-react/src/components/editable.tsx

Fixes a regression introduced by https://github.com/ianstormtaylor/slate/pull/4933. Basically, when triple-clicking the editor root, the path has a length of 0 so it was calling `Editor.start`,`Editor.end` with a path of `[undefined]`.
This pr also moved some in-place checks for the later handling before the manual triple-click handling to ensure we are acting on a valid state.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4941
**Checks**

Fix editor root triple click crash

---

.changeset/poor-mangos-burn.md
packages/slate-react/src/components/editable.tsx

Updates the 'native insert' logic to don't treat inserts at the end of anchor elements as native. Currently, we only check if we insert at the end of inline elements to try and catch this case, but this is insufficient as we can:
- Render leaves as anchors 
- Render elements as anchors
This PR updates the check to be on a dom level to try and catch the 2 cases mentioned above.
Chrome is very aggressive in trying to insert outside anchors. It seems to determine the end of an anchor element on a text level so even higher level blocks rendered as anchor elements can cause issues.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4911
**Example**
See https://github.com/ianstormtaylor/slate/issues/4911 which includes a sandbox link as well.
**Checks**

Prevent native insert at the end of anchors

---

.changeset/little-plums-behave.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/positions/range/start-in-void.tsx

The 'positions' iterator code has special logic to always return the 'start' of the first node in a block, when using a content based 'unit' such as 'character'. There's a flag to track whether we've returned that start point or not, in order to skip yielding the start point on subsequent nodes in the block. We also have an early continue on the loop for void nodes, to make sure we only ever yield the the first point of a void.
The bug was that if you start iteration inside a void, that early continue code executes, but does not reset the "I've returned the start point" flag, even though we have
**Example**
If you have 
```
<block>                  // path [0]
<text text="hello"/>   // path [0, 0]
<inline-void>          // path [0, 1]
<text/>              // path [0, 1, 0] …
```

Fix positions iteration when starting in an inline void node

---

.changeset/sixty-students-leave.md
packages/slate-react/src/components/editable.tsx

Adjusts the fix in https://github.com/ianstormtaylor/slate/commit/9957c214357dbbd5492ec4761fd6e1c7b14310f5 to truly catch all edge-cases.
Right now it doesn't work for decorations since the `Editor.isEnd()` check will return false for decorations that split text node.
The `createTreeWalker` approach was the fastest way I could find to get the last dom text node inside the anchor element. Maybe there is a smarter way to do it using e.g. `document.evaluate`.
**Checks**

fix double insert in anchor element decorations

---

.changeset/twenty-papayas-vanish.md
packages/slate-react/src/components/editable.tsx

Don't treat events with a non-selection target range as native. This e.g. happens with a 'i' => 'I' substitution on macos.
Before:
After:
**Checks**

Don't treat events with non-selection target range as native

---

.changeset/neat-pets-grow.md
packages/slate-react/src/components/editable.tsx

Fixes a regression introduced by the manual triple-click handling introduced in https://github.com/ianstormtaylor/slate/pull/4914
**Example**
Before:
After:
**Context**
https://github.com/ianstormtaylor/slate/pull/4914 changed the triple click handling to always select the entire root node, which doesn't match the native browser behavior on nested blocks.
**Checks**

Fix triple click handling in nested blocks

---

packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/src/interfaces/node.ts
packages/slate/src/interfaces/path.ts
packages/slate/src/interfaces/point-ref.ts
packages/slate/src/interfaces/point.ts
packages/slate/src/interfaces/range.ts
packages/slate/src/interfaces/text.ts
packages/slate/src/interfaces/types.ts
packages/slate/src/transforms/node.ts
packages/slate/src/transforms/selection.ts
packages/slate/src/transforms/text.ts

Adds options types such as `EditorPathOptions` for each of the inline object literal types used as function parameters.
Also adds union types of string literals such as `LeafEdge` for ones commonly reused.
I have low confidence in any names, as this is my first PR in this repository. 🙂 
**Issue**
Fixes #4966
**Example**
**Checks**

Added types for options and common string literals

---

docs/walkthroughs/06-saving-to-a-database.md

Fixed a bug in the example code which was causing a compiler warning: 
`React Hook useMemo received a function whose dependencies are unknown. Pass an inline function instead  react-hooks/exhaustive-deps`

Fixed a bug in the example code in docs

---

.changeset/breezy-lizards-impress.md
packages/slate-react/src/components/editable.tsx

The composition end event isn't fired reliably in all browsers, so we sometimes might end up stuck in a composition state even though we / aren't composing anymore resulting in the selection not being updated:
https://user-images.githubusercontent.com/13185548/166024085-cda35d14-05d7-457a-952e-3637d9cb4fe7.mov
**Checks**

Unset isComposing on keydown with isCompsing false

---

.changeset/odd-cats-tie.md
docs/libraries/slate-react.md
packages/slate-react/src/components/android/android-input-manager.ts
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

Moves the Editable `isComposing` state into the `isComposing` WeakMap used by the AndroidEditable and exposes the current state via `ReactEditor.isComposing(editor)`.
It's quite common to handle some events differently inside a user-defined handler based on the `isComposing` state (e.g. you don't want to trigger markdown shortcuts etc. while the user is composing as that often leads to undesirable behavior).
Currently, you have to keep track of the `isComposing` state on your own using your own, which I don't think is desirable.
**Checks**

Add ReactEditor.isComposing(editor)

---

.changeset/wise-dots-cheat.md
packages/slate/src/transforms/text.ts
packages/slate/test/transforms/insertText/selection/block-across-inline-wold.tsx

When select a paragraph with different styles of text, for example, bold and plain, and then insert the letter q. What I want is to insert a non-bold letter.
**PR**
Fixes: [#4804 ]
**Context**
I fix the error of PR #4804 , and add a test case to describe the scene as I see it. 
**Checks**

update insertText logic when selection is not collapsed

---

docs/Introduction.md

Change link for Links example to use Inlines examples from Readme

docs: fix links example not working

---

docs/api/locations/path.md
docs/api/nodes/node.md
packages/slate/src/interfaces/node.ts
packages/slate/src/interfaces/path.ts

This PR updates the documentation of `Node.ancestors`, `Node.levels` and `Path.ancestors` to be correct. They all depend on `Path.levels` which sorts from shallowest to deepest, but the docs stated they sorted from deepest to shallowest. This PR has no functional changes.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4398
**Example**
There is no example given for this PR, since it contains no functional changes. For reasoning for updating docs, see `Context` section. 
**Context**
[Node.ancestors depends on `Path.ancestors`](https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/interfaces/node.ts#L134), which [depends on `Path.levels`](https://github.com/ianstormtaylor/slate/blob/d2fc25c3c31453597f59cd2ac6ba087a1beb1fe3/packages/slate/src/int …

update docs on Node.ancestors/levels and Path.ancestors

---

.changeset/lovely-pumas-fix.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/test/index.spec.tsx
yarn.lock

This reverts #4876 (and the related #4910 fix to it) while we seek out another way of improving decorations to meet everyone's needs without regressions.
**Context**
See: https://github.com/ianstormtaylor/slate/pull/4993
One great addition from #4876 which was _not_ fully reverted here is the creation of tests for slate-react. The specific decorations tests themselves were removed--while the ideal behavior of decorations continues to be revisited in future PRs, and then we can restore them--but the test setup itself was kept, particularly since at least one subsequent PR also uses it.
**Checks**

Fix: revert to prior decorations behavior

---

docs/walkthroughs/01-installing-slate.md

This PR replaces the `useState`s in the "Installing Slate" walkthrough with `useMemo`s to reflect what's recommended in the rest of the documentation.

Replace useState with useMemo in the "Installing Slate" walkthrough

---

.changeset/twelve-elephants-burn.md
packages/slate/src/transforms/text.ts
packages/slate/test/transforms/delete/unit-character/thai-multiple-reverse.tsx
packages/slate/test/transforms/delete/unit-character/thai-reverse.tsx

When Thai characters are deleting from backward, each code point should be considered as 1 unit for deletion regardless of their grapheme cluster. For example, deleting พี่ from backward should delete the last code point, leaving พี instead of deleting all entirely. 
**This PR fixes deleteBackward behavior for Thai script where deleting N character(s) backward should delete N code point(s) instead of an entire grapheme cluster.**
This change should not affect other languages as the regular expression `/[\u0E00-\u0E7F]+/` checks for the range of Thai script before performing any operation.
**Issue**
Fixes: #4884 
**Example**
Before (unexpected behavior):
https://user-images.githubusercontent.com/30551284/171138953-e72f8c20-17d9-466b-afa1-64080a5a433e.mp4
After (expected): …

Fix deleteBackward behavior for Thai script

---

docs/concepts/09-rendering.md
docs/concepts/12-typescript.md
docs/libraries/slate-history.md
docs/libraries/slate-react.md
docs/walkthroughs/01-installing-slate.md
docs/walkthroughs/02-adding-event-handlers.md
docs/walkthroughs/03-defining-custom-elements.md
docs/walkthroughs/04-applying-custom-formatting.md
docs/walkthroughs/05-executing-commands.md
docs/walkthroughs/06-saving-to-a-database.md

The documentation was previously using a mix of `useState` and `useMemo` for storing the editor. 90% of the times it was using `useMemo`.
As pointed by @cameronbraid in https://github.com/ianstormtaylor/slate/pull/5020#issuecomment-1149450318, React may forget about a previously memoized value and recalculate the useMemo.
So this PR suggests replacing all occurrences of `useMemo` to store the `editor` with `useState`.

Replace useMemo with useState in the docs

---

site/examples/mentions.tsx

correct spacer tag position to avoid IME input being interrupted
**Issue**
Fixes:  #3490

fix(mentions): correct spacer tag position

---

.changeset/nervous-cars-divide.md
packages/slate/src/transforms/text.ts

`Path.previous()` dose not working when path is `null` because null is passed as the argument to `previous()`
`Path.previous()` argument does not allow `null`: https://github.com/ianstormtaylor/slate/blob/0a90e6420ca622077f59208b86ffaba2137c9477/packages/slate/src/interfaces/path.ts#L47
But here `previous()` can pass null. Because it uses the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator): https://github.com/ianstormtaylor/slate/blob/0a90e6420ca622077f59208b86ffaba2137c9477/packages/slate/src/transforms/text.ts#L454-L460
So I fixed it to not allow null. Please check codesandbox.
**Example**
codesandbox: https://codesandbox.io/s/young-paper-s9fhvf?file=/src/App.tsx:526-582
1. focus
2. …

fix: `Path.previous()` dose not working when path is `null`

---

.changeset/hot-seahorses-smile.md
packages/slate-react/src/components/editable.tsx

Workaround for a obscure bug in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1219139
**Example**
Behavior when adding whitespace="pre" styling to the code highlighting example and pasting tab chars:
Before:
After:
**Checks**

Don't native insert in elements with white-space="pre" containing tab chars

---

.changeset/ten-chefs-cheat.md
packages/slate-react/src/components/editable.tsx

Fixes inserting accented characters using the macOS accent menu when using arrow keys
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5038
**Example**
Before:
After:
**Context**
When holding down 'a' to type a with an accent the first 'ArrowLeft' key down is triggered with `isComposing=false` and before any event indicating that it is composing. Immediately afterward the 'normal' composition start/update events are fired and all following events have `isComposing` properly set, and because the composition start is fired before the selection change selecting the character / after the beforeinput we keep the selection obtained by manually handling the arrow keys which doesn't match the dom state and insert there because chrome doesn't fire the …

fix macos accent menu when using arrow keys

---

.changeset/pretty-plums-grow.md
packages/slate/src/transforms/text.ts
packages/slate/test/transforms/insertFragment/of-mixed/block-empty.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-empty2.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-empty3.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-end.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-end2.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-middle.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-start.tsx
packages/slate/test/transforms/insertFragment/of-mixed/block-start2.tsx

When insert mixed fragments (inline1 + block + inline2) at an empty block end, the insert result is: inline1 + inline2 + block
**Issue**
Fixes: #3457
**Example**
insertFragment([{"text":"inline1\n"},{"type":"ul","children":[{"type":"li","children":[{"text":"block li1 \n"}]},{"type":"li","children":[{"text":"block li2 \n"}]},{"type":"li","children":[{"text":"block li3 \n"}]}]},{"text":"inline2\n"},{"text":"inline3\n"},{"text":"inline4"}])
should result:
> inline1
> - block li1 
> - block li2 
> - block li3 
> 
> inline2
> inline3
> inline4
but result:
> inline1
> inline2
> inline3
> inline4
> - block li1 
> - block li2 
> - block li3 
NOTICE: to get the correct input of the insertFragment, it depends on the deserializer used by the slate instance. so no directly online …

Fix mixed inline/block insertFragment.

---

.changeset/five-snails-travel.md
packages/slate-react/src/plugin/react-editor.ts

Fixes `toSlatePoint` in void nodes with nested editors if children are rendered as the last (or not first) child. Currently `toSlatePoint` will return an incorrect path since `voidNode.querySelector('[data-slate-leaf]')` will match the first child inside the nested editor and not the void children.
Why would you ever want not to have the slate children as the first child? To get around [this chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1297461), if the last element inside your document is a void node (reproducible inside the slate playground as well):
https://user-images.githubusercontent.com/13185548/180413815-7e260167-85df-4f67-9a5f-4e129b970d0b.mov
**Checks**

Fix toSlatePoint in void nodes with nested editors if children are rendered as the last child

---

.github/workflows/release.yml

npm tags sometimes failing to get applied with releases, warning mentioned this error. It looks like switching from master to main was missed in one place.

Release workflow: Replace master with main

---

packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts

Fixes https://github.com/ianstormtaylor/slate/pull/4988#issuecomment-1201060222. Swiftkey is a pain 😅
**Checks**

Prevent swiftkey from closing when typing next to the placeholder element

---

.changeset/spotty-mirrors-matter.md
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Element/isElement/editor.tsx
packages/slate/test/interfaces/Element/isElementList/full-editor.tsx

https://github.com/ianstormtaylor/slate/pull/4012 Previously added the ability to customize the `getDirtyPaths` as one would any other editor method. In my case, this will be useful for the case where deleting a node results in two lists being adjacent to one another, in which case the I'd like the lists to be merged. Currently, the default implementation of `getDirtyPaths` only sets the ancestors of the removed node as dirty, while I'd need to set the immediate siblings as dirty as well. Presumably there are other helpful use cases out there.
From what I can tell, https://github.com/ianstormtaylor/slate/pull/4012 was approved and merged, but somewhere along the way the changes were lost. Viewing the [merge commit](https://github.com/ianstormtaylor/slate/commit/1bfde7efde1c …

Customize get dirty paths

---

.changeset/friendly-oranges-remain.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts
packages/slate-react/src/plugin/with-react.ts

Fixes 2 issues with the current android implementation:
1. Currently, writing in an empty editor with a visible placeholder won't auto-capitalize the first letter due to the IME picking up the text inside the non-contenteditable placeholder element. The most robust fix I found for this is to artificially add a line break to the end of it so the IME thinks the placeholder element is in the line above. Shoudn't have any visual impact on the rendered placeholder itself.
2. The current way we force a swiftkey update after inserting the first word after a mark placeholder to get around the incorrect insert offset causes issues if the editor flush takes a long time and/or you are typing fast because it causes the IME to drop the typed characters. I've experimented a lot around …

Fix selection handling with slow flush in mark placeholders on android, fix auto-capitalize after placeholder

---

site/examples/images.tsx

In the images example, it would still insert an image node after I cancel the file prompt which is unneccesary.
**Issue**
none
**Example**
none
**Context**
**Checks**

fix(example): no action when cancel a file prompt

---

.changeset/smooth-queens-tie.md
packages/slate-react/src/plugin/with-react.ts

`withReact()` plugin type signature is inaccurate. 
In reality, it accepts any `editor` instance implementing `BaseEditor` and extends it with additional `ReactEditor` API.
But the type definitions require to pass an instance that is already a `ReactEditor`. 
The typical workaround is either to [cast the instance with `as ReactEditor`](https://github.com/ianstormtaylor/slate/issues/4144#issuecomment-1046097560) or [define the `Editor` custom type in the project](https://github.com/ianstormtaylor/slate/issues/4144#issuecomment-1075045383). However, both are band-aid solutions to the real problem: invalid type spec of the `withReact()` function.
**Issue**
Fixes: #4144
**Example**
Before the fix:
After the fix:
**Context**
n/a
**Checks**

Fix - `withReact` type signature

---

packages/slate-react/src/components/slate.tsx

Fixes HMR breaking the Editable component
**Issue**
[HMR breaking Editable](https://github.com/ianstormtaylor/slate/issues/5093)
**Example**
https://user-images.githubusercontent.com/23149166/185932982-7cc097d3-7af6-41e5-88ac-e6923847c087.mp4
**Checks**
```
Error: Qualified path resolution failed - none of those files can be found on the disk.
Source path: /mnt/SSD/projects/work/vitereacttsslatehmr/src/slate/.yarn/__virtual__/slate-hyperscript-virtual-07e8ae0801/1/packages/slate-hyperscript/
Not found: /mnt/SSD/projects/work/vitereacttsslatehmr/src/slate/.yarn/__virtual__/slate-hyperscript-virtual-07e8ae0801/1/packages/slate-hyperscript/
Not found: /mnt/SSD/projects/work/vitereacttsslatehmr/src/slate/.yarn/__virtual__/slate-hyperscript-virtual-07e8ae0801/1/packages/slate-hy …
```

Fix children being undefined on HMR uploads.

---

docs/walkthroughs/01-installing-slate.md

Not having the brackets around the editor is inconsistent with the rest of the walkthrough and created some problems when I tried to use it.
**Example**
In this code block, there's no bracket: 
Those are the next three blocks in the walkthrough:

Added missing brackets to resolve inconsistency

---

.changeset/poor-jokes-chew.md
packages/slate-react/src/components/element.tsx

When a parent Element re-render child Elements using React context, Slate can no longer track the DOM node to Slate node mapping.
**Issue**
Fixes #5104
**Example**
The same repro in #5104 with locally patched `slate-react` package:
https://user-images.githubusercontent.com/1330321/187604574-36b4e2ea-2616-42fe-a51e-73de17498563.mp4
**Context**
This PR changes `Element` to use callback-style ref, so every change in the ref target (including unmounting) will be observed.
`Editor` and `Leaf` doesn't need this treatment, because they attach `ref` to nodes that can only change when the component itself re-renders.
However, if we also change `Editor` and `Leaf`, then `ELEMENT_TO_NODE` and `NODE_TO_ELEMENT` maps can use normal `Map`s, instead of `WeakMap`s, which is 5x faster in …

Use callback-style ref in `Element` component

---

.changeset/neat-pigs-hunt.md
packages/slate-react/src/components/editable.tsx

The portable text editor is a rich text field. It is marked up as a text field with `role="textbox"`, but does not have `aria-multiline="true"`. As it does allow for multiple lines, this attribute should be added to set the right expectations. 
Related reads:
- [WAI-ARIA 1.1 - textbox (role)](https://www.w3.org/TR/wai-aria/#textbox)
- [WCAG SC 1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#info-and-relationships)
Kind thanks to @hidde for the suggestion. :)
**Checks**

Add `aria-multiline` attribute to textbox editor

---

.changeset/calm-readers-brake.md
packages/slate-react/src/components/editable.tsx

The editor selection is not updated in correspondence with the dom selection in readonly mode. When clicking outside of the editor, the editor is not deselected as expected and the selection remains unchanged.
**Example**
Now:
https://user-images.githubusercontent.com/13460383/189302488-cd5453c2-ce78-47ae-a06b-2556e0c23c59.mov
After fix:
https://user-images.githubusercontent.com/13460383/189302512-1829a9e7-bd72-4a4a-8692-6ffe81786edf.mov
**Checks**

Fix selection out of sync in readonly mode

---

site/examples/hovering-toolbar.tsx

Currently, the [Hovering Toolbar example](https://www.slatejs.org/examples/hovering-toolbar) does not let edits pass through. This is because we are doing `event.preventDefault()` en every `onDOMBeforeInput`. This fixes the issue by running `event.preventDefault()` only when it applies.
**Example**
https://user-images.githubusercontent.com/40034115/188515801-657161c0-4bab-44c4-a06f-91be905177f6.mp4
**Checks**

only preventDefault if the input is actually a format action

---

.changeset/pink-panthers-appear.md
packages/slate-react/src/components/editable.tsx

Tiny cleanup and fix as discussed in https://github.com/ianstormtaylor/slate/discussions/5125
**Checks**

Cleanup and fix insertion placeholder mark compare

---

.changeset/good-cats-warn.md
packages/slate-react/src/components/editable.tsx

Make it possible to delete block elements with backspace on Chrome and Safari
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5122
**Example**
Before Chrome: 
After Chrome: 
**Checks**

Make it possible to delete block elements with backspace on Chrome and Safari

---

.changeset/dry-nails-brake.md
packages/slate-react/src/plugin/react-editor.ts

Updates `toDOMPoint` to explicitly put the dom point into the dom text element inside mark placeholders to get around https://bugs.chromium.org/p/chromium/issues/detail?id=435438. Seems like we didn't run into this issue beforehand because zero-widths typically have surrounding content (like <br/> on line break zero-widths), which forces chrome to put the selection into the actual dom text element resulting in `getBoundingClientRect` returning the correct values.
**Example**
Before:
https://user-images.githubusercontent.com/13185548/192734925-81103a0f-e345-4cb6-807c-e0a705a3a915.mov
After:
https://user-images.githubusercontent.com/13185548/192734942-9b702018-d0b1-40d0-8613-8f921da86676.mov
**Checks**

fix scrollIntoView when selection is collapsed inside mark placeholder

---

.github/workflows/ci.yml
.github/workflows/comment.yml
.github/workflows/release.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

packages/slate-react/src/components/editable.tsx

This reverts https://github.com/ianstormtaylor/slate/pull/4868.
The issue reported at https://github.com/ianstormtaylor/slate/issues/4862 is a valid complaint, but the change is not an appropriate fix. It is a serious breaking change, reported in https://github.com/ianstormtaylor/slate/issues/5153.
If we wish to fix Chromium's triple-click bug, we should do so by unhanging the selection when it is created; not by changing insertText behavior.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5153
**Checks**

Revert insertText breaking change that deletes fragment (fixes #5153)

---

.changeset/funny-sheep-double.md
packages/slate-react/src/components/leaf.tsx

Selector the correct DOM element on which to set the min-height in the case that the Editable has a custom renderElement set.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5147
**Checks**

Ensure the min-height for placeholders is set on the correct editor

---

.changeset/new-needles-itch.md
packages/slate/src/interfaces/path.ts
packages/slate/src/transforms/text.ts

delete and insert large fragment can be very time consuming，the time complexity is `O(n2)`
**Example**
```ts
import { createEditor, Editor, Descendant, Transforms } from "slate";
import type { Descendant } from "slate";
const createP = (i: string = '') => ({
type: "p",
children: [
{ text: `${i} This is editable ` },
{ text: 'rich', bold: true },
{ text: ' text, ' },
{ text: 'much', italic: true },
{ text: ' better than a ' },
{ text: '<textarea>', code: true },
{ text: '!' },
],
})
// one thousand paragraphs
const largeFragment: Descendant[] = new Array(2000).fill(1).map((_, i) => createP(i + ''));
export const testDelete = () => {
const editor = createEditor();
editor.children = largeFragment;
const sel = Editor.range(editor, []);
Transforms.select(editor, sel); …
```

transform.delete and transform.insertFragment performance optimize

---

.changeset/cuddly-kiwis-work.md
packages/slate-history/src/history-editor.ts
packages/slate-history/src/history.ts
packages/slate-history/src/with-history.ts
packages/slate-history/test/undo/cursor/keep_after_focus_and_remove_text_undo.js

This is a proposal, curious what you all think.
As @TheSpyder mentioned in https://github.com/ianstormtaylor/slate/issues/3756#issuecomment-737022068, often times normalization logic can trigger `set_selection` operations that modify the selection state in the middle of an operation stack. Also, the `set_selection` operation often only contains the `anchor` OR the `focus` property because partial updates are allowed. As the current handling of the `set_selection` operation in `slate-history` overrides the previous op, this information is often lost as you apply more operations and undo them.
Instead of using operations to reset selection, this change stores a separate `selectionBefore` property as part of the undo batch that contains the selection as it was before the …

Change how slate-history handles selection undo

---

docs/api/nodes/editor.md

Slight improvement to editor documentation.
No functionality changed.
**Checks**

Simplify / clarify wording in editor doc

---

docs/api/nodes/node.md
docs/concepts/03-locations.md

The Slate API is difficult to grok.  This example shows how to use several calls together, and is useful besides.

Adds an example using SlateNode.common() with the editor selection

---

packages/slate-react/src/components/slate.tsx

This PR fixes two typos in error messages:
- Adds missing space in `elementsbut`
- Capitalises `you` in `you passed`
It also removes the line breaks in the string interpolation for these error messages to make it easier to find them in search, e.g. currently searching the codebase for `Expected a list of elements but got:` yields no results.
**Issue**
N/A
**Example**
`Uncaught Error: [Slate] value is invalid! Expected a list of elementsbut got: [{}]` -> `Uncaught Error: [Slate] value is invalid! Expected a list of elements but got: [{}]`
`Uncaught Error: [Slate] editor is invalid! you passed: {}` -> `Uncaught Error: [Slate] editor is invalid! You passed: {}` 
**Context**
N/A
**Checks**

Fix typos in error messages + Improve searchability

---

.changeset/tame-melons-clap.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/above/range.tsx

Wrong matching ancestor above a location in the document when selection range multiple nodes.
**Jsfiddle**
[demo](https://jsfiddle.net/Steven_zhong/wsoaL4zk/45/)
**Context**
The correctness of the method is guaranteed by different verification processing logic for points, paths or range.
**Checks**

fix: error getting parentEntry in selection range

---

.changeset/modern-cooks-grow.md
docs/api/nodes/editor.md
docs/api/nodes/element.md
docs/concepts/07-editor.md
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
packages/slate/test/transforms/setNodes/inline/inline-void-2.tsx
packages/slate/test/transforms/setNodes/marks/mark-across-range.tsx
packages/slate/test/transforms/setNodes/marks/mark-void-collapsed.tsx
packages/slate/test/transforms/setNodes/marks/mark-void-range-hanging.tsx
packages/slate/test/transforms/setNodes/marks/mark-void-range.tsx
site/examples/mentions.tsx

Some void elements are effectively stand-ins for text, such as with the mentions example, where the mention element renders the character's name. Users might want to format Void elements like this with bold, or set their font and size, so `editor.markableVoid` tells Slate whether or not to apply Marks to the text children of void elements.
- Adds `markableVoid()` as a schema-specific overrideable test.
- Changes `addMark` and `removeMark` so marks can apply to voids. Also changes behavior of collapsed selection so that if a markable Void is selected, the mark will be applied / removed.
- Shows how `markableVoid()` can work in the Mentions example
**Example**
The Mentions example, with R2-D2 in bold text
**Context**
I have achieved a similar effect by overriding …

Allow void elements to receive marks

---

docs/concepts/11-normalizing.md

This is a documentation fix only.
A reference to the preceding code sample incorrectly mentions `Editor.unwrapNodes` instead of `Transforms.unwrapNodes`.

Docs: fix incorrect name.

---

.changeset/seven-waves-rhyme.md
cypress/integration/examples/editable-voids.ts
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

This PR makes it possible to copy/cut void elements. 
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4808 and https://github.com/ianstormtaylor/slate/issues/4806
**Example**
Before
After: 
**Context**
Created a new function hasSelectableTarget that checks if hasEditableTarget and isTargetInsideNonReadonlyVoid. 
Using this function instead of hasEditableTarget so we are not excluding nonReadonlyVoids fx onCopy and onCut and onPaste
I did not add Cypress tests for the new logic since Cypress does not support copy/paste and the only solution I found was to use some package like https://www.npmjs.com/package/clipboardy. If we want to include the package or if there is a better solution for it I'm happy to add the tests.
**Checks**

Fix Copy/pasting void elements is not working

---

site/examples/mentions.tsx

An error occurs if you try to change the line when there are no search results on the [Mentions Demo](https://www.slatejs.org/examples/mentions)
**Example**
**Checks**
- [ o ] The new code matches the existing patterns and styles.
- [ o ] The tests pass with `yarn test`.
- [ o ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ o ] The relevant examples still work. (Run examples with `yarn start`.)
- [ o ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

Fix: Mentions Example

---

.changeset/real-badgers-pull.md
packages/slate-history/src/history.ts
packages/slate-history/test/index.js
packages/slate-history/test/isHistory/after-edit.js
packages/slate-history/test/isHistory/after-redo.js
packages/slate-history/test/isHistory/after-undo.js
packages/slate-history/test/isHistory/before-edit.js

This change preserves the original functionality of `isHistory`, but does not add verification of `History` `Batch`'s new `selectionBefore` property.
**Issue**
Fixes: #5177
**Checks**

Update `isHistory` to match new interface.

---

docs/concepts/12-typescript.md

Remove duplicate useState import from React.
**Example**
**Checks**

remove duplicate useState import

---

.changeset/purple-planes-study.md
packages/slate/src/interfaces/editor.ts
packages/slate/src/transforms/node.ts
packages/slate/src/transforms/text.ts
packages/slate/test/interfaces/Editor/unhangRange/block-hanging-over-non-empty-void-with-voids-option.tsx
packages/slate/test/interfaces/Editor/unhangRange/inline-at-end.tsx
packages/slate/test/interfaces/Editor/unhangRange/multi-block-inline-at-end.tsx
packages/slate/test/interfaces/Editor/unhangRange/not-hanging-inline-at-end.tsx
packages/slate/test/interfaces/Editor/unhangRange/not-hanging-multi-block-inline-at-end.tsx
packages/slate/test/transforms/delete/voids-false/inline-over.tsx
packages/slate/test/transforms/insertText/selection/block-hanging.tsx
packages/slate/test/transforms/setNodes/marks/mark-void-range-hanging.tsx

`Editor.unhangRange()` could decide to proceed with an adjustment in cases where the range was not hanging. Because the algorithm it uses **always** skips over the first node it encounters, this meant the selection was adjusted in non-hanging cases. This change reduces the chances of an incorrect decision to adjust. Transforms now pass the `voids` flag to `unhangRange()` as it seems logical that the adjusted range should reflect the intention of the operation.
This change fixes a unit test I added for markable voids that had to be skipped because of the `unhangRange()` error, and fixes a couple other long-skipped tests.
**Example**
Previous code behavior in the Mentions example when the range is **not** hanging and the word "Test" is typed:
Because the range gets adjusted …

Fix overly-aggressive unhangRange

---

.changeset/light-moose-jam.md
docs/api/transforms.md
packages/slate/src/transforms/node.ts

Since `unsetNodes` really just calls `setNodes`, it seems like it should offer the same options.
Without this change, doing something like applying a mark to the contents of a selected block with `hanging` works one way, while trying to do the reverse (remove the mark) cannot include the "hang".
**Context**
We're running into some trouble with how `unhangRange` treats inline voids when they are at the end of a block (will open a separate issue for this), but an initial work-around was to change our code that adds marks to include `hanging: true` but we immediately discovered that removing a mark from the same range it was just applied to becomes impossible.
It just seems like `unsetNodes` and `setNodes` should be "symmetric".
**Checks**

Add hanging option to unsetNodes

---

.changeset/sixty-ghosts-invent.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/marks/markable-void-collapsed.tsx
packages/slate/test/interfaces/Editor/marks/markable-voids-mixed.tsx
packages/slate/test/interfaces/Editor/marks/mixed-text.tsx
packages/slate/test/interfaces/Editor/marks/text-collapsed.tsx

Now that `markableVoid()` allows marks to be applied to inline voids, our users discovered a problem where the marks applied to a currently-selected markable void are not reported properly by `Editor.marks()`
I have added a few unit tests for the previously un-tested `Editor.marks()`, including one for markable void that failed before the fix (markable-void-collapsed).
The `if (anchor.offset === 0)` test in `Editor.marks()` that checks if the `prevPath` is in the same block was effectively returning the marks of any Text that preceded the selected markable void.
**Checks**

Fix reporting of marks on a markableVoid

---

docs/api/locations/range-ref.md

Typo.
**Context**
Documentation.
**Checks**

Fix typo in documentation

---

docs/walkthroughs/03-defining-custom-elements.md

On this page (https://docs.slatejs.org/walkthroughs/03-defining-custom-elements) inline comments are not working as expected for `` Ctrl-` `` which is because of consecutive backticks with last backtick `` -` ``.
**Example**
This PR fixes the issue by adding spaces around inline code which prevents the issue and works as expected ( without surrounding spaces being rendered around the mark )
Here are screen shots of the solution markdown on 
VS Code markdown Preview
Github markdown preview
**Checks**

Docs: fix Ctrl-` backticks issue on 03-defining-custom-elements page

---

.changeset/strange-pens-lie.md
packages/slate-react/package.json
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/utils/weak-maps.ts
packages/slate-react/test/index.spec.tsx
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts
yarn.lock

This PR makes the default styles of an `Editable` component come from stylesheets added to the DOM rather than inline styles on the editor element.  This resolves an issue in which setting the `position`, `outline`, `white-space`, or `word-wrap` properties using the `className` prop would have no effect. It also resolves issue #4314 in which setting the `min-height` property on an editor would have no effect.
Additionally, a change was made to make the `min-height` of editors change when the size of their placeholder element changes.
**Issue**
Fixes: #4314
**Example**
Pictured is a modification of the custom placeholder example.
The `min-height` changes have no effect, and the change to `outline` only has an effect when passed as part of the `style` prop.
The `min-height` …

Use stylesheets to give Editable components default styles

---

.changeset/clean-socks-hammer.md
packages/slate-react/src/components/editable.tsx

The editable voids and emded examples are currently broken and don't allow you to type anything into the input fields. With this change it should be editable again.
**Checks**

fix: allow input into editable voids

---

.changeset/curly-news-cover.md
packages/slate-react/src/components/editable.tsx

The current implementation of defaultScrollSelectionIntoView makes tests run by node fail. 
```
/home/circleci/repo/node_modules/slate-react/dist/index.js:4937
leafEl.getBoundingClientRect = domRange.getBoundingClientRect.bind(domRange);
^
TypeError: Cannot read properties of undefined (reading 'bind')
at scrollSelectionIntoView (/home/circleci/repo/node_modules/slate-react/src/components/editable.tsx:1698:67)
at setDomSelection (/home/circleci/repo/node_modules/slate-react/src/components/editable.tsx:368:9)
at /home/circleci/repo/node_modules/slate-react/src/components/editable.tsx:376:25
at commitHookEffectListMount (/home/circleci/repo/node_modules/react-dom/cjs/react-dom.development.js:20573:26)
at commitLifeCycles …
```

Check if getBoundingClientRect exist before trying to call bind

---

docs/walkthroughs/04-applying-custom-formatting.md

Adds a note in the walkthrough section of the documentation that leaves must return inline elements.
**Issue**
This fixes no existing issues.
**Context**
One of the things I struggled with in my project was figuring out why arrow navigations between nodes were failing. I soon realized it was because my leaves were described as a `div` element, not an inline element. Not only did I have no idea where to find information about leaves, but the section itself doesn't seem to document this behavior. I believe this change can at least help prevent the same mistake and give a little more insight as to how and where to find more information regarding leaves.
I also believe updating the Leaves section to include information about this behavior will be great as well. Being new to …

Note that leaves must be inline elements

---

docs/concepts/07-editor.md

The existing link was dead, this references the current location of the selection transforms docs.
**Issue**
N/A
**Example**
Before
After:
**Context**
N/A
**Checks**

Fix broken selection transforms link in editor docs

---

.changeset/wet-tigers-double.md
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/above/point.tsx

Fixes `Editor.above` with `Point` locations. Currently it always return `undefined`.
**Issue**
Fixes: #5215
**Example**
Without this change, following code would always return `undefined`:
```js
export const input = (
<editor>
<block>
<block>one</block>
</block>
</editor>
)
export const test = editor => {
// at could be any Point
return Editor.above(editor, { at: { path: [0, 0, 0], offset: 0 } })
}
```
**Context**
`Editor.above` should ignore checking text nodes (they're never above anything) and continue looking for ancestors.
Otherwise it won't be able to find any above nodes when starting to look from a text node.
This is in line with how this method worked prior to #5168
**Checks**

Fix editor above with point

---

.changeset/fix-qq-browser-ime-input.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/environment.ts

Users cannot input any Chinese charactors on latest version(11.5.0) of QQ browser.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/pull/3730#issuecomment-1074819628 and #4962
**Example**
before:
after:
**Context**
The problem is caused by an earlier commit #3730. The changes could work for legacy versions. But for now, as mentioned in https://github.com/ianstormtaylor/slate/pull/3730#issuecomment-1074819628 and #4962, QQ browser might has changed its behavior of `beforeinput` since version 10.8.x in early 2022. And now in latest version of QQ browser, its chromium core version had updated to 94(And it's really hard to find legacy version installer of QQ browser except http://web.archive.org). So it's OK to remove these campat codes.
**Checks**

fix QQ browser IME characters input failure

---

Readme.md
docs/general/contributing.md

There were several places in the docs linking to a broken Heroku app for access to Slack. This PR replaces those links with the direct Slack invite link that had already been updated in the [GH issue config](https://github.com/ianstormtaylor/slate/blob/main/.github/ISSUE_TEMPLATE/config.yml#L4).
**Issue**
Fixes:
- Slack link in [readme](https://github.com/ianstormtaylor/slate/blob/main/Readme.md)
- Slack links in [contributing](https://github.com/ianstormtaylor/slate/blob/main/docs/general/contributing.md) 
**Context**
In the readme the link was part of a badge which was also broken as it was coming from the heroku app, this is now replaced with a badge from badge.io
Before
After
**Checks**

fix slack links in readme and contributing

---

.changeset/fast-apricots-deliver.md
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/utils/dom.ts

- Fixes the editor selection not getting updated during `readOnly` mode in the shadow dom
- The `hasShadowDom` was only working correctly in edit mode. We're now traversing the active node's parents and looking for a `[object ShadowRoot]` string to determine if we are in a shadow dom. This fix works for both edit and readOnly states now.
**Example**
I will share a video of the before and after soon! 
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is …

Fix selection getting incorrectly set in readonly shadow dom case

---

packages/slate-react/src/components/slate.tsx

With Strict Mode starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component. This change in behavior results in the `EDITOR_TO_ON_CHANGE` map getting set to a `NoOp` function due to the unmount call and does not reset to the correct callback function until the next state change happens within the `Slate` component. 
The fix for this is to put `EDITOR_TO_ON_CHANGE.set(editor, onContextChange)` into `useEffect` so that the correct `onContextChange` callback gets added back into the `EDITOR_TO_ON_CHANGE` map when effects get re-created on a mounted component.
[Link to read more about this change in React 18.](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state)
**Example**
**This is …

bugfix: moves EDITOR_TO_ON_CHANGE.set(editor, onContextChange) into useEffect 

---

site/examples/forced-layout.tsx

Updates the forced-layout example so that it can insert untitle node.
When `Editor.before()` return null, Slate will not actually delete. So `editor.children.length < 1` never trigger.
Now if you delete after `cmd+a`, also you delete the last paragraph when title is empty,  it can insert untitle node.
**Example**
before: 
https://user-images.githubusercontent.com/33490722/213435182-a9d757cd-430e-44f1-a9b1-294fd5c5d214.mov
after:
https://user-images.githubusercontent.com/33490722/213435161-311a65d0-f85a-46b1-b16a-b1bc09e2ec32.mov
**Checks**

Fix forced-layout example trigger insert untitle node

---

docs/general/contributing.md

Contributing.md had outdated instructions on how to run a filtered test suite.
**Issue**
**Example**
**Context**
**Checks**

docs: Update instructions to run tests in contributing.md

---

docs/concepts/04-transforms.md

Javascript syntax was not being highlighted on the [concepts/04-transforms](https://docs.slatejs.org/concepts/04-transforms) on the doc. Maybe this is an issue with GitBook. Code block started with `` ```js `` was not being highlighted whereas `` ```javascript `` and `` ```typescript `` was being rendered perfectly. So I changed all `` ```js `` to `` ```javascript ``.
**Issue**
Fixes: No issues were created for this
**Example**
Here's how the doc looks right now:
**Checks**

doc: syntax highlighting fix on concepts/04-transforms page

---

.changeset/thirty-starfishes-knock.md
packages/slate-react/src/plugin/react-editor.ts

This is a revival of PR #4908, which itself is a revival of #3374, both of which are currently inactive.
This PR fixes the bug in Firefox where double-clicking a word creates a selection whose anchor is inside the preceeding text node. (This is similar to the concept of a "hanging range", but not an example of it as per #4852.)
**Issue**
Fixes #3336
Fixes #3840
Fixes #4634
Fixes [#1987](https://github.com/udecode/plate/issues/1987) (Plate)
Fixes [#1897](https://github.com/udecode/plate/issues/1897) (Plate)
**Example**
From #4908:
**Context**
PR #4908 had two requested changes (left by @BitPhinix) which were never addressed.
1. [Relating to type signatures](https://github.com/ianstormtaylor/slate/pull/4908#discussion_r857711656)
I've fixed this and the resulting type …

Firefox: fix wrong text highlighting with double-click (revived PR)

---

docs/general/resources.md

add tripdocs link to docs resources
**Issue**
Fixes: null
**Example**
add a line
**Context**
This introduces an open source, modern, production-ready rich text editor
**Checks**

add tripdocs link to resources

---

.changeset/witty-tips-work.md
packages/slate-react/package.json
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/utils/where-if-supported.ts
yarn.lock

#5206 made Editable components use stylesheets for default styles instead of inline styles. However, it also inadvertently reduced compatibility with browsers that lack support for `ResizeObserver` and the `:where` CSS selector (mainly Safari versions released before September 2020). The result was that browsers that did not support `ResizeObserver` would throw a `ReferenceError` when rendering a placeholder element, and browsers that did not support `:where` would not see default styles for Editable components.
This PR adds a polyfill for `ResizeObserver` and a fallback for browsers that do not support `:where` to fix both of those problems.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/pull/5206#issuecomment-1384361788
**Context**
The latest major browser to …

Improve compatibility for browsers that do not support `ResizeObserver` or `:where` selector

---

playwright.config.ts
playwright/integration/examples/hovering-toolbar.test.ts
site/components.tsx

There was an issue with playwright integration test. There was wrong menu selection locator
**Issue**
**Example**
**Context**
**Checks**

Fix: hovering-toolbar playwright integration test

---

.changeset/afraid-cougars-smell.md
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/dom.ts

Allow customization of clipboard fragment format name. Based on #5233 and [slate-angular](https://github.com/worktile/slate-angular/blob/master/packages/src/plugins/with-angular.ts#L22)
**Issue**
#5233
**Checks**

feat: allow to change clipboard fragment format name

---

packages/slate-react/src/utils/weak-maps.ts

Remove weak maps `IS_DRAGGING` and `IS_CLICKING`, which are not used anywhere.
**Checks**

Remove unused weak maps

---

.changeset/unlucky-chairs-promise.md
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts

In Android, deleting text doesn't trigger the selectionchange event, so EDITOR_TO_PENDING_SELECTION doesn't be updated when deleting text.  And after deleting all the input that it makes hasPendingDiffs to be false, will triggers applyPendingSelection and it makes the the cursor jump to an unexpected position. So i have to force update EDITOR_TO_PENDING_SELECTION when deleting text.
**Issue**
Fixes: #5249 
**Example**
before:
https://user-images.githubusercontent.com/11460856/211196919-1d65e01b-fd89-49b3-a91a-3d50048619ed.mp4
after:
https://user-images.githubusercontent.com/11460856/211197195-9070f9b7-e540-43e7-8761-e7fc6e8daf50.mp4
**Checks**

Fix the cursor jump to an unexpected position after deleting in android

---

.changeset/grumpy-pianos-sit.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/text.tsx

It was discovered that slate-react was leaving behind detached spans and divs as the edited text was being updated causing  memory leaks.
The cause of the leaks were in the weak maps used in `packages/slate-react/src/components/editable.tsx` and `packages/slate-react/src/components/text.tsx`.  DOM nodes stored in the maps were detached but the keys still had strong references.
This PR adds callback refs to remove DOM nodes from the maps when the refs are set to null.
**Checks**

fix: remove memory leaks in Text and Editable

---

.changeset/two-books-bow.md
docs/api/nodes/editor.md
docs/concepts/07-editor.md
packages/slate-react/src/plugin/with-react.ts
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts

_not sure if the coding style fits as it looks to be the first time we have many parameters in an editor method, any suggestion is welcome_
Non-breaking changes:
- new `editor` method that can be overridden to control when the normalization should stop. Default behavior (unchanged) is to throw an error when it iterates over 42 times the dirty paths length.
```ts
shouldNormalize: ({
iteration,
dirtyPaths,
operation,
}: {
iteration: number
dirtyPaths: Path[]
operation?: Operation
}) => boolean
```
- `editor.onChange` signature change: `(options?: { operation?: Operation }) => void` where `operation` is triggering the function.
- `editor.normalizeNode` signature change: `(entry: NodeEntry, options?: { operation?: Operation }) => void` where `operation` is triggering the …

More control on `editor.normalizeNode`

---

.changeset/large-steaks-try.md
packages/slate-react/src/components/editable.tsx

This is a fix for the issue preventing pasting plain text into editable voids. At the moment one can paste other Slate elements into an editable void, but nothing happens when plain text (e.g. copying a URL from browser's search bar).
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5294
**Example**
Before:
https://user-images.githubusercontent.com/3620639/219029517-0f7b11e3-78ae-4033-af74-61730103ae04.gif
After:
https://user-images.githubusercontent.com/20068819/220671252-af48f410-a5c1-4e57-8fcc-4cb88242c953.mov
**Context**
A change was introduced recently to support copying and pasting void elements, which seems to have changed the behaviour for the paste action as you can find it here https://github.com/ianstormtaylor/slate/pull/5121/files#diff-1d0c52ec4c5 …

fix: add support for pasting plain text into editable void

---

.changeset/pretty-buses-stare.md
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/components/text.tsx

The merge of #5261 caused a regression where the first value of onChange is cached indefinitely because it is not used as a dependency of the effect that is supposed to maintain it. This fixes that bug, and similar bugs in the React.memo comparisons for MemoizedElement and MemoizedText where a cached `renderPlaceholder` is passed down to the leaf.
**Issue**
Fixes: #5289
**Example**
See the recording in #5289 for an example of the bug. A similar one could be crafted with renderPlaceholder being cached if necessary, but it should be pretty clear from the code.
**Context**
There aren't really other ways to fix these issues in a localized manner. I did look into adding the eslint plugin that can help check hook dependencies but there are violations in the code that would …

fix: Add missing dependencies to useEffect and React.memo calls (#5289)

---

.changeset/large-worms-jog.md
docs/api/nodes/editor.md
packages/slate/src/create-editor.ts
packages/slate/src/interfaces/editor.ts

The maximum number of iterations should be computed before the while loop, not inside.
**Checks**

fix: `normalizeNode`

---

.changeset/tall-adults-attack.md
packages/slate-react/src/components/editable.tsx

A bit of code clean up in Editable.  Combines the callback ref and the code in a call to useIsomorphicLayoutEffect that was attaching and event handler to the referenced node.
**Checks**

refactor: editable - combine ref callback and event handler in useIsomorphicLayoutEffect

---

.changeset/text-leaf-memoization.md
packages/slate-react/src/components/string.tsx

This PR changes the approach used in the `<TextString>` component to synchronize the DOM and the Virtual DOM. 
Previously, the initial render of the `<TextString>` component would render the initial text, but the second render would remove the text from the DOM, before quickly being re-committed to the DOM in the layout effect before the browser had time to paint.
This PR takes a different approach that avoids ever having to render an empty `textContent` on the second render. Instead, we render a memoized component in `<TextString>` (`<MemoizedText>`), that receives props that are referentially stable across re-renders, such that React never updates the DOM across re-renders.
This PR provides a significant performance improvement over the current implementation, as …

Use memoization to avoid unnecessary `textContent` updates in `TextString` component

---

.changeset/android-text-mutations.md
.changeset/consumer-oninput-event.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/restore-dom/restore-dom-manager.ts

Depends on https://github.com/ianstormtaylor/slate/pull/5306
This PR introduces two changes:
1. Consumers can define an `onInput` prop on the `<Editable>` component, but it wasn't being invoked, which is now fixed.
2. The `restore-dom-manager` no longer reverts `characterData` mutations
These changes are introduced so that consumers can listen to the `onInput` event to flush pending diffs on Android on every change:
```tsx
<Editable
onInput={() => {
// Reconcile the editor state with the pending changes on every input event.
const pendingDiffs = ReactEditor.androidPendingDiffs(editor)
const scheduleFlush = pendingDiffs ? pendingDiffs.length > 0 : false
if (scheduleFlush) {
ReactEditor.androidScheduleFlush(editor)
}
}}
```
Before this PR, it was not possible to reconcile …

Android related improvements

---

.changeset/red-hats-guess.md
packages/slate-react/src/components/editable.tsx

`Editable` creates a couple debounced selection event listeners. 
With the recent changes to remove memory leaks, if the debounced event listeners are triggered but the editor is removed from the DOM before the debounce timer fires, errors are thrown: "Cannot resolve a DOM node from Slate node".
The event handlers have `cancel` methods that need to be called when an editor's node is removed from the DOM.  
**Checks**

fix: cancel debounced listeners in Editable

---

.changeset/new-dryers-stare.md
packages/slate-react/src/utils/environment.ts

We found that the code for determining the conditions of use of the `beforeinput` event is based on the following code.
https://github.com/ianstormtaylor/slate/blob/96ad964beee5b7c67d4aa18bdd9d6e7d2f9ef3bf/packages/slate-react/src/utils/environment.ts#L36
https://github.com/ianstormtaylor/slate/blob/96ad964beee5b7c67d4aa18bdd9d6e7d2f9ef3bf/packages/slate-react/src/utils/environment.ts#L65
Where `IS_CHROME_LEGACY` determines that Chrome versions smaller than 76 cannot use the `beforeinput` event. This results in the following example of Chrome version 68 not being able to use `beforeinput`, resulting in a crash.
**Example**
https://user-images.githubusercontent.com/22654945/222090911-73fe7c1e-8638-44cf-b7a9-7de096d8fd5d.mp4
**Context**
We know from …

Fix the issue of composition API and beforeinput event triggering between Chrome versions 60-75 on the Android platform.

---

.changeset/android-removed-leaf.md
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts
packages/slate-react/src/utils/diff-text.ts

This PR fixes edge-cases in the Android input manager when text leafs are deleted.
Fixes: 
- https://github.com/ianstormtaylor/slate/issues/5192
**Context**
Previously, text leaf deletions were stored in pending diffs and only reconciled when flushing as a result of a selection change or an action (such as inserting a line break). This could result in a number of different edge cases, such as the browser not knowing where to place the selection after deleting a text node before or after a void node.
In order to fix these edge cases, we detect when an input event would result in a text leaf being deleted, and schedule an action to allow Slate to reconcile its state with the DOM and apply normalization fixes (such as inserting zero-width spacers next to inline void nodes) rather than …

[Android] Fix edge-cases when text leaf nodes are deleted

---

packages/slate/src/interfaces/path.ts

This pull request implements a type predicate for the function `operationCanTransformPath` which lives within the `Path` interface.
We have figured, it helps us in writing cleaner code if the function would use a type predicate.
**Example**
```
if (Path.operationCanTransformPath(operation)) {
// ts would complain here without the type predicate
console.log(operation.path);
}
```
**Checks**

Implement type predicate for `operationCanTransformPath`

---

.changeset/small-timers-sin.md
packages/slate-react/src/components/editable.tsx

PR #5310 introduced a performance issue when typing in large documents, caused by adding `renderPlaceholder` to `useMemo` in `element.tsx`. This PR fixes that performance issue by wrapping the default `renderPlaceholder` in a `useCallback`.
In addition, all custom `renderPlaceholder` functions passed to `Editable` should also be wrapped in `useCallback`. 
**Issue**
Fixes: #5335
**Checks**

Fix performance issue with `renderPlaceholder`

---

.changeset/lucky-falcons-reflect.md
packages/slate-react/src/plugin/react-editor.ts

Triple-clicking a word in Chrome will sometimes place the focus inside a `contenteditable="false"` DOM node following the word, which causes `toSlatePoint` to throw an error. This PR checks for this and adjusts the `focusNode` if necessary.
**Issue**
Fixes #5341 
**Context**
https://github.com/ianstormtaylor/slate/issues/4329#issuecomment-894212249
**Checks**

Fix error when triple-clicking a word preceding a `contenteditable="false"` DOM node in Chrome

---

.changeset/dry-bugs-protect.md
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts

Fixes this problem:
1. On an Android phone, open the "Search Highlighting" example page.
2. Search for test.  For example, "search".
3. Place the cursor immediately after one of the highlighted strings.
4. Type additional text.
The additional text will be highlighted as if it matched the search string.
The problem was `Editable` was not calling the `decorate` function that was passed to it when it should.
One thing to note with the fix.  If you follow the steps above and you type additional text quickly, some of it will appear highlighted for a split second.  The gif below demonstrates that.
**Checks**

fix: Editable not calling decorate as it should

---

docs/concepts/10-serializing.md

The node name should be `STRONG` instead of `strong` in the example deserialize function.
In the given deserialize section of the docs, the `el.nodeName` should be upper case. Instead of `strong` it should be `STRONG`. 
**Issue**
Fixes: the deserialize function mentioned in the [Deserializing](https://docs.slatejs.org/concepts/10-serializing#deserializing) section of the docs. 
**Checks**

Fix the nodeName from lower to upper case

---

site/examples/mentions.tsx

This fixes the Android keyboard handling of mentions by moving the non visible space character after the mention. This PR also adds a click handler to the mention dropdown to make it easier to test on mobile.
**Issue**
Solves the issue where typing immediately after a mention on Android causes the text of the mention to be repeated.
**Example**
As tested on Chrome on a Pixel 5A.
Before:
https://user-images.githubusercontent.com/11273838/225190460-8d7a1535-2afe-4dff-9482-812adb7e8a88.mp4
After:
https://user-images.githubusercontent.com/11273838/225190511-06bfbaba-9c7f-4b4f-bb9e-8229da326644.mp4
Note that an issue with a period before a mention still persists.
**Context**
The non-visible spacer is important for focus and mention styling. There are a lot of issues related to …

Android mentions fixes

---

playwright.config.ts
playwright/integration/examples/code-highlighting.test.ts
playwright/integration/examples/markdown-shortcuts.test.ts

The `markdown-shortcuts.test.ts` Playwright test uses the `Home` key, which doesn't work in webkit. This PR changes the test to use `Meta+ArrowLeft` instead.
It also increases the default timeout from 10s to 20s, and 60s for the code highlighing tests. This was necessary to make the test suite pass consistently on my Mac.
**Checks**

Fix `markdown-shortcuts.test.ts` for webkit

---

.changeset/funny-students-sparkle.md
packages/slate-react/src/components/editable.tsx

Copying from an editable void ends up with the whole void element being copied instead of the selected text only. I added a fix so that, when the target of the event is an input field it won't apply the regular Slate logic for copying and instead will just rely on the default browser's functionality.
You'll notice in the video that there is still a not-ideal use case where, if a section of text is selected from an editable void it still ends up copying the whole element, not just the text. This kind of approach is useful to enable, for example, copying a non-editable void element such as a mention. Let me know please if someone has a better idea of how to better handle it.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5366
**Example** …

fix: allow copying from editable void input

---

.changeset/shaggy-donuts-applaud.md
.eslintrc.json
package.json
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/hooks/android-input-manager/use-android-input-manager.ts
packages/slate-react/src/hooks/use-mutation-observer.ts
packages/slate-react/src/hooks/use-slate-selector.tsx
packages/slate-react/src/hooks/use-track-user-input.ts
packages/slate-react/test/index.spec.tsx
site/examples/code-highlighting.tsx
site/examples/markdown-shortcuts.tsx
site/examples/mentions.tsx
yarn.lock

**Issue**
**Example**
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly helpful so that reviewers …

enable eslint hooks rules

---

docs/concepts/07-editor.md

just little mistake in the code example

docs(concepts): fix code example on the Editor page

---

packages/slate-history/src/history-editor.ts
packages/slate-history/src/with-history.ts

This PR extracts pushing to `history.undos` and `history.redos` into its own function. This allows interception of writing to the editor history in other plugins.
**Checks**

Extracts history push to own function

---

site/examples/inlines.tsx

When copying inline nodes from the Slate example, you get a dollar sign around the Inline text you were copying. I believe this is because of the `$` in the `InlineChromiumBugfix` component. 
**Example**
Old behavior:
https://user-images.githubusercontent.com/10213761/231716884-36b739a9-99a9-4d82-a7f7-83526e1f779b.mov
New behavior: 
https://user-images.githubusercontent.com/10213761/231721835-7758507a-7895-4846-a6fd-0823b6a2bed6.mov
**Checks**

Remove unnecessary dollar sign from Chromium bug fix

---

docs/walkthroughs/03-defining-custom-elements.md

A code example in [Defining Custom Elements](https://docs.slatejs.org/walkthroughs/03-defining-custom-elements) documentation page has code that doesn't work.
The code example in question explains how to enable adding code blocks with a keyboard shortcut.
This PR updates the documentation so that the code example has working code.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5293
**Example**
No new behavior, it's just a documentation fix.
**Context**
It is explained in [this comment](https://github.com/ianstormtaylor/slate/issues/5293#issuecomment-1439401672).
**Checks**

docs(walkthroughs): fix incomplete code block keyboard shortcut example

---

docs/walkthroughs/01-installing-slate.md

The "Installing Slate" tutorial starts off with an empty array for the initial editor state. I think a lot of people (including myself) assume the initial state can *always* be an empty array, but this breaks if you go straight to implementing other code samples that attempt to manipulate the state children.
For example, I implemented most of the logic in the [rich text editor sample](https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx), but it will fail with `Uncaught Error: Cannot resolve a Slate point from DOM point:` if your initial state is set to `[]`.
This PR cleans up the tutorial so that users simply start with an initial state that has children defined, so other code samples don't break. This will make it more likely that a user's first …

Add initial value with children in install tutorial

---

docs/walkthroughs/03-defining-custom-elements.md

In the Walkthroughs / Defining Custom Elements documentation page, the last code example didn't work for me: the type of a node didn't change when I pressed the Ctrl+\` key combination. I looked at the differences between this example and the previous one that was working, and found that the `match` condition of the last example for missing a part that was there in the example before.
I added it and it fixed the example.
**Issue**
It doesn't seem there is an existing issue for that.
**Example**
I don't think it is needed for this change
**Context**
I don't think it is needed for this change
**Checks**

docs(walkthroughs): fix broken code example

---

.changeset/few-queens-fold.md
packages/slate-react/src/components/leaf.tsx
yarn.lock

Placeholder position in Safari 16.4 is not correct. this PR aims to fix that. I also checked that in other versions of Safari there's no regression.
**Issue**
Fixes: #5386 
**Example**
Before:
After:
**Checks**

fix(slate-react): add top css to placeholder

---

.changeset/late-zebras-dream.md
packages/slate-react/src/components/editable.tsx

Resolves #5146
Prevents default focus styles from being removed, making the behaviour opt-in via `<Editable>`'s `style` prop or other CSS
**Issue**
Fixes: #5146
**Example**
**Context**
Since Slate.js does not provide any custom focus styles for the editable area, it should not remove the built-in focus style which is required per WCAG criterion [Focus Visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)
If a particular focus styling technique is preferred by library authors (e.g. highlighting the whole area with `:focus-within`), it should be described in the relevant documentation article (e.g. https://www.slatejs.org/examples/styling) rather than being hard-coded in the Editable component.
**Checks**

Fix default focus styles

---

.changeset/six-dryers-raise.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/leaf.tsx
packages/slate-react/src/utils/environment.ts

The previous `IS_SAFARI` test did not catch some WebKit based environments that should have the special cased behavior. For example, running Slate inside a webview on iOS would result in a userAgent like: `"Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"` which would not match the previous `IS_SAFARI` definition, but **does** have the same quirks since it is WebKit based.
**Issue**
No matching issue reported.
**Example**
One manifestation of this is the special behavior for Chrome/Safari (i.e. WebKit) for handling deleting selected inline voids [relevant code](https://github.com/ianstormtaylor/slate/blob/b7fd322f01fde36ff65f3c75a47a9972257f76e7/packages/slate-react/src/components/editable.tsx#L1627-L1628). …

Test for WebKit based browsers instead of Safari

---

docs/walkthroughs/03-defining-custom-elements.md

Imports Element from slate, as it is used in the given code sample of the walkthrough:
```ts
// docs/walkthroughs/03-defining-custom-elements.md
// line 156
{ match: n => Element.isElement(n) && Editor.isBlock(editor, n) }
```
Prevents the following TS error:
```
Property 'isElement' does not exist on type '{ new (): Element; prototype: Element; }'.ts(2339)
```

include missed import in docs walkthrough

---

docs/concepts/06-commands.md
docs/concepts/09-rendering.md
docs/walkthroughs/04-applying-custom-formatting.md
docs/walkthroughs/05-executing-commands.md
site/examples/hovering-toolbar.tsx

When documenting how to apply character-level styling, uses `addMark` and `removeMark` instead of `setNodes`. This avoids new users creating code that only works in the simplest cases.
Similarly, updates the Hovering Toolbar example to apply marks instead of setting nodes.
**Context**
This change was prompted by a discussion on Slack where the developer was disappointed that `markableVoid` did not appear to be working. The problem was they were using `setNodes` to apply Marks, and did not use the same `match` function that `addMark` uses.
**Checks**

Use mark functions for docs and examples

---

.changeset/rare-glasses-tickle.md
packages/slate-react/src/components/editable.tsx

Correct caret position during composition. 
When useIsomorphicLayoutEffect was triggered during composition, caret would jump to wrong position (jump to the start).
This commit fix the bug when using chinese IME.
More info about the bug is in the issue.
**Issue**
Fixes: [#5442](https://github.com/ianstormtaylor/slate/issues/5442)

fix:  caret jump to the start of composition string

---

.changeset/popular-shrimps-give.md
packages/slate-react/src/plugin/react-editor.ts

#5343 Introduced a workaround in `toSlateRange` with a purpose to fix [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=608393)  with triple-clicking that sometimes moves cursor inside non content editable nodes `contentEditable="false"`. Unfortunately, the same workaround causes void elements to crash when being selected, since in the [official docs slates requires](https://docs.slatejs.org/api/nodes/element#rendering-void-elements) void nodes to also have `contentEditable="false"` attribute. Issue #5406 describes the problem in detail.
**Issue**
Fixes: #5406
**Proposed solution**
The original issue focused on fixing selection for `contentEditable="false"` nodes that **were not** void element root nodes at the same time. Also `toSlateRange` already …

Fixed triple click workaround breaking void elements selection

---

.changeset/khaki-toys-unite.md
packages/slate-react/src/utils/environment.ts

Fix the regular expression for testing Webkit based browser. This bug was introduced in #5437 which changed `IS_SAFARI` environment constant to `IS_WEBKIT`, intending to apply all COMPATs for safari to Webkit based browsers like Chrome for ios. However, the regular expression for `IS_WEBKIT` is not correct, because it doesn't exclude blink based browser like Chrome for desktop. That makes some COMPATs for Chrome not work as expected.
**Issue**
Fixes: #5450 
Besides the problem mentioned in #5450, this bug breaks all user inputing behaviors using an IME which triggers a series of composition events in Chrome.
**Example**
**Video**
Chrome not working using an IME:
https://recordit.co/wYOq8Lj7RR
Safari works fine:
https://recordit.co/auIGkmenlk
**Sandbox** …

fix: regular expression for testing Webkit based browser

---

.changeset/nice-shirts-flash.md
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/environment.ts

Checks if `React.version` is < 18 before calling `unstable_batchedUpdates` in `with-react.ts`.
**Context**
Updates are batched automatically in React >= 18. Calling `unstable_batchedUpdates` in React 18 produces an error in some circumstances:
```
[1] - error unhandledRejection: Error [TypeError]: ReactDOM__default.default.unstable_batchedUpdates is not a function
[1]     at e.onChange (webpack-internal:///(sc_client)/../../node_modules/slate-react/dist/index.js:5747:34)
[1]     at eval (webpack-internal:///(sc_client)/../../node_modules/slate/dist/index.js:3006:14) {
[1]   digest: undefined
[1] }
```
**Environment**
The above error was observed in the following environment:
```
react 18.2.0
react-dom 18.2.0
slate 0.94.1
slate-react 0.97.0
```
**Checks**

Do not try to batch updates in React >= 18

---

.changeset/many-cows-add.md
packages/slate-react/src/utils/hotkeys.ts

Changes the hotkeys util to use `isHotkey` instead of `isKeyHotkey`. This should give better support for non-Latin keyboards.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4591
**Context**
`isKeyHotkey` checks against `event.key`, which varies for keyboards of different alphabets. For example, trying to use the undo shortcut on a Russian keyboard on Windows would emit an `event.key` of `я` which fails to match the `mod+z` hotkey.
Using `isHotkey` instead checks against `event.which`, which doesn't vary across alphabets.
**Checks**

Update hotkeys util to use isHotkey for non-Latin keyboards

---

.changeset/two-tomatoes-deliver.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts

This PR fixes the invalid usage of the selection API in firefox. Firefox allows disconnected ranges that cause problems with slate. I originally started to work on this to fix . [this issue](https://github.com/udecode/plate/issues/560)
**Issue**
Fixes: (I do not think this fixes any slate issue, however I am not sure. I did not checked)
**Example**
Before my changes:
https://github.com/ianstormtaylor/slate/assets/50914789/54a02c0a-4211-4d87-b5bc-197433eafd62
After my changes:
https://github.com/ianstormtaylor/slate/assets/50914789/84c69ec1-3088-480f-a75e-7e73ab93bab7
**Context**
1:\
`anchorNode`, `anchorOffset`, `focusOffset`. Do not behave the same in chrome and in firefox. In firefox if there is more then 1 range said values would be invalid. I fixed this by using the …

Fix firefox disconnected selection api usage

---

.changeset/itchy-falcons-dream.md
packages/slate-react/src/plugin/react-editor.ts

This PR fixes the contenteditable table selection in firefox. Firefox uses a custom editor when table is contenteditable and this adds support for this custom editor.
**Issue**
Fixes: None, but it does fix [this](https://github.com/udecode/plate/pull/2538)
**Example**
https://github.com/ianstormtaylor/slate/assets/50914789/a6d0cb31-32d4-4be1-825a-8cce7e5cf781
Before this PR it threw some exception IIRC
**Context**
Firefox basically uses rows in the contenteditable table selection and `startOffset` is the cell offset. By walking down the DOM tree we can get the sames values as in chrome. I also added some checks to make sure this does not crash. 
**Checks**

Fix contenteditalbe firefox table selection

---

.changeset/grumpy-seahorses-love.md
packages/slate-react/src/utils/environment.ts

Fix the bug: cannot input chinese on mac wechat browser
**Example**
https://github.com/ianstormtaylor/slate/assets/42238241/baa5594d-7545-4a06-a5d6-6680271af614
**Context**
**Checks**

fix: no composing text inserted on mac wechat browser

---

.changeset/quick-eyes-count.md
packages/slate-react/src/utils/environment.ts

This is a very serious issue, as it breaks the app using slate on load, not even when interacting with certain parts of slate.
For details see issue below.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5502
**Example**
**Context**
The change makes the check a little bit more verbose but works in exactly the same way: We're testing the user agent for 'Wechat' but exclude 'MacWechat'.
**Checks**

bugfix: Slate breaks on load on Safari < 16.4

---

.changeset/selfish-frogs-press.md
packages/slate-react/src/plugin/react-editor.ts

When calling `ReactEditor.focus()` the current editor selection is lost and the caret is placed at the beginning of the document. This change retains the current editor selection when giving the editor focus.
**Issue**
Fixes: [(link to issue)](https://github.com/ianstormtaylor/slate/issues/5169)
**Example**
Before:
https://github.com/ianstormtaylor/slate/assets/28637598/b68fc68d-90b5-4428-ae2d-e403988e74be
After:
https://github.com/ianstormtaylor/slate/assets/28637598/d55170ed-d200-4cf2-a6e1-77e534638091
**Context**
Before focusing the editor we set the DOM selection so that the corresponding `onDOMSelectionChange` handler in `editable.tsx` does not reset the editor selection when it fires after the `el.focus()` call.
**Checks**

Retain editor selection when using ReactEditor.focus()

---

.changeset/curly-ligers-lay.md
packages/slate-react/src/components/slate.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/weak-maps.ts
packages/slate-react/test/index.spec.tsx

Add `onSelectionChange` and `onValueChange` in Slate React component
**Issue**
Fixes:  #5521 
/claim udecode/plate#2700
**Checks**

Add `onSelectionChange` and `onValueChange` in Slate React component

---

.changeset/empty-shirts-mate.md
packages/slate-react/src/components/editable.tsx

I've found a memory leak in `slate-react` where-in when you'd switch between two pages, each with their own editor instance, auto-focusing on these elements causes a memory leak, where there would be a lot of Detached HTML Element's just floating around.
At first I thought it a bunch of different bugs with chromium, but noticed that when I force removed the input elements from the dom before the component would unmount, we would still see small leak referencing "latestElement" (while simultaneously, I would still the element & children references in the `IS_FOCUSED` WeakMap) Looking at editable's code, I realized that we're storing state in a weird way, directly mutating it using `useMemo`, and React isn't removing all references (probably because its still stored in the …

[editable] Fix Memory Leak when switching between focused editables

---

.changeset/chatty-chefs-sneeze.md
packages/slate-react/src/plugin/react-editor.ts

Due to a [Firefox browser quirk](https://github.com/ianstormtaylor/slate/issues/5273#issuecomment-1789494609), the DOM selection sometimes includes the additional `\n` added when `isTrailing` is true in `TextString`. This results in an invalid focus point, causing a crash during delete operations.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5273
**Example**
Before:
https://github.com/ianstormtaylor/slate/assets/4272090/5195ec18-a630-48ef-8e8d-579ba471b832
After:
https://github.com/ianstormtaylor/slate/assets/4272090/32c15c50-52af-4c1a-92e5-43a50d6dfe10
**Context**
It's possible that the logic for the check I added might not be perfect. However, I'm 99% sure that any new bugs it introduces will be harder to reproduce accidentally than the bug it fixes. …

Fix crash when deleting paragraph ending `\n` in Firefox

---

.changeset/gold-bottles-collect.md
packages/slate-react/src/components/leaf.tsx

In PR #5368, a 300ms delay was added before showing the placeholder to prevent issues relating to mobile phone keyboards. This isn't great UX, and as far as I can tell (@edhager Can you confirm?) it's only needed on Android devices. This PR reduces the delay to 0ms on non-Android devices.
**Example**
https://github.com/ianstormtaylor/slate/assets/4272090/11f03149-cebb-4fba-8e54-bfb5855ab901
**Checks**

Apply placeholder delay only on Android devices

---

.changeset/quick-eels-leave.md
packages/slate/src/transforms-node/insert-nodes.ts

The "select" parameter not works
```
editor.insertNodes(content, { select: false });
```
**Checks**

fix:  the 'select' parameter of the insertNodes function has been overridden

---

.changeset/unlucky-paws-allow.md
packages/slate-react/src/components/editable.tsx

This PR fixes cursor position when selection is collapsed for RTL direction text.
**Issue**
Fixes: #5566
**Example**
For old behaviour please refer to issue #5566. The new behaviour video is attached below:
https://github.com/ianstormtaylor/slate/assets/60817786/548ac60d-82cc-4f89-a013-dd36782e481d
**Context**
N/A
**Checks**

Adjust cursor position when on selection collapse for RTL direction

---

.changeset/blue-flies-decide.md
packages/slate/src/editor/marks.ts
packages/slate/test/interfaces/Editor/marks/firefox-double-click.tsx

This PR contains a quick-fix of marks function using Firefox. This was already fixed, but the fix was removed inside of #5486. I put it back but this time only in marks code instead of selection handling one,  so it should not affect anything else. 
**Issue**
Fixes: #5574 #5560 
**Example**
Before the fix:
When fixed:
**Context**
This is related to firefox weird selection range when double clicking.
Explanation from original fix: 
* suppose we have this document:
*
* { type: 'paragraph',
*   children: [
*     { text: 'foo ' },
*     { text: 'bar' },
*     { text: ' baz' }
*   ]
* }
*
* a double click on "bar" on chrome will create this range:
*
* anchor -> [0,1] offset 0
* focus  -> [0,1] offset 3
*
* while on firefox will create this range:
*
* anchor -> [0,0] offset 4
* …

marks on double click selection using firefox fix

---

.changeset/light-bulldogs-refuse.md
packages/slate-react/src/components/editable.tsx

After `compositionend` event completion, `isComposing` fails to update.
**Issue**
https://github.com/ianstormtaylor/slate/pull/5576
**Example**
After using IME for input, mouse clicking does not trigger the update of the selection, resulting in subsequent input being placed in the wrong position.
**Checks**

Fix onCompositionEnd not updating isComposing

---

.changeset/shiny-numbers-matter.md
packages/slate-react/src/plugin/react-editor.ts

Sometimes, when calling `ReactEditor.focus` in [@testing-library/react](https://testing-library.com/docs/react-testing-library/intro/), the value of `useFocused` doesn't get updated. This PR addresses this issue by setting `IS_FOCUSED` to true prior to dispatching a DOM focus event.
**Context**
The `isFocused` state variable controlling `useFocused` (via `FocusedContext`) is [updated in `slate.tsx`](https://github.com/ianstormtaylor/slate/blob/8f2ad02db32f348eb9499e8db1e46d1b705d4d5d/packages/slate-react/src/components/slate.tsx#L96-L116) in response to focus and blur events, but the value of `isFocused` is always pulled from `IS_FOCUSED`, regardless of which event triggered the update. This stopped working in #5527 when the `ReactEditor.focus` line setting `IS_FOCUSED` …

Fix: Calling `ReactEditor.focus` doesn't update `useFocused` when running in @testing-library/react

---

docs/api/nodes/editor.md

Found a broken link while looking through docs
**Issue**
Fixes: relative pathing
**Example**
Link within [section](https://github.com/sunsheeppoplar/slate/blob/update-docs/docs/api/nodes/editor.md#editorwithoutnormalizingeditor-editor-fn---void--void) works now

Fix relative url to normalizing-11.md

---

site/examples/images.tsx

Automatically adds an empty text node after inserting an image in the example code for using images in Slate. 
**Issue**
Fixes #5597
**Checks**

fix: automatically inserts an empty text node after inserting an image

---

.vscode/launch.json

Add Visual Studio Code launch configuration for mocha tests.
**Context**
Needed to easily start/attach a debugger.
**Checks**

chore: add mocha tests launch configuration

---

.changeset/lazy-radios-smile.md
packages/slate/src/core/normalize-node.ts

Sometimes, when working with other tools such as Yjs, it so happens that we enter nodes into `editor.children` that slate cannot recover from. The most common case I come across is erronous nodes that are elements, and somewhere along the process the `children` field was dropped.
This could happen for various reasons, but IMO slate should be able to recover from them.
**Example**
Let's say you have the following:
```ts
editor.children = [
{
type: "table",
children: [
{
type: "row",
children: [{ text: "empty " }],
},
{
type: "not_row",
},
],
}
]
```
Using `editor.normalize` won't touch the `not_row` element, but if you attempt `editor.normalize({ force: true })`, slate will throw an error, and rightfully so.
This at least prepares the node, making it acceptable by …

feat(normalize-node): Adding `children` field to prevent erronous nodes from breaking notebooks.

---

.changeset/early-mayflies-grow.md

The changeset for #5621 included a trailing space that prevented the Release action from updating the Version Packages PR.
https://github.com/ianstormtaylor/slate/actions/runs/8515022105/job/23321746563#step:5:1704

Fix linting error in changeset

---

.changeset/red-poems-wave.md
.yarnrc.yml
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/utils/dom.ts
packages/slate-react/src/utils/environment.ts
playwright/integration/examples/shadow-dom.test.ts

Safari doesn't support access for selection inside shadow root, this PR implements a workaround that will be applied only for Safari inside shadow root to improve the editor experience inside Safari.
**Issue**
Fixes: #5144 #5321 
**Example**
**Context**
This PR introduces a workaround for the absence of the getSelection method in Safari versions prior to 17 when used inside a shadow DOM, which causes the behavior in the example above. By implementing a workaround, this fix ensures consistent behavior.
**Checks**

Add Safari workaround inside shadow DOM.

---

.changeset/stale-bats-jog.md
packages/slate-react/src/components/string.tsx

Capitalizing doesn't work for iOS if Editor has an empty initial state, see [Custom placeholder example](https://www.slatejs.org/examples/custom-placeholder)
**Issue**
Fixes: [#5199](https://github.com/ianstormtaylor/slate/issues/5199)
**Example**
***Before***
https://github.com/ianstormtaylor/slate/assets/19905096/19bf81a5-d57b-41d3-8451-9f4fcf6fba1f
***After***
https://github.com/ianstormtaylor/slate/assets/19905096/f07be158-ceb3-49e6-89a5-01311f135210
**Context**
There was a fix for Android but not for iOS. Basically `uFEFF` breaks capitalizing experience and it seems it can be removed for iOS devices as well
**Checks**

Make capitalizing work for iOS

---

.changeset/weak-files-jam.md
packages/slate-react/src/components/editable.tsx

#5648 Implements a workaround that will be applied only for Safari inside shadow root to improve the editor experience inside Safari, but it was applied to Safari < 17, and this PR enables it for Safari 17 as well, so that the editor works.
Ideally, the fix should include utilizing `Selection: getComposedRanges()` (I think), but that would require some work and thorough testing, so it can be scheduled for later.
**Issue**
Fixes: (part of) https://github.com/ianstormtaylor/slate/issues/5321
**Example**
**Checks**

Enable Shadow DOM fix for Safari 17.

---

.changeset/grumpy-icons-refuse.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/index.ts

Listen for `dragend` and `drop` events globally to reset `state.isDraggingInternally`. In Firefox, if a drop handler initiates an operation that causes the originally dragged element to unmount, that element will not emit a `dragend` event.
**Issue**
Fixes: #5663 
**Example**
See issue
**Context**
We may want to remove the React `onDragEnd` handler, since after this change, all it does is delegate the event if certain conditions are met.
**Checks**

Reset `state.isDraggingInternally` using global event handlers

---

site/examples/search-highlighting.tsx

When I was testing the 'decorations' feature on the[ official website (search-highlighting)](https://www.slatejs.org/examples/search-highlighting), I noticed that there were some issues with supporting content that had been split into multiple formats.
**Issue**
none
**Example**
When I search for "adds", it works pretty well. However, when I perform a search that spans nodes, it doesn't highlight the content very effectively.
**Context**
I think it's necessary to tackle this issue. Initially, I planned to start with [Range.intersection](https://github.com/ianstormtaylor/slate/blob/97c88d/packages/slate-react/src/hooks/use-children.tsx#L55), by calculating the overlapping ranges at the parent node and judging the intersection of multiple nodes to address this issue. …

fix: site example(Search Highlighting) range

---

playwright/integration/examples/shadow-dom.test.ts

Fixes an integration test introduced in #5648 
**Checks**

test: fix shadow-dom example test

---

.changeset/clean-rats-raise.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/utils/dom.ts

This pr fixes shadow dom example in firefox browser.
**Issue**
Fixes: #5321  
**Example**
**Context**
`ReactEditor.findDocumentOrShadowRoot` returns `document` instead of `ShadowRoot` in firefox. Because firefox doesn't support `getSelection` on `ShadowRoot`. 
This breaks the following: 
```
activeElement === el
```
Here, for example: 
https://github.com/ianstormtaylor/slate/blob/0dc5852da0c11186bc4c81380463658cfff47014/packages/slate-react/src/components/editable.tsx#L231-L241
So I decided to drop `root.getSelection != null` check from `ReactEditor.findDocumentOrShadowRoot` and added a separate function `getSelection` with it.
**Checks**

fix: focus loss inside Shadow DOM in Firefox.

---

.changeset/mighty-trainers-juggle.md
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/test/react-editor.spec.tsx
site/examples/richtext.tsx

When opening the document for the first time, using `ReactEditor.focus` to focus on the document unexpectedly triggers the `onValueChange` event, and there will also be an additional `onChange `event triggered.
**Issue**
Fixes:  #5672
**Example**
The debug code is shown below, and the autoFocus property of Editable is turned off.
https://github.com/ianstormtaylor/slate/blob/631a911ca96e5ac55b80bb260e1e8d114ba76337/site/examples/richtext.tsx#L30-L50
The effect when calling ReactEditor.focus is shown in the image, where you can see the unexpected event triggers.
**Context**
Actually, calling `onChange` in `ReactEditor.focus` isn't necessary. If needed, `Transforms.select` will handle triggering the event.
**Checks**

fix: unexpected event triggered when using ReactEditor.focus

---

docs/general/resources.md

This updates the documentation's "Products" page to include a project I created called Hot Page. I also noticed that Netlify CMS was linked, but they've since launched this as a separate product called Decap CMS.
My colleagues and I really appreciate all the work that goes into Slate. This is a totally amazing library and very inspiring to us. You guys rock! Thank you so much

Update Products listing to include Hot Page, rename Netlify CMS to Decap

---

site/examples/embeds.tsx
site/examples/inlines.tsx
site/examples/paste-html.tsx

The example code for links and embeds is vulnerable to XSS. This PR resolves the issue by explicitly checking the URL protocol.
**Example**
Before:
https://github.com/user-attachments/assets/97bc515e-b361-469b-b6ee-86a65510abbc
**Checks**

Fix link and embed XSS in examples

---

site/examples/mentions.tsx
site/utils/environment.ts

In the current [Mentions Example](https://www.slatejs.org/examples/mentions), the issue with #3490 still persists. Although I noticed it was fixed in #5013, it was reverted back in #5360 .
So this seems to be a compatibility issue with MacOS. Therefore, we check the environment here and only modify the spacer tag position on MacOS.
**Issue**
Fixes: #3490
**Example**
The current issues.
After making adjustments.
It's also running smoothly on my Android device.
**Checks**

fix: prevent IME input interruption on MacOS

---

.changeset/honest-rice-doubt.md
packages/slate-history/src/history-editor.ts

Currently, Slate lacks an API to merge a series of history records to the top of the stack. In some cases, the withMerging function is very useful, for example the upload status from pending to success and AI generate a series of text  withMerging can make sure to remove it in one times redo.
**Issue**
**Example**
**Context**
If your change is non-trivial, please include a description of how the new logic works, and why you decided to …

Add withMerging

---

.changeset/ten-queens-walk.md
docs/libraries/slate-react/hooks.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/use-composing.ts

Expose isComposing for external packages.
https://github.com/udecode/plate/discussions/3425
**Checks**

feat: add useComposing hook

---

.changeset/brown-ears-tap.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/plugin/react-editor.ts
packages/slate-react/src/utils/dom.ts

Currently, when I drag my browser selection focus into a `contentEditable={false}` DOM element that's being rendered by a non-void Slate element renderer, Slate's selection doesn't get updated. At times, this causes non-highlighted text to be deleted when pressing <kbd>Backspace</kbd> (first example below). At other times, this causes a <kbd>Backspace</kbd> press to crash the page (second example below).
The fix in this PR is to set the focus point to the edge of the nearest Slate leaf when the selection focus is in a non-void, non-editable node, instead of disregarding such selections.
Fixes #5714
These examples use https://www.slatejs.org/examples/check-lists, where the “non-void, non-editable” node is [this `<span>`](https://github.com/ianstormtaylor/slate/blob/7e77a932f0489a9fff2d8a195 …

Fix selections with non-void non-editable focus

---

.changeset/odd-falcons-hang.md
packages/slate/src/editor/marks.ts
packages/slate/test/interfaces/Editor/marks/focus-block-end.tsx

When the selection is at the end of the previous node, using Editor.marks retrieves the marks of the previous node. In this case, calling Editor.addMark does not override the previous node, thus causing the states to be out of sync.
**Issue**
Fixes: #5724
**Example**
Before the fix:
When fixed:
**Context**
Thanks to the fix in #5580 , we can easily address this issue. By swapping the positions of anchor and focus according to Range.isBackward, we can then proceed with the original correction logic.
Additionally, since Editor.nodes calls Range.edges to recalibrate the order of anchor and focus, it won't affect the original Editor.marks logic.
**Checks**

fix: marks at the start of the selection

---

.changeset/clean-icons-bow.md
packages/slate/src/interfaces/node.ts
packages/slate/test/interfaces/Node/getIf/root.tsx
packages/slate/test/interfaces/Node/getIf/success.tsx
packages/slate/test/interfaces/Node/getIf/undefined.tsx

This PR is an attempt to solve below issue and provide a graceful method to get a Node.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4845
**Example**
```ts
// If node exists
const node = Node.getIf(editor, [0]); // returns respective node
// If node doesn't exist
const node = Node.getIf(editor, [0]); // return undefined rather than error
```
**Context**
I simply used the existing logic of get method and instead of throwing any error returned undefined
**Checks**

feat: add Node.getIf method

---

.changeset/old-frogs-run.md
packages/slate-react/src/plugin/with-react.ts

Adds an `unref` call on `pathRef`s created for the `move_node` operation after they're used, preventing a memory leak.
**Issue**
Fixes: #5726
**Checks**

Call unref on pathRefs created for move_node

---

.changeset/small-carrots-jam.md
docs/api/locations/range.md
packages/slate/src/interfaces/range.ts

feat: add prop surrounds with range
**Issue**
fix https://github.com/ianstormtaylor/slate/issues/4283
**Example**
```js
let data = {
"anchor": {
"path": [ 0, 0 ],
"offset": 0
},
"focus": {
"path": [ 0, 0 ],
"offset": 5
}
}
let target = {
"anchor": {
"path": [ 0, 0 ],
"offset": 0
},
"focus": {
"path": [ 0, 0 ],
"offset": 8
}
}
Range.surrounds(data, target)
```
**Context**
If your change is non-trivial, please include a description of how the new logic works, …

feat: add prop surrounds with range

---

site/examples/js/mentions.jsx
site/examples/ts/mentions.tsx

I found an issue in Chromium: when a node (A) is set to contenteditable=false and is followed by a text node (B), activating the IME between A and B and then holding the left arrow key to adjust input causes the IME to disappear and leads to unexpected state issues, such as composition events. 
This problem does not occur in Firefox and Safari, only in browsers with the Chromium engine. 
This issue is also mentioned in https://github.com/ianstormtaylor/slate/issues/3490#issuecomment-2241179871.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/3490#issuecomment-2241179871
**Example**
The current issues.
After making adjustments.
**Context**
Here's the minimal demo for this issue: when you activate the IME before the "!" character and then hold the left arrow …

fix: chromium interrupt IME when moving cursor

---

docs/libraries/slate-history/history-editor.md

[`withMerging`](https://github.com/ianstormtaylor/slate/blob/8c7f7ea6ac491d6e1325810ef11fc2b3455b1304/packages/slate-history/src/history-editor.ts#L65-L74) is currently missing from the [`HistoryEditor` docs](https://docs.slatejs.org/libraries/slate-history/history-editor).

Add `HistoryEditor.withMerging` to docs

---

.github/workflows/ci.yml
.github/workflows/codeql.yml

We're using a really old version of Node (12), and then it got bumped to the oldest available version (16), which might still be too old.
<p></p>
**Example**
Now Node has been upgraded to the latest version. You can check the link.
https://github.com/ianstormtaylor/slate/pull/5743/checks
**Checks**

chore: upgrade the ci to node20 to avoid warnings

---

.changeset/gold-cheetahs-rest.md
packages/slate-history/src/history-editor.ts
packages/slate-history/src/with-history.ts

Add a new method `withNewBatch` to `HistoryEditor`. This method allows users to explicitly start a new batch in the history for the first operation, while merging subsequent operations as usual. This provides more fine-grained control over history management, particularly useful for complex editing operations that should be treated as a single unit in the undo/redo history.
**Example**
```ts
HistoryEditor.withNewBatch(editor, () => {
// The first operation here will start a new batch in the history
editor.insertText('Hello')
// These operations will be merged into the new batch
editor.insertText(' ')
editor.insertText('World')
})
```
**Checks**
_Disclaimer: AI generated_

History: withNewBatch

---

.changeset/bright-fishes-protect.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/hooks/android-input-manager/android-input-manager.ts
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/src/plugin/with-react.ts
packages/slate-react/src/utils/weak-maps.ts

This fixes an editor crash where the user types quickly after earlier nodes have been added, split or deleted, but the node maps have not yet been regenerated on React render. 
**Issue**
Fixes: [(link to issue)](https://github.com/ianstormtaylor/slate/issues/5694)
**Example**
Recording (from issue linked above)
https://github.com/user-attachments/assets/a68453b1-df47-4324-a542-9313569958ca
Sandbox (from issue linked above)
https://codesandbox.io/s/slate-selection-change-repro-ztssmp
**Context**
The `NODE_TO_INDEX` WeakMap is built on each React render as part of the `useChildren` hook. Both `onDOMBeforeInput` and `onDOMSelectionChange` use these maps to set the selection. This change introduces a new `WeakMap` called `IS_NODE_MAP_DIRTY` to track whether the underlying …

fix: invalidate node maps when nodes change in-between paints #5694.

---

.changeset/eleven-cycles-kneel.md
docs/libraries/slate-react/hooks.md
packages/slate-react/src/hooks/use-slate.tsx

The `useSlateWithV` return object's `editor` property is currently typed as just a `ReactEditor`, which causes type errors in our app when we try to use it as the extended `Editor` type. This change brings `useSlateWithV`'s return type in line with those of `useSlate` and `useSlateStatic`.

Use extended `Editor` type in `useSlateWithV` return type

---

.changeset/serious-eels-pay.md
packages/slate-react/src/components/editable.tsx

Somehow related to https://github.com/ianstormtaylor/slate/pull/5407 and https://github.com/ianstormtaylor/slate/pull/5571
I debugged an issue in our application where using the [TextExpander](https://textexpander.com/) extension on a Slate input would cause the editor to crash with `Cannot resolve a DOM point from Slate point` coming from `setDomSelection`'s call.
I was able to prevent the crash in our codebase using an ErrorBoundary as suggested [here](https://github.com/ianstormtaylor/slate/pull/5407#issuecomment-1673337395), but wondered why it was crashing to begin with. 
As far as I can tell, although the TextExpander text is not expanded, the editor recovers fine if we discard the error and the existing code supports having a null `newDomRange` so I figured I could …

fix: Prevent ReactEditor.toDOMRange crash in setDomSelection

---

.changeset/large-cars-itch.md
packages/slate/src/core/normalize-node.ts
packages/slate/test/normalization/block/remove-block.tsx
packages/slate/test/normalization/inline/remove-block.tsx

`normalizeNode` ensures that all children of a node are either all blocks or inline/text nodes.
When blocks need to be removed, we can at least unwrap the nodes instead of removing them altogether and thus prevent data loss.
(As normalization is called again on changes, this recursively ensures that the inline/text nodes contained in a block eventually remain.
The other way round, i.e. when inline/text nodes need to be removed, is not fixable, since we do not know which block element to use to wrap the inline/text nodes.)
**Issue**
Fixes: no issue created yet
**Example**
See the changed unit tests. Instead of throwing away text nodes contained in a block, the inner text nodes are added to the parent node (and then merged).
**Context**
This change improves resiliency on …

Fix `normalizeNode` to keep text/inline nodes when removing blocks

---

docs/api/nodes/editor.md

Clarify in the documentation that the default value for `edge` in `Editor.point` is `start`. 
This is helpful for developers who are not deeply familiar with the framework but need to quickly use it for development. 
They no longer need to inspect the source code or experiment with sample code to understand the default behavior.
**Issue**
**Example**
**Context**
**Checks**

docs: specify default value of `edge` in `Editor.point` as `start`

---

.changeset/tiny-cheetahs-ring.md
docs/api/nodes/text.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/components/element.tsx
packages/slate-react/src/components/text.tsx
packages/slate-react/src/hooks/use-children.tsx
packages/slate-react/src/hooks/use-decorate.ts
packages/slate/src/interfaces/text.ts
packages/slate/test/interfaces/Text/decorations/merge.ts

Currently, when decorations overlap with each other and they are merging with each other, `Object.assign` is used.
However, if two decorations with the same key has different values, one of the decoration will overwrite the other.
``` js
// text content: `them are happy`
// decoration 1:
{
anchor: {
path: [0],
offset: 0,
},
focus: {
path: [0],
offset: 1,
},
message: '`t` should be upper case.'
}
// decoration 2:
{
anchor: {
path: [0],
offset: 0,
},
focus: {
path: [0],
offset: 4,
},
message: 'The correct word is `they`.'
}
```
In this example, two messages cannot be shown together due to `Object.assign` overwriting behavior.
**Example**
A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If …

feat: add optional merge method to decoration object

---

.changeset/empty-pillows-exercise.md
packages/slate-react/src/components/editable.tsx

In Chrome, `selectionchange` events can fire when `<input>` and `<textarea>` elements are appended to the DOM, causing `editor.selection` to be overwritten in some circumstances. This PR addresses this issue by ignoring `selectionchange` events originating from these elements.
**Issue**
Fixes: #5791
**Example**
Before:
https://github.com/user-attachments/assets/1e550014-0ece-4354-b768-13b23da8b93b
After:
https://github.com/user-attachments/assets/49113ad1-1046-4cfc-8b3f-94efb6ef3250
**Context**
Although Chrome's behaviour is apparently [compliant with the spec](https://issues.chromium.org/issues/389368412#comment9), other browsers do not behave this way, and the spec may at some point be changed to match other browsers' behaviour. See the [Chromium …

Ignore `selectionchange` events originating from `<input>` and `<textarea>` elements

---

.changeset/gold-tomatoes-grab.md
packages/slate-dom/src/plugin/with-dom.ts

Sorry, ue to the problem of English writing ability, the following English content is translated from Chinese by claude3.5
```任何会改变 selection 的 op 同步到 dom 之前，onDOMSelectionChange 都不应该执行```
onDOMSelectionChange should not be executed before any selection-changing operations are synchronized to the DOM
**Issue**
```所有出现”Cannot resolve a DOM point from Slate point“的 issue 可能都是，包括但不限于：```
Maybe all issues where 'Cannot resolve a DOM point from Slate point' occurs include but are not limited to:
https://github.com/ianstormtaylor/slate/issues/5694
**Example**
```
在协同场景下很常见，例如内容 ‘1234567'，光标在末尾
1. 当前用户光标 selection 在 path: [0,0], offset: 7
2. 收到一条 op ，删除 '7'，在相关处理中（applyToDraft），selection 的 offset 会变成6
3. 所有状态渲染至 dom ，在这之前，Editable.tsx 306 line 的 …
```

fix: supplement of (fix: Prevent ReactEditor.toDOMRange crash in setDomSelection #5741)

---

Readme.md

I noticed that the link references in the Readme for examples were broken, I updated them to the correct references.

docs: Fix link references to examples in Readme

---

docs/walkthroughs/04-applying-custom-formatting.md

I noticed that the current example for toggling a code block using the backtick key doesn't work as expected. The issue occurs because `Editor.nodes()` can return text nodes instead of block elements, causing`Transforms.setNodes()` to fail.
To fix this, I added an extra check using `Element.isElement(n)`, ensuring that only block elements are transformed.
**Issue**
[Slate docs - Applying Custom Formatting](https://docs.slatejs.org/walkthroughs/04-applying-custom-formatting)
**Example**
Before the fix: 
Pressing the backtick key sometimes fails to toggle a code block due to Transforms.setNodes() being applied to text nodes - [demo](https://codesandbox.io/p/sandbox/ph86gf).
After the fix:
The backtick key now correctly toggles a code block, as the logic ensures only block …

Fix: Ensure block transformation works in the example

---

docs/walkthroughs/05-executing-commands.md
site/examples/js/tables.jsx
site/examples/ts/tables.tsx

There's some strange selection behavior on the sides of the table. The table should take up a whole line instead of being inline, so this behavior is a bit odd.
**Example**
Here are some examples of the abnormal behavior:
This is essentially a selection issue and should be corrected in `normalizeDOMPoint`. In fact, slate is implemented correctly, but it doesn't call `setBaseAndExtent` again when the selection changes. 
The browser selection is updated only in `useEffect`, but when you click again, the `slate` selection model isn't updated, so the browser selection doesn't get updated either(`useEffect` doesn't get triggered).
Although I want to fix this issue, I found that elements like Mention rely on this behavior to independently select text within the node. So, I've …

fix: unexpected table selection behavior

---

.changeset/fifty-walls-search.md
docs/walkthroughs/05-executing-commands.md
packages/slate-react/src/components/editable.tsx

Added Context Menu Undo Support. 
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5188
**Example**
https://github.com/user-attachments/assets/e7ce42d0-1770-43d1-9356-427d4f4fcc8a
**Context**
To support context menu undo we needed to listen on `beforeinput` event as it provides historyUndo/historyRedo events.
Sadly today it only shows undo as changes undone by editors are not tracked by DOM so redo doesn't show up. This behaviour is consistent in across other editors which works like slate.
**Checks**

fix: context menu undo support

---

packages/slate-dom/src/utils/lines.ts

Code was introduced [in this PR](https://github.com/ianstormtaylor/slate/pull/3364) that adds the ability to delete a line backwards using cmd + backspace. However, it is always short by one character. 
In standard paragraphs of text that span many lines without a break the issue is not immediately obvious as after deleting a line the character/word left over often jumps back to the available space on the previous line. We first noticed the issue in our Slate project in a code block element where it was more apparent.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5292
**Example**
You can see in this video that unless it's the first line of an element (in this case the range is returned before hitting the problem algorithm), deleting a line always misses …

Fix delete line being out by 1 char

---

docs/api/locations/path-ref.md
docs/api/locations/path.md
docs/api/locations/point-ref.md
docs/api/locations/range-ref.md
docs/api/nodes/editor.md
docs/api/nodes/node.md

I was going through the API references, and I found that there are some APIs that aren't documented yet, such as the newly added `getIf()` method. I have documented those missing APIs.
I am unsure if some of the APIs written years ago are intentionally left in the documentation. I have tried to cover all the missing changes I could. If some of them are intentionally left out, I will remove those changes from the PR.
**Issue**
Fixes: #5834 
**Checks**

doc: add missing APIs in the doc

---

.changeset/rotten-taxis-battle.md
docs/api/nodes/editor.md
packages/slate/src/editor/nodes.ts
packages/slate/src/interfaces/editor.ts
packages/slate/test/interfaces/Editor/nodes/pass/block.tsx
packages/slate/test/interfaces/Node/nodes/pass.tsx

Adds the `pass` option from `Node.nodes` to `Editor.nodes`, making it possible to skip the descendants of certain nodes while keeping the `match` predicate simple and efficient.
**Example**
```ts
const isUnmarkable = (node: Node) => Element.isElement(node) && node.type === 'code-block';
const markableLeaves = Array.from(Editor.nodes(editor, {
at: [],
match: Text.isText,
// Skips all leaves inside unmarkable nodes
pass: ([node]) => isUnmarkable(node),
}));
```
**Context**
As per the behaviour of `Node.nodes`, passed nodes may still be returned from `Editor.nodes` if none of their ancestors were passed. I've modified the test for `Node.nodes` to make it clearer from reading the test that this is the intended behaviour.
**Checks**

Add `pass` option to `Editor.nodes`

---

.changeset/clever-moose-exist.md
packages/slate/src/transforms-node/insert-nodes.ts

Previously, the condition used was "if (!Text.isText)" without passing the node, which always evaluated to false. This caused the code to always take the branch intended for non-Text nodes, even for Text nodes. The fix now correctly checks "if (Text.isText(node))" to determine if the node is a Text node. Text nodes, which have no children, will now correctly add only their own path, while non-Text nodes continue to have all their descendant paths added.

fix: correct dirty path update for Text nodes

---

.changeset/many-lobsters-joke.md

The changeset for PR #5827 never got created, so although #5292 is fixed on https://slatejs.org, the latest released version of `slate-dom` doesn't include the fix.

Add changeset for #5827

---

.changeset/tough-falcons-itch.md
packages/slate-react/src/hooks/use-slate-selector.tsx
packages/slate-react/test/use-slate-selector.test.tsx

Currently, `useSlateSelector` only uses `equalityFn` when recalculating the value after the editor updates, but not when recalculating it after the selector function changes. That by itself doesn't cause any extra re-renders, but it means that the result can be referentially unstable. That can cause issues if used in dependency arrays later, or passed as a prop to a memoized component. This is surprising behavior if `equalityFn` checks deep equality.
This PR improves referential stability in these cases by only returning the new value if it differs according to `equalityFn`.
**Issue**
I didn't find an existing GitHub issue, but we've encountered this in our code base at work.
**Example**
```
// Pointless selector for demonstration purposes
const state = …
```

Use equalityFn in useSlateSelector during render

---

.changeset/tough-actors-play.md
packages/slate-react/package.json
yarn.lock

`slate-react@0.114.0` and newer depends on `slate@0.144.0` or newer. This PR updates `slate-react`'s minimum peer dependency version for `slate` to reflect this.
**Issue**
Addresses one side of #5852. Unfortunately, the other side of that issue cannot be addressed using peer dependencies.
**Checks**

Increase `slate-react`'s minimum `slate` version to 0.114.0

---

docs/general/resources.md

Hi, I hope to add slate-vue3 to the documentation resources, which would be very useful for those who want to use slate in Vue projects. At present, the functionality of slate-vue3 has reached consistency with slate-react.
You can view demos in [slate-vue3](https://guan-erjia.github.io/slate-vue3/examples/rich-text)

feat(docs): add another member for slate (#5838)

---

.changeset/silly-lamps-sing.md
packages/slate-history/package.json
packages/slate-hyperscript/package.json
yarn.lock

Following #5859, `slate-history` and `slate-hyperscript` depend on a minimum `slate` version of 0.114.3 due to the `isObject` export.
**Checks**

`slate-history`, `slate-hyperscript`: Increase minimum `slate` version to 0.114.3

---

.changeset/friendly-socks-divide.md
packages/slate-history/src/with-history.ts

When the first operation in a frame is a `set_selection`, it causes each following operation to merge into the previous history step, no matter where or when it took place, causing some undos to undo more than expected.
This is a one-line change to fix that.
**Issue**
Fixes #5572, fixes #5773, fixes #5554
Might also affect #5364 and #5587, but unable to easily reproduce those circumstances in a testing environment to verify.
Edit: also seems to fix #3838, looks like @verngutz had this figured out two years before me lol
**Example**
https://github.com/user-attachments/assets/2f835fe5-16a0-4a60-823b-4d25636d8d0a
**Context**
Instead of just checking for the existence of previous operations this frame when considering a merge, `HistoryEditor#apply` now checks that one of those …

Fix certain undos undoing more than they should

---

site/next.config.js

The Netlify build workflows have been failing for some time. The error message `Command failed with exit code 129: yarn build` might indicate a problem with memory usage; if so, [this forum thread](https://answers.netlify.com/t/basic-nextjs-website-failing-to-build-with-exit-code-129/120273/2) indicates that limiting the number of CPUs during the build might address the problem.
<details>
<summary>Full error message</summary>
<pre>
8:18:01 PM:    Generating static pages (0/27) ...
8:18:27 PM: ​
8:18:27 PM: "build.command" failed                                        
8:18:27 PM: ────────────────────────────────────────────────────────────────
8:18:27 PM: ​
8:18:27 PM:   Error message
8:18:27 PM:   Command failed with exit code 129: yarn build …

Fix Netlify builds for PRs

---

.changeset/orange-ears-help.md
packages/slate-react/src/components/string.tsx

There are issues on iOS surrounding the `\uFEFF` character inserted into empty leaves by `ZeroWidthString`.
- With the `\uFEFF`, iOS does not automatically capitalise the first letter typed into an empty editor - #5199
- Without the `\uFEFF`, the editor crashes when inserting text with an IME at the start of a block - #5703
Ideally, we would find a way to resolve both issues at once. However, until we are able to find such a solution, I think fixing the IME crash should be a higher priority than fixing capitalisation. This PR reverts #5654, breaking capitalisation but fixing IME composition on iOS.
**Issue**
Fixes #5703
Fixes #5762
Reopens #5199 (this will need to be reopened manually after merging)
**Context**
See the comment in `string.tsx`
**Checks**

Fix IME crash on iOS, but break capitalisation on iOS

---

.changeset/mean-carpets-tap.md
packages/slate-react/src/components/leaf.tsx

When composition starts and the placeholder is showing, Slate hides the placeholder. Due to a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1967203), this causes macOS's IME to receive outdated information about the start offset of the composition. This PR works around this issue by rendering the placeholder after the cursor instead of before.
**Issue**
Fixes #5766
**Example**
https://github.com/user-attachments/assets/41382b2f-6d0e-4f34-9727-c3f7daac64be
**Checks**

Fix Firefox IME bug caused by placeholder

---

.changeset/popular-bags-relax.md
packages/slate/src/editor/above.ts
packages/slate/test/interfaces/Editor/above/potential-parent.tsx

Currently calling `Editor#above` will error if the node that its input argument resolves to doesn't exist--even though it can never return that node and doesn't depend on it at all.
This fixes that and also reduces the amount of repeated/wasted checks in the implementation. (its probably faster now; I didn't check)
**Issue**
(just a personal issue 🙂)
In my usecase I want to filter/modify certain operations in `Editor#apply` depending on whether they are within a certain kind of block. A problem arises with `insert_node` (and `move_node`) operations: if I call `editor.above(operation.path)`, it errors because there is no node at `operation.path` yet. This seems silly because `editor.above` can never return the node at `operation.path`, the lowest node it can return is its …

Optimize editor#above and allow passing a location that doesnt exist as long as its parent exists

---

packages/slate-history/test/undo/delete_backward/custom-prop.tsx
packages/slate-history/test/undo/delete_backward/inline-across.tsx
packages/slate-history/test/undo/insert_fragment/basic.tsx

After turning off the skip logic, the unit test can pass

fix: Closing skip logic for some unit tests in slate history section

---

.changeset/fifty-shirts-tap.md
packages/slate-react/src/components/editable.tsx
packages/slate-react/src/index.ts

Exports `defaultScrollSelectionIntoView` from `slate-react`, making it easier to extend rather than replace the default `scrollSelectionIntoView` behaviour.
**Example**
```ts
const SCROLLING = new WeakMap<Editor, boolean | undefined>()
// Custom scroll handler
const scrollSelectionIntoView = (editor: ReactEditor, domRange: DOMRange) => {
if (SCROLLING.get(editor) ?? true) {
defaultScrollSelectionIntoView(editor, domRange)
}
}
const withoutScrolling = (editor: Editor, fn: () => void) => {
const value = SCROLLING.get(editor) ?? true
SCROLLING.set(editor, false)
try {
fn()
} finally {
SCROLLING.set(editor, value)
}
}
```
**Checks**

Export `defaultScrollSelectionIntoView`

---

.changeset/strong-humans-taste.md
packages/slate-dom/src/plugin/dom-editor.ts

The `DOMEditor.focus` method has a retry mechanism built in. It can happen, that while retrying to focus the dom node of the editor, meanwhile the editor has been unmounted, which will result in an error when calling `DOMEditor.toDOMNode(editor, editor)`.
This PR adds a check on top of the `DOMEditor.focus` method, to check if the editor is still mounted, if not return and do not retry to focus the editor dom node anymore.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5915
**Context**
This error happened in our unit tests. I guess it's hard to reconstruct in the browser, since it is happening in the milliseconds area.
**Checks**

Check if editor is still mounted before trying to focus

---

packages/slate-dom/src/utils/environment.ts

Now the latest WeChat browser for Windows has used a newer version of Chrome
**Issue**
Fixes: [https://github.com/ianstormtaylor/slate/issues/5912](url)

fix: Determine the higher version of WeChat browser for Windows

---

.changeset/stupid-ants-buy.md
packages/slate/src/interfaces/transforms/general.ts
packages/slate/test/operations/remove_node/cursor-aunt-text-after.tsx
packages/slate/test/operations/remove_node/cursor-aunt-text-before.tsx
packages/slate/test/operations/remove_node/cursor-sibling-inline-after.tsx
packages/slate/test/operations/remove_node/cursor-sibling-inline-before-text-after.tsx
packages/slate/test/operations/remove_node/cursor-sibling-inline-before.tsx
packages/slate/test/operations/remove_node/cursor-sibling-text-after.tsx
packages/slate/test/operations/remove_node/cursor-sibling-text-before-inline-after.tsx
packages/slate/test/operations/remove_node/cursor-sibling-text-before.tsx
packages/slate/test/operations/remove_node/cursor-sibling-text-both-sides.tsx
packages/slate/test/transforms/delete/point/inline-void-reverse.tsx

Previously, when removing the node containing the cursor, the selection would enter a sibling inline in some circumstances, even when a sibling text node was available. This PR ensures that if a sibling text node is available, the cursor is always placed inside it.
**Example**
The most noticeable side-effect of this change occurs when pressing backspace at the start of line N when the last non-empty node in line N-1 is an inline.
Before:
https://github.com/user-attachments/assets/3aa335fb-48b2-4f07-9656-59bbd305ecb9
After:
https://github.com/user-attachments/assets/c87219ba-99b7-4e69-bfe2-9ccd4eb5ef8a
**Context**
The purpose of this change is to ensure that `editor.isSelectable` is respected when the default normalization rules remove an empty text node containing the …

When removing the node containing the cursor, always prefer placing the cursor in a sibling text node

---

.changeset/eleven-clocks-begin.md
packages/slate/src/editor/positions.ts
packages/slate/test/interfaces/Editor/after/non-selectable-block-last.tsx
packages/slate/test/interfaces/Editor/after/non-selectable-block.tsx
packages/slate/test/interfaces/Editor/after/non-selectable-inline-last.tsx
packages/slate/test/interfaces/Editor/before/non-selectable-block-first.tsx
packages/slate/test/interfaces/Editor/before/non-selectable-block.tsx
packages/slate/test/interfaces/Editor/before/non-selectable-inline-first.tsx

`Editor.positions` would sometimes throw a runtime error when no node exists immediately before or after a non-selectable node. This PR resolves that error.
In addition, this PR fixes how `editor.isSelectable` is handled when consuming more than one point from `Editor.positions` - see changeset. The previous behaviour worked correctly when consuming only one point (as in `Editor.before` and `Editor.after`), but consuming additional points would return points inside the non-selectable node.
**Issue**
Fixes #5927
**Checks**

Fix handling of `editor.isSelectable` in `Editor.positions`

---

.github/workflows/ci.yml
.github/workflows/comment.yml
.github/workflows/release.yml

It looks like CI was broken with the [release of Node 22.18.0](https://versionlog.com/nodejs/22/).
This PR patches the issue by pinning to 22.17.1, but we should look into fixing compatibility with later Node versions.
```
file:///home/runner/work/slate/slate/packages/slate/test/interfaces/CustomTypes/custom-types.ts:2
BaseEditor,
^^^^^^^^^^
SyntaxError: Named export 'BaseEditor' not found. The requested module 'slate' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'slate';
```

Fix CI by pinning Node to 22.17.1

---

.changeset/heavy-pants-cover.md
packages/slate/src/transforms-node/wrap-nodes.ts
packages/slate/test/transforms/wrapNodes/split-block/block-mark.tsx
packages/slate/test/transforms/wrapNodes/split-inline/inline-mark.tsx

Previously `Transforms.wrapNodes`, when called with `split: true`, did not split at the start or end of the selection correctly if that point was at the start or end of a text node. This could result in adjacent text nodes being inadvertently wrapped.
**Issue**
Fixes #5942
**Checks**

Fix `Transforms.wrapNodes` where `split: true` at text node start or end

---

.changeset/real-clouds-accept.md
packages/slate-dom/src/plugin/dom-editor.ts

This PR change the `toSlatePoint` function in a way, that if the selection is within a `contentEditable={false}` node, it will search backward and forward for valid slate leafs. Before it was only looking backward by default.
**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/5932
**Example**
You can find a GIF and a codesandbox link in the linked issue. Here you can see how it behaves after the fix:
**Context**
I am aware, that this is a very sensible spot to make changes. Help appreciated!
**Checks**

fix: Search backward and forward for leaf nodes in non contenteditable elements
