ianstormtaylor/slate

- examples/rich-text/state.json
After simply copy and pasting the rich-text component and locally, ran into this error:
```bash
ERROR in ./client/components/HomeView/state.json
Module build failed: SyntaxError: Unexpected token } in JSON at position 1206
at Object.parse (native)
at Object.module.exports (/Users/jaredpalmer/workspace/github/jaredpalmer/slateTest/node_modules/json-loader/index.js:7:48)
@ ./client/components/HomeView/index.js 13:13-36
```
Just a dangler.
> remove dangling comma in rich-text example state.json

- docs/guides/installing-slate.md
`import { Editor, Raw } from 'state'` → `import { Editor, Raw } from 'slate'`
> Fix typo in Installing Slate doc

- docs/guides/installing-slate.md
I tried to use the example however I received errors saying that `map` could not be executed over `undefined`.
It looks like the deserialiser was trying to map over the `nodes` prop of an object, but the example passes in an array of objects.  I removed the wrapping array and all was well again.
> Fix "initialState" declaration in "Installing Slate" doc

- docs/guides/installing-slate.md
Looks like the `deserialize()` function expects to be passed an object with a `nodes` key.
> Fix error in Hello World of installation guide

- lib/components/content.js
- lib/components/editor.js
- lib/plugins/core.js
My attempt at #174.
I added an `onSelect` method to the core plugin with the Content component `onSelect` logic and then added an `onSelect` prop to the Editor component.
Tests and linting pass on my machine. I also did a local install into my project and it solves my problem in #173.
> moved onSelect event handling to core plugin

- docs/reference/models/transform.md
This PR fixes the documentation for `undo` and `redo` transforms, which return a new `State` instead of a `Transform`.
> undo and redo transform does not return Transform

- docs/reference/models/selection.md
This PR fixes the signature of `Selection.has{Edge}In` in the documentation.
> Fix signature of Selection.has{Edge}In in documentation

- lib/components/content.js
I think at some point in the `onSelect` changes the `isBackward` value broke. I mostly just copied how `moveTo` managed to update it, which was the method used before `onSelect` was moved.
Hopefully this is the correct way to do it?
> fix isBackward in onSelect event selection

- docs/reference/models/state.md
- lib/models/state.js
This PR adds two computed properties  to `State`: `hasUndo` and `hasRedo`.
These properties are shortcuts when for example rendering Undo/Redo buttons in a toolbar.
I’ve documented the properties, but I’m not an english native so let me know if the descriptions are not good enough.
> Add properties hasUndo and hasRedo to State

- lib/models/transforms.js
This PR prevents the deletion of `data` by passing `{ data: null | undefined }` to `setBlock`.
> Fix #194: fix possilbe deletion of "data" property with setBlock transforms

- test/transforms/fixtures/wrap-inline/twice/index.js
- test/transforms/fixtures/wrap-inline/twice/input.yaml
- test/transforms/fixtures/wrap-inline/twice/output.yaml
So unfortunately it looks like the `0.8.0` release did not fix #185. I added a small test to show this.
I hope calling the folder `twice` is clear enough. Please let know if I should change anything.
> add tests for calling wrapInline twice

- lib/components/editor.js
- lib/components/leaf.js
- lib/components/void.js
- test/rendering/fixtures/custom-decorator/output.html
- test/rendering/fixtures/custom-mark-combine/index.js
- test/rendering/fixtures/custom-mark-combine/input.yaml
- test/rendering/fixtures/custom-mark-combine/output.html
- test/rendering/fixtures/custom-mark-multiple/index.js
- test/rendering/fixtures/custom-mark/output.html
This PR fixes #201 
Basically, it allows `renderMarks` to return React components:
```js
const BoldSpan = (props => <b>{this.props.children}</b>)
renderMarks(mark) {
if (mark.type == 'bold') return BoldSpan
}
```
Currently, if a leaf has 2 marks (`bold` and `italic`), it will result in one `span` with `style={ { fontWight: 'bold', fontStyle: 'italic' }}`; with this PR it will result in `<b><em>{text}</em></b>`.
--- 
@ianstormtaylor I'm posting this PR while it's still a WIP so that you can review it and tell if it looks like the right implementation for you.
> Add ability for `renderMark` to return a React componen

- lib/serializers/base-64.js
As the title suggests, it'd be best to drop [`escape`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) and [`unescape`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape) since they are both deprecated methods that serve no real purpose when in combination with `decodeURIComponent` and `encodeURIComponent`.
In addition, a quick [benchmark](https://jsfiddle.net/w00fz/3mgLe6bf/) shows a ~50% boost in speed.
> Drop deprecated `escape` and `unescape`

- docs/reference/plugins/plugins.md
- lib/components/editor.js
- lib/plugins/core.js
This PR is related to #218.
It adds an handler `onBeforeChange` that can be used to do validation before rendering:
Here is an example for a plugin to enforce that the document contains only one block:
```js
function MyPlugin(blockType) {
function onBeforeChange(newState) {
let { document } = newState;
let { nodes } = document;
if (nodes.size > 1) {
nodes = nodes.slice(0, 1);
}
document = document.merge({ nodes });
return newState.merge({ document });
}
return {
onBeforeChange
};
}
````
> Add handler "onBeforeChange"

- docs/guides/saving-and-loading-html-content.md
While trying to serialize it to HTML I had an issue while copying from the docs/guide and now it should be fixed, was just a small typo.
> Fix typo in serialize methods

- lib/serializers/raw.js
- test/serializers/fixtures/raw/deserialize-terse/text-with-mark-without-range/input.yaml
- test/serializers/fixtures/raw/deserialize-terse/text-with-mark-without-range/output.yaml
Text nodes in terse form can contain marks - but currently they are being ignored when "untersifying Text".
Referenced in https://github.com/GitbookIO/markup-it/pull/23
> terse text can contain marks

- docs/reference/components/editor.md
In the Editor reference documentation, there was a typo.  Blur() is listed twice; once under "blur" and again under "focus."
> fixed a typo where the method for focus was blur()

- docs/walkthroughs/applying-custom-formatting.md
There were two occurrences of the state attribute in the Editor element; I believe one was for the schema.
> fixed a few typos

- lib/models/transforms.js
- test/transforms/fixtures/split-block/with-void/index.js
- test/transforms/fixtures/split-block/with-void/input.yaml
- test/transforms/fixtures/split-block/with-void/output.yaml
Not sure what I actually expected calling `splitBlock()` on void block, but I would expect `splitBlock()` to respect a given block type's isVoid property.
This failing test demonstrates that `splitBlock()` always creates a the new block with `isVoid: false`.
Edit: Sorry, here's the test runner output... the second block has `isVoid: false` and some extra child nodes:
> Add failing test showing splitBlock with isVoid bug

- examples/images/index.js
Fix this https://github.com/ianstormtaylor/slate/issues/302
@ianstormtaylor Not really sure, but I think to prevent this kind of problem should `removeNodeByKey` unset selection before doing it's job?
> Fix issue #302

- src/models/node.js
- src/transforms/apply-operation.js
This PR is intended to fix #318.
Since upgrading to 0.14, `splitBlockAtRange` is no longer a method of `Node` (before it was a transform that was also set as a Node's method).
I was not sure what kind of solution to apply to this problem, so feel free to reject this PR.
1. I've moved the code from the `splitNode` operation into a Node method
2. I've modified the `split_node` operation to call `node. splitNode`
3. I've implemented `node. splitBlockAtRange` (which require the transform of method `splitNode`)
- The code for `splitBlockAtRange` is duplicated between the transform and the node method, I'm not sure how to fix this.
> Fix #318: Implement "splitBlockAtRange" as a node method

- src/transforms/operations.js
- test/transforms/fixtures/on-selection/blur/marks/index.js
- test/transforms/fixtures/on-selection/blur/marks/input.yaml
- test/transforms/fixtures/on-selection/focus/marks/index.js
- test/transforms/fixtures/on-selection/focus/marks/input.yaml
In our editor, we have buttons to toggle style, and to ensure that clicking on it does not remove focus, we `.focus()` after toggling marks. But the [current implementation](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/operations.js#L374-L378) of the `setSelectionOperation` clear the marks on focus/blur. So our style buttons do not work on a collapsed selection.
I see two options:
1. Implement a different `focus` transform (or modify it) to not clear the marks.
2. Adapt the condition in `setSelectionOperation`
This PR opts for 2.
> Focus and blur should not clear marks on selection

- examples/tables/index.js
https://github.com/ianstormtaylor/slate/issues/344
> Prevent backspace to move selection into table-cell issue #344

- docs/reference/models/transform.md
- examples/images/index.js
- src/models/state.js
I simply updated any reference to `snapshot` that I could find and replaced them with the new `save` parameter. The documentation still refers to the concept of snapshot though for clarity. Just the name of the parameter changed.
This also fixes a bug: that normalization was pushing a to the undo/redo history.
> Remove old `snapshot` parameter for Transform.apply

- src/models/state.js
I found out causing error 
```
Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".
```
which mentioned in issue #342 is that when the node is removed `this.selection.anchorKey` and `this.selection.focusKey` are both `null` and are asked to get `getDescendant(key)`!
> fix #342, Uncaught Error: Invalid `key` argument when `removeNodeByKey`

- src/components/node.js
This PR fixes #385, basically it extends the condition in the `shouldComponentUpdate` of `Node` to re-render when selection has changed for an `inline` or `block` node:
- selection is in the node != selection was in the node
- was focused != is focused
We'd be great to have unit tests for this, but I'm not sure how to write unit tests for `shouldComponentUpdate`.
> Fix #385: Re-render when selection state changed for a node

- src/transforms/at-current-range.js
- test/transforms/fixtures/at-current-range/insert-fragment/end-block-multiple-blocks/fragment.yaml
- test/transforms/fixtures/at-current-range/insert-fragment/end-block-multiple-blocks/index.js
- test/transforms/fixtures/at-current-range/insert-fragment/end-block-multiple-blocks/input.yaml
- test/transforms/fixtures/at-current-range/insert-fragment/end-block-multiple-blocks/output.yaml
Previously inserting fragment at the end of current text node may lead to inconsistent selection, where offset was greater than text length.
> Fix inserting fragment at the end of current text node

- docs/reference/serializers/html.md
- src/serializers/Readme.md
- src/serializers/html.js
- test/serializers/index.js
This PR adds an options parameter to the Html serializer so that it can be asked to return a list of React elements, instead of automatically rendering these to static markup. 
I see a number of use cases in my own application where I'd love to use the existing serializer and rules but handle placing the resulting tree of React elements into my UI directly instead of receiving an HTML string.
> Html serializer: optionally return React elements

- package.json
- src/components/void.js
- src/models/node.js
- src/models/selection.js
- src/models/state.js
- src/transforms/at-current-range.js
Working on https://github.com/ianstormtaylor/slate/issues/180
I open this PR as a work in progress to gather reviews as I work on it.
I cannot measure the impact of the changes, so I'm not sure each point actually improves performances (tricky case of memoization).
So far:
- Optimize `Node.getParents` to return as soon as the child is found
- Add `Node.getAncestors` method (used in `Node.getClosest`)
- Optimize `Node.getClosest` to not use successive `getParent`, by using `Node.getAncestors` instead. I don't know if there is a benefit to this, since `getParent` is recursive and memoized.
- Remove extra use of `assertDescendant` (but keep throwing when not found) in the following implementations:
- `Node.getPath`
- `Node.updateDescendant`
- `Node.removeDescendant`
> Node methods optimizations

- docs/reference/components/editor.md
I noticed some broken links in the `Editor` docs, this PR should make them all work.
> Fix broken links in the docs

- src/components/content.js
Resolves an issue where `this.getPoint(anchorNode, anchorOffset)` throws an error if a key event is triggered although not in focus.
> Do not process onInput events when selection is lost

- package.json
Fixes an issue where debug may clear localStorage.debug on start, making it impossible to use. See https://github.com/visionmedia/debug/issues/330
> Upgrade debug package

- src/components/content.js
Use `isContentEditable` HTML element property to check if an element is editable.
This does not change how Slate handles its content except for `contenteditable="true"` elements nested inside `contenteditable="false"`. Those elements, noneditable by Slate before, now are editable.
At the moment, as far as I could see, there should be no components with such a structure, so this PR shouldn't in fact alter Slate behavior.
Anyway, I manually tested few `isVoid: true` components: images, embeds and emojis, and they still work.
This PR fixes issue #410.
> Use `isContentEditable` HTML element property to check if an element is editable

- src/components/node.js
cc @SamyPesse @Soreine 
Wanted to run this by you two, just so you're aware of my thinking. In testing out `0.15` with this new warning added, I've realized that there are a few valid cases where a node will be exactly the same structure, but a different instance, when certain transforms happen to happen:
1. Select a range, copy, and paste it immediately without changing the selection. This will essentially cause nothing to happen, but it will have actually applied the paste transform. 
2. With the cursor in an empty paragraph, and a paragraph with text above it, delete backwards. This will essentially also cause nothing to happen, but it will have actually joined the empty text onto the previous paragraph's text.
3. There are probably other cases...
Now, those cases could have …
> remove Immutable.is check in node shouldComponentUpdate

- src/utils/transfer.js
@jasonphillips this closes #442 
Basically we just check to see if there is `text/rtf` content in the data, and if so we make `html` and `text` the preferred type. Let me know if you still run into problems!
> add logic to handle rich text pastes

- src/components/content.js
I am attempting to embed a Slate editor inside a void node inside another Slate editor. In v0.14 this actually worked alright, but in v0.15 the events started bubbling up improperly. This is probably a more extreme use case for Slate, however adding support was very straight forward and on the surface this appears to work consistently.
The original code was just checking that bubbled events happen inside of a content-editable node, not specifically the one created by the content node. My changes add a React ref for the root content-editable and then all events make sure the event bubbled from the correct element.
I wanted to add tests for this, however Slate appears to be missing integration tests currently. I am happy to add tests for this if/when those are in place.
> add support for nested content-editables

- src/models/node.js
node.getPreviousText and node.getNextText is called with a node parameter, and not node.key, in node.getNextBlock and node.getPreviousBlock. It triggers a deprecation warning.
> Avoid deprecation warnings in node.getNextBlock and node.getPreviousBlock

- src/plugins/core.js
This is a fix for the following issue:
https://github.com/ianstormtaylor/slate/issues/464
Reposted the details here:
According to the "Mac Keyboard Shortcuts" listing here:
https://support.apple.com/en-ca/HT201236
And also confirmed in the Pages app on Mac OS X, these are expected behaviours:
**Option–Shift–Up Arrow** Extend text selection to the beginning of the current paragraph, then to the beginning of the following paragraph if pressed again.
**Option–Shift–Down Arrow** Extend text selection to the end of the current paragraph, then to the end of the following paragraph if pressed again.
In Slate, using Chrome, it does not go the beginning or end of each additional paragraph selected. Instead, it goes to a position that is based on the offset (within a block) of the anchor position. …
> Fix for OPTION-SHIFT-UP and OPTION-SHIFT-DOWN

- package.json
- perf/index.js
- src/constants/environment.js
This removes `lodash` from the dependencies. I think it's for the best. If we need some utilities, we can always include them individually instead.
> Remove lodash dependency

- Readme.md
See #486, I missed this functionality
> Mention slate-drop-or-paste-images in plugins

- book.json
This adds a button that links to the GitHub repo
> Add a GitHub link as icon in the docs

- src/components/content.js
- test/rendering/fixtures/custom-block-void/output.html
- test/rendering/fixtures/custom-block/output.html
- test/rendering/fixtures/custom-decorator/output.html
- test/rendering/fixtures/custom-inline-void/output.html
- test/rendering/fixtures/custom-inline/output.html
- test/rendering/fixtures/custom-mark-with-component/output.html
- test/rendering/fixtures/custom-mark-with-function/output.html
- test/rendering/fixtures/custom-mark-with-mixed/output.html
- test/rendering/fixtures/custom-mark-with-object/output.html
- test/rendering/fixtures/custom-mark-with-string/output.html
- test/rendering/fixtures/default-block-and-inline/output.html
- test/rendering/fixtures/default-block/output.html
- test/rendering/fixtures/empty-text/output.html
- test/rendering/fixtures/multiple-custom-block/output.html
- test/rendering/fixtures/multiple-custom-inline/output.html
- test/rendering/fixtures/nested-text-direction/output.html
- test/rendering/fixtures/text-direction/output.html
Add `data-slate-content` attribute to the divs used to render `content` components.
Use that attribute to uniquely identify them.
Update test expected results to reflect the presence of the new attribute.
This fixes issue #468.
> Add an attribute to uniquely identify divs used to render `content` component

- docs/reference/models/transform.md
- src/transforms/by-key.js
- src/transforms/index.js
- src/transforms/operations.js
- test/transforms/fixtures/by-key/unwrap-node-by-key/first-sibling/index.js
- test/transforms/fixtures/by-key/unwrap-node-by-key/first-sibling/input.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/first-sibling/output.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/last-sibling/index.js
- test/transforms/fixtures/by-key/unwrap-node-by-key/last-sibling/input.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/last-sibling/output.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/single-block/index.js
- test/transforms/fixtures/by-key/unwrap-node-by-key/single-block/input.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/single-block/output.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/with-siblings/index.js
- test/transforms/fixtures/by-key/unwrap-node-by-key/with-siblings/input.yaml
- test/transforms/fixtures/by-key/unwrap-node-by-key/with-siblings/output.yaml
- test/transforms/fixtures/on-history/undo/unwrap-node-by-key/index.js
- test/transforms/fixtures/on-history/undo/unwrap-node-by-key/input.yaml
- test/transforms/fixtures/on-history/undo/unwrap-node-by-key/output.yaml
This PR adds a transform named `unwrapNodeByKey`, to unwrap a particular node from its parent.
Calling `unwrapNodeByKey` on a block is not equivalent to calling `unwrapBlockByKey` on that same block though, because the latter will unwrap the block's children, whereas the former will unwrap the block itself from its parent. I'm open to renaming that transform for that reason, but I could not find another name.
I needed that one to fix an issue with unwrapping lists https://github.com/GitbookIO/slate-edit-list/issues/13
I have added tests for all the cases covered by this transform, as well as documentation.
> Add unwrapNodeByKey

- examples/dev.html
- package.json
I was trying to start working on some issues and I wanted to use the examples to find out how Slate works inside; however, I could not get any changes I made to the code to show up in the browser. I was using `npm run watch` to do so.
I dived into various things and when I looked at watchify, I noticed I couldn't tell if bundling was even happening. It helped when I set the `watch:examples` script to `watchify -v` to get some feedback. This is also helpful when working on code because you need to wait for the bundling to happen before you can reload the examples page and the verbose mode lets you see when the bundling has finished.
Eventually I realized that Chrome was reloading the HTML page but was not updating the loaded script. This is because it doesn't know that the code inside the …
> Improve `examples` so that code changes propagate to browser

- docs/reference/models/transform.md
I noticed that in the code, it's pretty common to pull the `state` out of the `transform`.
The only way I was able to learn about this was by looking through the code and then I wasn't sure if it was a supported property. Considering that it seems to be fairly commonly used and looks like it will be officially supported, I made a pull request to add it to the documentation.
> Added `state` as a property to Transform in the documentation

- examples/dev.html
When reloading a page in `/examples/dev.html` it will now also reload the CSS.
Also updated the JavaScript from last time as I realized I wasn't using the JavaScript style guidelines in Slate.
> Reloading the page now also reloads the CSS.

- examples/index.css
- examples/index.js
Added GitHub link to examples as per this issue:
https://github.com/ianstormtaylor/slate/issues/362
Also added a link to the Documentation.
In order to make the changes work, I updated some of the HTML/CSS. Notably:
* Added a top bar that displays "Slate Examples" + the links at the upper right.
* Added a background rounded box behind the current example. This was to distinguish the stateful tab from the non-stateful links to GitHub/Docs
* Put rounded box on tabs in hover (but not the white font colour) just to provide some nice UI hints about its tab-like nature. The white font colour is reserved for the active tab.
> Updated examples to add GitHub and Docs link + some styling.

- src/components/content.js
- src/components/node.js
Propagate `readOnly` editor property to node components.
Update nodes when `readOnly` editor property changes.
This fixes issue #543
> Update nodes on `readOnly` editor property change

- docs/reference/components/editor.md
- src/components/content.js
- src/components/editor.js
- test/rendering/fixtures/custom-block-void/output.html
- test/rendering/fixtures/custom-block/output.html
- test/rendering/fixtures/custom-decorator/output.html
- test/rendering/fixtures/custom-inline-void/output.html
- test/rendering/fixtures/custom-inline/output.html
- test/rendering/fixtures/custom-mark-with-component/output.html
- test/rendering/fixtures/custom-mark-with-function/output.html
- test/rendering/fixtures/custom-mark-with-mixed/output.html
- test/rendering/fixtures/custom-mark-with-object/output.html
- test/rendering/fixtures/custom-mark-with-string/output.html
- test/rendering/fixtures/default-block-and-inline/output.html
- test/rendering/fixtures/default-block/output.html
- test/rendering/fixtures/empty-text/output.html
- test/rendering/fixtures/multiple-custom-block/output.html
- test/rendering/fixtures/multiple-custom-inline/output.html
- test/rendering/fixtures/nested-text-direction/output.html
- test/rendering/fixtures/text-direction/output.html
This PR adds two accessibility properties to the `<Editor />`:
- [`tabIndex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
- `role`
> Add props "tabIndex" and "role"

- Readme.md
Right now the `###`-prepended lines aren't being converted to header tags when displayed on npm.
> Add significant whitespace to fix headers on npm

- src/components/void.js
- test/rendering/fixtures/custom-inline-void/output.html
In Chrome, when it is positioned right before a `Void ` `Inline` node, the caret is not visible.
That can be verified, for example, by using the [Emojiis example](http://slatejs.org/#/emojis).
This PR fixes that issue setting to `inline-block` the css `display` property of the `Void` `Inline` wrappers.
As always I'm open to any change you think needed. :blush:
> Set the `Void` `Inline` wrapper css `display` property to `inline-block`

- src/transforms/at-range.js
When we have nested inlines in startBlock, startOffset points to the wrong character. So, i think that using startText will be correct here.
> Fix deleteCharBackwardAtRange

- src/components/content.js
- src/components/editor.js
- test/rendering/index.js
This allow user to turn off predictive text input on iOS thus mitigating #540…
> Add props “autoCorrect” to editor and content.

- src/models/node.js
Looking at `getBlocks` implementation confirma my thoughts that `getBlocksAtRange` is broken and can return the same block multiple times.
> Eliminate duplicates in getBlocksAtRange

- src/serializers/html.js
- test/serializers/fixtures/html/deserialize/default-block/index.js
- test/serializers/fixtures/html/deserialize/default-block/input.html
- test/serializers/fixtures/html/deserialize/default-block/output.yaml
We need to be able to set the data on the defaultBlockType.
> Allow setting a defaultBlockType as object for HTML serializer

- src/plugins/core.js
- src/transforms/on-selection.js
Use key, not node, with ``document.getNextBlock``  and ``document.getPreviousBlock``to avoid deprecation warnings.
Also, in the core plugin onCutCopy, one must check for a selection with ``isCollapsed``, because ``rangeCount`` can return 1 even though nothing is selected.
> Various fixes for selections

- src/components/leaf.js
- src/components/void.js
- test/rendering/fixtures/custom-block-void/output.html
- test/rendering/fixtures/custom-inline-void/output.html
- test/rendering/fixtures/custom-inline/output.html
- test/rendering/fixtures/default-block-and-inline/output.html
- test/rendering/fixtures/multiple-custom-inline/output.html
Trying to hide text cursor inside `Void` `Inline` nodes, commit a836a347861d7f0d3cb452bfe0f5b6e82cf04e31 has introduced some weird bugs in caret movement in Chrome. To understand what I mean go to [emoji example](http://slatejs.org/#/emojis), place the cursor on the first line of text (even far from emoji) then press down arrow key. The cursor should jump on the second line, but it doesn't.
After some investigations, I found the best way to hide the caret avoiding that sort of problems is to make it invisible setting to `transparent` the spacer CSS `color` property, instead of moving the spacer out of screen.
This PR implements that idea.
Among other things, to avoid graphics glitches, in Chrome, it replaces the zero-width space inside spacer with an hair space.
As always l'm open to any …
> To hide caret inside `Void` `Inline` nodes, set spacer CSS `color` property to `transparent`

- src/transforms/at-range.js
- test/transforms/fixtures/at-current-range/delete-backward/empty-after-void-block/index.js
- test/transforms/fixtures/at-current-range/delete-backward/empty-after-void-block/input.yaml
- test/transforms/fixtures/at-current-range/delete-backward/empty-after-void-block/output.yaml
- test/transforms/fixtures/at-current-range/delete-forward/empty-before-void-block/index.js
- test/transforms/fixtures/at-current-range/delete-forward/empty-before-void-block/input.yaml
- test/transforms/fixtures/at-current-range/delete-forward/empty-before-void-block/output.yaml
The expected behaviour should be to delete the current empty non-void block instead.
> Fix behaviour where deleteBackward/Forward on empty non-void block deleted the void block above/below

- src/utils/scroll-to.js
I don't think this is the best fix for the issue (I would have liked it to allow the browser to deal with moving the cursor into view.) but for now I think this is better than what it was before. I tried to imitate what chrome was doing when the cursor was out of view. (Except when it was partially in view but I decided to just keep it simple) 
This basically checks the cursor's position and if it isn't in view it'll move the cursor into the middle of the view. 
Fixes #279
Fixes #589
> Fix jumpy scroll behaviour

- src/utils/scroll-to.js
I realized I made a mistake in the scrollWindow function I was calculating the scrollBy position incorrectly. I decided to just switch to scrollTo instead of scrollBy
Also I was getting an issue where the `getBoundingClientRect().bottom` of one of my wrapper elements was incorrect when the height changed via newline or deletion. I'm not entirely sure why but I noticed that if I used wrapperRect.top + wrapper.offsetHeight it gave the correct bottom so I swapped to use that instead. Let me know if there's any issue with these changes.
Also I'm wondering is there anyway to add tests for these changes? I'm not too familiar with testing for scroll.
> Fix issue with scrollTo

- src/plugins/core.js
To show the bug:
* Load the link example. Delete the exclamation sign in the end of the first paragraph, leaving the inline link node at the end of the paragraph.
* Try to select the last character of the link with shift-left-arrow. It will not be selected.
This PR fixes that. I would love to write a test for it, but not sure how to do that.
> Fix bug where first/last char of inline node couldn't be selected with keyboard

- examples/images/index.js
As void-nodes now can be deleted with backspace, use a schema rule to normalize the document, and insert a paragraph when the document is empty. Delete old "onDocumentChange" handler.
Fixes #625
> Image example: fix delete bug. Fixes #625

- docs/reference/models/transform.md
Hey @ianstormtaylor, while upgrading to 0.17, I noticed that some of the methods that were mentioned in the History file were not in the reference docs. I added those!
Let me know if the descriptions are accurate!
> Methods missed in upgrade 0.17

- src/transforms/at-range.js
- test/transforms/fixtures/at-range/unwrap-inline-at-range/with-text-between/index.js
- test/transforms/fixtures/at-range/unwrap-inline-at-range/with-text-between/input.yaml
- test/transforms/fixtures/at-range/unwrap-inline-at-range/with-text-between/output.yaml
Hi.
This pull request fix issue #620, when inline nodes with text between are unwrapped in incorrect way.
> Fix getting index for inline node in unwrapInlineAtRange, fixes #620

- docs/reference/plugins/plugin.md
Hey @ianstormtaylor, I am adding some clarification to the docs so that others don't run into the issue that I did. However, I am not sure if that is the clearest way to explain the point - so please double-check!
Also, since React doesn't allow you to return an array of nodes, this necessarily means that all the plugins will render nested components, i.e., if you have two toolbars, one would be the parent of another as well as the parent of the editor itself.
Let me know if that should be added, and what do you think is the best way do phrase that note. 
Finally, do you think there should be a way to allow plugins to render as siblings rather than parents of each other?
> Clarify usage of plugin.render

- src/utils/scroll-to-selection.js
Since I already had the code loaded up for this one I figured a pull-request was easy. This will add support for scrolling in IE (even though other things are broken) which prior was scrolling to the top frequently. See #663 for my other IE11 support items.
For more info on IE compatibility with window scrolling, see the [MDN article on scrollX](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX).
> use pageXOffset instead of scrollX for IE11 support

- src/models/node.js
As per @ianstormtaylor's [comment here](https://github.com/ianstormtaylor/slate/issues/660#issuecomment-287970164), this PR removes the code which was returning early when selection was collapsed.
When the selection is collapsed and not in void node, it return fragment with no text inside. If the selection is collapsed and in void nodes, it returns the void node block.
> getFragmentAtRange returns range when selection is collapsed (including in void nodes)

- docs/walkthroughs/saving-to-a-database.md
> Fix a typo in walkthroughs/saving-to-a-database

- src/components/content.js
- src/plugins/core.js
- src/utils/get-point.js
For #540
Here's an explanation of what the following codes try to achieve.
> During autocorrection (in iOS’s Safari), `onSelect` event is triggered after `onBeforeInput` event.
> The plugins/core updates the state during `onBeforeInput` event, thus causing selection triggered by autocorrect to be lost/overridden.
> This behaviour caused dupe text bug during autocorrection.
>
> To overcome this issue, we try to query the selection and conditionally fix out of sync cases with an additional transform before inserting the text.
The con of this fix is that it adds an additional query to native selection per text input.
I choose this solution because it is less destructive to existing execution flow.
Feel free to reject or rewrite if this isn't the right way to fix this.
> Fixed autocorrect causing dupe text

- docs/walkthroughs/saving-and-loading-html-content.md
the section on saving and loading content was using `set` instead of `setItem`
> Documentation: use correct localStorage method for setting content

- src/components/content.js
If Slate editor contains nested editable components and the native selection enters one of those, focus moves from the `Content` DOM element to the new active one but editor doesn't really lose focus and selection must not be blurred.
> Don't blur selection when focus moves to nested editable elements

- src/components/content.js
When editor contains nested editable elements, in some situations, the focus goes to those elements. In Firefox, this causes issues with keyboard navigation and therefore it must be prevented
> Prevent focus from going to nested editable elements 

- examples/check-lists/index.js
- examples/index.css
Also with the new (shining :blush:) selection updating code, there are issue with selection in the "Check List" example.
For example, in Firefox, putting the caret on the left end of a check list item and pressing left arrow key moves the caret on the left of the checkbox.
This PR intends to fix this making contenteditable just the area we really want to be editable.
Basically, it replaces a structure of the type
```
<div contenteditable>
<div>
<span contenteditable="false">...<span>
<span>...</span>
</div>
</div>
```
in which the position on the left of the first `<span>` is a legitimate caret position because it lies inside a contenteditable area, with
```
<div contenteditable>
<div contenteditable="false">
<span>...<span>
<span contenteditable>...</span>
</div>
</div>
```
where the …
> Fix selection issue in "Check List" example

- src/components/void.js
Hi.
I found, that [here](https://github.com/ianstormtaylor/slate/commit/059ee96db8d9ea73db94375eb1365625a56b6ec8#diff-93192bd0f30cb73c4088f025f5cf47d4R32) `block` property was added  for `Leaf` node. But, the `Void` component doesn't set this props for the `Leaf`.
This pull should fix the issue. Because, `React` throws warning when a `Leaf` component is rendered by `Void` component.
> Fix forgotten props 'block' for Leaf

- src/components/content.js
Hi.
As I know, `ReactTestRenderer` doesn't work well with `findDOMNode` and I caught an error with it. 
https://github.com/facebook/react/issues/8324
This pull should fix that issue.
> Use refs for div component instead findDOMNode

- src/plugins/core.js
Right now if you copy "This thing" from Slate and paste
into a plain text app you will get "T his thing" because
Slate is making the first character a data holding span.
This diff makes the data containing span empty to eliminate
this extra space.
Closes #562
> Remove space after first char when copying from Slate

- src/transforms/by-key.js
Transforms should be applied in an order so that the selection is
preserved. This replaces "remove --> insert" with "move --> remove".
Close #670
> Keep selection while applying Transform.unwrapNodeByKey

- examples/index.html
* Fixes issue with IE11 simply not displaying anything on load due to missing `Symbol` shim
> feat: Add ES6 polyfill to examples page

- src/components/content.js
- src/utils/find-closest-node.js
- src/utils/offset-key.js
* A lightweight utility that wraps the functionality of the native `Node.closest` method
* IE11 and Edge don't support this native method
* For these browsers that don't support it, we mock it with a [shim](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) taken from MDN
* All supporting browsers use the native method
> feat: Add findClosestNode utility

- src/components/content.js
- src/utils/extend-selection.js
* Implements the native `Selection.extend` method if not available with a simplistic [shim](https://gist.github.com/tyler-johnson/0a3e8818de3f115b2a2dc47468ac0099) by @tyler-johnson
* Fixes IE10+ as they don't support the native method
* Browsers that support the native method are not affected
> feat: Add extendSelection utility

- src/plugins/core.js
Internal copy/paste broke with PR #716.
This reverts 3e573453a8c5d92963d3f290fb7266f66e2a6b78
Se issue https://github.com/ianstormtaylor/slate/issues/734 for more details.
EDIT: I thought I had a solution to support the intention of 3e57345 with this PR, but it was still containing a whitespace on the clipboard. Removed that commit from this PR. As it is just now a revert, feel free to close without merge. However, this should be taken care of ASAP as it breaks core functionality.
> Fix copy paste

- docs/walkthroughs/applying-custom-formatting.md
- docs/walkthroughs/defining-custom-block-nodes.md
- docs/walkthroughs/using-plugins.md
I decided to change this hotkey to `⌘ + Alt + C` because same hotkey uses Dropbox Paper and Bear (so I suppose it's kinda standard combination for code blocks).
> Changed Meta + ` hotkey in walkthrough

- docs/reference/models/document.md
can perhaps spare some time from someone else wondering about #746
> add note about only allowing block nodes as direct descendants of document

- src/components/content.js
- test/rendering/index.js
The goal is to be able to use `findDOMNode` with the `document` itself.
The tests were failing since https://github.com/ianstormtaylor/slate/commit/a98b687aa538138be427f419ac5489cdbf72d51c. Since PR also fixes them.
> Add "data-key" to root div for the whole document

- docs/walkthroughs/defining-custom-block-nodes.md
The sentence read "'renderer" instead of "rendered"
> Fixed typo in custom block nodes walkthrough

- docs/general/faq.md
- docs/reference/models/block.md
Just a small edit that we discussed in #644.
> Address doc suggestion in #644

- src/transforms/apply-operation.js
- test/transforms/fixtures/by-key/move-node-by-key/to-sibling/index.js
- test/transforms/fixtures/by-key/move-node-by-key/to-sibling/input.yaml
- test/transforms/fixtures/by-key/move-node-by-key/to-sibling/output.yaml
`moveNode` moves a `node` from its old `parent` to a new parent `target` with path `newPath`.
When `parent` is an ancestor of `target` and the index of `node` is less than the index of the ancestor of `target` with the same depth of `node`, removing `node` changes the path to `target`.
As consequence of that, `newPath` needs to be adjusted.
> `moveNode` operation fix

- benchmark/compare.js
- benchmark/fixtures/models/get-blocks-at-range/index.js
- benchmark/fixtures/models/get-blocks-at-range/input.yaml
- benchmark/fixtures/models/get-characters-at-range/index.js
- benchmark/fixtures/models/get-characters-at-range/input.yaml
- benchmark/fixtures/models/get-characters/index.js
- benchmark/fixtures/models/get-characters/input.yaml
- benchmark/fixtures/models/get-inlines-at-range/index.js
- benchmark/fixtures/models/get-inlines-at-range/input.yaml
- benchmark/fixtures/models/get-marks-at-range/index.js
- benchmark/fixtures/models/get-marks-at-range/input.yaml
- benchmark/fixtures/models/get-texts-at-range/index.js
- benchmark/fixtures/models/get-texts-at-range/input.yaml
- src/models/node.js
- src/models/text.js
A few performance tweaks to help ease some of the issues with #791...
Looking in the **Performance** tab of devtools, we can see that most of the tab is spent in re-rendering the toolbar buttons. Because when the selection changes, they need to recalculate whether they should be "active" or not.
Which (on my machine), when selecting the "large document" amount of text in the "rich text" example is taking 38 seconds. 😱  
Most of the time is spent re-rendering the mark buttons...
But there is also a decent chunk spent recalculating the block buttons...
All in all the largest amount of time is spent in...
```
78.2% RichText.renderToolbar()
64.5% RichText.renderMarkButton()
60.8% RichText.hasMark()
60.8% getMarksAtRange()
60.5% getCharactersAtRange()
60.5% reduce()
59.2% concat()
-> …
```
> improve perf delaying conversion to immutable objects

- test/index.js
- test/plugins/fixtures/custom-rules/index.js
- test/plugins/fixtures/custom-rules/input.yaml
- test/plugins/fixtures/custom-rules/output.html
- test/plugins/index.js
I set out to provide a failing test for some weird behaviour I'm seeing with a custom plugin I'm writing where the `rules` of a plugin schema are not ran. This is JSFiddle reproducing the issue: https://jsfiddle.net/8y30hx90/ (note how the `alert()` is never called)
For some reason the tests passes, so I guess I'm doing something wrong? Time to quadruplecheck... Anyways, at least you now have a first test for plugins!
> Add tests for plugins

- examples/links/state.json
Because of comma, this json file occured an syntax error. I removed it.
Below shows the error message.
```
Error: Parse error on line 18:
...hyperlinks"					}, ]				},				{					
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'
```
> Fix state.json in examples/links

- docs/walkthroughs/saving-to-a-database.md
I was going through the documentation, and ran into an error when reproducing the code in the "Saving to Database" section:
*TypeError: Cannot read property 'key' of undefined*
```
Object.deserializeDocument
node_modules/slate/lib/serializers/raw.js:101
98 | 
99 | deserializeDocument: function deserializeDocument(object, options) {
100 |   return _document2.default.create({
> 101 |     key: object.key,
102 |     data: object.data,
103 |     nodes: _block2.default.createList(object.nodes.map(function (node) {
104 |       return Raw.deserializeNode(node, options);
Object.deserializeState
node_modules/slate/lib/serializers/raw.js:234
231 | 
232 | if (options.terse) object = Raw.untersifyState(object);
233 | 
> 234 | var document = Raw.deserializeDocument(object.document, options);
235 | var …
```
> Minor update to "Saving to Database" doc

- src/serializers/html.js
- test/serializers/fixtures/html/deserialize/html-comment/index.js
- test/serializers/fixtures/html/deserialize/html-comment/input.html
- test/serializers/fixtures/html/deserialize/html-comment/output.yaml
If you paste in HTML with comments, the comments get pasted in as text. I noticed this when using Google Sheets with cell borders.
> Ignore comments in Html deserializer

- src/components/node.js
For the problem come here: https://github.com/ianstormtaylor/slate/issues/279#issuecomment-304215238
Detail fix:
The native selection will be updated after componentDidMount or componentDidUpdate. We use setTimeout to queue scrolling to the last, when the native selection has been updated to the correct value.
> Wrap scrolling logic in setTimeout

- docs/walkthroughs/using-plugins.md
The first MarkHotkey example threw an error about isAltKey being undefined.
In the second MarkHotkey example copying using `cmd/ctrl+c` did not work anymore, because there was nothing checking if the alt key was pressed.
> Fix missing isAltKey

- src/models/stack.js
The `onBeforeChange` (and so normalization) was never called after a keyboard event.
The issue come from the call of `onBeforeChange` which was not at the right spot.
So currently, the normalization is only called when the `<Editor />` receive a new state (in `constructor` and `componentWillReceiveProps`).
I found this bug while trying to implement a normalization to prevent an empty document. When pressing <kbd>Backspace</kbd> in an unique void node, it was crashing the app, because the document was left empty.
> Fix critical bug with onChange/onBeforeChange

- src/components/node.js
This bug occurs after my previous fix at https://github.com/ianstormtaylor/slate/pull/847
It happens because some nodes are unmount right after they did update.
It's supposed to wrap only the get native scroll, not the whole findDOMNode included. That's my fault when I didn't think about this problem.
> Fix: findDOMNode was called on an unmounted component

- src/components/content.js
To test if `target` belongs to the editor, `isInEditor` `Content` method uses the code:
```
target.isContentEditable &&
(target == element || findClosestNode(target, '[data-slate-editor]') == element)
```
but `isContentEditable` is a property of `HTMLElement` only.
Therefore when `target` is a text node `isInEditor` returns false even when it should not.
To fix this, use `target` parent in the check when `target` is a text node.
> When the parameter passed to `isInEditor` is a text node use its parent instead

- docs/reference/utils/utils.md
Newer implementations of findDOMNode take the node to find as the argument, not the key of the node
> Updated findDOMNode function

- examples/index.css
- examples/plugins/index.js
There was a question in Slack about how this property worked, so thought it would be worth adding a simple example. Let me know if you think any thing should be changed?
> Add example of using plugin.render to /examples/plugins

- docs/Readme.md
Fixes the auto markdown preview link in the list of examples
> Fix "Auto-Markdown" Doc Link

- docs/reference/plugins/core.md
I tried using the exact code from the example to be met by errors.
The order of arguments in the function example is wrong, it should be use the API described in the [docs](https://docs.slatejs.org/reference/plugins/plugin.html#onbeforeinput).
```
Function onBeforeInput(event: Event, data: Object, state: State, editor: Editor) => State || Void
```
> Issue with the Overriding Defaults example.

- examples/images/index.js
- src/components/node.js
- src/plugins/core.js
Currently drag and drop of text in the same editor doesn't work (You can test it at http://slatejs.org/#/rich-text).
The `data.type` is set to `node` only when dragging a void node. I've also moved to the core plugin, the `onDrop` handling when `data.type == 'node'`.
I don't understand why the type `node` has been introduced instead of just using the type `fragment` when dragging a void node; but anyway with this fix, dragging text works fine, and dragging void nodes works fine as well.
> Fix dragging text in the editor

- src/components/void.js
As pointed here, in read-only mode, Void nodes onClick still triggers.
https://github.com/ianstormtaylor/slate/issues/508#issuecomment-265607814
> Ignore Void nodes onClick in read-only

- docs/reference/models/state.md
- examples/hovering-menu/index.js
- src/models/state.js
Fix #862 by adding a property `isEmpty`. The computation tries to be performant by not computing `state.fragment` when the selection is "simple".
I've also updated the "Hovering menu", it works perfectly with it.
@ianstormtaylor I'm not sure where to put unit tests for this property.
> Add property "isEmpty"

- examples/index.html
- src/components/content.js
- src/components/node.js
- src/utils/get-transfer-data.js
- src/utils/set-transfer-data.js
As described here: https://github.com/ianstormtaylor/slate/issues/922
A few weird things to work around; the main problem was the custom node and fragment types causing errors to be thrown with `dataTransfer.setData()`. Now when this happens, all custom data is stored in JSON object under `text/plain`.
> Fix Edge Drag & Drop Issues

- src/components/content.js
- src/components/void.js
- src/plugins/core.js
As described here - https://github.com/ianstormtaylor/slate-drop-or-paste-images/issues/9, it isn't possible to fire drop events when dragging items onto void nodes.
This pull request adds drag handlers to the Void component, to temporarily switch off the `contenteditable=false` div, and adds new behaviour, so dropped text is inserted into the nearest non-void text node.
> Allow drop events on void nodes

- src/models/node.js
Related to #706.
When highlighting a 40k character document (not an uncommon blog post size for larger web publications) and applying marks, scripting time compounds with each additional mark, mostly due to the performance of `Node.getMarksAtRangeAsArray`. This was only tested in Chrome, but it seems that concatenating arrays at scale is less performant than looping and pushing.
**Using `concat`:**
* Add first mark: ~9s
* Add second mark: ~21s
* Add third mark: ~35s
* Total time: ~65s
**Using `forEach` + `push`:**
* Add first mark: ~6s
* Add second mark: ~6s
* Add third mark: ~7s
* Total time: ~19s
> improve mark handling performance for large selections

- src/serializers/html.js
- test/serializers/fixtures/html/deserialize/empty-string/index.js
- test/serializers/fixtures/html/deserialize/empty-string/output.yaml
- test/serializers/index.js
Thanks to @vpontis for doing the actual work, I noticed that all we need to close this PR https://github.com/ianstormtaylor/slate/pull/742  and this issue https://github.com/ianstormtaylor/slate/issues/539 was a test case to cover deserialising an empty string. Let me know if this looks ok?
> Allow HTMLSerializer to deserialize an empty doc

- Readme.md
I noticed that the file size badge didn't change when Cheerio was removed in 0.21.0. Because I stupidly pinned it to version 0.19.0 😳  - this will now always show the gzip size of the latest release
> Omit version on gzip size badge

- examples/paste-html/index.js
- src/serializers/html.js
There's a few inconsistencies between parse5's output and the native DOMParser that were causing problems:
* The native DOMParser outputs tag names in CAPS. It's not clear to me if this is a consistent behavior across browsers, so I just updated the HTML example to force to lower case.
* The native DOMParser uses a `NodeList` for `childNodes`. Updated to coerce into an array if that's the case so `filter` exists.
* The native DOMParser will parse error with `application/xml` and something that is not valid HTML. I changed to `text/html` which will always work but does wrap the output in `html` and `body` tags, and then added a line to dig back to the actual output
* The native DOMParser will render a parsing of a plain text string as a `span` instead of a `#text` node
Also changed from …
> Reckon with inconsistencies between parse5 and native DOMParser

- package.json
- yarn.lock
Gets rid of warning in dev about directly accessing `React.PropTypes`
> Upgrade react-frame-component.

- src/serializers/html.js
Even if the `el.tagName` is a span, it will fall through to the child text node so the check introduced in #952 is unneeded.
> Remove unneeded check.

- src/models/node.js
Old implementation was far too slow if a selection included many nodes.
The performance hit occurred when converting each and every text node
into a block.  This is now avoided by using the same logic as
getTextsAtRangeAsArray for getBlocksAtRangeAsArray, but using blocks
directly.
> Speed up getting blocks at a range

- src/serializers/html.js
- test/serializers/fixtures/html/deserialize/mark-with-data/index.js
- test/serializers/fixtures/html/deserialize/mark-with-data/input.html
- test/serializers/fixtures/html/deserialize/mark-with-data/output.yaml
This pull requests reverts a previous change that I couldn't find any information on.  I'm not sure what `value` means to a mark, and I couldn't find anything relevant in `models/mark.js`.
I wrote a test to make sure in the future we don't break this functionality.  In master this test is failing but in my branch this test passes.
> Allow Data to be passed to Marks when using HTML Deserializer

- src/plugins/core.js
A patch for Chrome in regards to #938
> Fixes #938 chrome eating first line of text on Space key

- docs/walkthroughs/saving-and-loading-html-content.md
With the changes to how we handle HTML Parsing, you no longer get a lower case `tagName`.  This updates the documentation to account for that change.   This should reduce some confusion.
> Updating HTML Walkthrough Documentation

- src/components/content.js
Fix for a bug encountered in IE 10/11 where `isInEditor` can throw due to `el` not having an `isContentEditable` property (found while using the `Raw` serializer).
The issue appears to be that `target` can have a `nodeType` of 3 and no `parentElement`, which sets `el` to `undefined`. Likely related to https://github.com/ianstormtaylor/slate/pull/857.
To reproduce in IE 10/11: Click into the editor, make no edits or delete some text, then click out of the editor.
> When the `isInEditor` parameter is a text node use its parent only if the parent exists

- src/components/content.js
- src/plugins/core.js
Re: https://github.com/ianstormtaylor/slate/issues/938 this makes synthetic Space insertion in Chrome less obtrusive, now allowing insertion of emoji chars and possibly fixing IME (although I don't have one around to test)
> Don't break macOS emoji insert nor composition when fixing #938

- docs/walkthroughs/saving-and-loading-html-content.md
- test/serializers/fixtures/html/deserialize/block-nested/index.js
- test/serializers/fixtures/html/deserialize/block-no-children/index.js
- test/serializers/fixtures/html/deserialize/block-with-data/index.js
- test/serializers/fixtures/html/deserialize/block-with-is-void/index.js
- test/serializers/fixtures/html/deserialize/block/index.js
- test/serializers/fixtures/html/deserialize/default-block/index.js
- test/serializers/fixtures/html/deserialize/html-comment/index.js
- test/serializers/fixtures/html/deserialize/inline-nested/index.js
- test/serializers/fixtures/html/deserialize/inline-no-children/index.js
- test/serializers/fixtures/html/deserialize/inline-with-data/index.js
- test/serializers/fixtures/html/deserialize/inline-with-is-void/index.js
- test/serializers/fixtures/html/deserialize/inline/index.js
- test/serializers/fixtures/html/deserialize/mark-interleaved/index.js
- test/serializers/fixtures/html/deserialize/mark-nested/index.js
- test/serializers/fixtures/html/deserialize/mark-with-data/index.js
- test/serializers/fixtures/html/deserialize/mark/index.js
- test/serializers/fixtures/html/deserialize/no-next/index.js
- test/serializers/fixtures/html/deserialize/skip-element/index.js
Currently, we use the native `DOMParser` for HTML deserialization in browser environments, while recommending `parse5` for server-side rendering or node environments. The `DOMParser` implements the DOM spec which returns uppercase tag names, while `parse5` implements the more low-level HTML spec and ends up returning lowercase tag names (it's a little more nuanced but that's the TL;DR, see [this issue](https://github.com/inikulin/parse5/issues/210) for the full discussion). Because of this discrepancy, for the time being we should consistently use & recommend case-insensitive comparisons of tag names to prevent potential environment-specific bugs and confusion. (Currently we use `DOMParser`-compatible CAPS tags in some documentation/examples while using `toLowerCase` elsewhere.)
> Consistently use toLowerCase in tag name comparisons.

- docs/reference/components/editor.md
- docs/reference/plugins/plugin.md
This PR fixes some minor typos, and adds missing Editor props to the docs (according to https://github.com/ianstormtaylor/slate/issues/714).
> Improve documentation

- src/components/content.js
Provides a more complete solution to https://github.com/ianstormtaylor/slate/pull/974 by using `parentNode` in place of `parentElement` to find the parent of a text node and perform the `isContentEditable` check.
`parentNode` has full browser compatibility as opposed to `parentElement`, which [is not defined for text nodes](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement#Browser_compatibility) in IE and Opera.
> Use parent node to find text node parent

- docs/reference/models/state.md
Realized while discussing https://github.com/ianstormtaylor/slate/pull/990 that the docs were missing this.
> Add State.characters to docs

- docs/walkthroughs/using-the-bundled-source.md
Because `src/serializers/html.js` depends on `ReactDOMServer.renderToStaticMarkup`, which is no longer bundled with ReactDOM, ReactDOMServer is needed to avoid errors when the HTML serializer is used.
> Add a missing dependency which was causing errors

- .npmignore
See Issue #1019 
This PR solves babel transform issue when user imports slate in webpack project with default `babel-loader` config.
> Add .babelrc into .npmignore

- src/components/void.js
I stumbled upon this while debugging some weird behavior regarding DnD. Currently, once a void node has had something dragged over it, it will always stay editable (since the drag counter is never decremented).
> Reset drag counter properly in void nodes

- src/plugins/core.js
When pressing up-arrow key or down-arrow-key near a void block, it would not position the cursor properly, making shift-key-up-down-arrow-selections very difficult.
This will fix it.
> Fix bug with up and down arrow keys near void blocks

- src/components/content.js
Slate no longer shows the cursor when dragging a fragment, so there is no way to tell where the target actually is. This worked fine before https://github.com/ianstormtaylor/slate/pull/923.
The reason is that the ``event.preventDefault()`` is called in the content component's ``onDragOver``method.
Not sure why this event is required to be prevented (can't find a good reason), I see it is discussed here: https://github.com/ianstormtaylor/slate/pull/923#pullrequestreview-49357444
@mjadobson: any comments on this?
> Fix bug where cursor is not shown when dragging selected fragment

- src/components/content.js
As stated in #9, when a drop happens inside Slate, on a position not allowed by the editor, then the default browser action takes place: for example, if an URL is dropped on a void node, the browser loads that resource in the current tab.
PR #921 should have solved this issue, but it didn't, at least in Firefox.
Drop a string on an emojii in the Slate example using Firefox to see that.
This PR fixes definitively the issue calling always `preventDefault` on  drop events.
> Always call `preventDefault()` on `onDrop` events

- src/utils/normalize.js
@ianstormtaylor in #1033 I had a sloppy moment in `nodeProperties` and `markProperties` where I returned nothing if there was a `@@__SLATE` key in the node/mark.  This causes `properties` to be undefined for any transform and does some pretty bad stuff.
This new fix just makes it so it skips over those keys, which was the original intended effect.
> fixing a breaking change in node/mark properties

- docs/reference/models/schema.md
When talking about `rules` and old interface was being used.
> Update schema model documentation

- examples/embeds/video.js
- examples/images/index.js
- src/components/node.js
As described in #536, it's currently impossible (or at least very hard) for `block` and `inline` nodes to know whether or not they're part of a selection. The reason being that they only re-render if their focus changes, which I don't think is enough.
What's worked for us is to instead re-render if:
1. A node became part of a selection
**or**
2. A node was part of a selection, but isn't any longer.
> Make sure nodes always know if they're selected

- docs/walkthroughs/installing-slate.md
The old onChange function caused a bunch of `Uncaught TypeError: _this.state.state.change is not a function` errors. Adding the object destructure to the arguments fixes this.
> fixes errors for basic app with installation

- src/models/history.js
- src/models/state.js
since `state.history.undos` and `state.history.redos` are Immutable `Stack`'s we should look to see if their `size` is greater then 0 as opposed to their `length`
> Fix hasUndos and hasRedos

- src/components/node.js
In #1058 we figured out that the selection logic checks in sCU aren't aggressive enough to cover every case.  I believe this change would cover all of our bases.  Basically, if you have nodes that aren't text nodes, then you must let your child nodes determine wether or not they can re-render.  We can change this to be more performant if we find that selection is the only case where this is true, but I kept it open ended.
I was having trouble figuring out how to run the performance tests, is there any documentation on that?
Thoughts?
> sCU Changes for #1058

- src/changes/at-range.js
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void/index.js
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void/input.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void/output.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-void/index.js
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-void/input.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-void/output.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void/index.js
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void/input.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void/output.yaml
- test/changes/fixtures/at-current-range/delete/void-inline-as-first-with-non-void-block-next/index.js
- test/changes/fixtures/at-current-range/delete/void-inline-as-first-with-non-void-block-next/input.yaml
- test/changes/fixtures/at-current-range/delete/void-inline-as-first-with-non-void-block-next/output.yaml
- test/changes/fixtures/at-current-range/delete/whole-block-with-other-block-type-below/index.js
- test/changes/fixtures/at-current-range/delete/whole-block-with-other-block-type-below/input.yaml
- test/changes/fixtures/at-current-range/delete/whole-block-with-other-block-type-below/output.yaml
Fix bug in deleteAtRange when selecting a part of non-void block followed by void block.
Fix bug in deleteAtRange when selecting from an inline-void.
Fix bug in deleteAtRange when selecting a whole block, it should just be removed, and not moved  fixing #1021
Also tests for this.
> Fix bugs in deleteAtRange

- src/components/content.js
There are two things fixed here. The first one is a fix for ``content.updateSelection`` when the selection is deselected and ``anchorKey`` and ``focusKey`` is unset.  It should then return as the rest of the code acts on ``anchorKey`` and ``focusKey``.
The second fix is regarding selecting void nodes. When selecting text from a non-void block to the end, neighbouring a void-block, the ``focusOffset`` is (most of the time) set at the end of the void block when it shouldn't. This will delete the void block as well when you press backspace. Therefore make sure that the ``focusOffset`` is always set to 0 in the void block in those conditions.
Also if you move the cursor to a void-block, the same problem occur. It is most of the time set to anchor and focusOffset 1, making it impossible to …
> Fix bug with updating a deselected selection and void block selection issues

- docs/reference/components/editor.md
- docs/reference/plugins/plugin.md
- docs/walkthroughs/saving-and-loading-html-content.md
- docs/walkthroughs/saving-to-a-database.md
- src/components/editor.js
This deprecates `onDocumentChange` and `onSelectionChange` to avoid confusion from #614. As you can see from the updated walkthroughs, the workaround is actually pretty straightforward, and way simpler to reason about.
> deprecate onDocumentChange and onSelectionChange, fixes #614

- src/changes/at-range.js
- test/changes/fixtures/at-current-range/delete/hanging-selection-multiple-blocks/index.js
- test/changes/fixtures/at-current-range/delete/hanging-selection-multiple-blocks/input.yaml
- test/changes/fixtures/at-current-range/delete/hanging-selection-multiple-blocks/output.yaml
- test/changes/fixtures/at-current-range/delete/hanging-selection-single-block/index.js
- test/changes/fixtures/at-current-range/delete/hanging-selection-single-block/input.yaml
- test/changes/fixtures/at-current-range/delete/hanging-selection-single-block/output.yaml
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void/index.js
- test/changes/fixtures/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void/output.yaml
- test/changes/fixtures/at-current-range/delete/void-block-as-first-with-non-void-siblings-select-void-end-and-next-word/input.yaml
- test/changes/fixtures/at-current-range/delete/void-block-as-first-with-non-void-siblings-select-void-end-and-next-word/output.yaml
- test/changes/fixtures/at-current-range/delete/void-blocks-as-first-with-non-void-siblings-only-first-void/index.js
- test/changes/fixtures/at-current-range/delete/void-blocks-as-first-with-non-void-siblings-only-first-void/output.yaml
- test/changes/fixtures/at-current-range/delete/void-inline-as-first-with-non-void-block-next/index.js
- test/changes/fixtures/at-current-range/delete/void-inline-as-first-with-non-void-block-next/input.yaml
This cleans things up a lot. It handles:
- All cases (that I can think of) of deleting a range that starts of ends with a void node. 
- The "hanging" selections being deleted, (the triple-click issue), where you don't actually want the final node to be deleted.
- Not merging the child nodes of a block if the entire start block was deleted, so that you don't accidentally keep a block quote style if you're deleting the entire quote.
Fixes #548
cc @skogsmaskin
> refactor delete at range, fixing edge cases

- src/components/content.js
- src/utils/get-caret-position.js
When updating selection, if it is collapsed, there is no need to look for focus position: just reuse already found anchor position.
Move code to get caret position from a selection point to a standalone function in `utils`.
> Avoid finding native selection focus position when selection is collapsed

- src/serializers/base-64.js
It's puzzles me that it has to be required like this, but I see things break if I do a ``import Node from '../models/node'`` at top.
Anyway, it must get the ``.default`` export if required.
> Fix an invalid require statement in base-64 serializer

- examples/embeds/video.js
- packages/slate-react/src/components/void.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
This PR modifies the structure of the component used to render void blocks, mainly, to get rid of the ugly off-screen spacer.
As side effect it fixes issue #1103.
Maybe it also allows us to throw away some [hacks](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L767). :thinking:
On the other side this introduce an issue in the "Embeds" example: video does not respect the supplied size.
I'm going to fix this issue in a coming PR.
> Reshape void component structure.

- packages/slate-react/src/components/node.js
This fixes #1102.
The sCU `isSelected` logic could be made more effective if `isSelected`was a three-state variable:
* `-1` if the node does not intersect selection
* `0` if the node contains one of the selection edges
* `1` if the node is all inside the selection
In this case we can avoid to update a node that is, and was already, entirely selected.
But I don't know if the gain is worth the code we should add.
> Fix SCU `isSelected` logic.

- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/node.js
Why all [this complexity][1] to update the editor scroll position?
Isn't it sufficient to call `scrollToSelection` on selection update?
This PR implements that idea and it fixes issue #1133 too.
[1]: https://github.com/ianstormtaylor/slate/blob/f52967c9e6cc821856bbd5537e72ae0f52eac6c3/packages/slate-react/src/components/node.js#L183
> Call `scrollToSelection` on selection update.

- packages/slate/src/models/node.js
fixes #1123 
This one is weird, and I think there may be another underlying problem?
Basically, if they start and end keys are the same, we `getNextText`, but that always returns an empty text node next to our startNode.  This causes splice to fire on the same index, and returns no  nodes.
Is there a better way to do this?  I don't think `getNextText` should be modified.  Is it okay to assume that we just need to do it twice?
> Fixing Drag and Drop, and getFragmentAtRange

- packages/slate/Changelog.md
The following change surprised me in some of my tests concerning normalization:
https://github.com/ianstormtaylor/slate/blame/master/packages/slate/src/schemas/core.js#L55-L60
I thought it was worth mentioning in the Changelog.
> Mention change in core block normalization

- docs/reference/slate-react/custom-nodes.md
- packages/slate-react/src/components/node.js
We face issues with `shouldComponentUpdate` from times to times. For example, we're currently implementing a way for the user to sort top-level blocks in a document, with drag and drop. The node components need to be passed their index (within their parent, the `document`). While they're properly sorted, the `index` prop is not updated because the component rendering is blocked by `shouldComponentUpdate`.
For example, here's what would do the job for us:
```js
MyBlock.shouldNodeComponentUpdate = (props, nextProps) => {
if (nextProps.parent !== nextProps.state.document) {
return false;
}
const prevIndex = props.parent.findIndex(
child => child.key === props.node.key
);
const newIndex = nextProps.parent.findIndex(
child => child.key === nextProps.node.key
);
return prevIndex !== newIndex; …
```
> Add a way to customize shouldComponentUpdate logic

- packages/slate-react/src/components/content.js
`Received 'true' for non-boolean attribute 'autoCorrect'. If this is expected, cast the value to a string.`
Latest react won't autocast the bool to on/off
> Fix warning with latest react due to autocorrect being bool

- packages/slate-react/src/components/node.js
- packages/slate-react/src/components/text.js
The code used to render text nodes shares almost nothing with the code used to render other nodes.
So move it into a separate React component.
This improves the code readability a lot, many  `if (node.kind === 'text')` are eliminated, and we can make more fine-grained rendering optimization without adding others.
For example, we can safely avoid to re-render a text node if only its `isSelect` state has changed.
> Move code used to render text nodes into a separate React component

- packages/slate-react/src/plugins/core.js
@skogsmaskin this is just a different way to fix #1153 that is a bit cleaner hopefully, and in a weird way kind of makes sense, but not really.
> fix copying text with leading/trailing white space, fixes #1153

- packages/slate/src/changes/at-range.js
- packages/slate/src/changes/by-key.js
- packages/slate/test/changes/by-key/replace-node-by-key/block.js
- packages/slate/test/changes/by-key/replace-node-by-key/inline.js
- packages/slate/test/changes/by-key/replace-node-by-key/text.js
This follows up https://github.com/ianstormtaylor/slate/pull/665.
Add ``change.replaceBlock(oldBlock, newBlock)`` method to replace a block with another block.
Remove code that replaced an empty block in ``.insertBlock``
> Add replaceNodeByKey change

- packages/slate-html-serializer/src/index.js
When pasted HTML includes a doctype definition, `parsed.childNodes[0]` is the doctype node, not the `<html>` node, so it's not safe to assume that `parsed.childNodes[0].childNodes[1]` is the `<body>` node.
Using `parsed.body` ensures that we always get the `<body>` node no matter where it is in the document.
I wanted to add a test for this, but it looks like the HTML serializer tests are currently only able to run in Node using parse5, so can't exercise `DOMParser`. If there is a way to test this and I've missed it, please let me know.
The easiest way I've found to reproduce this issue manually is (weirdly enough) to type some text into a macOS Messages input field, then select all, copy, and paste into Slate. The [Paste HTML example](http://localhost:8080/dev.html#/paste-html) exhibits …
> Fix error when pasted HTML includes a doctype

- examples/paste-html/index.js
*Due to the upgrade of slate, adjust the way of el.attrs.find to el.href.
Since the upgrade of slate, el is now become an NamedNodeMap and not support .find anymore,
so I adjust it with el.href to explicit get the href value.
> Pasting external HTML does not work with Slate example. (#1129)

- packages/slate-react/src/components/leaf.js
fixes #1159 
Now if the parent node is changed, leaves will make sure that they are rendered correctly, instead of not updating at all.
> fixing empty leaft nodes in text getting desynced

- docs/walkthroughs/installing-slate.md
- docs/walkthroughs/saving-and-loading-html-content.md
- docs/walkthroughs/saving-to-a-database.md
From v0.24 slate is maintained as a monorepo with multi packages. This changes the way how user imports slate. Demos are updated while this isn't reflected in walkthrough doc. This PR updates doc contents to keep it in sync. Changes include:
- Installation of `slate` and `slate-react` instead of `slate`.
- Installation of `immutable` as peer dependency.
- Import declaration of `Editor` and `State`.
- Import declaration of `Html` and `Plain`.
> [Doc] Update installation guide and import declaration in walkthrough.

- packages/slate-react/src/components/editor.js
We just noticed from the Changelog that `onBeforeChange` is no longer called from the Editor `componentWillReceiveProps`.
This is causing issues for us, since after making changes outside of the editor (using `editor.onChange` actually) our rules are no longer applied. That’s exactly what @ianstormtaylor  explained in this issue https://github.com/ianstormtaylor/slate/issues/1111
We were thinking about a way to normalize the state ourselves, outside the editor. But this is not easy since we can’t easily get a hand on the same Schema instance than the editor’s. Not being able to do so breaks memoization.
So here is a temporary solution, that makes `stack.onBeforeChange` (and normalization) called even during the `editor.onChange`. If we end up moving the `schema` into the `state`, this …
> Apply stack.onBeforeChange in editor.onChange

- examples/emojis/index.js
In the "Emojis" example, `props.attributes` are not added to the `p` elements used to render paragraphs.
This fixes that.
> Add `props.attributes` to the element used to render paragraphs.

- packages/slate-react/src/components/editor.js
Unfortunately, I just realized that even our old system of call `onBeforeChange` in the `<Editor>`'s constructor doesn't work anymore because it doesn't obey the "all changes will result in `props.onChange` being called" rule.
So instead of just silently normalizing, we actually have to normalize and call `props.onChange` with the changes, so the parent is aware of them. To do this we have to queue and flush the change in `constructor` and `componentWillReceiveProps` because we can't trigger async logic from inside either of those methods.
cc @SamyPesse @Soreine 
---
I also feel like this means we're not going to be able to do smart things like add `state.schema` and have the normalization take place automatically, even though I thought we might be able to in #1111.
> fix change queueing in <Editor>

- docs/reference/slate/change.md
I noticed this method recommended in the changelog for 0.25.0 so this just adds it to the docs. It does take an [optional Options argument](https://github.com/ianstormtaylor/slate/blob/f9894ed443706174085e3317fc5ca3d4e6b69ec8/packages/slate/src/changes/by-key.js#L379) to manage normalization, but I presume thats an internal implementation detail is its been omitted from other methods that feature it too?
> Document `replaceNodeByKey`

- packages/slate-html-serializer/src/index.js
`In XML (and XML-based languages such as XHTML), tagName preserves case. On HTML elements in DOM trees flagged as HTML documents, tagName returns the element name in the uppercase form.`
> Sanitize tagName check

- docs/reference/slate/node.md
Just noticed a 404 when clicking "setKeyGenerator" in the "key" property description here: https://docs.slatejs.org/slate-core/node
This PR fixes the path to the utils.md file.
> Fix broken link to setKeyGenerator

- packages/slate/src/models/node.js
Fixes #1204, and perhaps more?
The current behavior of the changed line is opposite of the comment above said line.  Return `false` from a Immutable.List forEach loop causes the forEach to exit early.  I'm pretty sure we only want to return early if both start and end aren't `null`.
Let me know if you see any problems @ianstormtaylor
> Fixing getSelectionIndexes

- packages/slate-html-serializer/src/index.js
Ensure el has a tagName (e.g. textnode will not have a tagName) - found in slack channel
Strict equality checks for strings
> Some fixes

- packages/slate-react/src/plugins/core.js
If selecting a single marked word and copying it, it will not preserve the marks when pasting. This works fine in Firefox.
Before:
After:
> Fix copy single marked word bug (Chrome/Safari)

- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/void.js
- packages/slate-react/src/utils/get-drop-point.js
The state of drag&drop in Slate is far from perfect especially when void nodes are involved (see #1170 and #1192 for examples).
This PR aims to solve some of those problems.
First of all, `onDragEnter`, `onDragLeave` and `onDrop` `Void` handlers are removed . That code is a bit tricky (among other things it temporally changes the editable state of the node content) and we can live without it.
In place of the removed code, a new function, `getDropPoint`, is added to `utils`.
It returns the document point (key and offset) for a drop event.
The point is chosen following the rules below:
1. if the drop event DOM target is inside an inline void node, the point is the first position of the next sibling text node if the event happens closer to the right side of the void node, the last position …
> Rewrite drag&drop code related to void nodes.

- packages/slate-react/src/components/node.js
- packages/slate-react/src/components/void.js
`onDragStart` `Node` handler is used only by void nodes, so move it to `Void`.
> Move `onDragStart` handler from `Node` to `Void`.

- examples/hovering-menu/index.js
Try to fix hovering menu example on slatejs.org. It uses the new portal api, so it only works with React v16+. I am not sure whether it's a problem with examples.
> Fix hovering menu

- docs/Readme.md
- docs/reference/slate-react/plugins.md
- docs/reference/slate/block.md
- docs/reference/slate/change.md
- docs/reference/slate/document.md
- docs/reference/slate/inline.md
- docs/reference/slate/node.md
- docs/walkthroughs/defining-custom-block-nodes.md
During translating [Slate's Chinese doc](https://doodlewind.github.io/slate-doc-cn/) I've found several typos. This PR simply fixes them together.
BTW, Chinese translation for `v0.24.1` is done and released now. If this PR get merged, I'll be able to sync latest change from upstream then 😀 For any suggestion about this [side project](https://github.com/doodlewind/slate-doc-cn) please let me know.
> [Doc] Fix minor typos

- docs/general/resources.md
- docs/reference/slate-react/plugins.md
- docs/walkthroughs/adding-event-handlers.md
- docs/walkthroughs/applying-custom-formatting.md
- docs/walkthroughs/defining-custom-block-nodes.md
- docs/walkthroughs/using-plugins.md
- examples/check-lists/index.js
- examples/code-highlighting/index.js
- examples/huge-document/index.js
- examples/markdown-shortcuts/index.js
- examples/rich-text/index.js
- examples/rtl/index.js
- examples/syncing-operations/index.js
- examples/tables/index.js
- package.json
- packages/slate-react/src/components/content.js
- packages/slate-react/src/plugins/core.js
- packages/slate-react/test/plugins/core/on-key-down/split-empty-block.js
- yarn.lock
This removes the `data.*` properties for keyboard information. Things like `data.isShift`, `data.key`, `data.code`, `data.isMod`, etc. 
- **The `data.*` properties that relate to keyboard events have been deprecated.** There were a few different issues with these "helpers": `data.key` didn't account for international keyboards, many properties awkwardly duplicated information that was available on `event.*`, but not completely, and many properties were confusing as to when they applied. If you were using these, you'll now need to use the native `event.*` properties instead. There's also a helpful [`is-hotkey`](https://github.com/ianstormtaylor/is-hotkey) package for more complex behavior matching.
Fixes #958 
Fixes #559
> remove keyboard `data.*` properties

- packages/slate-react/src/constants/environment.js
- packages/slate-react/src/plugins/core.js
This PR closes a series of desktop IME issues: #1229 #1209 #854 #810 .
It also closes PR #885 #880 .
All issues mentions above is caused by a workaround introduced in #655 , which adds a piece of iOS COMPAT code fixing autocorrect behaviour. In this workaround, `onBeforeInput ` will adjust slate's selection **if selection is expanded**, resolve the mismatch.
However, during desktop IME composition, the selection is also expanded. This leads to deletion of unrelated text, in other word, 'eating' characters afterwards:
Previous solution adds composition-state-related `data` for `onBeforeInput`, this works but may introduce more potential issues. In fact, by simply limiting the iOS COMPAT code according to environment, this issue can be solved in a much simpler way. Moreover, it also …
> [IME] Disable iOS COMPAT behaviour on desktop

- packages/slate-react/src/components/content.js
Need to always make sure that `rangeCount` is checked before trying to get ranges.
> fix to check range count before getting ranges, closes #1237

- packages/slate-react/src/components/content.js
- packages/slate-react/src/constants/environment.js
- packages/slate-react/src/plugins/core.js
- packages/slate-react/src/utils/find-range.js
In browsers that support it (currently only Safari has full support), the native `beforeinput` DOM event provides much more useful information about text insertion than React's synthetic `onBeforeInput` event.
By handling text insertion with the native event instead of the synthetic event when possible, we can fully support autocorrect, spellcheck replacements, and related functionality on iOS without resorting to hacks.
See the discussion in #1177 for more background on this change.
Note: Chrome has partial support for `beforeinput`, but doesn't allow the event to be canceled and doesn't reliably provide information about the affected range. Possibly because of this, Chrome doesn't report the existence of the `beforeinput` event, so it fails the feature test for that event and will still …
> Use native `beforeinput` events to handle text insertion when possible

- .eslintrc
- packages/slate-react/package.json
- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/editor.js
- packages/slate-react/src/constants/event-handlers.js
- packages/slate-react/src/constants/hotkeys.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
- packages/slate-react/test/plugins/index.js
- packages/slate-simulator/src/index.js
- packages/slate/src/models/stack.js
- yarn.lock
This refactors the core plugin into two: one `BeforePlugin` and one `AfterPlugin`, places on respective ends of the plugin stack. It simplifies lots of the logic in `<Content>`, because it now all lives in the plugin code. This is the first step towards #1240, but in a non-deprecating/breaking step first.
Fixes #1109 
Fixes #1119
Fixes #1241
> Split core plugin

- examples/images/index.js
- examples/links/index.js
- examples/paste-html/index.js
- packages/slate-dev-logger/src/index.js
- packages/slate-react/src/index.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
- packages/slate-react/src/utils/get-event-range.js
- packages/slate-react/src/utils/get-event-transfer.js
This deprecates the remaining `data.*` properties. I'm going to push this as a patch release because it was so close to the `slate-react@0.5.0` which deprecated other `data.*` properties, to make it easier for people to update all in one go. (I generally try to avoid deprecating in patches, but since it's all deprecations, and it's just logging in dev, I sometimes make exceptions.)
Right now this deprecation is achieved by duplicating a lot of logic. Soon we'll remove all of the existing deprecations, and then we'll be able to remove lots of code.
Fixes #1240
> deprecate data, add getEventRange and getEventTransfer helpers

- docs/guides/changes.md
Not sure if this was an intentional omission in the `Change` guide for simplicity (understandable), but thought I'd add a block mentioning schema rules as a valid place to make changes.
Also, happy to have tiny nitpicks on individual words/tone/whatever, just roughed it in to see if it was worth adding. :)
> Mention schema rules as a valid place to make changes

- packages/slate-react/src/components/content.js
- packages/slate-react/src/utils/find-range.js
When we used native ranges in onNativeBeforeInput, we weren't carrying
over the marks from Slate's selection. This made it impossible to know
that the next character typed should have a set of marks.
Fixes #1270.
> Save marks when creating native ranges in onNativeBeforeInput

- packages/slate-simulator/src/index.js
In `slate-react@0.6.0`: The data argument to event handlers has been removed...
The event handlers generated in the slate-simulator `Simalator` object was
still passing a data argument. This data argument got passed as the `change` argument to the plugin handlers because of:
```javascript
handle(handler, change, editor, ...args) {
debug(handler)
for (let k = 0; k < this.plugins.length; k++) {
const plugin = this.plugins[k]
if (!plugin[handler]) continue
const next = plugin[handler](...args, change, editor)
if (next != null) break
}
}
```
which was called as `handle(handler, change, editor, event, data)`.
> Removed `data` argument from simulator event handlers

- packages/slate-react/src/plugins/after.js
If you have, for example, a bold mark, and you hit "Enter", the new
block won't carry over the formatting. Instead, it should (at least if
you start typing right away).
Fixes #1269.
> Keep marks after splitting a block

- packages/slate-react/src/utils/get-event-transfer.js
Pasting HTML was failing on Edge. It looks like `event.clipboardData.transfer.types` doesn't respond to `indexOf`. Alternatively, it appears to have `contains`.
Tested against Edge 38
> Fix Edge pasting exception

- examples/index.html
Slate uses `Array.prototype.includes` in at least one place:
https://github.com/ianstormtaylor/slate/blob/b558872/packages/slate/src/schemas/core.js#L62
So, request an `Array.prototype.includes` polyfill from polyfill.io if the user's browser needs it, which is the case with IE 11. I discovered this need when looking at the examples on slatejs.org to see how well Slate works in IE 11.
Also requests minified JavaScript, since this code is used for the slatejs.org website, and there's no need to serve non-minified code there.
> Request Array.prototype.includes polyfill

- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/void.js
- packages/slate-react/src/plugins/before.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Reshape `Void` component and prevent editor blur in some circumstances.
This fixes #1223 and #891 (at least on Chrome, Edge needs some extra work).
> Reshape `Void` component.

- packages/slate-react/src/plugins/after.js
This reverts commit 6f676d67712b15216cf611e01dead990ee0dd8c1.
This behavior should be in userland, because there isn't agreement
among text editors on how it should behave.
Resolves #1269.
> Revert "Keep marks after splitting a block (#1273)"

- packages/slate-react/src/utils/find-dom-point.js
`createNodeIterator` does not work at IE11 if you provide less than 4 arguments.
Also to make slate work with IE11 currently I use next hack (otherwise you cant focus editor)
```javascript
<Editor
ref={ref => { ref_ =  ref; }}
onFocus={() => { ref_.focus() }}
...
```
Without additional focus call as like as above, for unknown reason in IE11 this line is always called 
https://github.com/ianstormtaylor/slate/blob/6c42f6c9c30f6874ff1f20a916df36e922ef2f24/packages/slate-react/src/components/content.js#L137
Everything other looks like works fine.
> Fix IE11 error

- examples/dev.html
- examples/index.html
In 070a700, the `default` feature set was added and the `Array.prototype.includes` feature removed from the polyfill.io request. I think it's great to include the `default` feature set, but `Array.prototype.includes` is not included in the `default` set, so we have to explicitly request it. IE 11 needs an `Array.prototype.includes` polyfill in order for the examples to work. Without it, IE 11 gets this error:
> Include Array.prototype.includes polyfill

- docs/reference/slate/change.md
current doc for `{wrap/unwrap}{Block/Inline}` is incorrect.
> Fix wrap-unwrap Block-Inline docs

- examples/tables/index.js
Handlers in table example are passed in `state` instead of `change`, leading to bug when press delete or backspace key in table. this PR simply fixes it:
> Fix table example

- packages/slate-react/src/components/leaf.js
- packages/slate-react/src/components/text.js
- packages/slate-react/src/utils/find-dom-point.js
- packages/slate-react/test/rendering/fixtures/empty-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
Closes #1229 
When inserting new line in Slate with IME, browser automatically removes `<br />` generated for rendering empty block, then the mapping from Slate Value => React vDOM => DOM is broken, React then throws error, page is stopped.
#1316 introduces a workaround but is reverted, this PR is a leaner version as a replacement, with related assumptions updated.
BTW, currently I can see many other cases that IME's native behavior breaks the sync from vDOM to DOM, resulting in serious error thrown by React. Any ideas for a universal workaround?
> Replace <br /> with line break

- packages/slate-react/src/components/editor.js
Fixes #1318
Hey @lxcid this should fix the issue. The problem was that the editor was queue new changes, but timeouts were being set regardless of one was already upcoming or not. So now it will only ever have one timeout active at a time, so you should now see `onChange` called only once per editor in those cases when it is initialized.
> Fix flush change

- packages/slate/src/models/stack.js
> fix renderEditor to not mutate plugins when reversing

- examples/paste-html/index.js
Currently when testing paste feature, the `Paste HTML` example mainly supports:
* Block nodes with text, like `h1` and `paragraph`.
* Block nodes with text but is 'flat', like `code`.
* Void Inline nodes, like `link`.
So how about **void block nodes** like `image`? IMHO supporting image makes sense, since we can copy image from the `Images` example and paste it then, making it easier for smoke tests.
This PR simply adds this functionality.
> Handle pasting image in `Paste HTML` example

- packages/slate-react/src/plugins/before.js
- packages/slate-react/src/utils/get-event-range.js
After the change in the structure of void nodes (#1265), `getEventRange` does not work correctly anymore.
This PR fixes that issue.
> Adjust drop code to the new structure of void nodes.

- docs/reference/slate-html-serializer/index.md
- docs/walkthroughs/installing-slate.md
- docs/walkthroughs/saving-to-a-database.md
This appears to have been missed recently when `ranges` was renamed.
Strange because it seemed `ranges` had initially worked for me, and then stopped working later on in the day... :man_shrugging:
> Update walkthrough documents' initial values

- packages/slate/src/changes/on-history.js
Closes #1305 
We've discussed an approach fixing the unaccessible history state issue:
> Instead of discarding only blurs, we actually change `undo/redo` to ignore all changes to isFocused, so that the focused state will never change when undoing, it will remain whatever it currently is.
This is a cool idea and this PR implements this by checking operation type during `undo/redo`. Now no matter `undo/redo` is triggered from toolbar button click or keyboard hotkey press, editor focus remains intact, making successive history traveling unhindered.
> Omit focus change when traveling in history

- packages/slate-react/src/plugins/before.js
- packages/slate/src/changes/on-value.js
Fixes #1327 
Fixes #1328 
Currently there are two weird history stack behaviors:
1. When popping up last undo item, redo stack is cleared.
2. After initialization, `undos.size` is 1 instead of 0.
According to existing comments, during initialization, `editor.schema` will change once, then `onChange` in before-plugin triggers `change.setValue`, this saves to history by default, making undo stack's size 1 instead of 0.
Then when popping up this undo item, a redundant `setValue` operation is performed as inverse, this operation contains `{ save: true }`, so it fills undo stack again, which is makes undo stack behaves as alway 'remaining' one sole item.
This screenshot demonstrates the process described above when trying to pop up last undo item:
As as solution, this PR detects history stack …
> Prevent history mutation during initialization

- examples/history/index.js
- examples/history/value.json
- examples/index.js
Slate's examples are awesome for quick prototyping and bug reporting. For history-stack-related issues, it'll be more efficient tracking and reporting them with a live example. The more user playing with this, the easier to expose related bugs.
Another major point for adding this example is that to my knowledge, each example shipped with Slate demonstrates one major feature.  For custom components and changes, one great advantage of Slate is that their history operations are handled automatically, without the need implementing their own undo/redo method. So from this point of view, adding it as a standalone example also makes sense.
Currently this example looks like below:
Willing to update whatever needed 😀
> Add history example

- packages/slate-react/src/plugins/after.js
Closes #1335 
Currently when user click on a void block/inline node, this node appears in `value.blocks` or `value.inlines`, but selection is collapsed in this case. Then if user cuts it, we can't simple calling `change().delete()` to remove it, instead we manually remove it.
Since we still perform deletion through changes, undo/redo behaves just as what it is.
> Delete single void node when cutting

- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/utils/get-event-transfer.js
Closes #1332 
In current implementation, transferred text may be `null` instead of empty string, which may breaks deserializer. This PR fixes it.
> Add default transferred text

- packages/slate-react/src/plugins/before.js
Closes #1341
`onBlur` events are not firing because the PERF code in before-plugin returns `true` when `event.relatedTarget` is null, preventing custom callbacks from being called.
This is somewhat overkill, since according to [this post](https://stackoverflow.com/questions/42764494/blur-event-relatedtarget-returns-null), `event.relatedTarget` returns elements **only if this element can gain focus**, so clicking on plain `<div>` outside editor won't trigger `onBlur`, which is not very reasonable.
This patch removes this limitation and `onBlur` intuitively works. As for the side effect I can think of, this change may allow some `set_selection` pushed into history stack, causing focus change on undoing, but we already have #1330 handle this case.
> Trigger `onBlur` regardless of `relatedTarget`

- packages/slate-react/src/plugins/after.js
The function `onCutOrCopy` in `after.js` plugin stack creates a phony div with encoded slate fragment in an attribute and selects it (to make the browser copy those contents instead of the actual selection). 
In Firefox this causes the viewport to jump to the bottom (if the window can scroll), to find the div (presumably). `clipboard.js` fixes this by creating the phony div at the same scroll offset as the current viewport.
(See attached issue for gif)
- Creating phony div at the scroll offset as the window scroll offset 
Resolves #1339
> [onCutOrCopy] Creating the phony copy div at the same level as the real div

- packages/slate-react/src/plugins/after.js
- packages/slate-react/test/rendering/fixtures/empty-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
For some reason the rendering the empty placeholder `<span />` ends up making the caret render out of the element.
Before: 
After:
> Avoid rendering an empty placeholder by default

- packages/slate-react/src/components/content.js
previously performing a change to backward selection will trigger two changes, the change itself and selection change from backward to forward selection. This PR fixes the updateSelection logic to make sure that it preserve the backward selection on changes.
fixes: https://github.com/ianstormtaylor/slate/issues/1308
fixes: https://github.com/ianstormtaylor/slate/issues/1355
> fix backward selection always changed to forward

- packages/slate-react/src/components/leaf.js
- packages/slate-react/src/utils/find-dom-point.js
- packages/slate-react/src/utils/find-point.js
- packages/slate-react/test/rendering/fixtures/empty-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
Closes https://github.com/ianstormtaylor/slate/issues/1340.
Related to https://github.com/ianstormtaylor/slate/pull/1322.
/cc @doodlewind, did you want to test your non-native pinyin input first? This works for the native macOS input.
> Fix native IME input at the beginning of a line

- packages/slate-react/src/utils/scroll-to-selection.js
As the editor may be inside a scrollcontainer with it's own scrolling, the ``scrollToSelection`` should look for this first and scroll there,  otherwise deal with ``window``.
This is a proposal for how this can be checked and dealt with accordingly.
Se more about this issue in https://github.com/ianstormtaylor/slate/issues/1032
Before:
After:
> [WIP] Scoll to selection tweaks, possible fix for #1032

- packages/slate-react/src/plugins/before.js
This PR avoids executing _any_ hotkey shortcuts while in `isComposing` mode. This is needed because, in `master`, when hitting something like `mod+z` while composing will result in _both_ an undo event and `z` being inserted. To repro, enter some text, then type with IME, hit `mod+z` and `mod+shift+z`. You should see the data before the IME input changing and the characters being appended to the current IME ASCII text.
/cc @doodlewind I want to verify the behaviour of your custom IME input, because I can't tell why `HOTKEYS.COMPOSING` should exist otherwise. If it's to handle that, I'm happy to restore it and tidy the code up differently.
> Avoid executing hotkeys while composing

- packages/slate-react/src/plugins/after.js
I swear I found the related issue before I discovered this issue and started working on fixing it, but I can't find it again now.
Before: 
After:
> Fallback to last leaf node when inserting change

- packages/slate-react/src/plugins/after.js
Previously, `.select(entire)` would end up changing the selection to the entire line. When undoing, it results in an odd experience of the entire line selected instead of just the change (or wherever you were before in the case of Firefox). This avoids moving the selection when changing the content.
Before:
After:
> Avoid changing selection when deleting old content

- packages/slate-react/src/constants/environment.js
- packages/slate-react/src/constants/hotkeys.js
UA sniffing stops at the first match when trying to determine the client's OS. Since the macOS sniff always ran before the iOS sniff and matched the string "mac os x", which is also present in iOS Safari's user agent string, `IS_MAC` was always `true` for iOS Safari and `IS_IOS` was always `false`.
The iOS sniff now runs before the macOS sniff, which prevents false positives. Existing uses of `IS_MAC` that should also apply to iOS have been updated to check for `IS_MAC || IS_IOS`.
This also re-fixes #1176 and #1177, which regressed when a recent change added `IS_IOS` checks that inadvertently prevented code from running on iOS.
> Fix broken iOS UA sniff that identified iOS as macOS

- packages/slate-react/src/utils/scroll-to-selection.js
previously findScrollerContainer always return window as scroller variable is assigned to window.
this fix the intended fix from https://github.com/ianstormtaylor/slate/pull/1165
> fix scrolling on slate inside scrollable container that is not a window

- packages/slate-react/src/utils/scroll-to-selection.js
previous scrolling fix works fine if we're typing at the end of the document. if the edited text is at the middle or beginning of the document, it's unusable.
> scroll to the correct position

- packages/slate-react/src/plugins/before.js
Currently we use a plain `setTimeout` to delay `onCompositionEnd`, while this timeout may be leaky for some IMEs.
In [workaround of Draft.js](https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L74) there's an 'magic' constant timeout, while it'll be more semantic and COMPAT-proof with the `requestAnimationFrame` approach.
Smoke tested on Chinese / Japanese / Korean / French and no regression found.
> Replace IME `setTimeout` with `requestAnimationFrame`

- packages/slate-simulator/src/index.js
The Simulator was calling the handlers with the `change` argument as the first argument instead of the `event`.
> Fixed simulator handler argument order

- examples/emojis/index.js
Fixes #1192.
For the emojis example, default dropping behavior may raise unexpected issue on corner cases. Simply `preventDefault` on drop fixes this.
This tweak does not affect current word DnD behavior in this example. When dropping on emojis, still can word inserted into text in correct order.
> Disable dropping in inline void node example

- packages/slate-react/src/components/leaf.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Render text inside void nodes with a zero-width space.
So the node can contain selection but the text is not visible.
> Render text inside void nodes with a zero-width space.

- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/delete-line-backward/inline-middle-emoji.js
- packages/slate/test/changes/at-current-range/delete-line-backward/inline-multi-voids.js
- packages/slate/test/changes/at-current-range/delete-line-backward/inline-void-first.js
- packages/slate/test/changes/at-current-range/delete-line-backward/text-end.js
- packages/slate/test/changes/at-current-range/delete-line-backward/word-middle.js
Fixes #1199 
`Change.deleteLineBackward` is generally called by `cmd-del`, which deletes the whole line before cursor. This method fails if first node in the line is an void inline node, e.g. `<emoji />`.
Reason for this issue is that when we calculate the offset to delete, the void inline node has an empty text child node, which disturbs the offset.
Say we'd like to delete such a line:
```
<p>
<emoji />
hello world
</p>
```
The actual structure is somewhat like following:
``` html
<p>
<text key="1" />
<emoji key="2">
<text key="3"/>
</emoji>
<text key="4">hello world</text>
</p>
```
Currently when we attempt to find the beginning text node, we loop from end of the line, and eventually try finding previous text node of "hello world", which is `3` in this example. But the "actual" previous …
> Fix `deleteLineBackward` when first node is void inline

- packages/slate-react/src/utils/find-point.js
Error occurs when render `<input />` in readOnly mode
```js
function Input(props: any) {
return (
<input
onFocus={(e) => {
e.preventDefault()
e.stopPropagation()
// console.log(e)
}}
/>
)
}
```
```js
<Editor
placeholder="Enter a title..."
renderNode={this.renderNode}
readOnly
/>
```
```js
renderNode = (props: any) => {
const { node } = props
const Component = {
input: Input,
}[node.type]
if (!Component) return undefined
return <Component {...props} />
}
```
> Fix find-point.js when void node is input (in readOnly mode)

- packages/slate-react/src/components/content.js
fixes #1385  
by using Selection.collapse/extend, we can preserve the backward/forward selection direction, and they are supported on IE 11
EDIT: Selection.extend is not available in IE11...
> IE 11 compatibility, use Selection.collapse/extend instead of Selection.setBaseAndExtent

- packages/slate-react/src/components/content.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/utils/find-dom-node.js
- packages/slate-react/src/utils/find-dom-point.js
- packages/slate-react/src/utils/find-dom-range.js
In findDOMNode util function the global window was being used, by passing down window from Content we assure it works inside an iframe.
Fixes #1390
> Add support to iframe

- packages/slate-react/src/components/editor.js
This should fix #1395.
This is related to #1324. The `flushChange()` function in the Editor component sets a timeout for calling onChange, which means it can be called after the component has unmounted.
I added a `componentWillUnmount()` handler which simply clears the timeout if it exists.
I did some local testing by modifying one of the examples, and it seemed to work as expected. But I'm not sure how to write a test case for this, if it is needed...
> fix calling onChange handler after Editor component unmount

- packages/slate-react/src/utils/scroll-to-selection.js
After recent fix to scrolling within scrollable containers, the editor now scrolls the scroller container to the end on every key press. Seems to be doing this because it is not subtracting the distance between the top of the window and the scrollable container. (I have mine within an absolute position modal.)
I fixed the issue for myself by subtracting that top distance from `top` var before calculating the final `y` to scroll to within `scroll-to-selection.js`.
> corrects overscroll issue inside scrollable containers (#1032)

- examples/images/index.js
> This example shows images in action. It features two ways to add images. You can either add an image via the toolbar icon above, or if you want in on a little secret, copy an image URL to your keyboard and paste it anywhere in the editor!
Paste is broken on slatejs.org. on Paste event, getEventRange(event) always returns null because there is no clientX and clientY from the Clipboard event.
> Fix image example's onPaste

- docs/guides/changes.md
- docs/guides/data-model.md
- docs/guides/plugins.md
- docs/guides/rendering.md
- docs/guides/schemas.md
I just got around to read the new Guides section, and wow was I'm impressed! I fixed some typos while reading (and my editor apparently stripped some hanging whitespace as well, let me know if that's annoying and I'll add them back).
> fix some typos in docs/guides

- examples/syncing-operations/index.js
- packages/slate/src/changes/by-key.js
- packages/slate/src/changes/on-history.js
- packages/slate/src/changes/on-selection.js
- packages/slate/src/constants/model-types.js
- packages/slate/src/constants/operation-attributes.js
- packages/slate/src/index.js
- packages/slate/src/models/change.js
- packages/slate/src/models/operation.js
- packages/slate/src/models/range.js
- packages/slate/src/operations/apply.js
- packages/slate/src/operations/invert.js
- **The operation objects in Slate are now immutable records.** Previously they were native, mutable Javascript objects. Now, there's a new immutable `Operation` model in Slate, ensuring that all of the data inside `Value` objects are immutable. And it allows for easy serialization of operations using `operation.toJSON()` for when sending them between editors. This should not affect most users, unless you are relying on changing the values of the low-level Slate operations (simply reading them is fine).
- **Added a new `Operation` model.** This model is used to store operations for the history stack, and (de)serializes them in a consistent way for collaborative editing use cases.
---
Fixes #1143
> add immutable operation model, with serialization

- packages/slate-html-serializer/benchmark/html-serializer/serialize.js
- packages/slate-plain-serializer/benchmark/plain-serializer/serialize.js
- packages/slate-react/benchmark/rendering/normal.js
- packages/slate/benchmark/changes/delete-backward.js
- packages/slate/benchmark/changes/delete-forward.js
- packages/slate/benchmark/changes/insert-text-by-key-multiple.js
- packages/slate/benchmark/changes/insert-text-by-key.js
- packages/slate/benchmark/changes/insert-text.js
- packages/slate/benchmark/changes/normalize.js
- packages/slate/benchmark/changes/split-block.js
- packages/slate/benchmark/models/from-json.js
- packages/slate/benchmark/models/get-blocks-at-range.js
- packages/slate/benchmark/models/get-blocks.js
- packages/slate/benchmark/models/get-characters-at-range.js
- packages/slate/benchmark/models/get-characters.js
- packages/slate/benchmark/models/get-inlines-at-range.js
- packages/slate/benchmark/models/get-inlines.js
- packages/slate/benchmark/models/get-leaves.js
- packages/slate/benchmark/models/get-marks-at-range.js
- packages/slate/benchmark/models/get-marks.js
- packages/slate/benchmark/models/get-path.js
- packages/slate/benchmark/models/get-texts-at-range.js
- packages/slate/benchmark/models/get-texts.js
- packages/slate/benchmark/models/has-node-multiple.js
- packages/slate/benchmark/models/has-node.js
- packages/slate/benchmark/models/to-json.js
- packages/slate/benchmark/models/update-node.js
This just fixes the benchmark to be run in the latest version.
```
benchmarks
html-serializer
deserialize
8.68 → 7.20 ops/sec
serialize
852.30 → 775.35 ops/sec
plain-serializer
deserialize
254.89 → 247.64 ops/sec
serialize
7248.68 → 7343.98 ops/sec
rendering
normal
78.13 → 78.87 ops/sec
changes
delete-backward
72691.07 → 75240.82 ops/sec
delete-forward
13114.26 → 15398.91 ops/sec
insert-text-by-key-multiple
75.88 → 85.22 ops/sec
insert-text-by-key
1053.04 → 962.39 ops/sec
insert-text
952.91 → 1014.81 ops/sec
normalize
3037.60 → 3518.49 ops/sec
split-block
59.17 → 61.41 ops/sec
models
from-json
118.76 → 126.34 ops/sec
get-blocks-at-range
549113.52 → 564613.16 ops/sec
get-blocks
2852520.48 → 2724271.59 ops/sec
get-characters-at-range
601222.96 → 589214.31 ops/sec
get-characters
2837836.98 → …
```
> Update benchmark to use Value

- package.json
- packages/slate/src/models/history.js
Undos are measured in `.size` rather than `.length`; previously Slate would allow for unlimited undos _(see screenshot below)_. This patch fixes that.
I am looking for help to implement an API that would allow the user to control the max history step size. It's very easy for me to replace `100` with a variable, but I don't understand how the `options:{}` work - where the values come from and whether the user has any control over it.
Should it be like `value.history.undos.set({max: 20})`?
Your insights are appreciated :)
***
> Managing History limits

- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/insert-text/hanging-selection-multiple-blocks.js
- packages/slate/test/changes/at-current-range/insert-text/hanging-selection-single-block.js
Added 2 new tests to exploit the bug from #1189 :
changes/at-current-range/insert-text/hanging-selection-multiple-blocks.js
changes/at-current-range/insert-text/hanging-selection-single-block.js
removed test:
changes/at-current-range/delete/whole-block-with-other-block-type-below.js
which was just a duplicate of:
changes/at-current-range/delete/hanging-selection-single-block.js
implemented a fix for the 2 new failing test cases by updating `startKey` and `startOffset` after `deleteAtRange()` call.
> Fix inserting text with hanging selection, issue #1189

- docs/reference/slate/operation.md
`merge_node` has a `position` field, which is exactly what I needed in order to transform some operations. It should be documented.
> Document the `position` field of `merge_node`

- packages/slate/src/models/node.js
If you move to the beginning of a text node, and the previous text
node has marks, `marks` is set but `activeMarks` is not. This was
caused by `getActiveMarksAtRangeAsArray` looking for a function that
didn't exist. With this change, `activeMarks` is brought in line with
how `marks` works for collapsed selections.
> Fix activeMarks at the beginning of a line

- packages/slate-react/package.json
- packages/slate-react/src/components/content.js
- yarn.lock
This adds support for the native `selectionchange` event, which prevents people from having their selection blocks by concurrent changes being applied to the editor.
> handle native `selectionchange` event, closes #1135

- packages/slate/src/models/schema.js
- packages/slate/test/schema/custom/child-kind-invalid-custom-optional-first.js
When moving to the next definition with `continue` `nextChild` gets called twice and skips over a child before it's proven valid.
This rewinds the index and offset before `continue`. Ensuring the current child gets validated with the next definition instead of being skipped.
> Fix nodes validation with e.g. an optional first child

- packages/slate-react/src/utils/scroll-to-selection.js
Tested on OS X 10.12 in Safari 11, Firefox 57, and Chrome 62, with both horizontal and vertical overflow, for both window and a scrollable wrapper div, with and without borders.
Fixes #1416 and #1032.
Also sort of fixes an issue where `Range.getBoundingClientRect()` returns 0s in Safari, causing the scroll behavior to fail.
Known caveat:
1. Will not work (does nothing) if `document.body` is actually the scrollable element, in which case `window.scrollTo()` is incorrect. I believe this is only the case if the height is explicitly set via css:
```
body {
height: 100vh;
}
```
Unfortunately `document.body.scrollTop` does not work correctly in Chrome (always returns 0), so you have to use `document.documentElement` instead. Trying to handle this case was somewhat agonizing, but if this …
> Refactor scrollIntoView logic

- docs/Readme.md
- docs/reference/slate-react/utils.md
- packages/slate-react/src/index.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/utils/clone-fragment.js
- packages/slate-react/src/utils/copy-fragment.js
I took a stab at fixing #1410 and #1411 by creating an extra exposed helper function. Most of the new function was a direct move from `onCutOrCopy`, I just changed `fragment` to be a parameter.
> Add a `copyFragment` helper for plugin onCut/onCopy functions

- packages/slate-react/src/utils/scroll-to-selection.js
Tested on Safari 11.0.1 on OS X 10.13.1 with a scrollable container.
Fixes #1445 .
> fix(scroll-to-selection): use getClientRects when selectionRect.top/height is still 0 in Safari

- packages/slate/src/models/operation.js
Value is only used for local undo / redo, so it shouldn't be serialized along with the rest of the data. This fixes #1439.
> Remove `value` from `operation.fromJSON`

- packages/slate-react/src/components/editor.js
As operations is now a `Immutable.List`, `length` will always be `undefined`, thus changes through `<Editor />` never get flushed.
I am quite reluctant to fix this bug but ensuring the correctness of the code first should be the highest priority.
I'll file a separate issue, but the problem I have with fixing this is that it will reintroduce an extra `onChange` event scheduled with `setTimeout()` when `<Editor />` first get created and mounted. (It is trying to queue/flush the changes.)
This actually hurt a muilti-editors environment.
> Using the wrong property to access length of `change.operations`

- packages/slate/src/models/schema.js
- packages/slate/test/schema/custom/node-mark-invalid-default.js
- packages/slate/test/schema/custom/node-mark-valid-default.js
<s>`NODE_MARK_INVALID` should only happen if none of the node's mark are valid.</s>
> Fix schema marks validation

- packages/slate/src/changes/at-range.js
- packages/slate/test/history/undo/wrap-inline-across-blocks.js
Fixes #1487 
The problem was that `startIndex - 1` usually equalled -1, which worked with `Immutable.List.insert` to insert the new inline at the end of the startNode, but this messed up inverting the operation so that inserted inline node remained.
> fix for #1487

- packages/slate-react/src/components/content.js
We need to check that `this.element` is not `null` before calling `focus()`.
> `this.element` might be `null` when the callback is executed

- packages/slate-react/src/components/content.js
```
<IFrameComponent>
<SlateEditor {...props} />
</IFrameComponent>
```
Since react unmounts from top down, `IFrameComponent` will unmount first (destroying its window), then `SlateEditor` will unmount and attempt to access the iframe window (which no longer exists) throwing `Uncaught TypeError: Cannot read property 'document' of undefined`.
It should be safe to skip removing event listeners from windows that no longer exist since they will be garbage collected upon destruction of the window anyway
> Don't attempt to remove event listeners from non-existent window

- packages/slate/src/operations/invert.js
- packages/slate/test/history/undo/move-node-affecting-path.js
- packages/slate/test/history/undo/move-node-before-itself.js
When inverting a merge operation, we need to take into account the structure change caused by the merge operation. I can come up with two places where this happens:
* If you're moving from a left sibling of an ancestor of the new position, we need to adjust part of the new position by -1.
* If you're moving to an ancestor of the original position, or a left sibling of an ancestor of the original position, we need to adjust part of the path by 1.
I added tests for each of these, and have some other examples that could make good low-level test cases. Is there a good place to put those? I didn't see any tests on operations.
This fixes #1469.
> Properly invert `merge_node` operations

- packages/slate-react/src/components/editor.js
Propose to flush change immediately instead of delaying it using `setTimeout()`.
- Flushing change is only use for `props.onChange()` callback and invoked at the end of render lifecycle (didMount/didUpdate), can't find the rationale for delaying it.
- `setTimeout()` delay are not dependable for a predictive behaviour
- `onChange()` is an important callback for a controlled component, delaying it can cause race condition. e.g. any changes outside of the component lifecycle that happen between the delay of flushing change will be overridden
@ianstormtaylor I like to check with you on this proposal to see what you think of it
Ref #1479
> [WIP] Flush change immediately (Proposal fix for #1479)

- packages/slate-html-serializer/src/index.js
`el.value` vs. `el.value || el.nodeValue` were inconsistently used when deserializing HTML.
This caused a specific bug in which html looked like:
```
<ul>
<li>Some text</li>
</ul>
```
The HTML parser was finding `'#text'` nodes with no `value` but with a `nodeValue`, which was causing them to not be filtered out, resulting in improper nodes (text nodes as direct children of the `<ul>`).
To reproduce, see this fiddle: https://jsfiddle.net/usf40krv/
Go to line 320 and change `el.value` -> `getValue(el)`.
> slate-html-serializer: consistent element.value lookups

- packages/slate/src/changes/at-range.js
Currently the `moveNodeByKey` call in `change.deleteAtRange` normalizes the output.  This is problematic because this allows normalizers to modify the change object, potentially removing the endBlock node.
If that happens, we don't update our endKey, and that causes the `mergeNodeByKey` call afterwards to fail.  I think it's better if we just don't normalize any of the operations, and then normalize all at once at the end.
@ianstormtaylor This sounds like pretty common behavior to not want to normalize on a string of changes.  I wonder if this warrants some kind of flag?
> Adding normalize false to the moveNodeByKey call in deleteAtRange

- packages/slate/src/operations/apply.js
- packages/slate/test/index.js
- packages/slate/test/operations/apply/remove_text/cursor-inside-removed-text.js
- packages/slate/test/operations/index.js
If selection is inside a block of text that's removed, the part of the selection that's inside the bounds should clamp to the offset of the removed text. 
For example, if your cursor is at offset 5, and you're deleting from 2-10, your cursor should end up at offset 2.
Here's a fiddle showing the broken behavior: https://jsfiddle.net/w1dxg25n/2/ Wait 5 seconds, and you should see an error in the console.
> Move selection to the offset of remove_text if it's in its bounds

- packages/slate-react/src/plugins/after.js
Fixes #1519, which was introduced by 5f991645.
I'm honestly not sure how I missed this when I tested 5f991645. It's possible I was testing stale code without realizing it. Sorry about that!
This fix is (I think) a better alternative to my original approach of modifying the hotkey constants. Instead of preventing the hotkeys from being matched on iOS, we just avoid handling them when they shouldn't be handled. Turns out this is easy because it only needs to happen in one place, and doing it there also makes the intent more clear.
> Fix double-handling of iOS return and backspace keypresses

- docs/reference/slate-react/core-plugins.md
- docs/reference/slate-simulator/index.md
- packages/slate-react/src/index.js
In some scenarios we would like to use the core plugins inside tests with `slate-simulator`. That is currently not possible. This PR exposes the core plugins so we can import them on case by case basis.
> Expose core plugins

- packages/slate-react/src/utils/scroll-to-selection.js
This code simply disables the scroll to selection on all iOS devices.
The reason why is because on the iPad, any typing in the editor causes a scroll back to the top of the page. On other iOS devices, it appears the scroll to selection might not do anything anyways.
It's a bit brute force but it makes the editor usable if not necessarily convenient. Right now, it is unusable on the iPad.
The full discussion is here:
https://github.com/ianstormtaylor/slate/issues/1513
> Fixed scroll-to-selection jumping to top on iOS

- examples/search-highlighting/index.js
(Per #1454)
Hey! I saw this change was intended by @zhujinxuan but he hadn't had time to add it yet. I copied the search highlighting example today and ran into the same issue after a few hours so I think it should definitely be changed.
> Update search-highlighting example per #1454

- docs/guides/plugins.md
@ianstormtaylor plugins + typo in core-plugins link
Scope creep:
- `slate-mentions` and `slate-suggestions` referenced in the root `README.md` are no longer maintained/broken cause of the last months breaking changes, I did not remove the links cause at the moment I'm not sure I can offer an alternative solution (I have built a working one with latest specs but it is stored on a private repository for my company, I need to check if it can be open sourced).
> Fix broken links on docs

- docs/general/plugins.md
From https://github.com/withspectrum/slate-mentions
`WE'VE SWITCHED TO DRAFT.JS, SO THIS REPO IS NO LONGER MAINTAINED!`
Last version was released 8 months ago && was just a beta, not production ready (Info coming from the repo's README).
> Remove deprecated plugin

- packages/slate-react/src/utils/clone-fragment.js
Fixes #1484, which caused pasted material to retain styles (such as background color) from the page body.
Instead of appending the cloned fragment to the `<body>`, append it to the editor element instead.
Before:
After:
> Append copied fragment to editor DOM node instead of page body

- docs/reference/slate/change.md
Hi, I think `change.snapshotSelection` is useful in developing some packages with `removeNode`, for example, in the case of https://github.com/GitbookIO/slate-edit-table/issues/40
Therefore, I think it might be better if we have list the api in the document.
> Document: add `change.snapshotSelection` in the change.md

- packages/slate-react/src/plugins/after.js
- packages/slate/src/changes/at-current-range.js
- packages/slate/src/changes/at-range.js
- packages/slate/src/models/node.js
Fixes https://github.com/ianstormtaylor/slate/issues/1470. Also encountered and fixed an issue with marks being incorrectly applied (basically anything that was in the target text becomes an active mark). Behaviour is based on native document editing behaviour of marks (e.g. Word, Pages).
> Fix selection replacement and marks

- docs/Readme.md
> Use absolute links in changelog so they render correctly in GitBook.

- .npmignore
- packages/slate-base64-serializer/.npmignore
- packages/slate-base64-serializer/package.json
- packages/slate-dev-logger/.npmignore
- packages/slate-dev-logger/package.json
- packages/slate-html-serializer/.npmignore
- packages/slate-html-serializer/package.json
- packages/slate-hyperscript/.npmignore
- packages/slate-hyperscript/package.json
- packages/slate-plain-serializer/.npmignore
- packages/slate-plain-serializer/package.json
- packages/slate-prop-types/.npmignore
- packages/slate-prop-types/package.json
- packages/slate-react/.npmignore
- packages/slate-react/package.json
- packages/slate-simulator/.npmignore
- packages/slate-simulator/package.json
- packages/slate/.npmignore
- packages/slate/package.json
Note that npm [will include](https://docs.npmjs.com/files/package.json#files) the `package.json`, `Readme.md`, and `Changelog.md` regardless of whether it's in the `files` array.
Fixes #1442
> Switch to package.json "files" configuration rather than .npmignore

- examples/code-highlighting/index.js
Not exactly sure where it broke, but the code surrounding Prism token content didn't account for all the nested cases and it was possible to overflow the `texts` buffer. 
Fixes #1368
> Fix code highlighting example

- packages/slate/src/models/node.js
Hi, this is related to https://github.com/ianstormtaylor/slate/issues/1408, last two commits by https://github.com/ianstormtaylor/slate/pull/1538;  The path provides two methods to update node/path after change happens.
Cheers,
Jinxuan Zhu
> Faster (but also safe) method about re-find node by path

- packages/slate-react/src/constants/environment.js
- packages/slate-react/src/utils/find-range.js
The Edge browser (41) has a weird edge case when selecting. If you double click to select the last word in a block, and it's the last text in the block, it sets the `endContainer` of the selection range to the surrounding node. The `selection-is-backward` lib doesn't handle cases where node's are contained. 
The current effect is that `findRange` get's `isBackward` wrong, and the range collapses to the start when creating a native `Range`.
> Edge browser selection edge case

- packages/slate/src/changes/with-schema.js
Hi, this is a PR regarding:
1. https://github.com/ianstormtaylor/slate/issues/1537 and https://github.com/ianstormtaylor/slate/issues/1528
2. https://github.com/ianstormtaylor/slate/issues/1363 Not try to get the invalid node in parent stack
3. A bit change of code to make the `normalizeNodeAndChildren` shorter; Perhaps this change makes this function a bit more friendly to readers
If you like to have tests for the two issues; I would like to add one~
Thank you very much for your reviewing~
> Continue normalize next child when and only when the node exists still

- packages/slate/src/models/range.js
- packages/slate/test/changes/at-current-range/unwrap-block/middle-child-blocks-with-backward-selection.js
@CameronAckermanSEL   Can you have a test whether unwrapBlock is good after this PR?
It should fix https://github.com/ianstormtaylor/slate/issues/1500
The problem is that moveToRangeOf does not consider the case `Range.isBackward`.  I think there can be two options:
1. `moveToRangeOf` always return with `isBackward: false`
2. `moveToRangeOf` keep `isBackward`, but switch anchor and focus if necessary.
In this PR, I choose the second solution
> Fix range.moveToRangeOf when range is a backward range;

- docs/reference/slate/mark.md
Link was pointing to `./mark.md`, now points to `./character.md`
> Fix broken "Characters" link in docs

- docs/walkthroughs/defining-custom-block-nodes.md
The CTRL-` example fails in Edge due to lack of support for CTRL+... events. Reference: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/742263/.
Added a note so other Edge users won't be tripped up by the walkthrough.
> Docs: Add that Edge does not support `CTRL+...`

- packages/slate/src/models/range.js
Feel free to take or leave this, but I just spent a fair amount of time trying to understand why `change.addMarkAtRange()` was extending my mark to the end of each text node. Turns out, I was reading the offsets straight into a Range from window.location, and in `change.addMarkByKey()`, it was doing `offset + length` as `"13" + 158` giving `"13158"` instead of the expected `171` for the end of the range.  JavaScript 🙄.
Figured that normalizing offsets in `range.normalize` was a reasonable approach, and that it might save someone the same trouble later.
Happy to write tests for this, but couldn't see any locations that models were being tested, nor a specific `tests/changes/on-document` section either. If you let me know the right location, I can write one.
> Warn during normalization when range offsets are not numbers

- docs/walkthroughs/applying-custom-formatting.md
The *Applying custom formatting* guide states that Slate outputs an error in the console when a mark is applied without a corresponding renderer but AFAIK, that's not the case in the current version. I'm guessing this is an old behaviour (I'm completely new to this library), hence the doc update.
> [Doc] Adding an unknown mark doesn't produce an error

- Contributing.md
- package.json
- rollup.config.js
- support/rollup/factory.js
Based on the conversation in #1593 
1. Default to emitting both CJS and ES even in development/watch mode, as CJS is used by the tests so this allows for auto rebuilds that the tests can be run against
2. Move the `http-server` command to `yarn server` and change `yarn start` to both start the rollup watch and also start the http server. This is for a slightly more intuitive experience getting up and running -- you expect `yarn start` to be the default command to get started in development, rather than needing to either build first or run `yarn watch` instead.
3. Add a `watch:packages` command that builds & watches the packages (but not the examples), for super fast auto rebuilds when you are developing on a package and running tests against it but not using the examples.
Closes #1593
> Improvements to developer experience with building packages

- .travis.yml
- Contributing.md
- examples/Readme.md
Yarn does not require you to specify `run` when running a package script, i.e. `yarn run build` is the same thing as `yarn build`. Currently we have a mixture of invocations in the code/docs -- this PR standardizes around omitting `run`.
> Standardize on yarn shorthand rather than yarn run

- package.json
Run benchmark with `BABEL_ENV=test` to `import modules`
Fix https://github.com/ianstormtaylor/slate/issues/1606
> Fix BABEL_ENV bug in yarn benchmark

- packages/slate-react/src/components/content.js
`Selection.collapse()` can fail at setting the anchor point, but it does so without throwing. So when we do the following in `updateSelection`:
```
native.collapse(range.startContainer, range.startOffset)
native.extend(range.endContainer, range.endOffset)
```
`extend()` will throw if `collapse()` wasn't successful (since there's nothing to extend from). I haven't been able to figure out why it fails, but we can reproduce it consistently in our app (on Chrome). I can't find any info on when it could fail etc.
This PR just adds a safety check before running `extend` so that an error isn't thrown. What's interesting in our app is that it behaves as expected with this even when it can't set the anchor point.
> fix(updateSelection): make sure there is a node to extend from

- docs/walkthroughs/applying-custom-formatting.md
- docs/walkthroughs/using-plugins.md
As discussed in https://github.com/ianstormtaylor/slate/issues/1590, Windows already maps the `win-B` (metaKey) shortcut, which makes the walkthrough example fail. This changes the examples to use ctrlKey throughout.
> Examples: Use ctrlKey instead of metaKey (for Windows compatibility)

- packages/slate/src/models/node.js
Both `getAncestors` and `getDescendant` are DFS, but the `getDescendant` cannot take advantage by the cache by `getAncestors`.   This PR makes `getDescendant` taking advantage from `getAncestors` cache.
> Use getAncestors in getDescendant

- examples/emojis/index.js
currently, after clicking one emoji, user needs to click in the editor before being able to add another emoji
this fixes that by jumping to next text block and focusing selection to make it obvious where next insertion will take place.
> add ability to click multiple emojis in example

- packages/slate/src/models/node.js
When `Text.text === ''`, for example after delete or by normalization around inline, the `getInsertMarksAtRangeAsArray` will throw an error.
This PR fixes that.
Fix https://github.com/ianstormtaylor/slate/issues/1613
> Fix getInsertMarksAtRangeAsArray for empty Text Node

- packages/slate-react/src/plugins/after.js
When drag and dropping an inline node to a position earlier in the
document, the node is inserted and then removed right after.
Regenerate the key to make sure the old node is removed instead of the
new one.
> Fix drag and dropping an inline node "forward" in the document

- packages/slate/src/models/node.js
Fix https://github.com/ianstormtaylor/slate/issues/1561 that when the end of previous block is marked, then cursor at the block start is also marked.
> Fixing the bug that getMarks steals mark from the previous block

- packages/slate-react/src/components/leaf.js
- packages/slate-react/src/utils/clone-fragment.js
- packages/slate-react/src/utils/find-point.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-multiple.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline.js
- packages/slate-react/test/rendering/fixtures/default-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
- packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Add back empty blocks as a newline behaviour by swapping the text out at copy and paste time. It needs to stay as a zero width space because otherwise the browser swaps the `\n` out with nothing when inputting multiple IME characters. This results in Slate blowing up like before, so keeping the zero width behaviour is the simplest approach while using the copy and paste swap to get the plain text behaviour that's desired.
Happy to replace `z` and `n` with something else too, those are just short placeholders. I initially tried with `parent.kind` or `node.kind` as the values, but it resulted in undesirable behaviour because these nodes appear in a lot of places.
Fixes https://github.com/ianstormtaylor/slate/issues/1635.
> Replace zero width blocks with newline before copy

- packages/slate/src/models/node.js
`char` could be `undefined` when accessing `char.marks`, this PR make sure that char exists otherwise `return []` .
ideally, any `operations` should not result in `char` being `undefined`
> Fix marks of undefined on char.marks

- examples/hovering-menu/index.js
`scrollX`/`scrollY` do not work on some browsers, using `pageXOffset`/`pageYOffset` instead: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX#Notes.
This makes the hovering menu example work on IE11:
Before:
> Use pageXOffset instead of scrollX in hover menu example

- packages/slate-react/src/plugins/after.js
Unfortunately I don't have much detail from our error reporting but I can see that a user on latest Chrome and MacOS had text as `null` and the stacktrace is entirely internal to slate / react (below).
An alternative fix might be to ensure that the `text` value returned from `getEventTransfer` is an empty string instead of `null`? Happy to change to that or something else.
```
TypeError Uncaught TypeError: Cannot read property 'split' of null 
webpack:///node_modules/slate-react/lib/plugins/after.js:452 Object.d
webpack:///node_modules/slate/lib/slate.js:9593 t.value
webpack:///node_modules/slate-react/lib/components/editor.js:391 
webpack:///node_modules/slate/lib/slate.js:13134 e.value
webpack:///node_modules/slate-react/lib/components/editor.js:373 t.B.change …
```
> Fix for text value being null in an onDrop event

- docs/reference/slate/change.md
- docs/walkthroughs/applying-custom-formatting.md
- docs/walkthroughs/defining-custom-block-nodes.md
- examples/check-lists/index.js
- examples/markdown-shortcuts/index.js
- examples/rich-text/index.js
- packages/slate/src/changes/at-current-range.js
- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/set-block/across-blocks.js
- packages/slate/test/changes/at-current-range/set-block/across-inlines.js
- packages/slate/test/changes/at-current-range/set-block/data-only.js
- packages/slate/test/changes/at-current-range/set-block/hanging-selection.js
- packages/slate/test/changes/at-current-range/set-block/nested-block.js
- packages/slate/test/changes/at-current-range/set-block/single-block-string-shorthand.js
- packages/slate/test/changes/at-current-range/set-block/single-block.js
- packages/slate/test/changes/at-current-range/set-block/with-data-as-map.js
- packages/slate/test/changes/at-current-range/set-block/with-data-as-object.js
- packages/slate/test/changes/at-current-range/set-block/with-is-void.js
- packages/slate/test/changes/at-current-range/set-inline/across-inlines.js
- packages/slate/test/changes/at-current-range/set-inline/data-only.js
- packages/slate/test/changes/at-current-range/set-inline/nested-inline.js
- packages/slate/test/changes/at-current-range/set-inline/single-inline-string-shorthand.js
- packages/slate/test/changes/at-current-range/set-inline/single-inline.js
- packages/slate/test/changes/at-current-range/set-inline/with-data-object.js
- packages/slate/test/changes/at-current-range/set-inline/with-data.js
- packages/slate/test/changes/at-current-range/set-inline/with-is-void.js
> Convert setBlock and setInline to plurals for more intuitive naming.

- package.json
- support/rollup/factory.js
- support/webpack/config.js
- yarn.lock
Currently when an error happens, the console log looks like this:
Note the `slate.es.js:3166` on the right. Not too bad, it's the unminified ES build of Slate so we can read it pretty well and see what's going on. But it's all of Slate rolled up together, so it takes some hunting to figure out which original source file it came from. Also, if you click on the source, it looks like this:
which isn't exactly what the source looks like -- it's the source after it's been run through babel (so for example we get the `key/value` thing instead of an ES6 class).
There's a webpack loader, [source-map-loader](https://github.com/webpack-contrib/source-map-loader), which can help us do better. It consumes any sourcemaps in your "source" JS (in our case, the built `slate.es.js`) and rolls them …
> Use source-map-loader for more fine-grained sourcemaps.

- packages/slate-html-serializer/src/index.js
Get rid of "Each child in an array or iterator should have a unique "key" prop" warning when serializing with html-serializer.
> Add key prop to <br /> elements in html-serializer

- Readme.md
Just fixed the link to the auto-markdown example in the readme file.
> Fix link to auto-markdown example

- examples/check-lists/index.js
The check list example is a very important example for me to understand how to handle similar scenarios. So even it's already working as this example itself is not read-only, I think it still worth pointing out we may need to have the value of `contentEditable` accordingly to the `readOnly` property.
> Handle readOnly inside contentEditable check list

- packages/slate/src/constants/core-schema-rules.js
- packages/slate/test/schema/core/preserve-inline-with-empty-void.js
- packages/slate/test/schema/core/remove-nested-empty-inline.js
This PR attempts to fix 2 problems related to normalization of empty inlines:
1) [Nested empty inlines](https://github.com/urugator/slate/commit/64e84a14dfc8628c5ec52f22286742d63136de2c) not being removed  by normalization.
2) Since `0.33.0` void nodes can contain empty string `''`. This means that `inline.text === ''` is no longer a valid indicator of "emptiness". 
Consider: `<a><void/></a>` then `a.text === ''` , but `<a>` isn't actually empty and shouldn't be removed by normalization. This PR [changes the way](https://github.com/urugator/slate/commit/ddfb71f68f57a04e057ac00bb4daf6d3b31cb32e) how empty inlines are detected.
> Fix normalize empty inline

- docs/walkthroughs/saving-and-loading-html-content.md
- examples/paste-html/index.js
It just switches the `!=` to `==`, thus removing an empty `return` for the default return in case the `if` is not matched, looks friendlier, easier to read, less confusion.
> Make serialize/deserialize dev friendlier

- packages/slate/benchmark/models/from-json-big.js
- packages/slate/src/changes/with-schema.js
- packages/slate/src/models/node.js
- packages/slate/src/models/text.js
- packages/slate/test/schema/core/remove-empty-inline.js
I see @czechdave  say that normalization potentially slows down the Value.fromJSON; And I think perhaps it is a result from `normalizeKeys.includes`, a O(childNodes^2) comparison.  
This PR take advantage of cache and validate to ensure speed up normalization.
I am not confident about the benchmark running on my laptop.  Could anyone help me rerun the benchmark in their own computer?
```
benchmarks
html-serializer
deserialize
8.98 → 11.02 ops/sec
serialize
1057.71 → 1185.42 ops/sec
plain-serializer
deserialize
553.52 → 536.36 ops/sec
serialize
9107.18 → 9525.40 ops/sec
rendering
normal
111.93 → 126.17 ops/sec
changes
delete-backward
105548.40 → 144896.70 ops/sec (37% faster)
delete-forward
19318.61 → 30794.16 ops/sec (59% faster)
insert-text-by-key-multiple
85.57 → 97.89 ops/sec …
```
> Perhaps faster normalization: Never visit a descendant twice in normalizaton

- packages/slate-react/src/components/content.js
- packages/slate-react/src/plugins/before.js
We mirrored the fix in PR #1278 (meant for #1277) but for drop event.
This fixed an issue I faced with Slate swallowing drop event, kind of breaking compatibility with react-dnd.
/cc @AlbertHilb
> Don't stop propagation of drop event

- packages/slate-react/src/utils/find-dom-point.js
Adds remaining fix in PR #1400, as the null `char` possibility was taken care of.
Based on this comment: https://github.com/ianstormtaylor/slate/pull/1400/files#r151273901
> fix: ensure that offset is positive in findDomRange

- packages/slate-html-serializer/src/index.js
- packages/slate-html-serializer/test/serialize/null-rule.js
Sometimes, I have nodes that only make sense temporarily, so it doesn't make sense to serialize them. Following the pattern in React, explicitly returning `null` from a serialization rule should result in that node (and its children) not making it into the serialized document.
> Allow null return values, which will skip serializing that node

- packages/slate/src/changes/at-range.js
`insertTextAtRange` normalize the parent of startText, regardless of where the endText is.  (https://github.com/ianstormtaylor/slate/issues/1657) . This PR fixes the normalize range to normalize all affected nodes.
> Fix normalize range of the insertTextAtRange

- docs/guides/schemas.md
Just two simple fixes I noticed
before: ```
after: ```js
> add missing ```js instead of ``` on two code blocks

- packages/slate/src/utils/memoize.js
We are facing heap memory errors due to memoization taking more and more space. We are paying close attention to the progress made on that side and will be investing in the efforts as well. In the meantime, and as long as the issues are not fixed for good, it would be great to be able to opt-out of memoization.
> Make cache management available in non-dev environment

- packages/slate-react/src/utils/clone-fragment.js
Currently when multiple instances of `<Editor />` are on one page `onCopy` silently fails for all but the first instance in the DOM. This PR makes the `cloneFragment` function use the DOM node of the editor instance it's being triggered in which solves this issue.
(Issue #1722)
> Fix cloneFragment to work with multiple Editor instances

- examples/rich-text/index.js
- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/editor.js
- packages/slate-react/src/plugins/after.js
Close: https://github.com/ianstormtaylor/slate/issues/1669
Currently, Editor will cache the value which is passed from outside
https://github.com/ianstormtaylor/slate/blob/4346ad0e3f4a956e40a71f3cfd36682be6f90f4a/packages/slate-react/src/components/editor.js#L92
And then flush it when mount
https://github.com/ianstormtaylor/slate/blob/4346ad0e3f4a956e40a71f3cfd36682be6f90f4a/packages/slate-react/src/components/editor.js#L152
This will make any changes between Editor's initialization and componentDidMount lost. Such as `.focus` in Content's componentDidMount
https://github.com/ianstormtaylor/slate/blob/4346ad0e3f4a956e40a71f3cfd36682be6f90f4a/packages/slate-react/src/components/content.js#L109-L111
> fix: Editor[autoFocus] should work, close: #1669

- packages/slate-react/src/constants/hotkeys.js
Close: #1709 
On Mac, both of `shift+option+backspace` and `option+backspace` are *delete word backward*.
> fix: add missing hotkey for delete word backward, close: #1709

- docs/reference/slate/schema.md
`switch` operator was wrapped around `case` statements
> Fixed syntax mismatch at normalize method

- packages/slate/src/models/node.js
Ref: https://github.com/ianstormtaylor/slate/issues/1768
When we try to paste something into editor, the call stack:
```bash
plugin.onPaste => change.insertFragment => change. insertFragmentAtRange => node.mapDescendants
```
We need `node.mapDescendants` to re-generate keys. But the implementation of `node.mapDescendants` is extremely slow:
https://github.com/ianstormtaylor/slate/blob/a943eada8534ccdff05a770ad84ac599bd7b3682/packages/slate/src/models/node.js#L1854-L1868
If we paste a long list, the algorithm complexity will be almost O(n^2), for we need to `.forEach` n nodes and `.indexOf` n nodes.
> refactor: remove useless .indexOf to improve perf

- packages/slate-react/src/components/void.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Close: https://github.com/ianstormtaylor/slate/issues/1639
In Slate, we render void node as `contentEditable=false`, it works fine under most circumstances. 
However, if the void node is the first child of Editor, the behavior of selection will be broken, e.g. the void node will not be select when we try to select all.
So, I just make void node's wrapper `contentEditable=true`, and make its content `contentEditable=false`, and then everything works fine.
> fix: make void node selectable for edge case, close: #1639

- packages/slate-react/src/components/content.js
- packages/slate-react/src/plugins/before.js
fixes #1708 
fixes #1710 
**edit**: looks like it fixes #879 too
i've removed the tmp.key solution from content.js, because i think it isn't necessary anymore (the before.js > onCompositionStart/End handler triggers the force re-render by calling setState() when `isComposing` changed)
**edit**: I'm not a regular IME user, it would be great if someone could test it in case I introduced new issues with IME input handling
> IME - remove extra force re-renders on onCompositionStart/End

- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/insert-fragment/hanging-selection-single-block.js
We cannot paste on the hanging selection because deleteAtRange removes the startKey 
Use range.collapseToEnd() if startKey does not exists.
> Fix hanging selection paste in insertFragmentAtRange

- docs/guides/rendering.md
- docs/walkthroughs/saving-and-loading-html-content.md
- docs/walkthroughs/using-plugins.md
- examples/code-highlighting/index.js
- examples/hovering-menu/index.js
- examples/huge-document/index.js
- examples/markdown-preview/index.js
- examples/paste-html/index.js
- examples/rich-text/index.js
- examples/search-highlighting/index.js
- examples/syncing-operations/index.js
- examples/tables/index.js
- packages/slate-react/src/components/leaf.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/test/rendering/fixtures/custom-decorator.js
- packages/slate-react/test/rendering/fixtures/custom-mark.js
I find there is a solution in draft.js by https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorTextNode.react.js#L36
which is to add `data-*` in each layer of marks
This PR fixes the slate spellcheck problem in the same way.
After this fix, renderMark should have props.attributes to append `data-text:true`
Cheers,
Jinxuan Zhu
> Fix spell check bug

- packages/slate/src/changes/at-current-range.js
- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/split-block/with-delete-hanging-selection.js
- packages/slate/test/changes/at-current-range/split-block/with-marks.js
With hanging selection, splitBlock cannot find startKey.
split and then delete.
> Fix splitBlock bug with hanging selection

- packages/slate/src/changes/at-current-range.js
- packages/slate/test/changes/at-current-range/delete-forward/start-text-middle-inline.js
Problem:
We cannot see a cursor blink after delete hanging selection with backspace.
Before fix:
After fix:
> Ensure cursor is shown after delete hanging selection

- packages/slate/src/changes/with-schema.js
`normalizeNodeByKey` normalize all ancestors of the changed node.  However, an ancestor can by removed by `unwrapNodeByKey`, resulting an error in normalization.
This PR ensures that a `ancestor` is `normalized` when and only when it exists.
> Fix a bug in normalizeNodeByKey

- packages/slate/src/changes/at-range.js
Closes #917
Closes #1364 
According to #639, for now when inserting fragment, Slate tries to merge first block node into the block at cursor position. This is great if the fragment contains multi 'flat' blocks, while with a case that we insert one root block with multi child blocks (e.g. table), it will change the nested structure of the fragment.
This can be optimized with the detection of *single nested block*, and fallback to `insertBlockAtRange` in this case, which can be pretty straightforward.
For the table case, `firstBlock` and `lastBlock` are different table cells, so they are naturally different nodes. If the fragment has only one child but its `firstBlock` and `lastBlock` are different, we can confirm that the fragment is consist of one nested block.
As for test cases, I found …
> Limit melding behavior in `insertFragmentAtRange`

- docs/reference/slate/change.md
Okay, sorry this is a little poor; however, there are some things I'm still not understanding like
- why is {save: false} required
- In the code, I can see it calls Value.createProperties but Value.createProperties is not documented so I can't refer to it.
> Update change.md to include setValue

- packages/slate-react/src/components/void.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
As stated in https://github.com/ianstormtaylor/slate/issues/1726, having the `draggable` attribute set on the containers of void nodes can be a bit cumbersome when e.g. integrating with third party libs. This PR simply removes that attribute. I'm thinking it should be easy enough for people needing this to just add it to the actual nodes instead. 
As for the examples, DnD still works in the image example since the `<img>` element is draggable. Emojis though, are no longer draggable in the emojis example. I've opted not to add the `draggable` attribute to the emoji nodes since neither the dragging nor the dropping currently work properly (not sure it ever did?). For reference, this is what the dragging looks like before this PR:
> Remove draggable attribute from void nodes

- examples/rich-text/index.js
Just a small fix to the rich text editor example - when you use the numbered list/unordered list block level buttons, then focus within the block, the buttons were not previously properly reflecting an active state.
This is outlined in https://github.com/ianstormtaylor/slate/issues/1800
Thanks! Digging Slate so far.
> [examples] fix rich text editor active block logic

- packages/slate-react/src/components/content.js
spellCheck was disabled on `firefox` due to some compatibility issues. The comment for the compat sounds to be the same problem as what happened to `safari` and `chrome` on the most recent released of the browser that is fixed by https://github.com/ianstormtaylor/slate/pull/1753 therefore this PR is to remove the IS_FIREFOX check for disabling spellCheck by force
> remove spellcheck force disable on firefox

- packages/slate-react/src/components/void.js
#1731  causes an error in `yarn lint`
> Fix lint problem caused by #1731

- packages/slate-html-serializer/src/index.js
- packages/slate-html-serializer/test/deserialize/mark-void-inline.js
- packages/slate-html-serializer/test/helpers/h.js
Fix the bug when a nested in mark node a "void" inline node is the cause of error in the applyMark method because always trying to get children nodes without any checking.
For example, if we copy text from MS Word/Pages, HTML in clipboard will look like `<strong>first line<br/>second line</strong>`. Probably, break line(as well as `image`) node will be a void inline node without children and it'll break deserializer in this case.
I added test case `mark-void-inline.js` and new inline type `linebreak` in helpers.
> Fix slate-html-serializer: applyMark

- packages/slate-react/src/components/content.js
- packages/slate-react/src/utils/clone-fragment.js
- packages/slate-react/src/utils/remove-all-ranges.js
resolves #1824 by adding a compatibility helper function.
> fix: prevent IE11 from throwing if selection contains tables

- packages/slate-react/src/utils/get-event-range.js
Fixing [a bug](https://github.com/ianstormtaylor/slate/pull/1838#issuecomment-389915570):
When dropping something onto the first node's top part, when that node is void, we currently try to return the previous text node's range. This text node doesn't exist, and results in an error being thrown. Now we instead try to return the next text node's range. And if that doesn't exist, we return null (unless you have a better idea?).
> Fix invalid ranges in getEventRange

- packages/slate-react/src/utils/clone-fragment.js
better to avoid innerText https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Differences_from_innerText
Fixes: #
Reviewers: @
> avoid innerText

- examples/tables/index.js
bug; In the table-cell example, users cannot insert at the beginning of the cell.
Fix: https://github.com/ianstormtaylor/slate/issues/1571
People can insert in the start of the cell
Only blocks enter, backspace and delete at the beginning of the cell
Fixes: #1571
Reviewers: @amitm2
> Enable insert in the start of table cell

- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/insert-text/expanded-with-mark.js
Fixing a bug
previously the *PERF* normalization check isn't checking the right thing and also text that has marks that potentially needs to be normalized due to schema isn't normalized as well.This change is basically fix the *PERF* check and putting the correct normalization flag when needed.
Fixes: #1792 
> InsertTextAtRange normalize

- packages/slate-hyperscript/src/index.js
- packages/slate-hyperscript/test/default/perserve-keys-in-right-text.js
- packages/slate-hyperscript/test/index.js
Fix a bug;
For example, the following hyper-script 
```
<block>
"cat"
<inline/>
<text key="a">is cute</text>
</block>
```
will produce result like
```<block>
<text key="a">"cat"</text>
<inline/>
<text key="a">is cute</text>
</block>
```
Fix that bug
> Fix a hyperscript bug in perserving text-key

- packages/slate-react/src/utils/clone-fragment.js
Fixing a bug.
I was previously using the natively selected text when putting content into the `plain/text` register. That's problematic though since that text can contain zero width space characters. Since we already clean those up in our "dummy div", I just use the `textContent` of that div instead.
> Use cleaned up text content when copying into plain/text

- packages/slate-react/src/components/void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
fixing cursor being rendered on an inline void block where you won't be able to type anything inside
cursor is not rendered on an inline void block
adding `contentEditable={false}` on inline void node only. Previously this was the case for both block and inline void. It had problem mentioned in #1639 that was fixed on #1734 but introduced unnecessary cursor on an inline void. as this only do `contentEditable={false}` only on inline void, issue from #1639 is not there as well 👍 
a check from @benjycui would be great to make sure that #1639 issue is not reggressed
Fixes: #
Reviewers: @benjycui
> Inline Void block cursor

- packages/slate/src/models/stack.js
feature
The old stack render use slice().reverse(), which costs time creating new array and reverse it.   This PR use reduceRight instead.
> Perhaps Faster stack

- docs/guides/data-model.md
- docs/guides/schemas.md
- docs/reference/slate-react/core-plugins.md
- docs/reference/slate-react/editor.md
- docs/reference/slate/schema.md
- docs/walkthroughs/saving-and-loading-html-content.md
- docs/walkthroughs/saving-to-a-database.md
- docs/walkthroughs/using-plugins.md
Only docs changes - I read through a handful of the docs and made a few notes when things were kinda strangely worded or comma usage was off. Hope this is okay! Feel free to edit to undo anything you don't agree with.
> [docs] A handful of grammar nits in the docs

- docs/reference/slate/change.md
Just adding a new method into the docs and including some performance caveats, as mentioned in the issue discussion on https://github.com/ianstormtaylor/slate/issues/1833
Fixes: #1833
> [docs] add Change.normalize into the docs, add some caveats about perf

- packages/slate-react/src/utils/get-event-transfer.js
Fixing a bug.
Fixing the issue where dataTransfer or clipboardData are not populated in IE 11 under event.NativeEvent. Instead, if we are using IE11, use the base event object which contains a valid dataTransfer/clipboardData object.
Adding to the `event.nativeEvent` check in `getEventTransfer.js` to prevent reassigning `event` with `nativeEvent` in IE11.
Fixes: #897
> Fix issue with pasting in IE11

- packages/slate-react/src/constants/plugin-props.js
Fixing a bug
Previously, the `renderEditor` prop was only applied when defined on a plugin, not when it was passed as a prop to the top-level Slate Editor component. Now, the `renderEditor` prop will be invoked.
There was just a whitelist of plugin props that gets applied to the Editor component, `renderEditor` needed to be on the list
Fixes: #1841
> [slate-react] Pass renderEditor prop through into editor plugin

- packages/slate/src/models/text.js
fixing a bug
only last decorations of leaves are getting applied
All decorations of leaves are getting applied properly
Previously `getLeaves` of text only applied the last decoration of each leaves as on every single loop it reapplied decorations to the original leaves instead of the updated leaves
Fixes: #
Reviewers: @zhujinxuan @ianstormtaylor
> fix decoration rendering

- packages/slate/src/models/text.js
- packages/slate/test/models/text/delete/inside-a-leaf/delete-a-char-with-mark.js
fixing a _bug_
text with mark of length 1 get removed properly on deletion
previously, the `searchLeafAtOffset` got the wrong start point therefore returning previous leaves on leaves with length === 1
Fixes: https://github.com/ianstormtaylor/slate/issues/1916
Reviewers: @zhujinxuan
> fix removeText with Mark of length 1

- docs/reference/slate/change.md
the change() function doesn't exist on a change and given the context setValue() is probably the function that was meant.
> Fix typo in Docs

- docs/reference/slate/change.md
- packages/slate/src/changes/at-current-range.js
- packages/slate/test/changes/at-current-range/replace-mark/across-blocks.js
- packages/slate/test/changes/at-current-range/replace-mark/across-inlines.js
- packages/slate/test/changes/at-current-range/replace-mark/collapsed-selection.js
- packages/slate/test/changes/at-current-range/replace-mark/existing-marks.js
- packages/slate/test/changes/at-current-range/replace-mark/first-character.js
- packages/slate/test/changes/at-current-range/replace-mark/last-character.js
- packages/slate/test/changes/at-current-range/replace-mark/middle-character.js
- packages/slate/test/changes/at-current-range/replace-mark/whole-word.js
- packages/slate/test/changes/at-current-range/replace-mark/with-mark-object.js
- packages/slate/test/changes/at-current-range/replace-mark/with-plain-object.js
Instead of having to do:
```
change.removeMark(oldMark) && change.addMark(newMark)
```
one can do:
```
change.replaceMark(oldMark, newMark)
```
Calls the underlying removeMark && addMark instance methods
Fixes: #1903
> [core/models] add replaceMark method on Change, tests, docs

- .eslintrc
- packages/slate-react/src/utils/clone-fragment.js
bug
Previously we have to disable padding-lines rule when
```
if (...) {
..
}
;[].forEach((x) => {
...
})
```
becuase `;` is considered an empty block.  This PR fixes that problem
Fixes: #
Reviewers: @
> Fix a linter bug in a semi-colon case

- packages/slate-react/src/plugins/after.js
bug
Drag and drop works again.
This bug exists since : [Removed early return in onDragOver](https://github.com/ianstormtaylor/slate/commit/4712e64c308e68895f2601b5572b367aec2c4001). This commit removed the _return true_ that was stopping the call of `onDragOver` for the plugins stack. Since now the after plugin `onDragOver` is called, the internal dragging flag (`isInternallyDragging`) is reset to null which prevents the `onDrop` handler to remove the selection when it's an internal drag operation.
Fixes: #1871
> fix(DragAndDrop): isDraggingInternally should not be reset by the onDragOver handler

- packages/slate-react/src/utils/set-event-transfer.js
bug
While dragging some text or a node, it displays the caret where the drop will happen.
1. Go to the rich text example
2. Select words/sentences and move your selection somewhere else in the same slate editor
3. While dragging it, you'll see the "drop point" thanks to a caret
I suppose that Safari does not like to have a value for _application/x-slate-fragment_ in _dataTransfer_ and no _text_ value
Fixes: no issues found
> fix(Safari): Set a text value in dataTransfer to have the cursor on Safari when dragging a text node

- docs/reference/slate/schema.md
Hey, firstly thanks for creating and maintaining Slate! Love the concepts behind it as they make creating non-standard editors a breeze.
When working with Schema I found a part where docs do not reflect the actual code. Schema rule's property `marks` does not validate when provided with list of types, but needs list of objects with `type` property as it is apparent [from the code](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L306) and [tests](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/test/schema/custom/node-mark-valid-default.js#L8)
> Update schema rule's marks property documentation

- docs/reference/slate-simulator/index.md
Acording to https://github.com/ianstormtaylor/slate/blob/master/packages/slate-simulator/src/index.js onPaste event is suported by slate-simulator. Tested locally and the onPaste function of plugins gets called if simulator.paste() is called.
> Added missing paste event handler in slate-simulator docs

- packages/slate/src/changes/at-current-range.js
Fixing a bug introduced in https://github.com/GitbookIO/slate/commit/f07fc92f2e31a355a91f19ca080c2e380f883dae
In production, we have tracked this error several times already.
```
TypeError: Cannot read property 'object' of undefined
at getLast(./node_modules/slate/lib/slate.es.js:1756:1)
at apply(./node_modules/slate/lib/slate.es.js:1208:1)
at apply(./node_modules/slate/lib/slate.es.js:1687:1)
at collapseToEndOf(./node_modules/slate/lib/slate.es.js:1733:1)
at apply(./node_modules/slate/lib/slate.es.js:6167:1)
at call(./node_modules/slate/lib/slate.es.js:13116:1)
at insertFragment(./node_modules/slate/lib/slate.es.js:13220:1)
at apply(./node_modules/slate-react/lib/slate-react.es.js:3191:1)
at run(./node_modules/slate/lib/slate.es.js:9592:1)
at …
```
> Fix insertFragment: undefined newText

- packages/slate/src/changes/at-range.js
fixing a recent bug that slipped in during #1875 
No error is thrown.
> add null-guard for insertTextAtRange when marks is undefined

- docs/general/plugins.md
Following up https://github.com/ianstormtaylor/slate/pull/1933, I improved the library code quality and added tests.
The plugin repo: https://github.com/enzoferey/slate-instant-replace
Also added a direct link to search for slate plugins on NPM and Yarn as suggested in the comments.
> Added plugin to docs and direct links to NPM and Yarn

- docs/reference/slate-simulator/index.md
- packages/slate-simulator/src/index.js
Adding a new feature.
Now `slate-simulator` supports `onKeyUp` event.
> Added onKeyUp event suppor to slate-simulator and updated docs.

- packages/slate-react/src/plugins/before.js
- packages/slate-react/src/utils/get-event-range.js
Fixing a bug.
You can now drag-and-drop files into an editor that supports it, without console errors or uncaught exceptions.
There were three problems preventing drag-and-drop in IE:
* IE [doesn't consider contentEditables as inputs](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/913982/) when it comes to calling `onDrop`. So you have to `preventDefault` in `onDragOver`, which prevents the cursor from being displayed. Turns out _this is fine_, because:
* You can only get a cursor position from a point with `createTextRange` and `moveToPoint`. Also, `moveToPoint` raises an error if it's called during a dropEvent. So you wouldn't be able to drop into a specific point, even if you wanted to.
* Setting `dropEffect` causes an `unspecified error`.
> Fix drag-and-drop issues in IE11

- packages/slate/src/models/value.js
Arguably adding a feature
`Value.fromJSON` can rebuild the selection `anchorKey` and `focusKey` from `anchorPath` and `focusPath` respectively if they were dropped at `Value.toJSON`
Uses existing code from https://github.com/ianstormtaylor/slate/blob/e4ff1972d79911baf8a6aed683765b66107b09a4/packages/slate/src/operations/apply.js#L446-L454
* [*] The new code matches the existing patterns and styles.
* [*] The tests pass with `yarn test`.
* [*] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [*] The relevant examples still work. (Run examples with `yarn watch`.)
Fixes: #1978
> rebuild selection from anchorPath and focusPath if keys were dropped

- packages/slate/test/changes/at-current-range/add-marks/across-marks.js
bug
add-marks/across-marks.js misses a `focus` in hyperscript
Add it back
Fixes: #
Reviewers: @
> Fix a missing focus in test

- docs/reference/slate-simulator/index.md
Following up https://github.com/ianstormtaylor/slate/pull/1942#issuecomment-401518963, I improved the docs adding a DataTransfer mockup class and adding some details about core plugins to make it easier to understand their role for beginners.
> Improved slate-simulator docs.

- packages/slate-react/src/constants/event-handlers.js
Right clicks aren't handled by onClick in a content-editable component. So we need access to a onContextMenu handler to handle these events properly.
My use case is to be able to open a context menu with actions when the user right-clicks a specific inline node.
Let me know if you think we need tests for this, but I made the change in GitHub since it was so small.
> Allow onContextMenu event handler

- packages/slate/src/models/history.js
- packages/slate/src/models/value.js
Arguably adding a feature
`Value.fromJSON` can now restore `history` from the given object
Trivial
Fixes: #1977
> allow fromJSON to restore history

- packages/slate/src/changes/at-range.js
- packages/slate/test/changes/at-current-range/insert-block/is-inline-void.js
When inserting a block, we shouldn't split void inlines -- otherwise,
they're duplicated. Instead, move the insert to either before or after
the void node.
Fixing a bug.
When inserting a block while a void inline is selected, the block will be inserted before or after the block, rather than splitting the void node.
> Move `insertBlock`s outside of void inlines

- package.json
- packages/slate-dev-logger/src/index.js
feature
Calling deprecated interface during development & test mode will throw an Error.  This ensures that, after each interface change, all tested functions  in `slate/packages` are converted from old interface to new interface.
Fixes: #
Reviewers: @
> Ensure no deprecate exists in slate-core development

- packages/slate/src/models/node.js
- packages/slate/test/models/node/get-fragment-at-range.js
Bug.
Fixes `Node.getFragmentAtRange` to use the proper argument signature when calling `Node.splitNode`, and refactors it to use paths for all of its logic.
Fixes: #2009
> fix getFragmentAtRange to use paths properly

- docs/walkthroughs/using-the-bundled-source.md
Improving documentation.
Example in documentation was lacking react-slate which in reality is needed in order to successfully use Slate with React.
Fixes: #
Reviewers: @
> Add slate-react to the bundled source guide

- docs/guides/changes.md
Hey,
just started working with Slate.js, so far it looks pretty amazing! 🎉 ❤️ 
I think I found a bug in the docs.
In the [guides/changes](https://docs.slatejs.org/guides/changes) it says:
```jsx
render() {
;<img {...this.props.attributes} onClick={this.onClick} />
}
```
I suppose that the leading `;` is not intended so I attached a fix where I removed it.
Hope that's alright.
Thanks!
---
Fixes a bug.
Doesn't change the behaviour, just fixes a typo in the docs.
See above.
I did not change the code.
Hm I don't think so, no.
> Docs: Remove leading semicolon in code snippet

- examples/app.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/utils/find-range.js
- packages/slate/src/changes/on-selection.js
Bug.
Fixes selection operations from being duplicated.
Previously the selection properties were compared by reference, but paths are immutable `List` objects, which always show up as having changed, resulting in extra selection operations that without any real changes. We now use `Immutable.is` to remove those duplicates, fixing the undo history stack.
Fixes: #2006
> fix selection operations being duplicated

- docs/guides/rendering.md
@ianstormtaylor found another typo, see below.
~If you want you can keep this PR open (in case I find another typo) and I'll ping you(/whoever else) when I am done reading the docs?~ **edit** nvm think I read all articles
Really loving the docs so far and looking forward to working with Slate! 👏 👍 ⚡️ 
---
In [guides/rendering#Placeholders](https://docs.slatejs.org/guides/rendering#placeholders):
> That will render a simple placeholder element inside all of **~the~ your** caption blocks until someone decides to write in a caption.
---
Fixing a bug/typo in the docs.
This fixes a typo in the docs.
See above.
No.
No, I don't think so.
> Docs: Fix typo in guides/rendering

- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/utils/find-range.js
- packages/slate-react/src/utils/get-event-range.js
- packages/slate/src/changes/by-path.js
- packages/slate/src/changes/on-selection.js
- packages/slate/src/models/document.js
- packages/slate/src/models/node.js
- packages/slate/src/models/value.js
Improvement.
Adds a `Node.createRange` method for more easily creating ranges that are normalized to the current document. As well as a `Node.resolveRange` lower-level method for just doing the normalization on an existing range.
Later we can deprecate `Range.normalize` since it should be on the node instead.
Fixes: #2011
> add `Node.createRange` for range resolution

- packages/slate/src/models/range.js
Improvement.
This changes the `anchorOffset` and `focusOffset` of ranges to default to `null` instead of `0` as they did previously. This shouldn't affect people for almost any use cases, but it makes it more clear when a point is "unset".
Fixes: #1162
> fix range offset defaults to be `null`

- packages/slate-hyperscript/src/index.js
- packages/slate-hyperscript/test/fixtures/cursor-across-block.js
- packages/slate-hyperscript/test/fixtures/cursor-across-blocks-and-inlines.js
- packages/slate-hyperscript/test/fixtures/cursor-across-blocks-end.js
- packages/slate-hyperscript/test/fixtures/cursor-across-blocks-middle.js
- packages/slate-hyperscript/test/fixtures/cursor-across-blocks-start.js
- packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-end.js
- packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-middle.js
- packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-start.js
- packages/slate-hyperscript/test/fixtures/cursor-block-end.js
- packages/slate-hyperscript/test/fixtures/cursor-block-middle.js
- packages/slate-hyperscript/test/fixtures/cursor-block-start.js
- packages/slate-hyperscript/test/fixtures/cursor-custom-block-middle.js
- packages/slate-hyperscript/test/fixtures/cursor-inline.js
- packages/slate-hyperscript/test/fixtures/decoration.js
- packages/slate-hyperscript/test/fixtures/selection.js
- packages/slate/src/changes/at-range.js
- packages/slate/src/models/operation.js
- packages/slate/src/models/range.js
- packages/slate/src/models/value.js
- packages/slate/src/utils/path-utils.js
- packages/slate/test/serializers/raw/serialize/preserve-selection-and-keys.js
- packages/slate/test/serializers/raw/serialize/preserve-selection.js
Improvement.
The `isBackward` property is no longer a static property that can be set on `Range` objects, and is instead automatically derived from the range's paths and offsets. This is one less thing to worry about keeping in sync in the library, and really shouldn't be a user-level concern anyways.
Fixes: #2013
> change `isBackward` to be computed from paths

- packages/slate-react/src/utils/clone-fragment.js
This addresses https://github.com/ianstormtaylor/slate/issues/1932
I do not believe this will break any existing functionality. In my testing I could not find any issues with this solution so far.
> Adds Unicode LF character to line endings for clipboard plaintext

- packages/slate-hotkeys/Changelog.md
- packages/slate-hotkeys/package.json
- packages/slate-hotkeys/src/index.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
- yarn.lock
Bug & debt.
Refactor's the `slate-hotkeys` package to make it easier to reason about, and fix an issue that was present in the delete hotkeys on macs.
Use a simpler map of hotkeys instead of writing functions inline. This is possible thanks to the new version of `is-hotkey` with optional hotkeys and multiple hotkeys features.
Fixes: #1887
Fixes: #1888
Fixes: #1983
> refactor slate-hotkeys, fix deleting at start of block

- packages/slate-dev-environment/src/index.js
- packages/slate-react/src/components/content.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
Debt.
Moves the native `beforeinput` event handling into the `Before/AfterPlugin` and out of the `<Content>` component, so that all event handling remains in plugins.
Fixes: #2059
> refactor native beforeinput handling

- examples/app.js
- examples/input-tester/index.js
- examples/input-tester/value.json
- package.json
- yarn.lock
Example.
Adds a new example that is an input event logger, for more easily seeing which input/keyboard/selection events are firing when editing in a Slate editor.
> Add input tester example

- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
- packages/slate-react/src/utils/clone-fragment.js
feature
We are using dataTransfer for chrome, firefox and other modern browsers in clone-fragment.  Therefore, for these browsers, we do not need to call editor.change with `window.requestAnimation`.  
Calling `window.requestAnimation` sometimes makes the code hard to debug, and we cannot ensure there is no another React state change between `window.requestAnimation` in React v16 (as React.requestIdleCallback + queue are very unpredictable)
Fixes: #
Reviewers: @
> Do not use requestAnimation if DataTransfer is available

- Readme.md
- docs/Introduction.md
- examples/Readme.md
- examples/markdown-preview/index.js
- packages/slate-hyperscript/src/index.js
- packages/slate-hyperscript/test/decorations/across-blocks.js
- packages/slate-hyperscript/test/decorations/across-marks.js
- packages/slate-hyperscript/test/decorations/deep-anchors.js
- packages/slate-hyperscript/test/decorations/intersecting-marks.js
- packages/slate-hyperscript/test/decorations/multiple.js
- packages/slate-hyperscript/test/decorations/nested.js
- packages/slate-hyperscript/test/decorations/overlapping.js
- packages/slate-hyperscript/test/fixtures/decoration-across-blocks.js
- packages/slate-hyperscript/test/fixtures/decoration.js
- packages/slate/test/helpers/h.js
Debt.
`createHyperscript` takes an options object that now looks for the `decorations` property instead of the `decorators` property
Pretty straightforward rename of an option, then all of its uses and wherever the term decorators showed up in docs
Fixes: #1996
> [hyperscript] rename decorators option in params to decorations

- benchmark/slate-react/rendering/decoration.js
- benchmark/slate/changes/add-mark.js
- benchmark/slate/changes/insert-node-by-key.js
- benchmark/slate/changes/insert-text.js
- benchmark/slate/changes/normalize.js
- benchmark/slate/changes/split-block.js
- benchmark/slate/models/get-active-marks-at-range.js
- benchmark/slate/models/get-blocks-at-range.js
- benchmark/slate/models/get-inlines-at-range.js
- benchmark/slate/models/get-marks-at-range.js
- benchmark/slate/models/get-texts-at-range.js
bug
Fix key duplication warning and deprecation
Fixes: https://github.com/ianstormtaylor/slate/issues/2088 https://github.com/ianstormtaylor/slate/issues/2079
Reviewers: @
> Fix key duplication warning and deprecation in benchmark

- packages/slate/src/models/point.js
- packages/slate/src/models/range.js
- packages/slate/src/models/value.js
feature
Introduce `Range.updatePoints(Point => Point)` to make the code simpler.
We used to have `range.setPoints([anchor.doSomething, focus.doSomething])` that same point operation duplicated in setPoint.  This function mimics Immutable's update to reduce duplicated code.
Fixes: #
Reviewers: @
> Introduce Range.updatePoints

- packages/slate-html-serializer/src/index.js
This should fix `Unable to get property 'childNodes' of undefined or null reference` error in IE11 when using slate-html-serializer and deserializing an empty string (#1757, #1756).
The `defaultParseHtml` now returns an empty body element if the parsed body is null. 
I tested this in the latest Chrome, Firefox and Safari, and they all seemed to work similarly. If the html param was an empty string, `parseFromString` returned a document element, which had a body property which was an empty body element. In IE11 though the body property was null, which caused the undefined or null reference later.
> IE11 html serializer parser fix

- docs/guides/schemas.md
- examples/hovering-menu/index.js
- package.json
- packages/slate-react/src/components/leaf.js
- packages/slate-react/src/components/node.js
- packages/slate-react/src/plugins/after.js
- packages/slate-react/src/plugins/before.js
- packages/slate-react/src/utils/clone-fragment.js
- packages/slate-react/src/utils/get-event-range.js
- packages/slate/src/changes/at-range.js
- packages/slate/src/changes/on-selection.js
- packages/slate/src/models/block.js
- packages/slate/src/models/document.js
- packages/slate/src/models/inline.js
- packages/slate/src/models/node.js
- packages/slate/src/models/operation.js
- packages/slate/src/models/schema.js
- packages/slate/src/models/value.js
Improvement.
This deprecates the `node.isVoid` property in favor of using `schema.isVoid(node)`, which will allow us to remove the hardcoded "void" concept from the data model, and have it depend on the schema instead. 
This allows you to build different kinds of editors, with different void semantics, depending on your use case, without having this information hardcoded in the data itself. Even switching the `isVoid` semantics on the fly based on a user toggling a setting for example.
This is the first step, which just deprecates `node.isVoid`, and provides the new alternative of `schema.isVoid(node)`, while still using the `isVoid` value of nodes under the covers.
The next step is to change the logic to search the schema for real, and completely remove the `isVoid` value from nodes.
> deprecate isVoid and related properties/methods

- packages/slate-react/src/plugins/after.js
- packages/slate/src/changes/at-range.js
Fixing a bug
Creates a fragment EventTransfer instead of a node EventTransfer object. 
Previously only the direct node that was dragged was stored in the EventTransfer, now the complete fragment is, allowing for dragging of a selection with multiple blocks.
Fixes: #1850
Reviewers: @
> use fragment instead of node transfer type on drag

- Readme.md
Previous ".src" path no longer exists and throws 404.
No.
Fixes: 0
Reviewers: @
> Change source code url to be up-to-date

- packages/slate-react/src/components/content.js
Fixing a _bug_
In a recent change, handlers now only exist in `Content#handlers` and not directly on the instance itself. There were still a couple of places where they were being accessed directly from the instance for event listeners. This was causing some side effects in iOS.
More details in #2125 
Fixes: #2125 #2129 
Reviewers: @zhujinxuan @ianstormtaylor
> fix(content): use handlers that actually exist in event listeners

- examples/markdown-shortcuts/index.js
This got a bit mangled during find and replace in https://github.com/ericedem/slate/commit/08f270dc1b69074c876cd2022d7addb8ef5b5836
Fixing a bug
Markdown Shortcuts no longer throws an error
Fixes a misspelled method name.
Fixes: #2145 
Reviewers: @
> fix(markdown-shortcuts): moveFocusToStartOf -> moveFocusToStartOfNode

- packages/slate-react/src/components/content.js
Fixing a bug
This undoes a recent change https://github.com/ianstormtaylor/slate/pull/2131
Which hooked up `this.handlers.onNativeSelectionChange` to `'selectionchange'` as well as `this.handlers.onBeforeInput` to `'beforeinput'`.
It turns out that in order to fix the iOS issues, we only needed the change to `onBeforeInput`. The corect handler for `'selectionchange'` is the instance method `this.onNativeSelectionChange`. This broke a whole bunch of focus related issues.
I did double check that with this change, https://github.com/ianstormtaylor/slate/issues/2125 is still fixed.
Fixes: #2147
Reviewers: @ianstormtaylor @zhujinxuan
> fix(content): attach the right `onNativeSelectionChange`.

- docs/reference/slate/schema.md
- packages/slate/src/models/schema.js
- packages/slate/test/schema/custom/child-kind-invalid-function.js
- packages/slate/test/schema/custom/child-type-invalid-function.js
- packages/slate/test/schema/custom/first-child-kind-invalid-function.js
- packages/slate/test/schema/custom/first-child-type-invalid-function.js
- packages/slate/test/schema/custom/last-child-kind-invalid-function.js
- packages/slate/test/schema/custom/last-child-type-invalid-function.js
- packages/slate/test/schema/custom/next-kind-invalid-custom.js
- packages/slate/test/schema/custom/next-kind-invalid-default.js
- packages/slate/test/schema/custom/next-kind-invalid-function.js
- packages/slate/test/schema/custom/next-type-invalid-custom.js
- packages/slate/test/schema/custom/next-type-invalid-default.js
- packages/slate/test/schema/custom/next-type-invalid-function.js
- packages/slate/test/schema/custom/node-data-invalid-function.js
- packages/slate/test/schema/custom/node-mark-invalid-function.js
- packages/slate/test/schema/custom/node-object-invalid-function.js
- packages/slate/test/schema/custom/node-type-invalid-function.js
- packages/slate/test/schema/custom/parent-kind-invalid-function.js
- packages/slate/test/schema/custom/parent-type-invalid-function.js
- packages/slate/test/schema/custom/previous-kind-invalid-custom.js
- packages/slate/test/schema/custom/previous-kind-invalid-default.js
- packages/slate/test/schema/custom/previous-kind-invalid-function.js
- packages/slate/test/schema/custom/previous-type-invalid-custom.js
- packages/slate/test/schema/custom/previous-type-invalid-default.js
- packages/slate/test/schema/custom/previous-type-invalid-function.js
With this change we can now use validating functions inside schema's matching properties, at least for a few keys.
A few example:
```js
{
match: { /* something */ },
object: kind => kind !== 'text',
type: type => ['paragraph', 'image'].includes(type),
data: data => data.has('thing'),
marks: mark => mark.type === 'mention' && mark.data.has('userId'),
}
```
I also added documentation, specs, and default normalization on `next` and `previous` rules.
A more complex one now allowed by this change:
```js
{
// Merge two consecutives lists
match: { type: 'list' },
next: {
type: type => type !== 'list'
},
normalize: (change, error) => {
if (error.code === 'next_sibling_invalid_type') {
change.mergeNodeByKey(error.next);
}
},
}
```
Fixes: #2139
> Add support for validating functions inside schema's rules

- packages/slate-react/src/utils/get-event-range.js
Fixing deprecated function calls in ``slate-react`` (get-event-range.js).
> Fix deprecated function calls in slate-react

- docs/reference/slate/change.md
Fixing docs
`setOperationFlag()` actually accepts a `key` and a `value`.
https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/change.js#L161
> docs(change.md): correct `setOperationFlag()` signature

- packages/slate-react/src/components/content.js
Fixing a bug 
Content in slate-react will not crash if on componentDidMount if `window.getSelection()` returns null
`window.getSelection()` can sometimes return null (see https://bugzilla.mozilla.org/show_bug.cgi?id=827585). This change checks the return value of `window.getSelection()` before trying to use it.
Fixes: #2162
Reviewers: @
> Avoid crash in updateSelection() in editor when getSelection() is null

- examples/links/index.js
* Correctly use the selection
* check whether the user cancelled the prompt
* use `moveFocusBackward`
_bug_
Make links example work again after API changes, and add cancel handling for the prompt.
Fixes: #2164
> fix(example/links): a few fixes for the links example

- packages/slate-react/src/plugins/after.js
Fixing a bug where a deprecated call to ``move`` was made in the After Plugin (onDrop). Should be ``moveForward``
No new behaviour.
Fixes: (could not find any)
Reviewers: @
> Fix deprecated .move > .moveForward in the after plugin

- packages/slate-react/src/plugins/after.js
This is a bug fix.
https://jsfiddle.net/fj9dvhom/2040/
Here is a JSFiddle with a button that inserts some bold text, and then remove the bold from active marks. The bug is that the bold stays active:
The bug come from the fact that any `onSelect` event will clear the active marks from the selection. And in this case, an `onSelect` event is happening after the operation. Though the selection has not changed, this is something that can happen [as stated here](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L290-L294). The fix happens in the `onSelect` handling by the `AfterPlugin`, that was currently ignoring active marks.
---
I have checked that:
Reviewers: @uipoptart because it could be related to …
> Fix marks being cleared on selection events

- packages/slate-react/src/components/content.js
Fixing a bug
Not crashing in Firefox when clicking stepper arrows on number inputs (even outside of Slate itself) (#1819) and not crashing in embeds example (#843), and possibly providing a workaround for #1744.
This is a workaround for an issue with Firefox that causes `Restricted` nodes to throw on property access (e.g. `.nodeType`). I've tried to narrow the test to identify the particular situation as much as possible to avoid accidentally catching other errors that may happen here.
> Gracefully handle permission denied error in FF when checking for element.nodeType

- packages/slate-react/src/plugins/after.js
I improperly rebased my fix in https://github.com/ianstormtaylor/slate/pull/2158 and was setting `marks` on the old `Range` objects instead of the new `Selection` object.
> Actually fix marks being cleared on selection events

- .travis.yml
Right now code coverage results in a lot of false positives for failing builds. This makes it really difficult to tell at a glance whether PRs are passing / failing something more important like linting or tests.
Disabling for now until we can find a better approach.
debt
No more codecov in automated builds
Fixes: #2106 
Reviewers: @ianstormtaylor @zhujinxuan
> debt(codecov): disable code coverage in builds

- .nycrc
- .travis.yml
slate-react cannot be tested currently, so this PR limits the codecov covers the testable parts to avoid false failings.
Coverage only reports three packages. 
Fixes: #2106
Reviewers: @ianstormtaylor , @ericedem
> Codecov: Only test slate, slate-html-serializer and slate-plain-serializer

- packages/slate/src/interfaces/element.js
Previously, `decorateNode` would search the plugin stack for the first `decorateNode` handler that returned a value. With this change, it will call the `decorateNode` handler on every plugin in the stack and merge their results together.
The end result is that multiple plugins can provide `decorateNode` decorations to the same node.
cc @ianstormtaylor @zhujinxuan
> Merge decorations from multiple plugins

- packages/slate-react/src/components/content.js
fixing a bug
1. Click on a void inline node to select it
2. Copy (or cut), it will be placed on the clipboard.
The fix can be seen in the emoji demo where you can use command+c and x to copy an emoji after clicking on it. 
When a lone void inline node is selected copy and cut should behave consistently with what happens when a void inline node is selected along with other text. Prior to this commit, selecting a void node along with other text would cause it to be copied/cut. However, selecting a lone void inline would not permit copying. This change makes the behavior consistent.
`isInEditor` would return `false` for anything marked `contenteditable=false` causing void inline nodes to always return false. This change returns `true` when the `contenteditable=false` element has a parent …
> Normalize copying void inline nodes

- docs/general/resources.md
Now that Cake is coming out of invite only mode, figured it was a good time to add it as a product using Slate. :)
Link to https://www.cake.co/
> Update products to include Cake

- docs/reference/slate-react/plugins.md
Just a simple doc change: `onChange()` also receives the [editor as an argument](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugins/before.js#L106-L124).
> docs(plugins): update signature docs

- packages/slate-hyperscript/test/fixtures/cursor-across-blocks-and-inlines.js
- packages/slate/src/models/change.js
- packages/slate/src/utils/path-utils.js
Fix.
The dirty paths in a change are now transformed against incoming operations, such that they don't get out of sync as normalizations occur. This is a rough pass to get correctness and the bug fixed, and we can later optimize lots of the little details for performance.
Fixes: #2211
Fixes: #2215
Fixes: #2194
> Fix normalizing dirty paths

- packages/slate/src/models/text.js
- packages/slate/test/models/text/marks/get-active-marks/intersecting-marks-text.js
Fixes bug
Immutable OrderedSet is used instead of Set
Fixes: #2223
> fix activeMarks for intersecting marks text

- packages/slate/src/models/operation.js
fixing a bug
serializes the path for operations that have one instead of returning the immutable instance
Fixes: #
Reviewers: @
> serialize path as well in Operation.toJSON

- docs/walkthroughs/saving-and-loading-html-content.md
Fixes a borken link in the docs
Fixes: #
Reviewers: @
> [docs] Fixed broken HTML serializer link

- packages/slate/src/changes/on-selection.js
- packages/slate/src/models/change.js
- packages/slate/test/history/undo/remove-text.js
by using the options sent to the applyOperation method 
`change.applyOperation(
{
type: 'set_selection',
value,
properties: props,
selection: selection.toJSON(),
},
snapshot ? **{ skip: false, merge: false }** : {}
)`
`applyOperation(operation, options = {}) {
const { operations } = this
let { value } = this
let { history } = value
// Add in the current `value` in case the operation was serialized.
if (isPlainObject(operation)) {
operation = { ...operation, value }
}
operation = Operation.create(operation)
// Default options to the change-level flags, this allows for setting
// specific options for all of the operations of a given change.
let { merge, save } = **{ ...this.tmp, ...options }**
`
* [ x] The new code matches the existing patterns and styles.
* [x ] The tests pass with `yarn …
> Fix delete undo

- packages/slate-react/src/components/leaf.js
- packages/slate-react/test/rendering/fixtures/custom-block-blurred.js
- packages/slate-react/test/rendering/fixtures/custom-block-focused.js
- packages/slate-react/test/rendering/fixtures/custom-block-selected.js
- packages/slate-react/test/rendering/fixtures/custom-block-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline-multiple.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
- packages/slate-react/test/rendering/fixtures/custom-inline.js
- packages/slate-react/test/rendering/fixtures/default-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
- packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Bugfix
Regular "zero width whitspace" (200B) caused odd line-breaks/empty lines when it got inserted before an inline block that exceeded width of container (fe. long text without whitespaces). "Zero width no break whitespace" FEFF is similar 200B but doesn't trigger a line break.
See https://github.com/ianstormtaylor/slate/issues/2231 for more context.
Fixes: https://github.com/ianstormtaylor/slate/issues/2231
> Replace "zero width whitspace" with "zero width no break" character

- examples/plugins/word-count.js
FIx two Bugs in example.
1. Block break is not considered as word break in the old example
2. Continuous spaces are considered as words
Fixes: #
Reviewers: @
> Take Blocks as word break to fix word counting in example

- Contributing.md
I’m hoping to start making a few contributions myself and was checking this guide out, but noticed that the `✓ easy one` label hasn’t been used in a while and has no open issues.
Instead, we now recommend the `♥ help please` label as a source of issues to fix for potential contributors.
> Update ‘Submitting Pull Requests’ to refer to an active label

- packages/slate/src/commands/at-range.js
- packages/slate/test/changes/at-range/insert-text-at-range/non-matching-section-and-range.js
Fixing a bug.
The issue is describe in detail in #2209 and demonstrated by the test included here. But, basically, this makes `insertTextAtRange` insert text at the range specified instead of the current selection when the selection is elsewhere. Here was the original issue in action:
Instead of referencing the current selection to determine the key to use for text insertion, `insertTextAtRange` now preserves the path of the original block that may be deleted during the replacement of the range. If the block is deleted and keys change, the path should remain consistent. So, this change gets the key from the new block at that path, regardless of where the current selection is. (Previously, it tried to get the range start block from the current selection, which isn't always the same). …
> Fix insertTextAtRange selection

- packages/slate-plain-serializer/src/index.js
- packages/slate-plain-serializer/test/deserialize/custom-delimiter.js
- packages/slate-plain-serializer/test/serialize/custom-delimiter.js
It adds the option to specify a custom delimiter to the plain deserializer for more complex scenarios.
eg:
- A paragraph the accepts single new lines and every paragraph is delimited by two new line "\n"
- Support regexp(split) as a delimiter for more flexibility
Simply add a delimiter to the options passed to the slate-plain-serializer
Fixes: #
Reviewers: @ianstormtaylor 
This is a quick fix I did for my project, and I thought it would be a good addition to the project
> Add possibility to specify a custom delimiter to slate-plain-serializer

- examples/input-tester/value.json
Initial value in the input-tester example renders the bolded items as "bold".
This fixes the initial value so it reads correctly.
Current initial value:
Fixed:
> Fix bolded text in input-tester initial value

- docs/guides/commands-and-queries.md
- docs/reference/slate/plugins.md
- packages/slate/Changelog.md
This is just a documentation fix. After https://github.com/ianstormtaylor/slate/commit/bd24739411f4b5d7d6341d0e3aaa43e2e78df3a7 hit, docs weren't updated to show that queries take an `editor` object as the first argument.
eg:
```javascript
queries: {
getActiveListItem(editor) {
...
}
}
```
cc @ianstormtaylor for review
> Fix queries documentation to show editor argument

- docs/guides/commands-and-queries.md
The paragraph mentioned handle signature being `event, change, next` but the snippet had a signature with `event, change, editor`
Fixes: #
Reviewers: @
> Fixed KeyDown handler signature in code snippet

- packages/slate-react/src/utils/clone-fragment.js
Fixing a bug
Fixes the `cloneFragment` function to the intended purpose
According to the comments in the file and the diff, the intention was for `requestAnimationFrame` to only be used when the Clipboard API's `setData` method was either not available or lackluster (IE). 
The issue was introduced accidentally here (which is how I figured out what needed to be done): https://github.com/ianstormtaylor/slate/commit/dc95ad66a522e9d5c1626e65844f160834224696#diff-dfb9fbad6106fa548b8335a644d03e49L109
This was especially problematic in the `onCut` command, since the callback was being called twice in browsers with the necessary support.
Fixes: #2279
Reviewers: @zhujinxuan (since you made the change above)
> Fix cloneFragment conditional handling of clipboardData.setData

- package.json
- packages/slate-hotkeys/package.json
- packages/slate-react/src/plugins/after.js
- yarn.lock
_bug_
Fix behavior for <kbd>shift + left</kbd> and <kbd>shift + right</kbd>. Now they will correctly move forward / backward.
turns out that the hotkey `'left'` would also pick up with a modifier key `'shift+left'` so checking for `Hotkeys.isExtendForward()` needs to come before `Hotkeys.isMoveForward()` and it needs to short circuit with `return true`. Likewise for backward.
Fixes: #2307 
> fix: extend forward / backward

- packages/slate/src/controllers/change.js
- packages/slate/src/utils/path-utils.js
_bug_
Now on normalization, anywhere we were marking parent paths as dirty, we will now also mark all ancestors as dirty using the new `PathUtils.getAncestors()` function.
Fixes: #2312
Reviewers: @ianstormtaylor @Slapbox
> fix: use ancestors for dirt paths

- packages/slate-react/src/components/leaf.js
- packages/slate-react/test/rendering/fixtures/custom-block-blurred.js
- packages/slate-react/test/rendering/fixtures/custom-block-focused.js
- packages/slate-react/test/rendering/fixtures/custom-block-selected.js
- packages/slate-react/test/rendering/fixtures/custom-inline-void.js
- packages/slate-react/test/rendering/fixtures/empty-block.js
- packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Fixing more or less. 
Selected empty blocks now look selected as well
Adds a `<br />` inside the `<span data-slate-zero-width="n" />` after the zero-width no-break space
Other editors use `<br />` in those empty spaces. I had originally just replaced the `span` with the `br`, but on enter, it added the new line but the cursor didn't move. This fixes that oversight. And since that render branch is matches one specific case (when it's the last node in a block), it doesn't seem to have any additional side effects.
Fixes: #2275
Reviewers: @
> Use <br /> inside empty block so those appear selected

- examples/input-tester/index.js
- examples/input-tester/value.json
If an Input event with inputType `"insertReplacementText"` is received, the example crashes because `event.dataTransfer.get is not a function`
The correct API is `getData()`, not `get()`. Ref: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/getData
You can cause the exception by mis-spelling a word in the Input Tester with Safari, then using control-click (or right-click on a 2-button mouse) to correct the spelling.
> Fix exception in Input Tester example

- packages/slate-react/src/plugins/before.js
Fix 
Doesn't crash when compositions starts on expanded selection.
When composition starts and the current selection is not collapsed, the
second composition key-down would drop the text wrapping <spans> which
resulted on crash in content.updateSelection after composition ends
(because it cannot find <span> nodes in DOM). This is a workaround that
erases selection as soon as composition starts and preventing <spans>
to be dropped.
Note that composition is still not handled quite right in Slate - when composing, the caret should be at the end of composition rather that at start. I might look into that later.
Fixes: https://github.com/ianstormtaylor/slate/issues/1879
> Prevent crash when handling composition when selection is not collapsed

- packages/slate/test/commands/at-current-range/insert-fragment/end-inline.js
- packages/slate/test/commands/at-current-range/insert-fragment/middle-inline-fragment-inline.js
- packages/slate/test/commands/at-current-range/insert-fragment/start-inline.js
Previously, `start-inline` and `end-inline` included the cursor at the end of an inline, i.e.
```js
<paragraph>
<link>example<cursor /></link>
</paragraph>
```
Using Slate in a browser, it doesn’t seem possible to me to actually achieve this state: i.e. whenever the cursor is on either side of an inline such as a link, typing will not add text to that inline. (This is consistent with other editors, for example Google Docs).
Now, these tests are updated to have a cursor just outside the inline. This leads to more sensible outputs.
(Finally, I removed a TODO comment indicating that `middle-inline-fragment-inline`’s cursor output was incorrect. I believe this is a sensible expectation, which matches behavior in editors including Google Docs.)
Fixes …
> Alter cursor placement in `insertFragment` tests to reflect reality

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/insert-fragment/merge-deep-nested.js
- packages/slate/test/commands/at-current-range/insert-fragment/merge-lists.js
Fixing a bug. This is a proposed solution for https://github.com/ianstormtaylor/slate/issues/2064 (which also aims to maintain the existing _single nested block_ behavior added in https://github.com/ianstormtaylor/slate/pull/1366).
Today, we always insert all nodes of the fragment at the range.
After this change, if the fragment is wrapped by/nested in blocks, and the nesting pattern already exists at the range, we meld the fragment contents into the document’s existing nesting pattern as much as possible.
Put another way, we can skip adding the fragment’s wrapping nodes if equivalent nodes already wrap the range.
Here’s a quick sketch that may better demonstrate the intention:
Here, both the document and fragment wrap their content in two paragraphs. Therefore, we can add the fragment …
> [proposal] Meld fragment into document in `Commands.insertFragmentAtRange`

- packages/slate/src/utils/path-utils.js
- packages/slate/test/commands/at-current-range/delete/non-void-triple.js
- packages/slate/test/commands/at-current-range/delete/void-inline-as-last-with-non-void-previous-siblings.js
Fixing a bug. 
Moving a node from ``path`` to an equal ``newPath`` would increment the returned path when it shouldn't.
Fixes: #2291
Reviewers: @ericedem @ianstormtaylor @Slapbox
> Fix invalid transform path in move_node operation

- packages/slate/src/commands/by-path.js
- packages/slate/src/controllers/change.js
- packages/slate/src/operations/apply.js
- packages/slate/src/operations/invert.js
- packages/slate/test/commands/by-path/move-node-by-path/path-equals-new-path.js
- packages/slate/test/operations/apply/move-node/path-equals-new-path.js
Fixing potential bugs and improving performance.
Commands or operations trying to move a node from one path to a equal path should be ignored throughout the code.
By simply ignoring those operations, or not returning anything (like for marking dirty paths).
Fixes: Issues where ``slate-react`` will regenerate keys for nodes when it's really not necessary. Improving performance. 
> When trying to move a node from a path to an equal path, ignore it

- packages/slate-react/src/plugins/after.js
Fixing a forgotten editor.change call.
Fixes: #
Reviewers: @
> Fix deprecated editor.change in after/onCut

- examples/paste-html/value.json
fixes #1392
This just adds clarification to the paste HTML example that confused myself and others (as evidenced by #1392).
N/A
This only changes one line in the JSON example.
Fixes: #
Reviewers: @
> add clarification for paste HTML example

- packages/slate/src/interfaces/element.js
These functions now check for `nodes` before running `nodes.first()`
Bug
Checks for `nodes.size` before running `nodes.first()` in `isLeafInline` & `isLeafBlock`
Fixes: #2356
> Checks for nodes in isLeafBlock & isLeafInline

- examples/mentions/index.js
It also works in Safari now :)
_bug_
Convert to using the editor directly instead of a change object.
Fixes: #2360
Reviewers: @ianstormtaylor 
I'm not super excited about how I had to fix the `onChange()` handling, by wrapping it in a `setState()` callback. It seems to work ok, but it feels a bit off. If anyone has a similar issue or recommendations please let me know!
> fix: update mentions example to slate 0.43

- packages/slate/src/commands/at-range.js
- packages/slate/src/commands/with-intent.js
- packages/slate/src/plugins/core.js
- packages/slate/test/commands/at-current-range/delete/across-blocks-inlines.js
- packages/slate/test/commands/at-current-range/split-block/with-delete-across-blocks-and-inlines.js
- packages/slate/test/commands/at-current-range/split-block/with-delete-hanging-selection.js
Bug / improvement.
This fixes the "user intent" with deletes, ensuring that `editor.delete()` is always channeled if the selection is expanded, preserving the ability to override the command in a single place.
It also cleans up the deleting logic to ensure that cases where missing start/end nodes after a delete are fixed consistently.
> Fix delete intent

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/wrap-inline/collapsed-range-without-parent-void-inline.js
Fixing a bug
Check if inline ancestor exists before using it in wrapInlineAtRange when selection is collapsed.
Fixes: #2366
> Check if inline ancestor exists before using it in wrapInlineAtRange

- examples/syncing-operations/index.js
- packages/slate/src/models/operation.js
- packages/slate/test/index.js
- packages/slate/test/models/operation/create/add-mark-with-data.js
- packages/slate/test/models/operation/create/add-mark-without-data.js
You can now add arbitrary data associated with an operation just like the `Node` models (`Block`, `Inline`, etc). 
Added `data` property to the `Operation` model.
Fixes: #2346
> Data property for Operation model

- support/webpack/config.js
_bug_
Go from this:
To this:
This change adds the standard meta tag for supporting mobile devices. Now when viewing on mobile the viewport width will adapt to the device.
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_basics
Fixes: #
> fix: support mobile devices in examples

- book.json
- docs/Summary.md
This PR adds the schema reference to the list of documents for gitbook and renames Readme.md to Summary to be consistent with conventions.
Documentation Bug
Schema reference document is available, and the summary config file is renamed appropriately.
* Adds /docs/reference/slate/schema.md to the list of documents in the summary config file.
* Renames summary config file from `Readme.md` to `Summary.md` to be consistent with gitbook conventions and alleviate confusion.
Fixes: #2383
> added the schema reference to the list of documents for gitbook

- packages/slate-react/src/components/editor.js
SLACK CONVERSATION ↓
gersom [4:26 PM]
If a plugin has a command that makes an async change, how do you make sure this change is only applied if the editor component is still mounted in React? Currently, I get the well-known `Can't call setState (or forceUpdate) on an unmounted component.` when I navigate away from the editor page before async commands are finished running.
gersom [4:33 PM]
And if there would be a user work-around for this, I was wondering if it wouldn’t be better to make all the async editor commands safe in a way that slate-react knows not to update state or call onChange anymore?
gersom [5:18 PM]
I have come up with one workaround, that involves doing this:
```
componentWillUnmount() {
if (this.editor.current) {
this.editor.current.change(change => {
const document = …
```
> Avoid async commands causing rerenders after unmount.

- packages/slate-react/src/components/content.js
- packages/slate-react/src/constants/event-handlers.js
- packages/slate-react/src/plugins/after.js
Bug.
Fixes focus events and selection updating logic across multiple editors.
There was an issue in resolving two separate cases...
- When focusing for the first time, we need to call `editor.focus()` to ensure Slate's internal model knows it should be focused, otherwise it will blur itself in the DOM to keep its internal model "correct".
- When re-focusing an editor that used to have focus, Slate's internal model will still show it having a selection range, and it will try to update to that range immediately. Doing so would clobber the incoming `selectionchange` event, causing the editor to re-focus with its old selection instead. So we need to check if its a focus derived from mouse events, and deselect while focusing.
Fixes: #2352 
Fixes: #2390 
Fixes: #2038
Fixes: #2137
Fixes: #2210
> fix focusing across multiple editors

- docs/reference/slate/node.md
- packages/slate/src/interfaces/element.js
- packages/slate/test/models/node/get-nodes-at-range/multiple-blocks.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-cursor-in-first-leaf-of-first-parent.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-cursor-in-first-leaf-of-second-parent.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-cursor-in-second-leaf-of-first-parent.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-selection-overlapping-multiple-blocks.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-selection-overlapping-texts-in-second-parent.js
- packages/slate/test/models/node/get-nodes-at-range/nested-blocks-selection-spanning-first-text.js
- packages/slate/test/models/node/get-nodes-at-range/single-block-cursor-beginning-of-text.js
- packages/slate/test/models/node/get-nodes-at-range/single-block-cursor-end-of-text.js
- packages/slate/test/models/node/get-nodes-at-range/single-block-cursor-middle-of-text.js
- packages/slate/test/models/node/get-nodes-at-range/single-block-with-inline.js
- packages/slate/test/models/node/get-nodes-at-range/single-void-block.js
Feature
Adds method `node.getNodesAtRange` which returns all text nodes inside the range plus all ancestors of those text nodes up to (but not including) the calling node.
Added a method which does a depth-first stack-based search for all relevant nodes using paths.
Fixes: #2351 
- **Big caveat**: I'm not sure if paths are always based on the document root or if they are based relative to the callling node. I went with the calling node so let me know if I'm mistaken.
- I went for a custom and more performant implementation instead of using existing methods. This might make it more difficult to maintain so let me know if you want something else.
- I only made one method `getNodesAtRange` which returns a [`List`](https://facebook.github.io/immutable-js/docs/#/List) which is memoized, is …
> Add `node.getNodesAtRange`

- packages/slate/Changelog.md
Improving documentation.
Adds info about the type change for paths from array to [`List`](https://facebook.github.io/immutable-js/docs/#/List) to the changelog entry for version 0.35.0.
Fixes: #2212
> Add path type change to changelog entry

- docs/reference/slate-react/editor.md
- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/editor.js
- packages/slate-react/src/plugins/react.js
The `Editor` React component now takes an `id` prop which is put on the top-level rendered HTML element of the editor.
Fixes: #2184
> Add optional `id` prop to the `Editor` component

- docs/reference/slate/node.md
- packages/slate/src/interfaces/element.js
- packages/slate/test/models/node/is-node-in-range/block-above-using-key.js
- packages/slate/test/models/node/is-node-in-range/block-above.js
- packages/slate/test/models/node/is-node-in-range/block-below-using-key.js
- packages/slate/test/models/node/is-node-in-range/block-below.js
- packages/slate/test/models/node/is-node-in-range/first-block-inside-using-key.js
- packages/slate/test/models/node/is-node-in-range/first-block-inside.js
- packages/slate/test/models/node/is-node-in-range/first-text-inside-using-key.js
- packages/slate/test/models/node/is-node-in-range/first-text-inside.js
- packages/slate/test/models/node/is-node-in-range/last-block-inside-using-key.js
- packages/slate/test/models/node/is-node-in-range/last-block-inside.js
- packages/slate/test/models/node/is-node-in-range/last-text-inside-using-key.js
- packages/slate/test/models/node/is-node-in-range/last-text-inside.js
- packages/slate/test/models/node/is-node-in-range/text-above-using-key.js
- packages/slate/test/models/node/is-node-in-range/text-above.js
- packages/slate/test/models/node/is-node-in-range/text-below-using-key.js
- packages/slate/test/models/node/is-node-in-range/text-below.js
- packages/slate/test/models/node/is-node-in-range/text-in-middle-inside-using-key.js
- packages/slate/test/models/node/is-node-in-range/text-in-middle-inside.js
Adds `node.isNodeInRange` method which can be used to check whether a descendant node is inside a range. This will return true for all text nodes inside the range and all ancestors of those text nodes up to this node.
Using `PathUtils.compare` method against the start and end paths of the range.
Fixes: #2103
> Add `node.isNodeInRange`

- packages/slate-react/src/plugins/react.js
- packages/slate-react/test/rendering/fixtures/placeholder/multiple-blocks-with-single-empty-text.js
- packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-inline.js
- packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-single-empty-text.js
Fixing a bug
Placeholder are not shown when document contains multiple text nodes.
We check for `node.getTexts().size === 1`.
Fixes: #2397
> Do not show placeholder when document contains multiple text nodes

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/delete-backward/join-blocks-from-inline.js
Fixing a bug
The bug was that `deleteBackwardAtRange` grabbed the previous Text node, but it was in the same Block as Inline and merging Blocks was not triggered correctly; then it tried to remove previous character and did so in the previous block.
Fixes: #2391
> Fix deleteBackwardAtRange removing extra character when called at start of Inline

- examples/rich-text/index.js
Fixing a bug.
When refocusing (click outside editor -> click inside editor) the example will not crash.
Checking if there are any blocks in the selection before doing stuff with the first block in the selection.
Fixes: #2407
> Fix `renderBlockButton` of rich text example

- examples/check-lists/index.js
- examples/code-highlighting/index.js
- examples/embeds/index.js
- examples/emojis/index.js
- examples/forced-layout/index.js
- examples/huge-document/index.js
- examples/images/index.js
- examples/input-tester/index.js
- examples/markdown-preview/index.js
- examples/markdown-shortcuts/index.js
- examples/paste-html/index.js
- examples/plain-text/index.js
- examples/plugins/index.js
- examples/read-only/index.js
- examples/rtl/index.js
- examples/search-highlighting/index.js
- examples/tables/index.js
- packages/slate-react/src/components/editor.js
The `Editor` component now takes a `defaultValue` prop which makes it behave like an uncontrolled input component.
Adds a state inside the `Editor` component which keeps track of a `Value` if it is initially set using `defaultValue`. Examples have also been updated to use this prop.
Fixes: #1257
> Add `defaultValue` prop to `Editor` component

- examples/versions/index.js
Fixing a bug.
The `Versions` example will not break on (versions of) browsers that does not support the experimental array method `flat`.
Since we are flattening a nested array that are exactly two levels, we can just use `reduce` instead.
Fixes: #2444
> Fix: Do not use experimental array method `flat` in `Versions` example

- packages/slate-dev-environment/src/index.js
Fixing a bug
When importing slate in a JSDom environment, it won't crash
We are importing some code from node.js that we run through JSDOM. It in turn imports slate, which thinks it's a browser (this is fine, since that's the reason for using JSDOM in the first place). There is a check in the  `slate-dev-environment` module that _checks_ for `window.InputEvent`, but tries to instantiate an event from the *global* `InputEvent`, which in this case is the node environment, not the browser.
This is a simple fix that prevents the crash from happening.
Reviewers: @skogsmaskin
> fix InputEvent global check

- packages/slate/src/plugins/schema.js
fixing a _bug_
In `validateNodes` function, the `index` variable may decrease by code `index -= 1` in some specific occasion.
Thus the old code `previous = child` and `child = children.get(index)` will make child and previous variable exactly the same, and eventually lead to error of `previous_sibling_type_invalid`.
The new way can make sure the `previous` variable is the real previous node of child.
Fixes: #
> fix(schema): previous and child variable may be exactly the same

- packages/slate/src/utils/memoize.js
Fix potential bug and Refactor code
Instead of this.__cache and __cache_key; the cache will be stored in WeakMap.  
Then we can:
1. We have some one-time range in memorized `getXXXAtRange(range)`. After this PR, the memoized one-time range results will be removed.
2. clear cache will be localized in one place, rather than `__cache_key` logic scattering everywhere.
3. clean the object stucture.  We will not see `this.__cache` in logging out the object.  Perhaps it makes moving to immer with cache easier.
4. Use symbol instead of object for some readability.
For normal arguments, the cache tree will visit directly as a property of dictionary.  If an object is passed, it will visit a WeakMap store to ensure no memory leak.
Fixes: #
Reviewers: @
> Use weakmap to prevent memory leak and remove indirect __cache__key

- packages/slate-react-placeholder/src/index.js
- packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-single-empty-text.js
`React.Fragment` is only available in react >= 16.2, which does not meet the dependency requirements specified by the package (react >= 0.14.0), so unfortunately needs to be replaced in order to maintain compatibility with older versions of react.
Updates from `React.Fragment` -> `<span>` to provide coverage for older versions of react.
Fixing a dependency bug
`Placeholder` component that is compatible with older versions of react
Replaces `React.Fragment` with `<span>` wrapper because `React.Fragment` is not available in react versions before 16.2.
Fixes: #
> Update Placeholder to be compatible with older versions of React

- support/webpack/config.js
Enable the webpack-dev-server from running at a host other than localhost. This is useful for debugging mobile devices for example where we need to specify the host by an IP address.
Just adds a simple configuration change to the webpack `config.js` file under `devServer` to set `host` to `0.0.0.0`
Nope. Need for working on mobile IME issues.
> Allow the dev server to work for non localhost host

- packages/slate/src/commands/at-range.js
fixing a _bug_
Blocks behave right  after unwrap.
As `document` variable is assigned before `forEach` and there are serval operations in each loop, it's not equal to `editor.value.document`. This causes `index` variable inaccurate and blocks disorder after unwrap.
Fixes: #
> fix unwrapBlockAtRange disorder

- packages/slate/src/interfaces/object.js
Refactor
Eliminate some duplication of `mixin(create())`
Fixes: #
Reviewers: @
> Refactor duplicate code in mixin

- docs/Introduction.md
Fix source link in documentation
The link to the package directory previously lead to a 404 page.
link now directs to https://github.com/ianstormtaylor/slate/tree/master/packages
> Update link to source

- docs/reference/slate-react/plugins.md
Docs improvement related to #2259 
Fixes: #
Reviewers: @
> Clarify children access in renderEditor in docs

- packages/slate/src/commands/by-path.js
- packages/slate/src/interfaces/element.js
- packages/slate/src/operations/invert.js
- packages/slate/test/commands/by-path/move-node-by-path/new-path-exists.js
- packages/slate/test/commands/by-path/move-node-by-path/new-sibling-is-text-node.js
- packages/slate/test/commands/by-path/move-node-by-path/path-left-sibling-of-new-path-ancestor.js
- packages/slate/test/commands/by-path/move-node-by-path/sibling-swap.js
- packages/slate/test/commands/by-path/move-node-by-path/text-nodes.js
- packages/slate/test/history/undo/move-node-by-path-ancestor-left-sibling.js
- packages/slate/test/history/undo/move-node-by-path.js
Improvement (mostly adding tests, some refactoring).
Mostly, this work / investigation was done to satisfy: https://github.com/ianstormtaylor/slate/issues/2192 (which appears to no longer be necessary, unless I misunderstood)
That issue was cited as a blocker for: https://github.com/ianstormtaylor/slate/pull/2225
This should also clear up: https://github.com/ianstormtaylor/slate/issues/2328
n/a
- `invert.move_node` was substantially simplified using `PathUtils`, bringing the code more in line with `element.moveNode`
- `Commands.moveNodeByPath` function arguments were renamed (internal) to clarify their purpose.
- tests added
Fixes: #2192, #2328
Reviewers: @
> move_node tests and code clean up

- packages/slate/src/utils/path-utils.js
- packages/slate/test/commands/at-current-range/delete-backward/join-nested-blocks-different-depth.js
- packages/slate/test/history/undo/delete-backward-nested-blocks.js
- packages/slate/test/history/undo/delete-backward.js
Fixing a bug
`PathUtils.transform` now returns correct updated path after a `move_node` operation
In this particular example:
```xml
<document>
<block key="A" path=[0] />
<block key="B" path=[1] />
<block key="C" path=[2] />
</document>
```
If I move the node `B` to the path `[2, 0]` so it becomes this:
```xml
<document>
<block key="A" path=[0] />
<block key="C" path=[1]>
<block key="B" path=[1, 0] />
</block>
</document>
```
If in the same `withoutNormalization` batch, I have a `tmp.dirty` that contains `[1, 0]`, the current `PathUtils.tranform` will transform our dirty path according to the `move_node` operation's `newPath`. Here it will be `[2,0]`. The new dirty path will eventually become `[2, 0, 0]` refering to a non-existing block, that will fail during the next normalization.
A …
> Fix dirty path normalization on move_node

- packages/slate-react/src/plugins/after.js
Fixing a **bug** 🐛 
In IE11, refocusing by click would cause the editor to immediately lose focus because of `editor.deselect().focus()`. The original behavior was added by #2396.
Now when refocusing, IE no longer does a deselect.
I've updated to skip the `deselect` in IE browsers as suggested by following @epotockly's [comment](https://github.com/ianstormtaylor/slate/issues/2364#issuecomment-443717248)
>Fixed this by running editor.focus() without deselect() inside onFocus event in MS Edge, problem definitely are in new range selection, but i don't know how to fix it without removing function
Fixes: #2364 
> Fix mouse refocus in IE 11

- packages/slate-react/src/components/content.js
Fixing a bug. 
Without this, when calling `this.element.focus`, the browser will scroll to the top of the container if the selection is not already set. Since we set the selection later in this function, we don't need the browser to handle this. 
Fixes: #2517
Reviewers: @
> Prevent default browser scroll on content focus

- packages/slate-react-placeholder/src/index.js
Now there can be multiple placeholders that do not interfere with each other.
No developer facing changes.
feature
Multiple placeholder components do not interfere.
A sample use-case with code sample is in #2459.
The placeholder component has an instance auto-counter.
Marks thus become 'placholder0', 'placeholder1', etc. and multiple placeholder components do not interfere.
`yarn lint` looked broken, ran prettier instead (would you welcome a PR with auto-prettier on commit?)
They should, haven't figured out the port number they'd run on.
Fixes: #2459 
Reviewers: I only know @ianstormtaylor here sorry.
> Improve slate-react-placeholder component.

- examples/app.js
Adding a new feature requested in #2576.
A new "View Source" button on the examples page next to the example title. 
The link points to `https://github.com/ianstormtaylor/slate/blob/master/examples/{example-name}`, for example, https://github.com/ianstormtaylor/slate/tree/master/examples/rich-text.
Fixes: #2576
Reviewers:
> Add View Source link on examples page

- benchmark/helpers/h.js
- benchmark/slate/changes/insert-fragment-deep-with-problems.js
- benchmark/slate/changes/insert-fragment-large.js
- benchmark/slate/changes/insert-fragment.js
- benchmark/slate/changes/insert-node-by-key.js
- benchmark/slate/changes/normalize-with-problems.js
- packages/slate-plain-serializer/test/helpers/h.js
Improving _benchmarks_
(See PR title)
`insert-node-by-key` wasn't working because the index passed into all but the first couple operations were invalid.
`normalize-with-problems` should check how long it takes to normalize a Slate tree that has some problems (`block` with no `text` children, `inline` not surrounded by `text`). This could potentially be improved by adding other types of things that violate the core schema, but those are two issues that we've noticed causing a lot of issues in our own app.
Fixes: #
Reviewers: @
> Fix insert-node-by-key benchmark, add normalize and insert-fragment benchmarks

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/insert-fragment/start-block-with-void-no-text.js
Fixing a _bug_.
When inserting a fragment into a range where `startBlock` has void children but no text, `startBlock` would be removed.
`startBlock` is not removed.
Check for void children before removing a node.
Fixes: #2545
Reviewers: @ianstormtaylor @ldavidpace
> fix insert fragment with void children

- docs/walkthroughs/adding-event-handlers.md
Correct me if I am wrong, but I believe that this `return true` is a no-op. I removed it and everything kept working as usual. And, when I was following the tutorial, that particular line created an interrogation mark in my brain. So, my suggestion is to remove that line to avoid creating entropy for no reason.
No.
Just updating the docs.
Correct me if I am wrong, but I believe that this `return true` is a no-op. I removed it and everything kept working as usual. And, when I was following the tutorial, that particular line created an interrogation mark in my brain. So, my suggestion is to remove that line to avoid creating entropy for no reason.
Nope.
> Remove return true on key down function

- docs/reference/slate/plugins.md
Docs.
There were two issues:
- copy/paste from queries docs
- The example code referred to `change` instead of `editor`
Fixes https://github.com/ianstormtaylor/slate/issues/2596
Fixes https://github.com/ianstormtaylor/slate/issues/2539
> Fix onCommand docs that referenced query instead of command

- docs/walkthroughs/applying-custom-formatting.md
In the last chunk of code, it was missing the `break` (or `return`). So, if used as is, the bold key will toggle the `code` feature as well.
A bug in the implementation example in the documentation
The `b` key should only toggle the `bold` behavior. That was fixed.
Nope :)
> Fix missing break in last example

- packages/slate-dev-environment/src/index.js
Adding a feature and fixing a bug. The feature is the export of `ANDROID_API_VERSION` from `slate-dev-environment`. The bug is that `HAS_INPUT_EVENTS_LEVEL_2` returns false for Android 9 but should return true.
Returns true for `HAS_INPUT_EVENTS_LEVEL_2` which results in Slate using the real `beforeinput` event instead of React's synthetic version.
Queries the browser's `window.navigator.userAgent` to derive the API version. When setting `HAS_INPUT_EVENTS_LEVEL_2` sets it to true if the `ANDROID_API_VERSION` is 28 even though it otherwise is not identified as supporting the feature.
> Add API version and Input Events Level 2 for Android

- packages/slate-react/src/utils/find-point.js
Fixing a Bug 🐛 
Edge has a [bug][1] where `Range.prototype.toString()` will convert `\n`
into `\r\n`. The bug causes a loop when slate-react attempts to
reposition its cursor to match the native position.
Example of broken behavior
Live example:
https://codesandbox.io/s/6mpnnqkpr
Open in Edge and attempt to click between `b` and `c`. Notice that the cursor will reposition to the end.
[1]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10291116/
This change avoids calling `Range.prototype.toString()` by cloning the
content nodes and measuring `textContent` on those instead.
`textContent` doesn't add `\r` to every `\n`, so the calculated offset will be correct
Fixes: #
> Fix Edge positioning with newlines

- packages/slate/src/models/block.js
Fixes: #2603
Switched `Map` to `fromJS` in order to convert the whole js object (also nested data structures) to immutable.js when creating a block.
> Use fromJS instead of Map to convert data into block data

- examples/images/index.js
This pull request is to fix a bug in the Slate image example code.
The following error occurs on https://www.slatejs.org/#/images when attempting to paste an image URL and the image isn't actually added due to the function not returning properly:
`Uncaught TypeError: String.prototype.endsWith called on null or undefined`
I'm aware that there is a separate image pasting plugin, however. Feel free to kill this PR if it makes more sense to use that instead.
This patch re-enables the pasting of images into the editor without using the previously mentioned plugin.
It strips query tags from the end of the URL, then grabs the URL extension and compares it to the given image extension list.
I couldn't find a bug that was reported for this.
> Fix error when pasting an image into Slate image example.

- Readme.md
- docs/Introduction.md
- docs/general/resources.md
- docs/guides/data-model.md
- docs/reference/slate/data.md
Update the domain regarding `immutable-js` from `facebook.github.io` to `immutable-js.github.io`
For instance,
https://facebook.github.io/immutable-js/docs/#/Record
https://immutable-js.github.io/immutable-js/docs/#/Record
N/A
N/A
Fixes: #
Reviewers: @
> docs: fix immutablejs doc domain

- docs/reference/slate-html-serializer/index.md
This can trip folks up who are using compile-to-JS languages (ClojureScript in my case), where return semantics may be different.
Fixes: #
Reviewers: @
> Clarify semantics of return from deserialize

- packages/slate-react/src/utils/get-event-range.js
Instead of using `x` and `y` from `event` object, which are [experimental properties](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/x) and missing in some cases, it uses `clientX` and `clientY` which are widely supported.
It doesn't change anything
Fixes: #2570
Reviewers: @
> Make use of clientX and clientY in getEventRange

- docs/guides/rendering.md
`<strike>` is obsolete and discouraged https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike
`<s>` is better alternative https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s
> Use <s> for strikethrough example

- examples/code-highlighting/index.js
- packages/slate-react/src/components/text.js
Fix bug in https://github.com/ianstormtaylor/slate/issues/2616 and https://github.com/ianstormtaylor/slate/issues/2319
Stops the editor from crashing in syntax highlighting when hitting enter in certain places
Generates a path for each decoration. Previously, we were only passing through the key that seems to work sometimes but not others. This is also referenced in a separate PR I made here https://github.com/ianstormtaylor/slate/pull/2697. Both these PRs improve Slate. This one fixes this bug. The other PR fixes all similar issues and provides a nice warning.
Fixes: #2616 #2319 
Reviewers: @
> Fix syntax highlighting

- examples/composition/index.js
- package.json
Improving examples
Adds a text box below the editor in the compositions example that shows the text inside the internal state of Slate. This is important because there can be bugs in compositions where the DOM correctly displays some content but that text has not been reconciled to Slate's internal `Value` yet.
This lets us see what's inside Slate as well as what's in the DOM.
Converts Slate's Value to an array of Strings (one string per top level block) then converts each item into a `div` displayed below the Editor.
Fixes: #
Reviewers: @
> Add value inspector to composition example

- packages/slate-html-serializer/package.json
- packages/slate-react/package.json
- packages/slate/package.json
bug
immutable-4.0.0-rc* shall be allowed.  As @denis-sokolov  pointed out, `>= 3.8.0` do not include `4.0.0-rc`
https://github.com/ianstormtaylor/slate/pull/1869#issuecomment-483283872
Fix as https://github.com/ianstormtaylor/slate/pull/1869#issuecomment-483283872
Fixes: #
Reviewers: @
> Allow immutable 4.0.0-rc

- packages/slate/src/interfaces/element.js
- packages/slate/test/models/node/get-marks-at-position/marked-text-with-zero-offset-with-no-previous-text.js
- packages/slate/test/models/node/get-marks-at-position/marked-text-with-zero-offset-with-previous-text-not-in-the-same-block.js
- packages/slate/test/models/node/get-marks-at-position/marked-text.js
- packages/slate/test/models/node/get-marks-at-position/text-with-zero-offset.js
- packages/slate/test/models/node/get-marks-at-position/unmarked-text.js
Fixing a bug when calling `getMarksAtPosition` with offset 0 throws an error.
Nothing
There is a typo calling `getMarksAtIndex` method on `previous` which is a tuple, it should be `previousText`.
Fixes: #2679
Reviewers: @ianstormtaylor @jtadmor
> fix get marks from previous text on method getMarksAtPosition

- packages/slate-react/src/plugins/after.js
If mouseDown happens inside editor container and mouseUp outside it,
then programmatically calling editor.focus() after that will mess up
the selection
fixing a _bug_
to reproduce the bug do the following:
1. mouseDown inside editor, move to select content and release mouse button outside editor
2. blur the editor (click outside the editor component)
3. programmatically call editor.focus() (maybe clicking a toolbar formatting button for example)
4. see selection being collapsed instead of resetting it to the selected fragment
the problem was is that when on mouseDown we set a closure variable isMouseDown to true and reset it on mouseUp event, but since mouseUp may happen outside the editor it was not resetting it.
The solutin is to reset it inside onSelect handler. We only need that …
> Fix selection being reset incorrectly after combination of events

- packages/slate-react/src/components/text.js
Fixing a bug.
Helps with
- https://github.com/ianstormtaylor/slate/issues/2319
- https://github.com/ianstormtaylor/slate/issues/2616
Instead of throwing on decorations without a path but a key, use the key to generate the path but display a warning. The syntax highlighting example is causing this issue and I had to deep dive to figure out the cause. This warning will let everything still work while giving us the opportunity to figure out the source of the path not being on the decoration.
My guess is that the example used to work but broke at some point when the `path` suddenly was required and the `key` wasn't enough.
If a path is missing on a decoration's `start` or `end` it will provide a warning but will use `document.assertPath` to deriver the path and the editor won't crash. 
Fixes: …
> Support decorations without path

- packages/slate-react/src/components/content.js
Fixing a bug
Some debug payloads contain expressions that need to be evaluated, which can be expensive. (for example calling `value.toJSON()` on a large document with many nodes)
This PR makes sure that those payloads are only evaluated if debugging is actually enabled, thereby improving performance in production.
We simply call `if (debug.enabled)` before those debug calls. This way, if debugging is indeed disabled, the contained expressions are not needlessly evaluated.
Fixes: #
Reviewers: @
> Improve performance on large documents with many nodes

- packages/slate/src/commands/with-intent.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-inline-node.js
Fix
After pasting a fragment with inline nodes, the selection is moved to the correct postition (after the inserted fragment). See the [Link example](https://www.slatejs.org/#/links).
Skip inline nodes before summing up the length of all text nodes, 
* [x ] The new code matches the existing patterns and styles.
* [x ] The tests pass with `yarn test`.
* [x ] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x ] The relevant examples still work. (Run examples with `yarn watch`.)
Fixes: #2582
Reviewers: @
> fix selection after pasting inline nodes

- docs/reference/slate/text.md
Docs
Update Text for latest changes. `text` property is no longer computed. Add `marks` field.
> Text documentation update

- docs/walkthroughs/defining-custom-block-nodes.md
This is updating the docs in response to a recent API change.
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#0220--may-8-2019
No change in behavior, just updating the docs.
There are still some docs that reference `renderNode` and `renderMark`, but I don't know enough about the new API (or event he old one, for that matter!) to make changes to those. It's just that this inconsistency personally tripped me up for awhile while I was going through the docs trying to get a basic example working, and wanted to get the ball rolling on updating the docs.
...
No.
> Replace renderNode with renderBlock in the docs

- packages/slate-react/src/plugins/dom/after.js
Bug
As it was intended, error free.
It's pretty easy to understand the fix if you compare the following two (`document.texts`):
https://github.com/ianstormtaylor/slate/blob/a5a25f97dde1de06ef0746e6f5285c04e503351c/packages/slate-react/src/plugins/dom/after.js#L553-L571
https://github.com/ianstormtaylor/slate/blob/a5a25f97dde1de06ef0746e6f5285c04e503351c/packages/slate-react/src/plugins/dom/after.js#L573-L587
Fixes: #2761
> Destructure texts iterable causing an error on backward shift+arrow selection

- examples/components.js
- examples/composition/index.js
Improvement
Move the `value` preview into its own component for the examples. Feel like this could be useful in other examples where we need to pay attention to what's inside Slate vs what's being rendered.
Just refactored into a separate examples components and matched the style.
Fixes: #
Reviewers: @
> Separate out EditorValue component for examples

- examples/app.js
- examples/restore-dom/index.js
- examples/restore-dom/value.json
- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/editor.js
- packages/slate-react/src/plugins/react/index.js
- packages/slate-react/src/plugins/react/restore-dom.js
Adding a feature which will help in fixing Android
Add a command to the editor called `editor.restoreDOM()`. This will blow away the current DOM and replace it with a new one built from scratch using the data in the Editor's `value`.
```
editor.restoreDOM()
```
To show this working, the PR includes an example where we change the state in the example without changing the `document` in Slate. In the example, I change the background color of the blocks when you click a button in the toolbar. Normally, this means that we won't see a change since the document hasn't changed (i.e. the state is outside of Slate).
As you can see in the example, the colors do change in all blocks. This is because after changing the state, I call `editor.restoreDOM()` which forces the editor to blow away the DOM …
> Restore dom

- examples/components.js
- examples/composition/index.js
- examples/composition/special.js
- examples/composition/util.js
Refactor an Instruction component so that it can be re-used by examples
Same as before with a slight visual improvement. The main difference is that the `Instruction` component can now be re-used in the examples.
Moved code and made it fit style of other shared components.
Fixes: #
Reviewers: @
> Extract Instruction component into components for examples

- packages/slate-react/src/plugins/react/commands.js
Add a feature
Add a `reconcileNode` method that uses a Slate node instead of a DOM node to reconcile.
It's pretty straightforward to understand.
Fixes: #
Reviewers: @
> Reconcile node

- packages/slate-react/src/plugins/react/queries.js
- packages/slate-react/src/utils/get-selection-from-dom.js
Fixing a bug.
We no longer see errors when the selection endpoints are at the beginning or end of inlines.
When `block.texts()` is passed a path, it treats that path as relative to `block`. `findSelection` passes it the selection path, which is relative to `document`.
In order to find the correct text nodes, we must convert the selection path to a path relative to `block`. Then, when a new path is returned, we need to convert that new block-relative path back to a document-relative path.
Fixes: #2769 #2779
> Use relative path to find a node's text nodes

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/delete/first-position.js
fixing a bug.
Calling `deleteAtRange` with a collapsed selection at the beginning of a text node will both null out the selection and delete the entire text node.
deleteAtRange will consider a zero-length range on the first character of a text node as a hanging selection, which is incorrect. This should not be considered hanging.
Note: It's still possible to hit the [`startKey === endKey && isHanging`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/commands/at-range.js#L166) conditional if endKey is in a void node, since we will bump the selection to the previous node and update endKey (but then endOffset is no longer 0, so it's not _really_ hanging anymore). We have an existing test for that, and it still passes after this change. 
I thought this was cleaner than …
> Allow deleteAtRange with a zero-length range on the first character

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-nested-blocks-end-of-node.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-nested-blocks-start-of-node.js
Bugfix
The order of blocks is correct (and not reversed) after pasting in some edge cases
insertBlockAtRange() determines if a block should be added before/behind a block or the block should be splitted. The PR refactors this logic into a separate function `getInsertionMode`, which can be called inside insertFragmentAtRange() to find out whether the blocks should be added in normal or reversed order (to end up in the correct order)
Fixes: #2771 
Reviewers: @
> fixing order of blocks if inserted at start of node

- packages/slate-react/src/plugins/react/queries.js
Bug
Return null instead of raising exception if missing content ref.  I started seeing these intermittently after upgrading to slate-react 0.22.0
Fixes: #
Reviewers: @
> Gracefully handle null content ref in slate-react findDOMNode query

- docs/walkthroughs/saving-and-loading-html-content.md
Nodes weren't properly rendering because the Editor was trying to call the function prop renderBlock but instead another called renderNode was passed.
> Fix: prop name

- packages/slate-react/src/components/leaf.js
Bug
This fix is necessary to ensure leaf re-rendering when only content changes. Good example of that would be Slate search highlighting example. First try the [old version](https://www.slatejs.org/#/search-highlighting) and then netlify deployment below. 
This happens because all the other conditions still pass, only the text content changes. If you search for `h`, previous leaf content was `This is editable text that you can search. As you search, it looks for matching strings of text, and adds "annotation" marks to them in realtime.`, new one is `T`. Everything else is the same, including parent, index `0`, no annotations, etc.
Also compare text content when deciding if to re-render or not.
Fixes: #2767
> Fix leaf memoization bug

- examples/images/index.js
- packages/slate-react/src/plugins/dom/before.js
- packages/slate-react/src/plugins/react/queries.js
Moves to `findEventRange` query and adds a fallback to `findPath` that looks for the closest element with a `data-key` so it does not throw errors if dragging and element over a `data-slate-string` (amonst others).
Also, `document[iterable](path)` using `nextTexts` was undefined in `onDrop` so moved to `getNextText`
Fixes: #2788
Reviewers: @
> fallback findPath query to find closest element with a data-key

- packages/slate-react/src/plugins/debug/noop.js
- packages/slate-react/src/plugins/react/index.js
There is know way to know how the browser behaves natively within the context of Slate's DOM.
The `noop` plugin which is enabled by adding debug to localStorage (like all other debug) with a value of `slate:noop`.
All of the debug plugins will run before `noop` Plugin but after that, all the events aren't passed through the rest of Slate's stack. This means Slate's `value` is never updated and the Editor is never re-rendered.
The plugin simple doesn't call `next` on any of the `EVENT_HANDLERS` defined for Slate.
Fixes: #
Reviewers: @
> Add noop plugin

- packages/slate-react-placeholder/src/index.js
- packages/slate/src/models/text.js
Fix bug.
If decoration/annotation has both start and end offsets `0` and leaf content length is `0`, decoration/annotation is still added to leaf. 
This makes possible to add decoration/annotation that is content in itself, versus decorating the content that's in leaf. This fixes a bug where placeholder was not added to leaf and was not rendered.
Fixes: #2760 
> Fix placeholder not rendering

- packages/slate-react/src/components/content.js
As per https://github.com/ianstormtaylor/slate/issues/2548 this PR adds the editor's DOM element to the `editor` object.
`content.js` uses a `ref` prop with `this.ref` which was a `React.createRef()` in order for other methods like `updateSelection` to access the DOM element within `content.js` itself.
I switched the `ref` prop to `this.setRef`.
Within `this.setRef`, I set both `this.ref.current` and `editor.el` to the DOM element.
This maintains backwards compatibility but adds the `editor.el` property.
Fixes: #2548
Reviewers: @
> Add div to editor as editor.el

- packages/slate-react/src/components/editor.js
Make the `editor` available to plugins
Passes the `editor` object to plugins through the call to `ReactPlugin({ ..., editor: this })`
Fixes: #
Reviewers: @
> Add editor to plugin options

- packages/slate-react/src/plugins/debug/noop.js
Feature
Added a NoopPlugin which eats events so that Slate can't react to them. This helps us see DOM mutations and events while ignoring the noise that comes from what Slate itself is doing to DOM mutations and adding events.
Using the list of EVENT_HANDLERS, it creates functions that do nothing. In particular, they don't call the `next` method. Unlike the previous rejected version, the Plugin is detached. It must be hard-coded into the plugin chain for it to work.
For those following, this approach was approved in a Slack chat by @ianstormtaylor 
Fixes: #
Reviewers: @
> Add noop plugin as detached plugin

- packages/slate-react/src/plugins/debug/debug-mutations.js
- packages/slate-react/src/plugins/react/index.js
Add a feature
Same as earlier it allows developers to see mutations using `MutationObserver` in the context of Slate's DOM.
Add a MutationObserver. This implements all the recommendations from Ian to clean up the code.
Fixes: #
> Second attempt at Debug Mutations

- packages/slate-react/src/components/editor.js
Fixing a bug
Previously Hot Module Reload doesn't work when making a change to plugins. This fix means that making changes to plugins including any of the core plugins are reflected in the instance of the Editor without having to do a full reload.
In `slate-react/src/components/editor` there is a method called `resolveController`. It uses the method `memoizeOne` so that Slate is not rebuilding the controller on each `render`.
Previously `ReactPlugin` was not passed into the `resolveController` call so even if the `ReactPlugin` changed, it did not create a new version of the controller.
We now add `ReactPlugin` to the `this.resolveController` call in the `render` method. This makes sure that when `ReactPlugin` changes we get an updated controller.
Fixes: #2709
Reviewers:
> Fix Hot Module Reload for plugins

- packages/slate-react/src/components/content.js
Adds Plugin events for the following React lifecycle events:
- componentDidMount
- componentDidUpdate
- componentWillUnmount
As per the issue discussed here: https://github.com/ianstormtaylor/slate/issues/2832
in `content.js` where the Editor contents are rendered, I added calls like `this.props.onEvent('onComponentDidMount', {target: this.ref.current})` for each lifecycle callback.
Note that the `event` object passed through has a `target` property similar to what one would see in an actual event. This makes it easy to get the DOM element that represents the Editor element. Since this is likely the primary use case for these events, it felt useful to add them.
For the time being, I added these lifecycle events as `componentDidMount` as opposed to @brendancarney …
> Add lifecycle event handlers

- packages/slate-react/src/components/content.js
This just add to https://github.com/ianstormtaylor/slate/pull/2833 with an `onRender` method.
In particular, this is useful because we need to stop listening to mutations when Slate is doing them then we wish to listen to mutations that user's make.
There was code in a number of places to switch listening off immediately before sending commands to Slate but it turns out to be a lot easier to just turn listening to mutations off as soon as `render` gets called and then turn them on once `componentDidUpdate` gets called.
Tried it and works great.
Calls `this.props.onEvent('onRender', {})` in the `render` method of `content.js`
Fixes: #
Reviewers: @
> Add render event for plugins

- examples/composition/empty.js
- examples/composition/index.js
Adds an example in compositions with no content and some instructions
Very straightforward.
Because an empty block has a special zero width container, we need to make sure to handle the use case and therefore a way to test is required.
Fixes: #
Reviewers: @
> Add empty composition example

- examples/composition/index.js
- examples/composition/remove.js
Feature
Backspacing and otherwise removing content is a big part of implementing compositions and there are many edge cases related to it.
This gives us a few basic tests that allow us to make sure they are working.
Just add another example. It's straightforward.
Fixes: #
Reviewers: @
> Add remove composition example

- packages/slate-react/src/components/content.js
Improvement
Remove the pseudo-event object from the lifecycle events as per https://github.com/ianstormtaylor/slate/pull/2833#issuecomment-496648341
I just stop passing the event object through
Fixes: #
Reviewers: @
> Remove pseudo-event object from lifecycle events

- packages/slate-react/src/plugins/debug/debug-mutations.js
There is currently a `debug-mutations` plugin that lets us observe mutations on the Editor element.
However, it has two issues:
- It uses `setTimeout` to set up the mutation which is hacky because it relies on React having to have rendered to the DOM before the `setTimeout` executes. This is not necessarily guaranteed.
- When we call `restoreDOM`, the root element is destroyed and recreated. The mutations are now on the wrong element and we can't see mutations in our Editor.
Uses Slate's currently unstable lifecycle events to add the mutation observers when the Editor's `content` first mounts during `componentDidMount` fixing issue 1.
It then re-observes during `componentDidUpdate` if the root element for the editor has changed.
Fixes: #
Reviewers: @
> Hook debug-mutations into lifecycle events

- packages/slate-react/src/plugins/debug/debug-mutations.js
Mutation targets that are text node are rendered to debug as a String. This is an improvement because otherwise the reference is to the text node itself. The `textContent` of the node will often have changed so in the previous method with the reference we would never have known what the `textContent` was at the time of the mutation.
- Takes the prettifying code out into a separate `normalizeNode` method
- Returns the `textContent` of the node if the `nodeType` is of type `TEXT_NODE`
Fixes: #
Reviewers: @
> Normalize target node in debug mutations

- docs/walkthroughs/installing-slate.md
- docs/walkthroughs/saving-to-a-database.md
As a new user not being able to go through the walkthrough docs was somewhat harder than it need to be. Something else that could be improved is that the error message in the console told me what was wrong but not how to fix it.
This is a partial fix for #2754. I'd remove other references to leaves in the docs but I'm not yet up to speed on the project as a whole to understand the changes that need to be made.
> Remove leaves from docs

- packages/slate-react-placeholder/src/index.js
Fixing a bug
The cursor will be positionned correctly under chrome.
Before, the cursor would have a slightly different position when the mouse is pressed under chrome.
This doesn't look significant until you apply some styling:
It works by adding a vertical alignement to the placeholder element so it's aligned to the text-top position.
No matter the size, the placeholder element is aligned with the text top, keeping the cursor position at the right place in chrome.
Here's a gif that shows the behavior in chrome after the fix:
Firefox don't seem to be affected by this problem or the fix since it's algorithm to place the cursor seem to behave differently.
> Corrected placeholder alignement in chrome

- packages/slate-react/src/utils/get-event-range.js
Fixing a bug.
`getEventRange` no longer crashes when called.
This version of the method has drifted from `editor.findEventRange`, and now crashes when it's being used. This commit fixes an import and changes some code to match the new code in `editor.findEventRange`.
> Fix several errors in the deprecated `getEventRange`

- docs/guides/data-model.md
Current docs say:
> Learning Immutable JS is is well worth the investment!
Remove one "is".
> Fix typo on Data Model docs page

- examples/mentions/Suggestions.js
Improving an example (not technically a bug fix, but a UI/UX designer would call it a bug fix)
Currently, if you type `@` in the mentions example, it initiates the creation of an annotation wrapper. That wrapper is the target of the suggestions list dropdown.
Because of the use of `React.createPortal` to keep the suggestion list outside the editor's HTML, if you scroll before typing anything after `@` then the positions of the list will be incorrect relative to the cursor. (Note: you need to make the example contain enough text such that the page scrolls to replicate.)
By including the current scroll position in the absolute positions of the list, we ensure that it is always in the correct spot relative to the cursor regardless of the scroll position of the page.
NOTE: this fix will not …
> Improve mentions example by including scroll calculation

- docs/reference/slate-react/plugins.md
Improving slate-react plugin documentation.
Explicitly mentioning breaking API changes from 0.22.0, removing deprecated and unused functions.
The markdown is different than it was and now includes the new API.
No code changes.
Fixes: N/A
> Update slate-react plugin documentation with breaking changes from 0.22.0

- packages/slate-react/src/components/node.js
Hi,
There are problems with annotations that span across multiple blocks or other nodes after they are recomputed with `getRelativeRange`. 
The first problem is with `setStart` and `setEnd` called subsequently, because they do a check against the "backwardness" to set the anchor or focus relatively. But the check is done after the first point was already set, which might change the order, and lead to the same point being set twice. 
The second problem is that after the annotation is split, the keys do not get set, which leads to this annotation being omited, because the anchor or focus point is treated as unset (both path and key must be set).
Thanks in advance for reviewing it.
> Fix bugs in getRelativeRange.

- packages/slate-react/src/components/content.js
- packages/slate-react/src/components/editor.js
Feature(i guess): This enables the user to optionally pass a prop to enable Grammarly which was previously disabled in [#733](https://github.com/ianstormtaylor/slate/issues/733).
You can also check it here [sandbox](https://49zhg.codesandbox.io/). You will, of course, need to install the Grammarly extension. The above demo was tested on version 14.915.2321
Since Grammarly has moved to an API based content modification, it would be really helpful for users to be able to enable Grammarly if it suits them. So I have added a prop to enable the same. The only non-trivial part is that the extension doesn't seem to work as long as the prop `data-gramm` exists irrespective of its value.
Fixes: #733
Reviewers:
> Add prop to optionally enable grammarly

- examples/search-highlighting/index.js
- examples/search-highlighting/value.json
I just wanted to add this to start a discussion on how we can make the decorations and marks work together in a better way. I thought it could give us some more chances to find a solution for this case.
The problem I see with marks is that right now they inherently modify the structure of the document by splitting the `text` nodes which invalidates any `range` that decorations reference. This makes it quite difficult to apply decorations consistently when marks are added/removed as you need to apply multiple of them for every text node and hence set of marks. Also, decorations don't seem to work across text nodes.
> Add a mark in the search highlight example

- docs/reference/slate-react/plugins.md
Improving documentation
- `renderMark` is documented
- `renderDecoration` & `renderAnnotation` reflect actual code
The `slate-react` documentation has recently been updated to reflect lastest breaking changes, but `renderMark` has been wrongfully removed. This also fixe some incoherent props for `renderDecoration` & `renderAnnotation`.
Fixes: #
> Fix slate-react plugin documentation

- docs/reference/slate/schema.md
document issue
Add `next` property to `rules`
Fixes: #
Reviewers: @
> Add missing `next` property in rules

- docs/guides/data-model.md
This PR just changes a type from `an` to `can` in the marks section of the documentation
> Fix typo in marks

- packages/slate/src/models/value.js
Hi,
It looks like the annotation should be normalized when it is inserted and the anchor's and focus's keys should be populated to allow subsequent operations in `mapRanges`.
> Add point normalization to addAnnotation.

- packages/slate/src/utils/path-utils.js
Hi,
Annotation-related operations are not listed in path transform which leads to a crash, when we try to transform any path by such an operation. The result should be the path itself, as annotation-related op do not interfere with the tree.
Thanks in advance.
> Add annotation-related ops to path.transform. (#2)

- packages/slate-react/src/components/content.js
```
index.js:1 Warning: Unknown event handler property `onEvent`. It will be ignored.
in div (created by Content)
in Content (created by Editor)
```
Will gone.
Simply add a line of proptype.
Fixes: I'm using a local copy of the latest master and found this bug.
Reviewers:
> fix: Unknown event handler property `onEvent`

- examples/paste-html/index.js
It appears that render block is missing a case for rendering `paragraph`. Without this paragraphs are being rendered as `<div>`s.
It is fixing a bug in the example
paragraphs are now rendered as `<p>` tags
No
Fixes: #
Reviewers: @
> Fix renderBlock() in paste-html example

- packages/slate/src/commands/by-path.js
- packages/slate/test/history/undo/toggle-mark.js
This fixes a bug
| Before | After |
|---|---|
| ![Screen Recording 2019-07-26 at 15 46 06 2019-07-26 15_49_15](https://user-images.githubusercontent.com/3692274/61974726-9d0c0080-afbd-11e9-809f-1dbd6c41c5bd.gif) | ![Screen Recording 2019-07-26 at 15 46 41 2019-07-26 15_50_45](https://user-images.githubusercontent.com/3692274/61974745-a5643b80-afbd-11e9-8488-b1aa7c46dcef.gif) |
When adding a mark or selecting text around one, and then removing the mark, it results in an unwanted `remove_mark` operation on the next following text node. Undoing it would then result in an improperly reapplied mark.
A very naive fix is to check if the marks we are trying to remove are in the node beforehand.
<details>
<summary>👉 Click for a more detailed step by step 👈</summary>
```xml
<paragraph>
One <anchor …
```
> Fix undo a removeMark re-add mark to wrong nodes

- packages/slate/src/models/value.js
- packages/slate/test/commands/at-current-range/remove-mark/part-of-mark-backward.js
- packages/slate/test/commands/at-current-range/remove-mark/part-of-mark.js
This fixes a bug
| Before | After |
|---|---|
| <img src="https://user-images.githubusercontent.com/3692274/61561255-d1734000-aa44-11e9-871c-ea41ff406841.gif" width="434" /> | <img src="https://user-images.githubusercontent.com/3692274/61561260-d3d59a00-aa44-11e9-9231-658685ac2272.gif" width="434"  /> |
When splitting a node, [every ranges inside the value are re-normalized](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/value.js#L799-L816). This includes selection and annotations for example. But this is done using `range.start` and `range.end`. 
- Due to the order in which those are done, a very special case could move start **after** the end, before the end is normalized
- This is then passed to [`range.setEnd`](https://github.com/ianstormtaylor/slate/blob …
> Fix splitNode range update when selection is backward

- packages/slate/src/controllers/editor.js
Performance. 
Mutate `newDirtyPaths` on each iteration instead of copying it. For my unscientific paste test, this brings a 4s paste to about 2.5s.
> Mutate newDirtyPaths instead of creating a new array every iteration

- docs/general/glossary.md
Documentation improvement
`match` get's used a number of times within the slate/schema.md but it does not appear to be explicitly defined anywhere. This term seems like a great candidate for the Glossary.
The change is was trivial and only to the documentation
* [N/A ] The new code matches the existing patterns and styles.
* [N/A ] The tests pass with `yarn test`.
* [ N/A] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [ N/A] The relevant examples still work. (Run examples with `yarn watch`.)
No
Fixes: #
Reviewers: @
> Update glossary.md with definition of `match`

- packages/slate/src/commands/by-path.js
- packages/slate/test/commands/by-key/replace-marks-by-key/different-set-of-marks.js
- packages/slate/test/commands/by-key/replace-marks-by-key/empty-set.js
- packages/slate/test/commands/by-key/replace-marks-by-key/same-marks-different-data.js
- packages/slate/test/commands/by-key/replace-text-by-key/replace-with-active-marks-with-data.js
_bug_
before:
after:
`insertTextByPath` should replace marks on the inserted text with the once that are provided
It were trying to add those marks that are passed to the function to the existing once,
but it should replace them instead.
Example error behavior was:
* put cursor at the end of the marked text
* toggle marks
* enter text
expected:
text is being added without toggled marks
actual:
text is added with those marks applied
Fixes: #2848 
Reviewers: @adjourn, @erquhart
> Fix marks incorrect behavior on insertText

- packages/slate-react/src/components/content.js
it should check the latest rangeCount, not the previous memorized one
It fixes #1237 
Always check `rangeCount` with the latest Selection object
Fixes: #1237
Reviewers: @dmitrizzle @ianstormtaylor
> fixed #1237 which calls Selection.getRangeAt(0) when Selection.type = 'None'

- packages/slate/src/controllers/editor.js
Hi,
Paths accumulated for normalization are not deduplicated which leads to poor performance in case we wait with flushing for some reasons.
Thanks.
> Deduplicate dirty paths for normalization.

- packages/slate/src/commands/at-range.js
- packages/slate/src/commands/with-intent.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-multiple-marks.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-single-inline.js
- packages/slate/test/commands/at-current-range/insert-fragment/fragment-single-mark.js
- packages/slate/test/commands/at-current-range/insert-fragment/middle-inline-fragment-inline.js
Fixing a bug
| Before | After |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/3692274/63416345-8e1f3f00-c3ff-11e9-93ae-7bf9b11328ac.gif) | ![after](https://user-images.githubusercontent.com/3692274/63416357-911a2f80-c3ff-11e9-9a1a-c5cdb861189e.gif) |
When inserting a fragment, the new selection is calculated by looking at new texts in the document. This is done by comparing previous keys to new ones. On certain cases, specially when the text node where the selection is, the current `startText` node will be split, creating a new key for the remaining part of the node. This node will later be considered as new text, and a candidate to put the updated selection to.
This is not reliable when the fragment ends with un-mergeable text nodes like inlines or marks (like the …
> Fix improper selection after insertFragment

- packages/slate/src/models/text.js
Hi,
`renderAnnotation` is not called for *collapsed* annotation at offset *zero*. This patch fixes it.
Thanks.
> Fix rendering of collapsed annotation at offset zero.

- packages/slate/src/commands/at-range.js
- packages/slate/test/commands/at-range/delete-backward-at-range/from-offset.js
If `editor.deleteBackwardAtRange` is invoked and the range's offset is equal to `n`, `n` characters will be deleted.
Changes the check that `n < focus.offset` to `n <= focus.offset`.
Fixes: #2965
> deleteBackwardAtRange now works when offset is equal to n

- packages/slate/src/models/value.js
Hi,
In 'splitNode' and 'removeNode' range normalization start/end should be changed to anchor/focus, as those might change during normalization and the order might be reversed - leading to a point being set twice and the other not being set at all.
Thanks.
> Fix range normalization for node removal and split.
